### ISSUE TITLE
graphviz: error: return type is an incomplete type

### ISSUE THREAD

**Issue by lunik1** [Linuxbrew/homebrew-core#10014]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

 - [*] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [*] ran `brew update` and can still reproduce the problem?
- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [*] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [*] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

--------------

Trying to install root with a graphviz dependency. Failed when trying to install graphviz, and again when I tried to install graphviz alone. Command output:
```
==> Downloading https://www.mirrorservice.org/sites/distfiles.macports.org/graphviz/graphviz-2.40.1.tar.gz
Already downloaded: /home/eepgcjh/.cache/Homebrew/downloads/1c469743457f48b96f1f3fca3f9444a15736b2840413f31cc7e5f4a6bb5c8510--graphviz-2.40.1.tar.gz
==> ./configure --prefix=/home/eepgcjh/.linuxbrew/Cellar/graphviz/2.40.1 --disable-php --disable-swig --with-quartz --without-freetype2 --without-qt --without-x --without-pangocairo --without-rsvg
==> make install
Last 15 lines from /home/eepgcjh/.cache/Homebrew/Logs/graphviz/02.make:
malloc.c:331:15: error: return type is an incomplete type
 struct mstats mstats(void)
               ^
malloc.c: In function 'mstats':
malloc.c:334:19: error: storage size of 'ms' isn't known
     struct mstats ms;
                   ^
make[3]: *** [malloc.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/tmp/graphviz-20181026-32074-14wrc5f/graphviz-2.40.1/lib/vmalloc'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/tmp/graphviz-20181026-32074-14wrc5f/graphviz-2.40.1/lib'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/tmp/graphviz-20181026-32074-14wrc5f/graphviz-2.40.1'
make: *** [install] Error 2

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."
```

Expected: graphviz compiles and installs

To reproduce: `brew install graphviz`

[Gist](https://gist.github.com/lunik1/775efcec0949c08b6d01654c25c0bb45)

**Comment by msiemens** [comment]
For what it’s worth, I had the same error ...

**Comment by iMichka** [comment]
Looks like:
#10045
and
https://github.com/NixOS/nix-pills/issues/40

Not sure what the solution is. We will need to investigate this looking more closely at the source code and the build process ...

**Comment by iMichka** [comment]
Sorry we could not help you more on this. At first glance it looks like an upstream issue, nothing we can do about. If it builds fine outside of brew for you, it may be a bug in brew (probably a missing dependency). But you will be on your own to debug this.
