### ISSUE TITLE
Formula upx also depends on zlib.

### ISSUE THREAD

**Issue by ivysnow** [Linuxbrew/homebrew-core#10038]
When I install formula upx, I use
# brew install upx
so linuxbrew will make and install formula ucl first, then
> make[1]: Entering directory '/tmp/upx-20181029-170022-1w4npjo/upx-3.95/src'
> Updating .depend
> compress_zlib.cpp:49:10: fatal error: 'zlib.h' file not found
> #include <zlib.h>
>          ^~~~~~~~
> 1 error generated.
> p_vmlinz.cpp:37:10: fatal error: 'zlib.h' file not found
> #include <zlib.h>
>          ^~~~~~~~
> 1 error generated.
> make[1]: *** Deleting file '.depend'
means upx really depends on zlib but not in the formula file.

**Comment by iMichka** [comment]
Hi. It should be enough to add `depends "zlib" unless OS.mac?` to the `ucl` formula. Would you like to open a pull request for that?

**Comment by iMichka** [comment]
Sorry, I ment to add that line to the `upx` formula.

**Comment by ivysnow** [comment]
So how to mark depends in linux only? The formula upx doesn't depend on zlib in macos.

**Comment by iMichka** [comment]
Yes, because on Mac they rely on the preinstalled zlib library. So they do not add the dependency explicitly to the formula. On Linux we need to add it manually though. So adding the line above should fix it on Linux.

**Comment by iMichka** [comment]
Fixed by #10381
