### ISSUE TITLE
libproxy-0.4.15_1 fails to build

### ISSUE THREAD

**Issue by CristianCantoro** [Linuxbrew/homebrew-core#10032]
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/CristianCantoro/b48f2b000cb3092834e20f9d1c8916de
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrading `libproxy`

- What happened (include command output)
Upgrade fails

- What you expected to happen
Upgrade succeeds

- Step-by-step reproduction instructions (by running `brew install` commands)
N/A

**Comment by Char-Aznable** [comment]
I have the same problem here. This is caused by superenv removes the glib.h dependency:
```
g++-5 called with: -D_POSIX_C_SOURCE=200112L -I/scratch/tmp/libproxy-20181106-28548-uoqjrv/libproxy-0.4.15 -I/scratch/.linuxbrew/Cellar/glib/2.58.1/include/glib-2.0 -I/scratch/.linuxbrew/Ce  llar/glib/2.58.1/lib/glib-2.0/include -I/scratch/.linuxbrew/Cellar/pcre/8.42/include -fvisibility=hidden -DNDEBUG -o CMakeFiles/pxgsettings.dir/modules/pxgsettings.cpp.o -c /scratch/tmp/lib  proxy-20181106-28548-uoqjrv/libproxy-0.4.15/libproxy/modules/pxgsettings.cpp
  superenv removed:  -I/scratch/.linuxbrew/Cellar/glib/2.58.1/include/glib-2.0 -I/scratch/.linuxbrew/Cellar/glib/2.58.1/lib/glib-2.0/include -I/scratch/.linuxbrew/Cellar/pcre/8.42/include
  superenv added:    -pipe -w -O2 -march=native -isystem/scratch/.linuxbrew/include
  superenv executed: g++-5 -pipe -w -O2 -march=native -D_POSIX_C_SOURCE=200112L -I/scratch/tmp/libproxy-20181106-28548-uoqjrv/libproxy-0.4.15 -fvisibility=hidden -DNDEBUG -o CMakeFiles/pxgset  tings.dir/modules/pxgsettings.cpp.o -c /scratch/tmp/libproxy-20181106-28548-uoqjrv/libproxy-0.4.15/libproxy/modules/pxgsettings.cpp -isystem/scratch/.linuxbrew/include
```

**Comment by iMichka** [comment]
I pushed a patch for this: #10236

Can you update and try again?

**Comment by CristianCantoro** [comment]
@iMichka wrote:
> Can you update and try again?

It looks like it worked:
```
==> Installing libproxy
==> Downloading https://github.com/libproxy/libproxy/archive/0.4.15.tar.gz
Already downloaded: /home/cristian/.cache/Homebrew/downloads/8a958e74e2f2df2ee8da69026f33208df9eee39c35fc54309ccc0ffe0959fc0a--libproxy-0.4.15.tar.gz
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/cristian/.linuxbrew/Cellar/libproxy/0.4.15_2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND
==> make install
🍺  /home/cristian/.linuxbrew/Cellar/libproxy/0.4.15_2: 18 files, 448.4KB, built in 12 seconds
```

Thanks for your help!
