### ISSUE TITLE
glibc: Compiling with -Os breaks valgrind

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/homebrew-core#1005]
When I run valgrind I see the following error.
```
==11869== Memcheck, a memory error detector
==11869== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==11869== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==11869== Command: ./read
==11869== 
 
valgrind:  Fatal error at startup: a function redirection
valgrind:  which is mandatory for this platform-tool combination
valgrind:  cannot be set up.  Details of the redirection are:
valgrind:  
valgrind:  A must-be-redirected function
valgrind:  whose name matches the pattern:      strlen
valgrind:  in an object with soname matching:   ld-linux-x86-64.so.2
valgrind:  was not found whilst processing
valgrind:  symbols from the object with soname: ld-linux-x86-64.so.2
valgrind:  
valgrind:  Possible fixes: (1, short term): install glibc's debuginfo
valgrind:  package on this machine.  (2, longer term): ask the packagers
valgrind:  for your Linux distribution to please in future ship a non-
valgrind:  stripped ld.so (or whatever the dynamic linker .so is called)
valgrind:  that exports the above-named function using the standard
valgrind:  calling conventions for this platform.  The package you need
valgrind:  to install for fix (1) is called
valgrind:  
valgrind:    On Debian, Ubuntu:                 libc6-dbg
valgrind:    On SuSE, openSuSE, Fedora, RHEL:   glibc-debuginfo
valgrind:  
valgrind:  Cannot continue -- exiting now.  Sorry.
```

I believe this is because binutils is built w/ --disable-debug.

Is there any reason --disable-debug is used in the default binutils formula? Can we make it an optional flag? Otherwise is there a way to require optional flags for dependencies?

**Comment by sjackman** [comment]
I believe it's because `glibc` has `--disable-debug`. In a clean Linuxbrew installation, can you try removing `--disable-debug` from `glibc` before installing `glibc`? If that works, I'll accept a pull request to remove `--disable-debug` from `glibc`.

**Comment by carlorosati** [comment]
That didn't fix it. It looks like it's more complicated than that.
See:
https://wwwtech.de/articles/2012/jan/valgrind-again:-strlen-redirection
https://bugs.kde.org/show_bug.cgi?id=286864

**Comment by carlorosati** [comment]
I fixed this by adding the following line to glibc.rb.
```
ENV["CC"] = "cc  -fno-builtin-strlen"
```
.Do you know a better way to do this?

**Comment by rwhogg** [comment]
Maybe

```ruby
ENV.append "CFLAGS", "-fno-builtin-strlen" if OS.linux?
```

**Comment by sjackman** [comment]
The formula `glibc` is only for Linux, so no need for `if OS.linux?` in this case.

It seems like this bug (`glibc` with `-O2` without `-fno-builtin-strlen` doesn't work with `valgrind`) would make `valgrind` useless on most Linux distributions. I would like to know how this issue is resolved on Debian.

**Comment by carlorosati** [comment]
FWIW, --disable-debug, doesn't actually do anything. It's not even a valid flag.

**Comment by carlorosati** [comment]
I posit that --disable-debug doesn't actually do anything. It's not documented on the glibc wiki, and specifying it doesn't change the Makefile that is generated.

I fixed the issue by building with ```CFLAGS='-O2 -g'```

@sjackman Do you know what the ```--disable-debug``` flag does?

If it's okay I would like to patch and make the pull request by adding the CLFAGS line. Is that okay?

**Comment by sjackman** [comment]
> I posit that `--disable-debug` doesn't actually do anything.

That's quite possible. `--disable-debug` usually disables `-g` and sometimes also disables assertions.

> I fixed the issue by building with CFLAGS='-O2 -g'

Oh? The default on Linuxbrew is `-Os`. Perhaps that's what is breaking `glibc` and `valgrind`.

**Comment by carlorosati** [comment]
Running ```-O2``` "fixed" it. I also tried building with ```-Os -g``` but it did _not_ work.

**Comment by carlorosati** [comment]
@sjackman Is adding ENV.O2 sufficient for a pull request? It seems like it will be fine until gcc changes their O2 optimisations... I don't see a more permanent solution since, -g didn't work.

Also why cannot I push to my own fork of the project? I have followed [the wiki](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) and am seeing the following error message.
```
> git push --set-upstream carlorosati glibcO2
...
To https://github.com/carlorosati/homebrew-core.git
 ! [remote rejected] glibcO2 -> glibcO2 (shallow update not allowed)
error: failed to push some refs to 'https://github.com/carlorosati/homebrew-core.git'

```

**Comment by sjackman** [comment]
Nice troubleshooting, @carlorosati! `glibc` should be built with `-O2` rather than `-Os`. Feel free to submit a PR that adds `ENV.O2` to the `glibc` formula.

**Comment by sjackman** [comment]
You already have submitted a PR #1042. Thanks!
