### ISSUE TITLE
parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by mxplusb** [Linuxbrew/homebrew-core#10066]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to update linuxbrew via `brew update -v`, and ran into this issue. I can reproduce it.

- What happened (include command output)

https://gist.github.com/mxplusb/c6032643872f05a6e6db171efb11ad33

- What you expected to happen

`brew update -v` should continue without error.

- Step-by-step reproduction instructions (by running `brew install` commands)

1. Run `brew update -v` on WSL with Windows 1803 build 17134.376.

I'm not sure if this is directly related, but I have this configuration in WSL for my wsl.conf:

```ini
[automount]
root = /
options = "metadata"
```

They are filesystem configurations, so instead of the Windows directories being mounted on `/mnt`, I mount them at `/` and the filesystem driver should include metadata about the Windows filesystem when in those directories. Linuxbrew is installed on the root Linux pathing, so it's not residing on an external disk, such as `/c` or `/d`.

I did run `brew update -v` twice and `brew doctor`, as the wiki recommends, before running this and the error occurred both times.

**Comment by iMichka** [comment]
We have an open issue for this in the main repo: https://github.com/Linuxbrew/brew/issues/852
