### ISSUE TITLE
util-linux failed: ld: cannot find -lpam

### ISSUE THREAD

**Issue by dornED** [Linuxbrew/homebrew-core#1018]
https://gist.github.com/anonymous/ee97695000df1402681326b654bb46e6

**Comment by sjackman** [comment]
```
libtool: link: /scratch/dornbier/brew/bin/gcc-5 -fsigned-char -fno-common -Wall -Werror=sequence-point -Wextra -Wmissing-declarations -Wmissing-parameter-type -Wmissing-prototypes -Wno-missing-field-initializers -Wredundant-decls -Wsign-compare -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-parameter -Wunused-result -Wunused-variable -Wnested-externs -Wpointer-arith -Wstrict-prototypes -Wimplicit-function-declaration -Os -w -pipe -march=native -Wl,--dynamic-linker=/scratch/dornbier/brew/lib/ld.so -Wl,-rpath -Wl,/scratch/dornbier/brew/lib -o login login-utils/login.o login-utils/logindefs.o  -L/scratch/dornbier/brew/lib ./.libs/libcommon.a -lpam -lpam_misc
/scratch/dornbier/brew/bin/ld: cannot find -lpam
/scratch/dornbier/brew/bin/ld: cannot find -lpam_misc
collect2: error: ld returned 1 exit status
```
https://gist.github.com/anonymous/ee97695000df1402681326b654bb46e6#file-02-make-L830

`util-linux` appears to depend on PAM? I haven't experience that myself. I wonder if a configure option is needed to disable PAM.

**Comment by sjackman** [comment]
If you install Linuxbrew in `/home/linuxbrew/.linuxbrew` you can use the precompiled binary bottle of `util-linux`. You can also try `brew install --force-bottle util-linux`. The bottle is not tagged as being relocatable, so it may or may not work.

**Comment by dornED** [comment]
Wow, that was quick :)

My home is on a network drive, i.e. slow.
But <code>brew install --force-bottle util-linux</code> worked.
Thanks a lot!

I then had another issue with fontconfig (https://gist.github.com/anonymous/9df4a1aca7b2964eca791dfd4330553d), not sure if they are related.
Used <code>--force-bottle</code> again.
That also failed, because of a permissions issue (I don't have access to /usr/share/fonts), so that could also have been the problem.

**Comment by sjackman** [comment]
`fontconfig` shouldn't require write access to `/usr/share/fonts`.

I see this error:
```
/bin/sh: line 1: docbook2pdf: command not found
```
https://gist.github.com/anonymous/9df4a1aca7b2964eca791dfd4330553d#file-02-make-L434

This particular bug has some history: https://github.com/Linuxbrew/legacy-linuxbrew/issues/824

Try
```sh
brew update
brew install fontconfig
```

**Comment by carlorosati** [comment]
I am experiencing this issue as well. looks like we will need to downgrade the version of util-linux. See the following commit excerpt.
```
login: remove non-PAM code
If you need non-PAM login(1) then use shadow-utils or busybox.

Signed-off-by: Karel Zak <kzak@redhat.com>
```
[Source](http://git.kernel.org/cgit/utils/util-linux/util-linux.git/commit/?h=stable/v2.27&id=9244d3c2a60c39c7dd6250a8a6bf13d58bb76414)

@sjackman What do you think?

**Comment by sjackman** [comment]
There's a PR to create a formula for `linux-pam` at https://github.com/Linuxbrew/homebrew-core/pull/1186

**Comment by maxim-belkin** [comment]
try:
```sh
brew tap linuxbrew/extra
brew install linux-pam
brew install util-linux
```

**Comment by carlorosati** [comment]
@maxim-belkin That worked. Is it possible and intended for util-linux to depend on the linuxbrew/extra linux-pam formula?

**Comment by maxim-belkin** [comment]
that's possible, but not intended. There are only a few scenarios under which installation of `util-linux` fails (like yours), so we put `linux-pam` formula to `linuxbrew/extra` tap.

**Comment by carlorosati** [comment]
Is there a linuxbrew util to check if pam is installed? Then we could only require linux-pam from linuxbrew/extra when it isn't already installed. I am assuming the cases when util-linux fails to install are due to pam not being installed (my case).

**Comment by sjackman** [comment]
We generally do not use libraries provided by the host, because it's difficult to know whether the executables that we compile will be compatible with the libraries provided by the host.

I like your solution of `--disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-runuser`, although I believe `--disable-nologin` is not necessary. We could add
```ruby
depends_on "linuxbrew/extra/linux-pam" => :optional
…
args << %w[--disable-chfn-chsh --disable-login --disable-su --disable-runuser] unless build.with? "linux-pam"
system "./configure", …, *args

**Comment by dornED** [comment]
I just wanted to give a quick update.

I tried both options mentioned, namely:
- setting <code>--disable-chfn-chsh --disable-login --disable-su --disable-runuser</code>
- installing the new linux-pam formula, and then installing util-linux

They both work fine for me.

Thanks a lot for resolving this!
