### ISSUE TITLE
texlive: messed up paths

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#10299]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

After installing texlive by `brew install texlive`, all the texlive scripts are looking for the wrong paths. I can confirm that both the bottle and build from source (`--with-full`) versions have the same problems. For example,  `tlmgr version` gives
```
Can't locate TeXLive/TLConfig.pm in @INC (you may need to install the TeXLive::TLConfig module) (@INC contains: /home/linuxbrew/.linuxbrew/Cellar/texlive/texmf-dist/scripts/texlive /home/linuxbrew/.linuxbrew/Cellar/texlive/tlpkg  /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/site_perl/5.28.0/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/site_perl/5.28.0 /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0 /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.28.0/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.28.0) at /home/linuxbrew/.linuxbrew/bin/tlmgr line 100.
```

**Comment by Char-Aznable** [comment]
`kpsewhich -var-value TEXMFHOME` gives `/home/linuxbrew/.linuxbrew/Cellar/texlive/texmf-local` which doesn't exist. Setting `TEXMFLOCAL = $SELFAUTOPARENT/20181101` in `/home/linuxbrew/.linuxbrew/Cellar/texlive/20181101/texmf.cnf` solves the problem. We need some postinstall step to set the texmf paths correctly.

**Comment by iMichka** [comment]
I think @sjackman worked on that formula lately. Shaun, what do you think about this?

**Comment by sjackman** [comment]
Thanks for the bug report, Char. This issue should be resolved by PR https://github.com/Linuxbrew/homebrew-core/pull/10311.
