### ISSUE TITLE
CMakeFiles/Makefile2:2675: recipe for target 'ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/all' failed

### ISSUE THREAD

**Issue by danielaDESM** [Linuxbrew/homebrew-core#10318]
Hi! I hope you can help me. I would like to install PCL V 1.8. For that, I am following this blog:
https://askubuntu.com/questions/916260/how-to-install-point-cloud-library-v1-8-pcl-1-8-0-on-ubuntu-16-04-2-lts-for
I am failing in the installation of VTK. I have tried VTK-7.1.0, VTK-7.1.1, VTK-8.1.2 and in all of them I have the same error:

_make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'lib/libvtkglew-7.1.so.1'. Stop.
CMakeFiles/Makefile2:2675: recipe for target 'ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/all' failed
make[1]: *** [ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2_

So I decided to go with **brew install vtk**. It showed me an error and by following another Bug Report with the same issue I tried **brew audit --strict --online vtk**. The outcome  was an issue with some permissions of the vtk.rb file and after cganging them, I did not have the error again. However, after running again **brew install vtk** I continue having issues:

_make[2]: Leaving directory '/home/daniela/Downloads/VTK-7.1.0/build'
make -f ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/build.make ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/build
make[2]: Entering directory '/home/daniela/Downloads/VTK-7.1.0/build'
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'lib/libvtkglew-7.1.so.1'.  Stop.
make[2]: Leaving directory '/home/daniela/Downloads/VTK-7.1.0/build'
CMakeFiles/Makefile2:2675: recipe for target 'ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/all' failed
make[1]: *** [ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/all] Error 2
make[1]: Leaving directory '/home/daniela/Downloads/VTK-7.1.0/build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2_

Note: I have Ubuntu 16.04 LTS in a PC 64-bit, Intel® Core™ i7-6700 CPU @ 3.40GHz × 8 

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by iMichka** [comment]
Sorry we could not help you on this. VTK does not have a bottle at the moment. It is probably missing some dependencies.

Building vtk is on my to do list for 2019, but I can not promise when I will find time to work on this.
