### ISSUE TITLE
clang-format fails to install

### ISSUE THREAD

**Issue by thedrow** [Linuxbrew/homebrew-core#10368]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/thedrow/2bd702fea1a7b7fbad1373c4488d7a89
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install clang-format
- What happened (include command output)
Got the following exception:
```
Error: An exception occurred within a child process:
  NoMethodError: undefined method `installed?' for OS::Mac::Xcode:Module
Did you mean?  instance_of?
```
- What you expected to happen
clang-format should install and work as expected.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install clang-format
```

**Comment by thedrow** [comment]
Bump

**Comment by iMichka** [comment]
Here is an attempt to get this to build: #10613

Let's continue the discussion there.
