### ISSUE TITLE
Bottle support for Raspberry Pi 3b, 3b+, and friends

### ISSUE THREAD

**Issue by ipatch** [Linuxbrew/homebrew-core#10398]
Is there any plans for getting bottle support for the Raspberry Pi 3b 3b+?  I ask because I just installed linuxbrew on a Raspberry Pi 3b+ and following the instructions on [linuxbrew.sh](linuxbrew.sh) to check and see if the installation was successful or not is to run,

```shell
brew install hello
```

I began the process of running `brew install hello` at ~ **12:20 PM** CST on November 24, 2018, and it is ~ **2:10 PM** CST and the `brew install hello` has not even completed the dependency installation for **hello**.

Being that the Raspi ain't exactly built for super computing or mining crypto or whatever CPU taxing tasks one throws at it.  It only seems logical that having bottle support for such a device that has limited resource would be a moderate to high priority, no?

**Comment by iMichka** [comment]
Hi. I am sorry we did not answer previously but we are quite busy. Building for x68 already eats up the few resources we have, so there is not plan to build bottles for ARM.

I think ideally I would see a project like this start as a fork of linuxbrew, setup the whole infrastructure to build bottles and provide around 1500 to 2000 starting bottles, before we can consider proposing this to our users. We can help if there are any specific questions, but not in fully maintaining such a project for the moment.
