### ISSUE TITLE
gconf: missing dependencies

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#10400]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
brew install gconf
- What happened (include command output)
Build failed with a error:
```
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.22.30/include/gtk-3.0/gdk/gdktypes.h:35:25: fatal error: pango/pango.h: No such file or directory
```
and similar errors resulting from missing dependencies on gtk+3, libxml2, fontconfig...

Build with `--env=std` fixes the issue but I couldn't figure out all the missing deps

**Comment by iMichka** [comment]
`gtk+3` does depend on `pango` and `libxml2`. It is weird that the build fails for you.
I can not reproduce this in our CI env.

If `--env=std` fixes it for you then we have a workaround. It would be good if you could provide a full gist-logs with the build failure. If not, the `.cc` log files would help to find out what our superenv is doing here.

**Comment by iMichka** [comment]
Right, there is an issue with `gconf`. I was confused because the error you had was about `gtk+3`.
I will try to build a bottle for `gconf` here: #10931
