### ISSUE TITLE
"fd" formula installs from source although bottle exists

### ISSUE THREAD

**Issue by falzm** [Linuxbrew/homebrew-core#10429]
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Hi, question: when trying to install the [fd formula](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/fd.rb) brew wants to build it from source, although it looks like there are [bottled versions available](https://bintray.com/linuxbrew/bottles/fd#files): is there a reason why they are not referenced in the formula?

```console
$ brew install fd
==> Installing dependencies for fd: cmake, libssh2, pkg-config, binutils, gdbm, python@2 and
...
```

**Comment by iMichka** [comment]
Hi. This is because we did not create bottle for fd 7.2.0, see #10049

This is due to the fact that rust fails to build.

**Comment by falzm** [comment]
Is it possible to install the previous version? (e.g. 7.1.0)

**Comment by iMichka** [comment]
I was able to build a rust bottle. fd has been updated.

**Comment by falzm** [comment]
Great, thanks!
