### ISSUE TITLE
gnuplot: does not compile with readline 7

### ISSUE THREAD

**Issue by eiennohito** [Linuxbrew/homebrew-core#1043]
Fails with

```
make[2]: Entering directory `/dev/shm/gnuplot-20161012-1066-yd13nv/gnuplot-5.0.4/docs'
lua ../term/lua/gnuplot-tikz.lua termhelp > gnuplot-tikz.help
lua: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
make[2]: *** [gnuplot-tikz.help] Error 127
make[2]: Leaving directory `/dev/shm/gnuplot-20161012-1066-yd13nv/gnuplot-5.0.4/docs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/dev/shm/gnuplot-20161012-1066-yd13nv/gnuplot-5.0.4'
make: *** [all] Error 2
```

Readline was upgraded on 2016-10-03.

**Comment by rwhogg** [comment]
@eiennohito, thanks a bunch for the bug report!

I suspect that the problem is actually with `lua`, not with `gnuplot` itself. I've submitted a PR for a new revision for `lua` to rebuild it against the new `readline` at #1045

**Comment by rwhogg** [comment]
@eiennohito I've merged #1045. Can you please run `brew update`, reinstall `lua` if necessary and then retry the installation?

If `gnuplot` still fails, then I will bump the revision for that too.

Once again, thanks a bunch for the bug report!

**Comment by eiennohito** [comment]
Thank you for the incredibly quick fix.

The sequence of
```
brew update
brew upgrade lua
brew reinstall gnuplot
```
worked.

Closing this issue.

**Comment by rwhogg** [comment]
> Thank you for the incredibly quick fix.

Happy to help :smile_cat:
