### ISSUE TITLE
gettext: failed to build on Ubuntu-16.04

### ISSUE THREAD

**Issue by fabio-porcedda** [Linuxbrew/homebrew-core#1047]
https://gist.github.com/anonymous/c59f649e0b70ca2c299f777b9a99d690

The gettext packages fails to build on "configure" with this error message:

configure: error: C++ preprocessor "/lib/cpp" fails sanity check

The problem is that the host gcc doesn't support g++, I've installed g++ using "brew install gcc" so the "g++" command is available, but the "configure" check the host gcc that doesn't support c++.

There is a way to ignore the host gcc and use brew gcc?

Thanks

**Comment by rwhogg** [comment]
Either of the following should work:

* Pass `--cc=gcc-5` to the brew install command (i.e. `brew install --cc=gcc-5 gettext`)
* Set the environment variable `HOMEBREW_CC` to `gcc-5` and then retry the installation

**Comment by fabio-porcedda** [comment]
Hi whigg,
thanks for suggestion.

Unfortunately the host gcc is gcc-5 so "gcc-5" is the same for the host gcc and brew gcc, so it still fails:

whereis gcc-5
gcc-5: /usr/bin/gcc-5 /usr/share/gcc-5 /home/TMT/fabiopo/.linuxbrew/bin/gcc-5 /usr/share/man/man1/gcc-5.1.g

export HOMEBREW_CC=gcc-5
fabiopo@d0598:~$ brew install --cc=gcc-5 gettext

...
checking if /usr/bin/gcc-5 supports -c -o file.o... (cached) yes
checking whether the /usr/bin/gcc-5 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
...
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/home/TMT/fabiopo/tmp/gettext-20161012-15158-xnwmtr/gettext-0.19.8.1/gettext-runtime/libasprintf':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details

I've tried to use something different than gcc-5, so i've tried to install gcc4* or gcc6 but none of them install because formula "gmp4" fails to builds for the same reason.....

Any new idea?

Thanks in advance

**Comment by rwhogg** [comment]
Ah sorry, my bad. I read "14.04" in the issue title and thought that meant your host GCC was 4.something.

I'd recommend running `sudo apt-get install build-essential`, which depends on the host `g++`, as it is a dependency of Linuxbrew.

Failing that, you might be able to use the alternatives system to make `/usr/bin/gcc` refer to your Linuxbrew GCC (and likewise for `/usr/bin/g++`).

**Comment by fabio-porcedda** [comment]
You are right, the "build-essential" package wasn't installed, my fault.

Thanks a lot.

**Comment by rwhogg** [comment]
> You are right, the "build-essential" package wasn't installed, my fault.

No worries.

> Thanks a lot.

Happy to help :smile_cat:
