### ISSUE TITLE
ci/circleci says test failed but Details page gives 404

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/homebrew-core#1048]
Happens for example in #1042

**Comment by rwhogg** [comment]
Sorry for not getting back to you earlier. Some details of the CircleCI builds are private, so they return a 404 to non-members.

My apologies!

**Comment by sjackman** [comment]
We're unfortunately not able to expose the Circle results to the public due to credentials (tokens) in the build logs. =/ I wish I could.
