### ISSUE TITLE
shellcheck fails to install

### ISSUE THREAD

**Issue by thedrow** [Linuxbrew/homebrew-core#10694]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/b4469d04d5e42d0ca484c15d451af8ad
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Update packages
- What happened (include command output)
brew upgrade
==> Upgrading 1 outdated package:
shellcheck 0.5.0 -> 0.6.0_1
==> Upgrading shellcheck 
==> Downloading https://github.com/koalaman/shellcheck/archive/v0.6.0.tar.gz
Already downloaded: /home/omer/.cache/Homebrew/downloads/00c415cb83d69425845a48ed63547ba1aae2da4dd47bd406364e75a79bcd47a7--shellcheck-0.6.0.tar.gz
==> cabal v1-sandbox init
==> cabal v1-update
==> cabal v1-install --jobs=8 --max-backjumps=100000 --only-dependencies
Last 15 lines from /home/omer/.cache/Homebrew/Logs/shellcheck/03.cabal:
2018-12-16 14:31:10 +0200

cabal
v1-install
--jobs=8
--max-backjumps=100000
--only-dependencies

gcc-5: error: unrecognized command line option '-no-pie'
`gcc-5' failed in phase `C Compiler'. (Exit code: 1)

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."
- What you expected to happen
Shellcheck should compile
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install shellcheck
```

**Comment by root42** [comment]
Same problem here. Ubuntu LTS 18. gcc prior to 6 need -nopie option, later version need -no-pie:

https://bugs.launchpad.net/sbcl/+bug/1668986

**Comment by iMichka** [comment]
I was able to build a bottle with #10796.
If you install brew in `/home/linuxbrew/.linuxbrew` you will be able to use the precompiled bottle.

Is the pie/nopie problem only for `shellcheck`? Or is it a more general problem?

**Comment by thedrow** [comment]
I've only seen it for shellcheck.

**Comment by iMichka** [comment]
I could reproduce this on Ubuntu 18.10, using `brew install shellcheck -svd --cc=gcc`. This forces brew to use the gcc provided by brew, which is gcc5 (I did brew install gcc just before).

If I do not force the compiler, it works fine (with the host gcc 8).

I see that you have the following in your gist-logs:
```
HOMEBREW_CC: gcc-5
HOMEBREW_CXX: g++-5
```
Did you set these env vars somewhere?

**Comment by thedrow** [comment]
No I didn't not.

**Comment by iMichka** [comment]
Can you try:
> brew install gcc@8
> brew install shellcheck -svd --cc=gcc-8

**Comment by thedrow** [comment]
That worked.

**Comment by iMichka** [comment]
Glad to know that we have at least a workaround.

It is weird that it is using brewed gcc 5 to build by default, and not the system gcc. I have exactly the opposite behaviour on my setup.

Anyway, whatever the compiler, I think this is a bug in shellcheck, and needs to be reported to them. As we have a workaround I propose to close this issue. Of course you are free to open a ticket upstream to get cleared up a little bit.
