### ISSUE TITLE
homebrew/php/php56-memcached failed to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by leo108** [Linuxbrew/homebrew-core#1077]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

https://gist.github.com/abc6177a60df806de0c018da6e032dae

It seems like the libmemcached bottle built without the `--enable-sasl` option, which caused this problem.

I have tried `brew install homebrew/php/php56-memcached --disable-memcached-sasl`, but `--disable-memcached-sasl` option didn't passed to `./configure`

**Comment by leo108** [comment]
I have installed sasl by `apt-get install libsasl2-dev`

**Comment by sjackman** [comment]
The Homebrew/php tap is not supported by Linuxbrew. Sorry. 😞

**Comment by leo108** [comment]
@sjackman ,but you can control the `libmemcached` formula, for example, add support for `--enable-sasl` option

**Comment by sjackman** [comment]
Have you tried
```sh
brew install memcached --with-sasl
```

**Comment by leo108** [comment]
@sjackman 

```
brew reinstall memcached --with-sasl
brew reinstall libmemcached
brew install homebrew/php/php56-memcached
```

still the same error

**Comment by sjackman** [comment]
Try both `--with-sasl`? I'm just flinging mud at the wall here.
```
brew reinstall libmemcached --with-sasl
brew reinstall memcached --with-sasl
```

**Comment by leo108** [comment]
I install libmemcached with sasl by `brew reinstall libmemcached --with-sasl`, it download the source and compile with `--with-sasl` option, that works well.

Then `brew install homebrew/php/php56-memcached`, but it reinstall the libmemcached as dependency, this time it doesn't download the source but the bottle file (that built without `--with-sasl` option), so it failed again with the same error

**Comment by sjackman** [comment]
Try
```
brew reinstall php56-memcached --with-sasl
```
