### ISSUE TITLE
docker-compose: error: pyconfig.h: No such file or directory

### ISSUE THREAD

**Issue by RichardJECooke** [Linuxbrew/homebrew-core#1079]
When running `brew docker-compose` on Ubuntu 16.04, after `brew update`ing and `brew doctor`ing I get this error at the end:

``` bash
Last 15 lines from /home/rje/.cache/Homebrew/Logs/docker-compose/11.python:
copying lib/yaml/representer.py -> build/lib.linux-x86_64-2.7/yaml
copying lib/yaml/composer.py -> build/lib.linux-x86_64-2.7/yaml
copying lib/yaml/scanner.py -> build/lib.linux-x86_64-2.7/yaml
running build_ext
creating build/temp.linux-x86_64-2.7
checking if libyaml is compilable
/usr/bin/gcc-5 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Os -w -pipe -march=native -isystem/home/rje/.linuxbrew/include -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
checking if libyaml is linkable
/usr/bin/gcc-5 build/temp.linux-x86_64-2.7/check_libyaml.o -lyaml -o build/temp.linux-x86_64-2.7/check_libyaml
building '_yaml' extension
creating build/temp.linux-x86_64-2.7/ext
/usr/bin/gcc-5 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Os -w -pipe -march=native -isystem/home/rje/.linuxbrew/include -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o
ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory
compilation terminated.
error: command '/usr/bin/gcc-5' failed with exit status 1

```

**Comment by rwhogg** [comment]
Hi @RichardJECooke! 2 questions:

1. Are you using brewed or system Python? If you're using a brewed Python, then you should have pyconfig.h available (under HOMEBREW_PREFIX/include/python2.7/pyconfig.h). If you're using a system Python, you'll need to install `libpython2.7-dev` using Apt.
2. If neither of those two things solve your problem, please run `brew gist-logs docker-compose` and paste the result here please.

Thanks a bunch!

**Comment by RichardJECooke** [comment]
I don't know what Python I'm using, but apt says I have all those packages installed.

But running `touch ~/.linuxbrew/include/pyconfig.h` fixed the install. If this is a vital step shouldn't it be on the homepage or in `brew doctor` or something?

Thanks.

**Comment by rwhogg** [comment]
> But running touch ~/.linuxbrew/include/pyconfig.h fixed the install. If this is a vital step shouldn't it be on the homepage or in brew doctor or something?

We've discussed having a `brew doctor` check for missing Python dev dependencies before, and we definitely should have one (or something similar). We just haven't gotten around to it yet unfortunately.

Running `touch ~/.linuxbrew/include/pyconfig.h` shouldn't be necessary, and since `pyconfig.h` is supposed to contain various `#define` statements I would not recommend doing that. I suspect that none of the definitions are used, since otherwise you'd get a compile error, so it's probably fine as a workaround in this specific case though.
