### ISSUE TITLE
imap-uw: Depends on krb5 and PAM

### ISSUE THREAD

**Issue by alanwillms** [Linuxbrew/homebrew-core#1082]
This happens on Elementary 0.4, but I also tried on Ubuntu 16.04 and Arch Linux with no success.

The first error is this, and I can fix it by installing `libkrb5-dev`:

``` bash
# fix "gssapi/gssapi_generic.h: No such file or directory" error
sudo apt-get install libkrb5-dev
```

But the second error I was not able to fix or find a solution:

``` bash
# trying to fix "pam/pam_appl.h: No such file or directory" error, no success
sudo apt-get install libpam0g-dev
```

I can't get past this `pam/pam_appl.h: No such file or directory` error.

https://gist.github.com/anonymous/6f4df525156ed609ae884ae388c9061a

**Comment by sjackman** [comment]
Attempting to reproduce this error over at #1107.
Install krb5 using `brew install krb5`
PAM is unfortunately not packaged for Linuxbrew. Try
```sh
sudo apt-get install libpam0g-dev
```
See https://packages.debian.org/search?searchon=contents&keywords=pam_appl.h&mode=path&suite=stable&arch=any
