### ISSUE TITLE
Crash when upgrading Subversion

### ISSUE THREAD

**Issue by thedrow** [Linuxbrew/homebrew-core#10919]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/c9565d843a2337b179ae923542820934
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade subversion
- What happened (include command output)
```
==> Upgrading subversion 
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.11.0.tar.bz2
Already downloaded: /home/omer/.cache/Homebrew/downloads/bbfd832d56a567d4d34fa9a7048f111560c40ff1cb1baf2e5ca9e16072f17fe4--subversion-1.11.0.tar.bz2
==> Patching
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Downloading https://www.apache.org/dyn/closer.cgi?path=serf/serf-1.3.9.tar.bz2
==> Downloading from http://apache.mivzakim.net/serf/serf-1.3.9.tar.bz2
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/opt/scons/bin/scons PREFIX=/home/linuxbrew/.linuxbrew/Cellar/subversion/1.11.0_2 GSSAPI=/home/linuxbrew/.linuxbrew/opt/krb5 CC=/home/linuxbrew/.linuxbrew/bin/gcc-5 CFLAGS=-O
==> /home/linuxbrew/.linuxbrew/opt/scons/bin/scons install
Error: An exception occurred within a child process:
  NoMethodError: undefined method `sdk_path_if_needed' for OS::Mac:Module
```
- What you expected to happen
Linuxbrew should not crash.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install subversion
```

**Comment by iMichka** [comment]
Hi. I am trying to get subversion to build here: #10890
