### ISSUE TITLE
libxml2 cannot be compiled same error as in #910

### ISSUE THREAD

**Issue by JuPlutonic** [Linuxbrew/homebrew-core#10962]
It isn't realated to PR to compile libxml2's bottle.

- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by iMichka** [comment]
Hi. I uploaded a new libxml2 bottle with #10957, so you should be able to update now.

I'll close this issue for now, we will try to solve your problem in the other issue as it seems to be the same.
