### ISSUE TITLE
brew install terragrunt is throwing error in ubuntu

### ISSUE THREAD

**Issue by ReddyMalathi** [Linuxbrew/homebrew-core#11065]
Please fill out one of the templates on: https://github.com/Linuxbrew/homebrew-core/issues/new/choose

To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)

We will close issues requesting formulae changes without comment.

**Comment by iMichka** [comment]
Hi. Please fill out the issue template and provide the asked information. Thanks.
