### ISSUE TITLE
mpd (ninja(1.8.2, 1.8.2_1, 1.8.2_2)

### ISSUE THREAD

**Issue by JuPlutonic** [Linuxbrew/homebrew-core#11079]
please providea bottle (last couple of years every mpd update was baggy (every time different bug). Now ```ninja -C output/release``` or Cmake tries to use gcc6, when brew config's - 5.5. What I got after ```mpv install mpd -d``` [gist-logs mpd](https://gist.github.com/9a0cb0ba730b946922430f5c01d06b4).

- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by iMichka** [comment]
Hi. Here is an attempt to get this to build: #11105

**Comment by iMichka** [comment]
I'll close this issue. We can discuss this further on the pull request.
