### ISSUE TITLE
`brew install libscrypt` fails

### ISSUE THREAD

**Issue by lucasyvas** [Linuxbrew/homebrew-core#11153]
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I was just trying to upgrade tor and it looks like it has a new dependency (libscrypt) that now fails. It seems to not have a matching build spec for Linux in the source rb file (problem or not?) and there is no bottle available.

I presume `brew install libscrypt` should reproduce this just fine if it's not only on my end

https://gist.github.com/lucasyvas/0751575ebcabd5e443ada234629e6239

**Comment by iMichka** [comment]
Fixed by #11558
