### ISSUE TITLE
Point Linuxbrew to newer version of gcc

### ISSUE THREAD

**Issue by PrgrmAtCeleritas** [Linuxbrew/homebrew-core#1118]
- [x] Ran `brew update` and retried your prior step
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step

### Bug reports:

The gcc version pointed to by /usr/bin/gcc is 4.3.4, however my path is setup so that version 4.7.2 is used (located in a different place). However when I try to install glibc, it finds the old /usr/bin/gcc version instead of the newer version. I do not have root on this machine and therefore cannot change the link. How can I point linuxbrew to the newer version?

https://gist.github.com/7b2dd7240566fedf02d077fe76c14c4e

**Comment by sjackman** [comment]
Create symlinks named `gcc-4.7` and `g++-4.7` in `$HOMEBREW_PREFIX/bin/`
See https://github.com/Linuxbrew/brew/wiki/Standalone-Installation#create-symlinks-for-gcc
