### ISSUE TITLE
Cannot compile locally

### ISSUE THREAD

**Issue by CeleritasCelery** [Linuxbrew/homebrew-core#1119]
while trying to build xz-5.2.2 ...
error: C compiler cannot create executables 

more information can be found in the gist logs. I know that I can create executables using the C compiler. 
https://gist.github.com/8b5aed064597f586b6f882a408cbf36c

**Comment by sjackman** [comment]
The formula `xz` has a relocatable bottle. Any particular reason that you're building it from source?

You have `glibc` installed but not `gcc`. If possible I'd suggest uninstalling Linuxbrew and the first package that you install ought to be `brew install gcc`

**Comment by PrgrmAtCeleritas** [comment]
Thanks for your reply.
When Linuxbrew tries to download the `xz` bottle I get the following error.

``Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!
Error: Failure while executing: /nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/Cellar/patchelf/0.9_1/bin/patchelf --set-rpath /nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/lib
Warning: Bottle installation failed: building from source.``

that is why I am building from source. 

according to the config file from the gist, I have local copy of `gcc` that linuxbrew is using located at 

`/nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/bin/gcc-4.7`
which is a link to `gcc 4.7.4`
However, I will try your suggestion of reinstalling Linuxbrew and then install its version of `gcc`.

**Comment by sjackman** [comment]
See the warnings output by `brew doctor`
https://gist.github.com/anonymous/8b5aed064597f586b6f882a408cbf36c#file-00-doctor-out

**Comment by PrgrmAtCeleritas** [comment]
I removed and reinstalled Linuxbrew and the first package I installed was `gcc`. Its seemed to install fine but then it encountered problems while creating a spec file seen below
``==> Creating the GCC specs file: specs
Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!
Error: command failed: gcc-5 -dumpspecs``

I tried to run `brew install shellcheck` anyways, but it failed once again saying that I cannot create executables. it seemed to be able to download `xz` (which was giving this error before) but is encountering the problem with `pkg-config`. As you can see in the gist log, there is now a Linuxbrew version of `gcc`, but it still seems like it is trying to use the system version. 

https://gist.github.com/4d092778115cc67c7035a54f930540ad

**Comment by sjackman** [comment]
Strange. Can you report the output of `ls -l $(brew --prefix)/lib/ld.so` ?
Please also report the output of `brew install hello && brew gist-logs hello`

**Comment by PrgrmAtCeleritas** [comment]
output of `ls -l $(brew --prefix)/lib/ld.so` 

`lrwxrwxrwx 1 tjhinckl srvr10nm 102 Oct 27 10:25 /nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/lib/ld.so -> /nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/Cellar/glibc/2.19/lib/ld-linux-x86-64.so.2`

when I run `brew install hello && brew gist-logs hello` I get the following output 

`==> Downloading https://linuxbrew.bintray.com/bottles/hello-2.10.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring hello-2.10.x86_64_linux.bottle.tar.gz
  /nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/Cellar/hello/2.10: 52 files, 595.4K 
Error: No logs.`

no logs are generated.

**Comment by sjackman** [comment]
My mistake. Try
```sh
brew remove hello
brew install -s hello
brew gist-logs hello
```

**Comment by PrgrmAtCeleritas** [comment]
That failed with the same "C compiler cannot create executables" error. 
https://gist.github.com/76000861c76efa8e0dc56a909a937785

**Comment by sjackman** [comment]
```
configure:4014: checking whether the C compiler works
configure:4036: /nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/bin/gcc-4.7 -Os -w -pipe -march=native -isystem/nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/include -L/nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/lib -Wl,--dynamic-linker=/nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/lib/ld.so -Wl,-rpath,/nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/lib conftest.c  >&5
/nfs/sc/itools/em64t_SLES11/pkgs/gcc/4.7.2/.bin/../lib64/gcc/x86_64-suse-linux/4.7.2/../../../../x86_64-suse-linux/bin/ld: BFD (GNU Binutils) 2.23 internal error, aborting at reloc.c line 444 in bfd_get_reloc_size

/nfs/sc/itools/em64t_SLES11/pkgs/gcc/4.7.2/.bin/../lib64/gcc/x86_64-suse-linux/4.7.2/../../../../x86_64-suse-linux/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
```
https://gist.github.com/anonymous/76000861c76efa8e0dc56a909a937785#file-config-log-L104

**Comment by sjackman** [comment]
`BFD (GNU Binutils) 2.23 internal error, aborting at reloc.c line 444 in bfd_get_reloc_size`

Looks like a bug in binutils.
Please report
```sh
which -a ld
brew list --versions binutils
```

Try `brew install binutils`

**Comment by PrgrmAtCeleritas** [comment]
`which -a ld`
`/nfs/sc/disks/sdg74_1185/tjhinckl/personal/github/linuxbrew/bin/ld`
`/nfs/site/home/tjhinckl/.linuxbrew/bin/ld`
`/nfs/site/home/tjhinckl/.linuxbrew/bin/ld`
`/usr/bin/ld`
`/usr/bin/X11/ld`

`brew list --versions binutils`
`binutils 2.27`

`brew install binutils`
`Warning: binutils-2.27 already installed`

I also tried to remove and reinstall. Installed fine.

**Comment by sjackman** [comment]
The issue is that your compiler `gcc-4.7` is picking up `ld` 2.23 from
`/nfs/sc/itools/em64t_SLES11/pkgs/gcc/4.7.2/.bin/../lib64/gcc/x86_64-suse-linux/4.7.2/../../../../x86_64-suse-linux/bin/ld` rather than the `ld` 2.27 installed by Linuxbrew. I'm not sure why that should be. Double check the `$(brew --prefix)/bin` is first in your `PATH`. If you have a systems/IT/IS group, you may want to ask them for help in troubleshooting.
