### ISSUE TITLE
teleport won't build

### ISSUE THREAD

**Issue by klauern** [Linuxbrew/homebrew-core#11264]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/1f18eadbfd99cb7d4c9037a475ab3575

To help us debug your issue please explain:

- What you were trying to do (and why)
Attempted to install `teleport` on WSL on Ubuntu 18.04.1

- What happened (include command output)

https://gist.github.com/1f18eadbfd99cb7d4c9037a475ab3575

```
$ brew install teleport
Updating Homebrew...
==> Downloading https://github.com/gravitational/teleport/archive/v3.1.3.tar.gz
Already downloaded: /home/klauer/.cache/Homebrew/downloads/1eb394524abe5d892e958d53598520455592c7196e7351ac3e04c872729671d4--teleport-3.1.3.tar.gz

Warning: Calling MacOS.prefer_64_bit? is deprecated! There is no replacement.
Please report this to the homebrew/core tap:
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/teleport.rb:20

==> make full
Last 15 lines from /home/klauer/.cache/Homebrew/Logs/teleport/01.make:
VERSION=3.1.3 /usr/bin/make -f version.mk setver
make[1]: Entering directory '/tmp/teleport-20190118-27825-1gizxlr/teleport-3.1.3/src/github.com/gravitational/teleport'
fatal: not a git repository (or any of the parent directories): .git
make[1]: Leaving directory '/tmp/teleport-20190118-27825-1gizxlr/teleport-3.1.3/src/github.com/gravitational/teleport'
---> Building OSS binaries.
/usr/bin/make build/teleport build/tctl build/tsh
make[1]: Entering directory '/tmp/teleport-20190118-27825-1gizxlr/teleport-3.1.3/src/github.com/gravitational/teleport'
GOOS=`go env GOOS` GOARCH=`go env GOARCH` CGO_ENABLED=1 go build  -o build/teleport  -ldflags '-w -s' ./tool/teleport
# net
/home/linuxbrew/.linuxbrew/opt/go/libexec/src/net/cgo_bsd.go:15:72: could not determine kind of name for C.AI_MASK
Makefile:76: recipe for target 'build/teleport' failed
make[1]: *** [build/teleport] Error 2
make[1]: Leaving directory '/tmp/teleport-20190118-27825-1gizxlr/teleport-3.1.3/src/github.com/gravitational/teleport'
Makefile:62: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
```

- What you expected to happen

It would install
- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install teleport`

**Comment by iMichka** [comment]
Hi. I am attempting to fix this here: #11268

We can discuss this further on the pull request, I'll close this issue.
