### ISSUE TITLE
neomutt requires libsasl2 to complete installation

### ISSUE THREAD

**Issue by ipatch** [Linuxbrew/homebrew-core#11302]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Tried installing neomutt with,

```sh
brew install neomutt
```

- What happened (include command output)

Installation failed due to requiring a dependency of libsasl2

```
==> Installing neomutt
==> Downloading https://github.com/neomutt/neomutt/archive/neomutt-20180716.tar.gz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/neomutt/20180716 --enable-gpgme --gss --lmdb --n
Last 15 lines from /home/capin/.cache/Homebrew/Logs/neomutt/01.configure:
Checking for strsep...ok
Checking for vasprintf...ok
Checking for wcscasecmp...ok
Checking libs for gethostent...none needed
Checking libs for setsockopt...none needed
Checking libs for getaddrinfo_a...-lanl
Checking for xsltproc...ok
Checking for DocBook DTDs...yes
Checking for gpgme.h...ok
Checking libs for gpgme_new...-lgpgme
Checking for gpgme_op_export_keys...ok
Checking for sasl/sasl.h...not found
Checking for sasl/sasl.h...(cached) not found
Error: Unable to find SASL
Try: 'configure --help' for options
``` 
- What you expected to happen

expected neomutt to successfully install on Debian 9.6 stretch

- Step-by-step reproduction instructions (by running `brew install` commands)

```sh
brew install neomutt
```

☝️ The above command did not complete successfully until I installed libsasl2

```sh
brew install libsasl2
```

**Comment by iMichka** [comment]
Hi. I am attempting to build a neomutt bottle here: #11313

Closing this issue, we can continue to discuss this on the pull request itself.
