### ISSUE TITLE
geos: cannot find Python library path

### ISSUE THREAD

**Issue by ptitle** [Linuxbrew/homebrew-core#11339]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/8fe78bd0e036e52fdef3b5cfe4fadb02
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I am trying to install geos, mainly as it is a dependency for gdal and for some R packages that I use. However, if I run `brew install geos`, I get the following:

```
[ptitle@iu-eri-006207 ~]$ brew install geos
==> Downloading https://download.osgeo.org/geos/geos-3.7.1.tar.bz2
Already downloaded: /home/ptitle@ads.iu.edu/.cache/Homebrew/downloads/b39bdca9401be0f91056345a7d2c044869892eaf2fc4367cdae8b8de82112803--geos-3.7.1.tar.bz2
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/geos/3.7.1_1 --enable-python PYTHON=/home/linuxbrew/.linuxbrew/opt/python/bin/pytho
Last 15 lines from /home/ptitle@ads.iu.edu/.cache/Homebrew/Logs/geos/01.configure:
checking for isfinite... yes
checking for isnan... yes
checking whether int64_t is 64 bits... no
checking whether long long int is 64 bits... yes
checking for swig... /home/linuxbrew/.linuxbrew/opt/swig/bin/swig
checking for SWIG version... 3.0.12
configure: SWIG executable is '/home/linuxbrew/.linuxbrew/opt/swig/bin/swig'
configure: SWIG library directory is '/home/linuxbrew/.linuxbrew/Cellar/swig/3.0.12/share/swig/3.0.12'
checking for python version... 3.7
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.7/site-packages
checking for Python include path... /home/linuxbrew/.linuxbrew/opt/python/include/python3.7m
checking for Python library path... 
configure: error: cannot find Python library path

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."

These open issues may also help:
geos: Build a bottle for Linuxbrew https://github.com/Linuxbrew/homebrew-core/pull/11217
```

I did a `brew pull` on the link provided at the end, but that did not change anything on my end.

**Comment by iMichka** [comment]
I am working on this here: #11217 It will be fixed once this PR works.

I'll close here, we can continue the discussion on the PR.
