### ISSUE TITLE
bugs when install biobakery/biobakery/lefse 

### ISSUE THREAD

**Issue by lixuenan** [Linuxbrew/homebrew-core#11459]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

brew install biobakery/biobakery/lefse
==> Tapping biobakery/biobakery
Error: Version value must be a string; got a NilClass ()
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/version.rb:196:in `initialize'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/tap.rb:252:in `new'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/tap.rb:252:in `install'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/install.rb:83:in `block in install'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/install.rb:77:in `each'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/install.rb:77:in `install'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'
[lixn@cluster bin]$ brew update
Already up-to-date.
[lixn@cluster bin]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: /gpfs/users/lixn/soft/R-3.3.3/lib:/state/partition1/home/lixn/.linuxbrew/Cellar/openblas/0.2.18_2/lib:LD_LIBRARY_PATH

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /export/home/lixn/.linuxbrew/bin/xml2-config
  /export/home/lixn/.linuxbrew/bin/pkg-config
  /export/home/lixn/.linuxbrew/bin/Magick++-config
  /export/home/lixn/.linuxbrew/bin/libpng16-config
  /export/home/lixn/.linuxbrew/bin/MagickWand-config
  /export/home/lixn/.linuxbrew/bin/python2.7-config
  /export/home/lixn/.linuxbrew/bin/Wand-config
  /export/home/lixn/.linuxbrew/bin/ncurses6-config
  /export/home/lixn/.linuxbrew/bin/python2-config
  /export/home/lixn/.linuxbrew/bin/curl-config
  /export/home/lixn/.linuxbrew/bin/MagickCore-config
  /export/home/lixn/.linuxbrew/bin/pcre-config
  /export/home/lixn/.linuxbrew/bin/freetype-config
  /export/home/lixn/.linuxbrew/bin/ncursesw6-config
  /export/home/lixn/.linuxbrew/bin/libpng-config
  /export/home/lixn/.linuxbrew/bin/python-config
  /export/home/lixn/.linuxbrew/bin/Magick-config
  /usr/local/bin/python3.6-config
  /usr/local/bin/python3.7m-config
  /usr/local/bin/python3-config
  /usr/local/bin/python3.7-config
  /usr/local/bin/python3.6m-config
  /usr/local/bin/gsl-config
  /opt/ganglia/bin/ganglia-config
  /opt/rocks/bin/python-config
  /opt/rocks/bin/io_lib-config
  /opt/rocks/bin/python2.6-config
  /opt/rocks/bin/xml2-config
Error: /state/partition1/home/lixn/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:83: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/state/partition1/home/lixn/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:86: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/state/partition1/home/lixn/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:86: syntax error, unexpected ':', expecting keyword_end
/state/partition1/home/lixn/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:87: dynamic constant assignment
      PATH="#{opt_libexec}/gnubin:$PATH"
           ^
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formulary.rb:97:in `load_file'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formulary.rb:88:in `klass'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formulary.rb:222:in `factory'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/formula.rb:1413:in `[]'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/diagnostic.rb:973:in `check_for_non_prefixed_coreutils'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/state/partition1/home/lixn/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by iMichka** [comment]
Hi. You need to report this here: https://github.com/biobakery/homebrew-biobakery
