### ISSUE TITLE
undefined method `active_developer_dir' for OS::Mac:Module

### ISSUE THREAD

**Issue by koustav-pal** [Linuxbrew/homebrew-core#11484]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Regarding doctor

I ran doctor and the warnings that are there cannot be solved on my end as brew exists as a user installation. I do not have admin access.

# Output from brew gist-logs

Output from `brew gist-logs git`

https://gist.github.com/9887f1055e2269212173b19d26b60529

# What you were trying to do (and why)

Trying to run a brew update

# What happened (include command output)

brew is unable to install git.

<details>
  <summary>brew update</summary>
  <pre>
 ==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.20.1.tar.xz
Already downloaded: /storage/home/kpal/.cache/Homebrew/downloads/063b2cbf0886d9a7b67b41fcd6192398f8a9a8e44bbb7e9c216cedf1f6448401--git-2.20.1.tar.xz 
Error: An exception occurred within a child process:
  NoMethodError: undefined method `active_developer_dir' for OS::Mac:Module
Already up-to-date.

  </pre>
</details>

# What you expected to happen

For brew to replace the system default git version

# Step-by-step reproduction instructions (by running `brew` commands)

I first ran `brew config` and this is my system configuration.

```
brew config
HOMEBREW_VERSION: >=1.7.1 (shallow or no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1920eecb7104301647af0bcf548144f2d85f4e27
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 5a89a20d59f0bbdd5251fe0c5fe7f47de6c83792
Core tap last commit: 19 hours ago
HOMEBREW_PREFIX: /storage/home/kpal/.linuxbrew
HOMEBREW_REPOSITORY: /storage/home/kpal/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /storage/home/kpal/.linuxbrew/Cellar
HOMEBREW_CACHE: /storage/home/kpal/.cache/Homebrew
HOMEBREW_LOGS: /storage/home/kpal/.cache/Homebrew/Logs
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
CPU: 128-core 64-bit unknown_0x17_0x1
Homebrew Ruby: 2.3.7 => /storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 1.8.3.1 => /bin/git
Curl: 7.63.0 => /storage/home/kpal/.linuxbrew/opt/curl/bin/curl
Kernel: Linux 3.10.0-957.1.3.el7.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 7.6 (Maipo) (Maipo)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_4
xorg: N/A
```
### System information

My system version is RHEL 7 or 3.10.0-957.1.3.el7.x86_64. This is from `uname -a`.

It seems to be a problem originating only with the `git.rb` file. As other packages install cleanly.

```
brew reinstall bison
==> Reinstalling bison
==> Downloading https://ftp.gnu.org/gnu/bison/bison-3.2.4.tar.gz
Already downloaded: /storage/home/kpal/.cache/Homebrew/downloads/7c1b9811f985eb6bae32f5cdf4dc2dded2479eca7faac5730ae6ec5284498182--bison-3.2.4.tar.gz
==> ./configure --prefix=/storage/home/kpal/.linuxbrew/Cellar/bison/3.2.4
==> make install
🍺  /storage/home/kpal/.linuxbrew/Cellar/bison/3.2.4: 128 files, 3MB, built in 59 seconds
```

```
brew install git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.20.1.tar.xz
Already downloaded: /storage/home/kpal/.cache/Homebrew/downloads/063b2cbf0886d9a7b67b41fcd6192398f8a9a8e44bbb7e9c216cedf1f6448401--git-2.20.1.tar.xz
Updating Homebrew...
Error: An exception occurred within a child process:
  NoMethodError: undefined method `active_developer_dir' for OS::Mac:Module
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.20.1.tar.xz
Already downloaded: /storage/home/kpal/.cache/Homebrew/downloads/063b2cbf0886d9a7b67b41fcd6192398f8a9a8e44bbb7e9c216cedf1f6448401--git-2.20.1.tar.xz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `active_developer_dir' for OS::Mac:Module
```

## Debug output

```
/storage/home/kpal/.linuxbrew/opt/curl/bin/curl -q --show-error --user-agent Linuxbrew/1.X.Y\ \(Linux\;\ x86_64\ \"Red\ Hat\ Enterprise\ Linux\ Server\ release\ 7.6\ \(Maipo\)\"\)\ curl/7.63.0 --location --silent --head https://www.kernel.org/pub/software/scm/git/git-2.20.1.tar.xz
Already downloaded: /storage/home/kpal/.cache/Homebrew/downloads/063b2cbf0886d9a7b67b41fcd6192398f8a9a8e44bbb7e9c216cedf1f6448401--git-2.20.1.tar.xz
tar xf /storage/home/kpal/.cache/Homebrew/downloads/063b2cbf0886d9a7b67b41fcd6192398f8a9a8e44bbb7e9c216cedf1f6448401--git-2.20.1.tar.xz -C /tmp/d20190201-87962-1cilzxh
cp -pR /tmp/d20190201-87962-1cilzxh/git-2.20.1/. /tmp/git-20190201-87962-sff04r/git-2.20.1
/storage/home/kpal/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb:63:in `install'
NoMethodError: undefined method `active_developer_dir' for OS::Mac:Module
1. raise
2. backtrace
3. shell
Choose an action: 2
/storage/home/kpal/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb:63:in `install'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:22:in `block in install'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:92:in `debrew'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:22:in `install'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/build.rb:143:in `block (2 levels) in install'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1136:in `block in brew'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2057:in `block (2 levels) in stage'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:539:in `with_env'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2056:in `block in stage'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:103:in `block in unpack'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:173:in `block in mktemp'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:172:in `mktemp'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:98:in `unpack'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:75:in `stage'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2032:in `stage'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1131:in `brew'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:539:in `with_env'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/build.rb:111:in `install'
/storage/home/kpal/.linuxbrew/Homebrew/Library/Homebrew/build.rb:192:in `<main>'
```

**Comment by iMichka** [comment]
Fixed by #11486
