### ISSUE TITLE
ffmpeg: libsnappy not found

### ISSUE THREAD

**Issue by anishmittal2020** [Linuxbrew/homebrew-core#11482]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  - install  ffmpeg
- What happened (include command output)
```
$ brew install  ffmpeg
==> Downloading https://ffmpeg.org/releases/ffmpeg-4.1.tar.xz
Already downloaded: /home/nikhil/.cache/Homebrew/downloads/27fcba847bcc5ded1bba5cb5806ebf007aa67865fb5f3c29ea945a0d62b5a54e--ffmpeg-4.1.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/ffmpeg/4.1_3 --enable-shared --enable-pth
Last 15 lines from /home/nikhil/.cache/Homebrew/Logs/ffmpeg/01.configure:
--enable-frei0r
--enable-libass
--enable-libopencore-amrnb
--enable-libopencore-amrwb
--enable-librtmp
--enable-libspeex
--enable-videotoolbox

ERROR: libsnappy not found
```
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
brew gist-logs ffmpeg: [ffmpeg on Ubuntu 18.04.1 LTS - Homebrew build logs](https://gist.github.com/Agarwal-Nikhil/1cfee1c3605d663d490b9aee18284370)

**Comment by iMichka** [comment]
This has been fixed now, and a new bottle has been uploaded: #11624
