### ISSUE TITLE
Use a XDG directory instead of the ~/

### ISSUE THREAD

**Issue by pofl** [Linuxbrew/homebrew-core#11513]
Is there a reason why linuxbrew installs to ~/.linuxbrew and not ~/.config or ~/.local?

**Comment by iMichka** [comment]
Hi. Yes, there is a reason. From the docs:
```
The installation script installs Linuxbrew to /home/linuxbrew/.linuxbrew using sudo if possible and in your home directory at ~/.linuxbrew otherwise. Linuxbrew does not use sudo after installation. Using /home/linuxbrew/.linuxbrew allows the use of more binary packages (bottles) than installing in your personal home directory.
```

Binary files (bottles) are built against that path (`/home/linuxbrew/.linuxbrew`). We recommend you to setup that path to benefit from the pre-built binaries.

That kind of questions are also better to be discussed on our discourse: https://discourse.brew.sh/c/linuxbrew
