### ISSUE TITLE
libgsm: "cannot open linker script file ompatibility_version"

### ISSUE THREAD

**Issue by slhck** [Linuxbrew/homebrew-core#11608]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? See: https://gist.github.com/slhck/c2ea31e32359c56cf81af0e73999313d
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why): Install `libgsm`
- What happened (include command output):

```
➜ brew install libgsm
==> Downloading http://www.quut.com/gsm/gsm-1.0.18.tar.gz
Already downloaded: /home/werner/.cache/Homebrew/downloads/9ec8daff2437f0ae6fcc2b5b357e1cf23053069244d6917f06c2bed3f1d52a1b--gsm-1.0.18.tar.gz
==> Downloading https://gist.githubusercontent.com/dholm/5840964/raw/1e2bea34876b3f7583888b2284b0e51d6f0e21f4/gistfile1.txt
Already downloaded: /home/werner/.cache/Homebrew/downloads/96d7ee653366d28d31928b3b2be2c90219eebe60cfd6eafdffe27782a29b71d5--gistfile1.txt
==> Patching
==> Applying gistfile1.txt
patching file Makefile
==> make lib/libgsm.1.0.13.dylib CC=gcc-8 CCFLAGS=-c -O2 -DNeedFunctionPrototypes=1 LDFLAGS=
Last 15 lines from /home/werner/.cache/Homebrew/Logs/libgsm/01.make:
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/rpe.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/gsm_destroy.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/gsm_decode.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/gsm_encode.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/gsm_explode.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/gsm_implode.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/gsm_create.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/gsm_print.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/gsm_option.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/short_term.c
gcc-8 -c -O2 -DNeedFunctionPrototypes=1 -DSASR     -DWAV49  -I./inc src/table.c
gcc-8 -o ./lib/libgsm.1.0.13.dylib -dynamiclib -Wl,-compatibility_version,1,-current_version,1.0.13,-install_name,./lib/libgsm.1.0.13.dylib ./src/add.o ./src/code.o ./src/debug.o ./src/decode.o ./src/long_term.o ./src/lpc.o ./src/preprocess.o ./src/rpe.o ./src/gsm_destroy.o ./src/gsm_decode.o ./src/gsm_encode.o ./src/gsm_explode.o ./src/gsm_implode.o ./src/gsm_create.o ./src/gsm_print.o ./src/gsm_option.o ./src/short_term.o ./src/table.o -lc
/usr/bin/ld: cannot open linker script file ompatibility_version: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:304: lib/libgsm.1.0.13.dylib] Error 1
```

- What you expected to happen: The build succeeds

- Step-by-step reproduction instructions (by running `brew install` commands): `brew install libgsm`

**Comment by iMichka** [comment]
Fixed by #11611
