### ISSUE TITLE
shared-mime-info: "Your intltool is too old." – but it's not

### ISSUE THREAD

**Issue by slhck** [Linuxbrew/homebrew-core#11643]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? --> https://gist.github.com/slhck/d54ee289cee9a3966d3fdfe35835a3fa
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): install `shared-mime-info` (it came as a dependency)
- What happened (include command output)

```
➜ brew upgrade shared-mime-info
==> Upgrading 1 outdated package:
shared-mime-info 1.10 -> 1.12
==> Upgrading shared-mime-info 
==> Downloading https://gitlab.freedesktop.org/xdg/shared-mime-info/uploads/80c7f1afbcad2769f38aeb9ba6317a51/shared-mime-info-1.12.tar.xz
Already downloaded: /home/werner/.cache/Homebrew/downloads/bb212c7d7dc57e46f2886e4415d2f6acf8c919063b8ecf77c3ee918769e6f3cc--shared-mime-info-1.12.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/shared-mime-info/1.12 --disable-update-mimedb
Last 15 lines from /home/werner/.cache/Homebrew/Logs/shared-mime-info/01.configure:
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc-8 accepts -g... yes
checking for gcc-8 option to accept ISO C89... none needed
checking whether gcc-8 understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc-8... none
checking for an ANSI C-conforming const... yes
checking whether NLS is requested... yes
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^(.*)\${ <-- HERE ?([A-Z_]+)}?(.*)$/ at /home/linuxbrew/.linuxbrew/opt/intltool/bin/intltool-update line 1066.
checking for intltool >= 0.35.0...  found
configure: error: Your intltool is too old.  You need intltool 0.35.0 or later.
```

But for intltool I get:

```
➜ brew upgrade intltool
Error: intltool 0.51.0_1 already installed
```

- What you expected to happen: `brew install shared-mime-info` succeeds

**Comment by iMichka** [comment]
I updated the bottle here: #11641. You should be able to install this now.

`shared-mime-info` depends on `intltool`, it probably picks up your system version of it. I already saw that error somewhere else. Unless somebody has time to fix this, I propose to close this issue as we have now a bottle for this.

**Comment by slhck** [comment]
I can confirm it works now with the bottle. Thanks!
