### ISSUE TITLE
php pecl install swoole  failed

### ISSUE THREAD

**Issue by jk2K** [Linuxbrew/homebrew-core#11646]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/jk2K/9f9cd115b81248a554dc8f8fefd2b458

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

### What you were trying to do (and why)
I want to install php extension [swoole](https://www.swoole.co.uk/)

### What happened (include command output)

```plain
Build process completed successfully
Installing '/home/linuxbrew/.linuxbrew/Cellar/php/7.3.2/include/php/ext/swoole/config.h'
Installing '/home/linuxbrew/.linuxbrew/Cellar/php/7.3.2/pecl/20180731/swoole.so'

Warning: mkdir(): File exists in System.php on line 294
PHP Warning:  mkdir(): File exists in /home/linuxbrew/.linuxbrew/Cellar/php/7.3.2/share/php/pear/System.php on line 294

Warning: mkdir(): File exists in /home/linuxbrew/.linuxbrew/Cellar/php/7.3.2/share/php/pear/System.php on line 294
ERROR: failed to mkdir /home/linuxbrew/.linuxbrew/Cellar/php/7.3.2/pecl/20180731
```

I tried below
```
$ ls -l /home/linuxbrew/.linuxbrew/Cellar/php/7.3.2/pecl
lrwxrwxrwx 1 lee lee 39 Feb 14 00:08 /home/linuxbrew/.linuxbrew/Cellar/php/7.3.2/pecl -> /home/linuxbrew/.linuxbrew/lib/php/pecl
$ ls /home/linuxbrew/.linuxbrew/Cellar/php/7.3.2/pecl/
ls: cannot access '/home/linuxbrew/.linuxbrew/Cellar/php/7.3.2/pecl/': No such file or directory
```

### What you expected to happen
successful installation

### Step-by-step reproduction instructions (by running `brew install` commands)
```bash
sudo apt install libssl-dev libnghttp2-dev
brew install php
pecl install swoole
```

**Comment by iMichka** [comment]
Hi.

> sudo apt install libssl-dev libnghttp2-dev

You do not need to do that. We ship our own dependencies.

> brew install php

Did this one work?

> pecl install swoole

If it fails here, it is a problem with `pecl`. As this is a third-party tool, I have no control on that and can not really help if it fails. You may open a bug on the `pecl` bug tracker.

**Comment by jk2K** [comment]
`libssl-dev` and `libnghttp2-dev` is required to install swoole, they are not php dependencies, I am trying to solve this problem

**Comment by iMichka** [comment]
I think it would be better if you ask this question on our discourse (https://discourse.brew.sh) or on the swoole issue tracker.

I do not believe this is an issue with Linuxbrew.
