### ISSUE TITLE
While installing brew in bash(in windows ) it is failed and giving me error when trying to reinstall 

### ISSUE THREAD

**Issue by dileepmatha** [Linuxbrew/homebrew-core#11701]
Please fill out one of the templates on: https://github.com/Linuxbrew/homebrew-core/issues/new/choose

To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)

We will close issues requesting formulae changes without comment.

**Comment by dileepmatha** [comment]
when trying to run this command  **"brew install fceux"**
I am getting the error
E: Linuxbrew directory detected, but it seems to be broken.                                                                Try to remove '/home/dileep/.linuxbrew' and try again.

**Comment by aswger** [comment]
It seems duplicate to #11702
