### ISSUE TITLE
brew Installation broken 

### ISSUE THREAD

**Issue by dileepmatha** [Linuxbrew/homebrew-core#11702]
getting error when running the command **brew install fceux**

E: Linuxbrew directory detected, but it seems to be broken.                                                                Try to remove '/home/dileep/.linuxbrew' and try again.

**Comment by aswger** [comment]
may be you should reinstall linuxbrew again using official proedure. And make sure you install it in /home/linuxbrew/.linuxbrew so you can use prebuilt bottle so you won't need to install from source for several formulas

**Comment by iMichka** [comment]
Hi. Your setup maybe broken. Delete Linuxbrew and try to install it again.

And by the way:
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
