### ISSUE TITLE
fontconfig: docbook2pdf: command not found

### ISSUE THREAD

**Issue by kdfred** [Linuxbrew/homebrew-core#1177]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Getting error when installing fontconfig:

```
make install RUN_FC_CACHE_TEST=false
Last 15 lines from /home1/04497/kdfred/.cache/Homebrew/Logs/fontconfig/02.make:
Working on: /tmp/fontconfig-20161101-13973-1942wm9/fontconfig-2.12.1/doc/fontconfig-user.sgml
Using catalogs: /etc/sgml/sgml-docbook-3.1-1.0-51.el6.cat
Using stylesheet: /usr/share/sgml/docbook/utils-0.6.14/docbook-utils.dsl#html
Working on: /tmp/fontconfig-20161101-13973-1942wm9/fontconfig-2.12.1/doc/local-fontconfig-devel.sgml
Using catalogs: /etc/sgml/sgml-docbook-3.1-1.0-51.el6.cat
Using stylesheet: /usr/share/sgml/docbook/utils-0.6.14/docbook-utils.dsl#html
Working on: /tmp/fontconfig-20161101-13973-1942wm9/fontconfig-2.12.1/doc/fontconfig-devel.sgml
Using catalogs: /etc/sgml/sgml-docbook-3.1-1.0-51.el6.cat
Using stylesheet: /usr/share/sgml/docbook/utils-0.6.14/docbook-utils.dsl#print
Working on: /tmp/fontconfig-20161101-13973-1942wm9/fontconfig-2.12.1/doc/local-fontconfig-devel.sgml
nsgmls:(invalid location):E: invalid filename ""
make[2]: Leaving directory `/tmp/fontconfig-20161101-13973-1942wm9/fontconfig-2.12.1/doc'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/tmp/fontconfig-20161101-13973-1942wm9/fontconfig-2.12.1/doc'
make: *** [install-recursive] Error 1
```

https://gist.github.com/2c53d44f834ab3641ede51f1cf7d6e0b

### Formula Requests:

**Please note by far the quickest way to get a new formula into Linuxbrew is to file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sjackman** [comment]
```
/bin/sh: line 1: docbook2pdf: command not found
```
https://gist.github.com/anonymous/2c53d44f834ab3641ede51f1cf7d6e0b#file-02-make-L434

**Comment by sjackman** [comment]
You have a couple of options.

1. Reinstall Linuxbrew in `/home/linuxbrew/.linuxbrew` to use the precompiled bottle of `fontconfig`.
2. Install `docbook-utils` using yum with `sudo yum install /usr/bin/docbook2pdf`

**Comment by kdfred** [comment]
"brew install fontconfig --without-docs" fixed the issue.
