### ISSUE TITLE
gtk cannot open display

### ISSUE THREAD

**Issue by kdfred** [Linuxbrew/homebrew-core#1180]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ X] Ran `brew update` and retried your prior step?
- [X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Using Linuxbrew to install packages on a cluster (I do not have root access). In python, when I import gtk I get the error:

/home1/04497/kdfred/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)

Also when I run 'xhost +' I get the error:

xhost:  unable to open display ":0.0"

When I ssh into other clusters, I do not have any issues with X displays.

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Linuxbrew is to file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sjackman** [comment]
The `DISPLAY` environment variable does not appear to be set correctly. This issue is unrelated to Linuxbrew.
Try…
```sh
ssh -X your.host.name
echo $DISPLAY
xeyes
```
