### ISSUE TITLE
openssl@1.1: unrecognized command line option '-arch'

### ISSUE THREAD

**Issue by iggyvolz** [Linuxbrew/homebrew-core#1187]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

Openssl is complaining with:
`gcc-5: error: x86_64: No such file or directory
gcc-5: error: unrecognized command line option '-arch'`

Full gist-log: https://gist.github.com/7169ef43ce6f387d41aa6cbbc82f663d

Looks like the -arch argument is [Mac-only](http://stackoverflow.com/a/8184661), so Linuxbrew needs to use CFLAGS instead.

**Comment by sjackman** [comment]
I've opened PR #1189 to address this build error.

**Comment by andrewyatz** [comment]
Love to know if there's a fix to this problem as I've just bumped into it whilst trying to install Ansible. Checking #1189 suggests it's not working 100% perfectly well.

**Comment by sjackman** [comment]
I've merged PR #1189, which at least will fix the error `unrecognized command line option '-arch'`. It builds on Travis, but fails on Circle CI with the error `undefined reference to 'OPENSSL_sk_push'`. Try it out. I'd be curious to hear if it works for you.
