### ISSUE TITLE
Problem with installing multitail in linuxbrew

### ISSUE THREAD

**Issue by neil1hart** [Linuxbrew/homebrew-core#1191]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:
Failed to install

makefile.macosx
multitail
DESTDIR=/home/nhart/.linuxbrew

/home/nhart/.linuxbrew/bin/gcc-5 -O2 -DLinux -DVERSION=\"6.4.2\"  -DCONFIG_FILE=\"/home/nhart/.linuxbrew/etc/multitail.conf\" -isystem/home/nhart/.linuxbrew/include  -c -o utils.o utils.c
/home/nhart/.linuxbrew/bin/gcc-5 -O2 -DLinux -DVERSION=\"6.4.2\"  -DCONFIG_FILE=\"/home/nhart/.linuxbrew/etc/multitail.conf\" -isystem/home/nhart/.linuxbrew/include  -c -o mt.o mt.c
In file included from utils.c:34:0:
mt.h:70:21: fatal error: panel.h: No such file or directory
compilation terminated.
In file included from mt.c:45:0:
mt.h:70:21: fatal error: panel.h: No such file or directory
compilation terminated.
make: *** [utils.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [mt.o] Error 1

brew gist-logs multitail
https://gist.github.com/4038a352163e3896ae5001af115a08d2

**Comment by rwhogg** [comment]
Thanks a bunch for reporting this issue @neil1hart 😄

I've submitted PR #1192 to fix this.

**Comment by rwhogg** [comment]
I've merged #1192. Please do a `brew update` and then retry the installation. If it fails again, please feel free to reopen this issue.

Thanks again for the bug report 😸
