### ISSUE TITLE
w3m: Depends on w3m

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/homebrew-core#1199]
w3m failed to build at the step for libgc with the following errors.
```
configure: error: libgc not found
```
Ironically, after scouring the config.log, we find the following error. 
```
cannot find -lbsd
```
Installing libbsd before w3m fixes the issue. Is it okay to add libbsd as a requirement for w3m?

**Comment by sjackman** [comment]
Thanks for the bug report, @carlorosati. Yes, please add
```ruby
depends_on "libbsd" unless OS.mac?
```
