### ISSUE TITLE
"brew info distcc" fails on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by tjanson** [Linuxbrew/homebrew-core#1204]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Running `brew info distcc` or `brew install distcc` yield `Error: uninitialized constant ELF::ArchitectureListExtension` ([full output](https://gist.github.com/anonymous/ed8d54aac6454476f7de8420868f2894)).

The system is running Ubuntu 14.04.1 (`uname -a`: `
Linux starsky 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`); [`brew config` output](https://gist.github.com/anonymous/db1feaa8a04e77106cc937b220567410).

**Comment by sjackman** [comment]
I've merged PR https://github.com/Linuxbrew/brew/pull/138 to resolve this bug.
