### ISSUE TITLE
running patchelf after installation?

### ISSUE THREAD

**Issue by randy3k** [Linuxbrew/homebrew-core#1205]
I am writing a formula and `brew patchelf ...` is need to fix a `rpath` issue.
I wonder what is the best way to automatically trigger `brew patchelf <my-formula>` after a successful install?

```
  def post_install
    system "brew", "patchelf", "my-formula"
  end
```
obviously is not the best solution.

**Comment by sjackman** [comment]
That solution is actually not so bad, so I'd suggest:
```sh
system HOMEBREW_BREW_FILE, "patchelf", "my-formula"
```

The alternative is not so tidy:
```ruby
Keg.new(formula.prefix).relocate_install_names Keg::PREFIX_PLACEHOLDER, HOMEBREW_PREFIX,
  Keg::CELLAR_PLACEHOLDER, HOMEBREW_CELLAR
```

**Comment by randy3k** [comment]
The `brew` command is not available inside when `brew` is running which makes the first option not work.

This works for me.
```ruby
  def post_install
    if OS.linux?
      # brew patchelf rstudio-server
      Keg.new(prefix).relocate_dynamic_linkage Keg::PREFIX_PLACEHOLDER, HOMEBREW_PREFIX.to_s,
        Keg::CELLAR_PLACEHOLDER, HOMEBREW_CELLAR.to_s
    end
  end
```

**Comment by sjackman** [comment]
Glad to hear that you got it working.
