### ISSUE TITLE
supervisord installed error by Linuxbrew

### ISSUE THREAD

**Issue by FAKERINHEART** [Linuxbrew/homebrew-core#1208]
Recently, I upgraded the python to v2.7. And when I installed the supervisord(3.3.1) again later, I found the error,: "error: option --single-version-externally-managed not recognized", like this:
![1](https://cloud.githubusercontent.com/assets/13352188/20470687/d1876438-afe5-11e6-8411-ecc9205a2b8b.png)

And my file "supervisor.rb":
![image](https://cloud.githubusercontent.com/assets/13352188/20470733/367e9d7a-afe6-11e6-842a-5f57567dd1dc.png)

What could I do to solve this problem? Thank U.

**Comment by sjackman** [comment]
Hi. Sorry, I'm not sure. Perhaps this StackOverflow question will be helpful:
http://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind
