### ISSUE TITLE
doxygen: configimpl.l: error: stray ‘\’ in program

### ISSUE THREAD

**Issue by Horta** [Linuxbrew/homebrew-core#1212]
https://gist.github.com/Horta/eeadbb0bfdf57ab23bcba9d5c0771449

**Comment by rwhogg** [comment]
I can reproduce this error by building from source. Thanks for the bug report @Horta!

You may wish to use the precompiled bottle rather than building from source.

**Comment by sjackman** [comment]
```
cd /tmp/doxygen-20161123-709-ixus4m/doxygen-1.8.12/build/vhdlparser && /usr/bin/g++    -I/tmp/doxygen-20161123-709-ixus4m/doxygen-1.8.12/src -I/tmp/doxygen-20161123-709-ixus4m/doxygen-1.8.12/qtools -I/tmp/doxygen-20161123-709-ixus4m/doxygen-1.8.12/build/generated_src  -Os -w -pipe -march=native  -DNDEBUG   -o CMakeFiles/vhdlparser.dir/VhdlParserIF.cpp.o -c /tmp/doxygen-20161123-709-ixus4m/doxygen-1.8.12/vhdlparser/VhdlParserIF.cpp
configimpl.l:692:1: error: stray ‘\’ in program
configimpl.l: In function ‘int configimplYYlex()’:
configimpl.l:692:1: error: expected primary-expression before ‘<’ token
```
https://gist.github.com/Horta/eeadbb0bfdf57ab23bcba9d5c0771449#file-02-make-L200

**Comment by sjackman** [comment]
Note this important warning:
```
Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: /ebi/lsf/yoda/9.1/linux2.6-glibc2.3-x86_64/lib
```

**Comment by Horta** [comment]
I'm afraid of changing that variable as it is set to everyone in the cluster. I think that is a specific need for the cluster we use...

**Comment by sjackman** [comment]
You only have to unset it temporarily to build `doxygen`. Try
```sh
env -u LD_LIBRARY_PATH brew install doxygen
```
Why aren't you using the precompiled binary bottle of `doxygen`? It should be used by default.

**Comment by Horta** [comment]
Didn't work:

```
> env -u LD_LIBRARY_PATH brew install doxygen                                                                                                            (data)
==> Downloading https://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.12.src.tar.gz
Already downloaded: /homes/horta/.cache/Homebrew/doxygen-1.8.12.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/nfs/software/stegle/syst3m/linuxbrew/Cellar/doxygen/1.8.12 -DCMAKE_BUILD_TYP
==> make
Last 15 lines from /homes/horta/.cache/Homebrew/Logs/doxygen/02.make:
/usr/bin/ar qc ../lib/libqtools.a  CMakeFiles/qtools.dir/qbuffer.cpp.o CMakeFiles/qtools.dir/qcollection.cpp.o CMakeFiles/qtools.dir/qcstring.cpp.o CMakeFiles/qtools.dir/qdatastream.cpp.o CMakeFiles/qtools.dir/qdatetime.cpp.o CMakeFiles/qtools.dir/qdir.cpp.o CMakeFiles/qtools.dir/qfile.cpp.o CMakeFiles/qtools.dir/qfileinfo.cpp.o CMakeFiles/qtools.dir/qgarray.cpp.o CMakeFiles/qtools.dir/qgcache.cpp.o CMakeFiles/qtools.dir/qgdict.cpp.o CMakeFiles/qtools.dir/qglist.cpp.o CMakeFiles/qtools.dir/qglobal.cpp.o CMakeFiles/qtools.dir/qgstring.cpp.o CMakeFiles/qtools.dir/qgvector.cpp.o CMakeFiles/qtools.dir/qiodevice.cpp.o CMakeFiles/qtools.dir/qregexp.cpp.o CMakeFiles/qtools.dir/qstring.cpp.o CMakeFiles/qtools.dir/qtextstream.cpp.o CMakeFiles/qtools.dir/qtextcodec.cpp.o CMakeFiles/qtools.dir/qstringlist.cpp.o CMakeFiles/qtools.dir/qxml.cpp.o CMakeFiles/qtools.dir/qmap.cpp.o CMakeFiles/qtools.dir/qthread.cpp.o CMakeFiles/qtools.dir/qmutex.cpp.o CMakeFiles/qtools.dir/qutfcodec.cpp.o CMakeFiles/qtools.dir/qfile_unix.cpp.o CMakeFiles/qtools.dir/qdir_unix.cpp.o CMakeFiles/qtools.dir/qfileinfo_unix.cpp.o CMakeFiles/qtools.dir/qthread_unix.cpp.o CMakeFiles/qtools.dir/qmutex_unix.cpp.o CMakeFiles/qtools.dir/qwaitcondition_unix.cpp.o
/usr/bin/ranlib ../lib/libqtools.a
make[2]: Leaving directory '/tmp/doxygen-20161123-3309-42sc3s/doxygen-1.8.12/build'
[ 41%] Built target qtools
[ 42%] Linking CXX static library ../lib/libvhdlparser.a
cd /tmp/doxygen-20161123-3309-42sc3s/doxygen-1.8.12/build/vhdlparser && /nfs/software/stegle/syst3m/linuxbrew/Cellar/cmake/3.6.2/bin/cmake -P CMakeFiles/vhdlparser.dir/cmake_clean_target.cmake
cd /tmp/doxygen-20161123-3309-42sc3s/doxygen-1.8.12/build/vhdlparser && /nfs/software/stegle/syst3m/linuxbrew/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/vhdlparser.dir/link.txt --verbose=1
/usr/bin/ar qc ../lib/libvhdlparser.a  CMakeFiles/vhdlparser.dir/CharStream.cc.o CMakeFiles/vhdlparser.dir/ParseException.cc.o CMakeFiles/vhdlparser.dir/Token.cc.o CMakeFiles/vhdlparser.dir/TokenMgrError.cc.o CMakeFiles/vhdlparser.dir/VhdlParser.cc.o CMakeFiles/vhdlparser.dir/VhdlParserTokenManager.cc.o CMakeFiles/vhdlparser.dir/VhdlParserIF.cpp.o
/usr/bin/ranlib ../lib/libvhdlparser.a
make[2]: Leaving directory '/tmp/doxygen-20161123-3309-42sc3s/doxygen-1.8.12/build'
[ 42%] Built target vhdlparser
make[2]: Leaving directory '/tmp/doxygen-20161123-3309-42sc3s/doxygen-1.8.12/build'
make[1]: *** [CMakeFiles/Makefile2:257: src/CMakeFiles/_doxygen.dir/all] Error 2
make[1]: Leaving directory '/tmp/doxygen-20161123-3309-42sc3s/doxygen-1.8.12/build'
make: *** [Makefile:164: all] Error 2
```

**Comment by Horta** [comment]
Regarding the precompiled bottle, I'm setting ``export HOMEBREW_BUILD_FROM_SOURCE=1`` for everyone that uses brew. I'm doing that because I had too much pain before when I would install a binary bottle that is incompatible with the ancient compiler too chain that we are using:

```
> lsb_release -a                                                                                                                                         (data)
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.1 (Maipo)
Release:	7.1
Codename:	Maipo
```

Gcc:
```
> which gcc
/usr/bin/gcc
> gcc --version
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Before I tried to install a more up-to-date gcc using brew and other means, and it was a nightmare as the basic linux commands/libs have to match the same compiler.

**Comment by sjackman** [comment]
You may want to try a second binary installation of Linuxbrew including the updated `glibc` and `gcc` in the directory `/home/linuxbrew/.linuxbrew`, which allows you to use both relocatable and non-relocatable bottles, and obviates the need for compiling most formula. This installation can live in parallel with your source installation.

I'm afraid I don't have the time available to help you troubleshoot building `doxygen` from source. From here I'd recommend two things. Use `brew install -dv doxygen` and select a `Shell` after it fails so that you can troubleshoot yourself why that `lex` step of the build is failing.

Try building `doxygen` outside of Linuxbrew and within `brew sh` to see if those also fail. If they do, I'd suggest reporting this bug upstream to the authors of `doxygen`.

**Comment by Horta** [comment]
No worries, looks like doxygen problem anyway. Thank you for the help.

One thing that might be useful to say here is that C/C++ compilation happens everywhere: it often happens when someone is installing a python package (that comes with C/C++ code) or R package. Suppose I suggest to the people of my group to have their own gcc version in their home folders. It will create another more serious problem that I have seen before: those python and R packages, compiled with that newer gcc, cannot load some of its dynamically linked libraries because the python interpreter itself already loads ancient versions of the same beforehand.

**Comment by sjackman** [comment]
The typical Linuxbrew installation does not use any of the host system libraries. It installs everything itself, including the Python interpreter, Python libraries and their dependencies. That's the setup that I use on our ancient CentOS 6 and 7 systems.

**Comment by Horta** [comment]
So that is the problem: we rely on the Anaconda distribution for Python.

I'm aware that brew and anaconda don't talk well together but I can't see a better solution for us, to have both: up-to-date and well-managed linux tools (via linuxbrew) and up-to-date and well-managed Python (and recently R) packages (often depending on C/C++ and Fortran libraries) (via anaconda) on top of a old system that I hold no privilege.

**Comment by sjackman** [comment]
That's fine. Just try to keep the two worlds separate. Don't mix libraries between them. You can still use the precompiled Linuxbrew bottles for Linuxbrew. Just make sure that Anaconda doesn't use them.
