### ISSUE TITLE
util-linux: private method `xz_dep'

### ISSUE THREAD

**Issue by davideo** [Linuxbrew/homebrew-core#1221]
### Bug reports:

fails to upgrade linux-util

```
'brew outdated'
`util-linux (2.27.1_1) < 2.29`
'brew upgrade util-linux'
'Error: private method `xz_dep' called for #<DependencyCollector:0x00000001830c38>'
```

**Comment by rwhogg** [comment]
I've made a fix for this issue (Linuxbrew/brew#183), but it hasn't reached a stable release yet. My apologies :frowning_man:

I'll try to make one ASAP

**Comment by davideo** [comment]
Thanks! Not a blocker, just reporting the issue.

**Comment by rwhogg** [comment]
I've released a new stable build that includes Linuxbrew/brew#183. Please retry the installation; you should be updated to the fixed build automatically.

Thanks again and my apologies 🐱

**Comment by davideo** [comment]
No worries whatsoever! I was able to successfully install the tap. Thanks for the quick fix!
