### ISSUE TITLE
Cannot upgrade openssl (error while loading shared libraries: libssl.so.1.0.0)

### ISSUE THREAD

**Issue by tomas** [Linuxbrew/homebrew-core#1232]
Looks like Linuxbrew unlinks openssl when upgrading, which means the libraries are not available for curl to fetch the packages. Might be a duplicate of #632, altough it looks like a different scenario.

```
$ brew upgrade openssl
==> Upgrading 1 outdated package, with result:
openssl 1.0.2j
==> Upgrading openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2j.tar.gz
/usr/local/linuxbrew/opt/curl/bin/curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by tomas** [comment]
A temporary solution is to replace `/usr/local/linuxbrew/opt/curl/bin/curl` with a system version of curl -- one that doesn't point to the Linuxbrew openssl libs.

**Comment by sjackman** [comment]
Two more work arounds are
```sh
brew fetch openssl
brew upgrade openssl
```
and
```sh
LD_LIBRARY_PATH=`brew --prefix openssl`/lib brew upgrade curl
```

This bug is long-standing and on our radar to fix. We have ideas, but we haven't found a clear solution yet.

**Comment by tomas** [comment]
Good to know. Thanks @sjackman!

**Comment by sjackman** [comment]
I've got a fix for this issue, which will make it into the next release of Linuxbrew. If you want to try it out early, run…
```sh
cd `brew --repo`
git fetch
git checkout -B stable 1.1.2.1
```

**Comment by sjackman** [comment]
Fixed by https://github.com/Linuxbrew/brew/pull/196
