### ISSUE TITLE
cannot load such file 'utils/json' 

### ISSUE THREAD

**Issue by shuaib88** [Linuxbrew/homebrew-core#1233]
### Bug reports:

`brew install` and `brew doctor` are failing with the same error message

Error: Invalid formula: /home/brewinstaller/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/internetarchive.rb
cannot load such file -- utils/json
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/brewinstaller/.linuxbrew/bin/brew tap homebrew/core -q

I'm a noob to ruby but i figured the utils/json package was massing so I tried installing https://rubygems.org/gems/json-utils/versions/1.6.1 but that had failures installing that as well. 

these dependencies were successfully installed sudo yum groupinstall 'Development Tools' && sudo yum install curl git irb python-setuptools ruby

any advice would be very helpful!!!

**Comment by rwhogg** [comment]
This will be fixed by #1231.

**Comment by shuaib88** [comment]
Thanks, that did the trick. I just removed ~/.linuxbrew and just tried reinstalling linxubrew with: 

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"

**Comment by sjackman** [comment]
Great. Thanks for following up, Shuaib.
