### ISSUE TITLE
pam: Create formula for Linuxbrew

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#131]
_From @sjackman on March 17, 2016 18:43_

Homepage: http://www.linux-pam.org/

_Copied from original issue: Linuxbrew/linuxbrew#946_

**Comment by rwhogg** [comment]
_From @sjackman on March 17, 2016 18:43_

rstudio-server: Depends on pam #819

**Comment by rwhogg** [comment]
I'm happy to take this one on, but it's not all that high priority for me right now. I'll increase priority on it if you want to use R Studio, but since the only other formula I'm aware of that uses it is CVS (not exactly the most important formula in the world these days) I think dealing with X11 is more important right now.

**Comment by rwhogg** [comment]
_From @sjackman on April 3, 2016 19:48_

Agreed. I use RStudio on Mac. On Linux I use only R command line.

**Comment by sjackman** [comment]
`openssh` can also use `pam`.

**Comment by rwhogg** [comment]
This is now available: https://github.com/Linuxbrew/homebrew-extra/pull/3
