### ISSUE TITLE
Cannot install gmp4 on CentOS

### ISSUE THREAD

**Issue by mnunes** [Linuxbrew/homebrew-core#1343]
I need gcc 4.9 installed on my system. I tried to install it with linuxbrew, but I cannot compile the gmp4 dependency. This is the error I am always getting:

    ==> Installing homebrew/versions/gcc49 dependency: gmp4
    ==> Downloading https://ftpmirror.gnu.org/gmp/gmp-4.3.2.tar.bz2
    Already downloaded: /home/marcus/.cache/Homebrew/gmp4-4.3.2.tar.bz2
    ==> Patching
    patching file gmp-h.in
    ==> ./configure --prefix=/home/marcus/.linuxbrew/Cellar/gmp4/4.3.2 --enable-cxx --build=x8
    ==> make
    Last 15 lines from /home/marcus/.cache/Homebrew/Logs/gmp4/02.make:
    /home/marcus/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-415.o scanf/.libs/scanf.o .libs/libgmp.la-414.o
    /home/marcus/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-416.o scanf/.libs/sscanf.o .libs/libgmp.la-415.o
    /home/marcus/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-417.o scanf/.libs/sscanffuns.o .libs/libgmp.la-416.o
    /home/marcus/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-418.o scanf/.libs/vfscanf.o .libs/libgmp.la-417.o
    /home/marcus/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-419.o scanf/.libs/vscanf.o .libs/libgmp.la-418.o
    /home/marcus/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-420.o scanf/.libs/vsscanf.o .libs/libgmp.la-419.o
    /home/marcus/.linuxbrew/bin/gcc-5 -shared .libs/libgmp.la-420.o  -L/home/marcus/.linuxbrew/lib  -march=native -m64 -Wl,--dynamic-linker=/home/marcus/.linuxbrew/lib/ld.so -Wl,-rpath -Wl,/home/marcus/.linuxbrew/lib -Wl,-soname -Wl,libgmp.3.dylib -o .libs/libgmp.3.5.2.dylib
    /home/marcus/.linuxbrew/bin/ld: .libs/libgmp.la-420.o: relocation R_X86_64_32 against symbol `__gmp_sscanf_funs' can not be used when making a shared object; recompile with -fPIC
    /home/marcus/.linuxbrew/bin/ld: final link failed: Nonrepresentable section on output
    collect2: error: ld returned 1 exit status
    make[2]: *** [libgmp.la] Error 1
    make[2]: Leaving directory `/tmp/gmp4-20161208-19523-1ixvsp3/gmp-4.3.2'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/tmp/gmp4-20161208-19523-1ixvsp3/gmp-4.3.2'
    make: *** [all] Error 2

[Here is the gist-log](https://gist.github.com/anonymous/2c0850271cc9f4c27e9d564f6ed62109).

I updated linuxbrew twice and `brew doctor` result seems fine:

    $ brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!
    
    Warning: Setting LD_* vars can break dynamic linking.
    Set variables:
      LD_LIBRARY_PATH: /opt/rh/devtoolset-4/root/usr/lib64:/opt/rh/devtoolset-4/root/usr/lib

This is my `brew config`:

    $ brew config
    HOMEBREW_VERSION: >1.1.0 (no git repository)
    ORIGIN: https://github.com/Linuxbrew/brew
    HEAD: cfb3b88c2865c8fc0ff0985f2f6995229b105e9b
    Last commit: 5 days ago
    Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
    Core tap HEAD: f458f193151da0187936a86ef7c028c254b5426c
    Core tap last commit: 8 hours ago
    HOMEBREW_PREFIX: /home/marcus/.linuxbrew
    HOMEBREW_REPOSITORY: /home/marcus/.linuxbrew
    HOMEBREW_CELLAR: /home/marcus/.linuxbrew/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
    CPU: 16-core 64-bit westmere
    Homebrew Ruby: 2.0.0-p598 => /usr/bin/ruby
    Clang: N/A
    Git: 1.8.3.1 => /usr/bin/git
    Perl: /usr/bin/perl
    Python: /usr/bin/python => /usr/bin/python2.7
    Ruby: /usr/bin/ruby
    Java: openjdk version "1.8.0_111"
    Kernel: Linux 3.10.0-327.18.2.el7.x86_64 x86_64 GNU/Linux
    OS: CentOS Linux release 7.2.1511 (Core)
    OS glibc: 2.17
    OS gcc: 4.8.5
    Linuxbrew glibc: 2.19
    Linuxbrew gcc: 5.3.0
    Linuxbrew xorg: N/A

**Comment by sjackman** [comment]
Homebrew/versions is not a supported tap of Linuxbrew. Sorry. Your best bet is top copy the file `gcc.rb` to `gcc@49.rb` and edit it to install GCC 4.9.

**Comment by iMichka** [comment]
This issue is pretty old. `gmp@4` has a bottle and should be fine. `gcc@4.9` does not have a bottle for the moment (see #5276); but should be fine. Closing here.
