### ISSUE TITLE
cmake: ccmake is missing from the bottle: Depends on ncurses

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1388]
note to self:`sudo apt-get install cmake-curses-gui` as a workaround in the meantime

**Comment by maxim-belkin** [comment]
it does for me when building from source ([link](https://gist.github.com/4e75c731f7de39cab3c47bf7ebef1ea4))
But I confirm that `ccmake` is not in the `cmake` bottle

**Comment by sjackman** [comment]
Add a dependency on `ncurses` would likely resolve this issue.
```ruby
depends_on "homebrew/dupes/ncurses" unless OS.mac?
```

**Comment by sjackman** [comment]
Resolved by PR #1569

**Comment by maxim-belkin** [comment]
`cmake` bottle has been updated and now it includes `ccmake`
