### ISSUE TITLE
brew install homebrew/versions/llvm38: /usr/bin/ld: cannot find -lSystem

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1396]
https://gist.github.com/f239d4d79453adfba4a719866489a621

**Comment by rwhogg** [comment]
Unfortunately, homebrew/versions is not a supported tap on Linuxbrew.

Is there a reason you need version 3.8 in particular? If not, you may wish to try installing the standard `llvm` formula again. @maxim-belkin recently made a bunch of improvements to it.

**Comment by maxim-belkin** [comment]
3.8.1 bottle is [here](https://bintray.com/linuxbrew/bottles/download_file?file_path=llvm-3.8.1.x86_64_linux.bottle.tar.gz)
