### ISSUE TITLE
Unsupported taps should give a better error message

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1397]
When I ran into https://github.com/Linuxbrew/homebrew-core/issues/1396, the error I get contains:
```
READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-versions/issues
```

but the info there pertains to OSX[eg: mentions Xcode etc], not linux; usually for linuxbrew the error message should tell to submit bugs to https://github.com/Linuxbrew/homebrew-core/issues/

**Comment by sjackman** [comment]
The Homebrew/versions tap is not supported by Linuxbrew.

**Comment by rwhogg** [comment]
I've been wondering about something even more dramatic than just error messages.

Here's my thoughts:

1. We declare support levels for taps. These could be:
* **Fully Supported**: We are committed to things working well on Linux here and at least one tap maintainer is willing to invest in fixing issues related to this. Additionally, there should be some sort of automated testing on Linux. Examples might be linuxbrew/core, linuxbrew/dupes, linuxbrew/xorg, and homebrew/science.
* **Best-Effort Supported**: We want things to work well on Linux and will accept (non-invasive) PR's to fix them. Problems requiring invasive changes could be closed as "sorry, please maintain a fork". homebrew/emacs might be an example (although I'd have to clear that with someone from upstream)
* **Partially Supported**: Particular formulae are supported at least partially on Linux, perhaps with caveats, but others are explicitly not.
* **Not Supported**: Taps for which Linux support is not provided in any way and Linux-only issues can be immediately closed by maintainers. homebrew/core is the obvious example here.

2. Ask maintainers of Linux-supporting taps to explicitly select one of the above support levels. (No statement at all would be interpreted as **Not Supported** to avoid annoying maintainers of said taps)
 
3. Have some automated way for Brew to determine what category a tap is in and change behaviour accordingly. Ruby symbols combined with a well-known file included in the tap (".linux.rb" or something?) might be a cool way to do this.

Thoughts @Linuxbrew/core? (Not pinging Homebrew on this

**Comment by sjackman** [comment]
Yeah, I'm happy with that, although I feel the two most likely categories are probably `Fully` and `No`, and that the middle two categories could probably combined into a single category. Currently Homebrew/science and Homebrew/dupes accept Linux patches. It really hinges a person from the community (hopefully not necessarily us four) adopting a particular tap and volunteering to address all of the Linux issues for that tap, and the primary maintainer being willing to give commit rights to that Linuxbrew maintainer.
