### ISSUE TITLE
PDF2htmlex build fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#141]
_From @pdurusau on November 6, 2015 20:18_

Built finds gcc but then reports "checking whether the C compiler works... no" Gist URL below. 

https://gist.github.com/anonymous/058e0fb1d853e7566487

_Copied from original issue: Linuxbrew/linuxbrew#633_

**Comment by rwhogg** [comment]
Can you try `brew install gcc` and then try building again with Homebrew's GCC 5 (`brew install pdf2htmlex --cc=gcc-5`)?

**Comment by rwhogg** [comment]
Can confirm that it does the same thing on my machine.

**Comment by LeoKotschenreuther** [comment]
I'm experiencing the same issue. Any update on this?

**Comment by rwhogg** [comment]
I just made #723 to fix this. I'd like to wait until after Shaun merges Homebrew/homebrew-core into Linuxbrew/homebrew-core before merging it (and I'd also like to retest after he does that to make sure my patch is still necessary), but you can do `brew pull https://github.com/Linuxbrew/homebrew-core/pull/723` to test it out until then.

**Comment by LeoKotschenreuther** [comment]
Thanks a lot! It fixed the issue on my Ubuntu 14

**Comment by rwhogg** [comment]
Cool, glad I could help :smile: 

The merge has been completed, so I'll try and get this merged (if necessary) tonight.

**Comment by rwhogg** [comment]
I've merged my fix. I had to change it a bit, so the commit won't be exactly the same as the one you pulled.

You may wish to do a `git reset --hard HEAD~1` before doing a brew update to prevent merge conflicts.
