### ISSUE TITLE
GTK+3 missing dependency (atk-bridge)

### ISSUE THREAD

**Issue by YutingZhang** [Linuxbrew/homebrew-core#1412]
When install GTK+3, the configure script said `atk-bridge` is missing.
The problem can be easily resolved by install `at-spi2-atk`, however the dependency has not been encoded.

**Comment by rwhogg** [comment]
Thanks for finding this @YutingZhang!

Would you like to submit a PR to add this dependency? Just put `depends_on at-spi2-atk unless OS.mac?` into the formula. (If you don't want to, I can add the dependency myself later today).

**Comment by sjackman** [comment]
Resolved by #1412.
