### ISSUE TITLE
Error: Unsupported special dependency :perl

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#1415]
_From @jhumbertoh on December 28, 2016 17:47_

brew install node

Error: Unsupported special dependency :perl
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

_Copied from original issue: Linuxbrew/legacy-linuxbrew#1115_

**Comment by rwhogg** [comment]
Hi @jhumbertoh: can you please do a `brew update` twice and then retry?

If that fails, please run `brew gist-logs node` and then paste the link here.

Thanks a bunch :smile:

**Comment by jhumbertoh** [comment]
I updated and if I could install correctly. Thank you :D

**Comment by rwhogg** [comment]
:smile_cat:

**Comment by ScorpIan555** [comment]
This worked for me also.  I posted a link to this resolution in the comment section of John Papa's tutorial (where I encountered this issue).  Cheers.

https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/
