### ISSUE TITLE
util-linux fails to build

### ISSUE THREAD

**Issue by Xuphey** [Linuxbrew/homebrew-core#1418]
Hi

I was installing `qt5` on a centos7 box using `brew install qt5`
And one of the dependencies -- `util-linux` -- failed to build
Here is the [build log](https://gist.github.com/82d5dc90f9f701516b6b2ccf5d4eea20)

Any ideas?
Thanks

**Comment by Xuphey** [comment]
i linked the missing lib file to the ones in system lib dir /usr/lib64
the problem is now 
https://gist.github.com/267f9dfb6a83e9d0c5595a585b39bed2

**Comment by sjackman** [comment]
I believe your first issue is resolved by https://github.com/Linuxbrew/homebrew-core/pull/1524

**Comment by sjackman** [comment]
One possible work around is to install Linuxbrew in `/home/linuxbrew/.linuxbrew` to use the precompiled binary bottle for `util-linux`.
You can also try `brew install --force-bottle util-linux`, which may work (but no promises).

**Comment by Xuphey** [comment]
i somehow overcame this problem by building the dependencies separately, it might be a dependency chain problem.
Thanks for the attention.

**Comment by sjackman** [comment]
Glad to hear that you were able to resolve your issue, Edward.
