### ISSUE TITLE
synapse package

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#142]
_From @typekpb on September 5, 2015 6:6_

not sure about the proper place to report, but would love to see the package for launcher called synapse: https://launchpad.net/synapse-project

please note this would be linux only package

_Copied from original issue: Linuxbrew/linuxbrew#539_

**Comment by rwhogg** [comment]
I'd welcome a pull request for this, but I don't have the time to do it myself.

If you want to try to create the formula yourself, please see [the formula cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook).

Thanks for the package suggestion!

**Comment by sjackman** [comment]
If you do create a formula for `synapse`, please submit the PR to https://github.com/Linuxbrew/homebrew-extra
