### ISSUE TITLE
texlive: SHA-256 is wrong

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#1425]
Looks like `texlive` has been updated again.

**Comment by rwhogg** [comment]
Also note that if you try to use HTTPS, you get a non-matching certificate.

I'd jump on this myself if HTTPS worked, but since it doesn't and I'm in no position to audit the download, I'll leave this task to someone who has better knowledge than me of TeX

**Comment by sjackman** [comment]
Resolved by https://github.com/Linuxbrew/homebrew-core/pull/1561
