### ISSUE TITLE
Jasper can fail to build if an incomplete TeX environment exists

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#1427]
For example, if the Ubuntu package texlive-latex-base is installed but texlive-latex-extra is not, it can fail with the message:

```
File `tabu.sty' not found.
```

Installing the `texlive` Linuxbrew formula doesn't help. I wanted to try building with `--with-full`, but unfortunately due to #1425 that's not possible to test at the moment.

**Comment by sjackman** [comment]
#1425 is resolved by #1561
