### ISSUE TITLE
util-linux: conflicts with gnu-getopt

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#144]
_From @rwhogg on April 21, 2016 3:23_

Both of them install a `getopt` command.

_Copied from original issue: Linuxbrew/linuxbrew#1091_

**Comment by rwhogg** [comment]
_From @sjackman on April 21, 2016 16:26_

I'm inclined to remove the `getopt` command from `util-linux` and use `gnu-getopt`. In cases like this, I usually defer to whatever Debian is doing.

**Comment by rwhogg** [comment]
> I'm inclined to remove the getopt command from util-linux and use gnu-getopt

I like that plan; it's what I did locally to deal with this.

**Comment by rwhogg** [comment]
_From @sjackman on April 21, 2016 18:10_

`/usr/bin/getopt` is provided by `util-linux` on Debian.
https://packages.debian.org/search?searchon=contents&keywords=%2Fbin%2Fgetopt&mode=exactfilename&suite=stable&arch=any

Unless we have a good reason otherwise, I prefer to go with whatever Debian has done.

**Comment by sjackman** [comment]
There are a small handful of core formula (eight) that depend on `gnu-getopt`. If `util-linux` conflicts with `gnu-getopt`, these formula will not be installable. For this reason, `gnu-getopt` should be removed from `util-linux` to resolve the conflict.

**Comment by DoomHammer** [comment]
I'm afraid this will either require an upstream patch or some hackery during linking as it is not possible to build all of `util-linux` save `gnu-getopt` as far as I am aware.

**Comment by rwhogg** [comment]
> There are a small handful of core formula (eight) that depend on gnu-getopt.

I guess the question is if they specifically depend on GNU's behaviour or they just don't work with BSD getopt for whatever reason.

From `util-linux`'s [documentation](https://github.com/karelzak/util-linux/blob/master/Documentation/getopt.txt):

```
It can do anything that the GNU getopt(3) routines can do.
It can cope with spaces and shell metacharacters within arguments.
It can parse long parameters.
It can shuffle parameters, so you can mix options and other parameters on
the command-line.
It can be easily identified as an enhanced getopt(1) from within shell scripts.
It can report parse errors as coming from the shell script.
It is fully compatible with other getopt(1) implementations.
```

So from the sounds of it, we're fine going with `util-linux`. In any case, we can check to see which of those 8 packages are included in Debian and see if they needed patches in order to work with `util-linux`. My guess is that they didn't.

**Comment by sjackman** [comment]
In that case we can make `gnu-getopt` `:keg_only` on Linux, and everything should be fine.

**Comment by rwhogg** [comment]
One other thing worth pointing out is that `gnu-getopt` is *already* keg-only on Mac. It's not keg-only on Linux (but see #329 where I make it so).
