### ISSUE TITLE
tldr depends on curl

### ISSUE THREAD

**Issue by waldyrious** [Linuxbrew/homebrew-core#1471]
I'm getting a `src/net.c:4:23: fatal error: curl/curl.h: No such file or directory` error during the build.
 
Here are the relevant logs: https://gist.github.com/anonymous/3635bed06a7c741e54ee3e01513f578c

/cc @Leandros, @danielcompton, @zmwangx and @DomT4 per #4637. Particularly, [this exchange](https://github.com/Homebrew/homebrew-core/pull/4637#discussion-diff-78221277) seems relevant.

**Comment by waldyrious** [comment]
Here's the original output, btw:

```
$ brew install tldr
Updating Homebrew...
==> Installing dependencies for tldr: patchelf, pkg-config, libzip
==> Installing tldr dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
######################################################################## 100,0%
==> Pouring patchelf-0.9_1.x86_64_linux.bottle.tar.gz
🍺  /home/waldyrious/.linuxbrew/Cellar/patchelf/0.9_1: 6 files, 1.2M
==> Installing tldr dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar.gz
######################################################################## 100,0%
==> ./configure --prefix=/home/waldyrious/.linuxbrew/Cellar/pkg-config/0.29.1_2 --disable-host-tool --with-internal-glib --with-pc-path=/home/waldyrious/.linuxbrew/lib/pkgconfig:/home/waldyrious/.linuxbrew/share/pkgconfig:/usr/local/lib/pk
==> make
==> make check
==> make install
🍺  /home/waldyrious/.linuxbrew/Cellar/pkg-config/0.29.1_2: 11 files, 677.8K, built in 57 seconds
==> Installing tldr dependency: libzip
==> Downloading https://linuxbrew.bintray.com/bottles/libzip-1.1.2.x86_64_linux.bottle.tar.gz
######################################################################## 100,0%
==> Pouring libzip-1.1.2.x86_64_linux.bottle.tar.gz
🍺  /home/waldyrious/.linuxbrew/Cellar/libzip/1.1.2: 120 files, 617.9K
==> Installing tldr 
==> Downloading https://github.com/tldr-pages/tldr-cpp-client/archive/v1.3.0.tar.gz
==> Downloading from https://codeload.github.com/tldr-pages/tldr-cpp-client/tar.gz/v1.3.0
######################################################################## 100,0%
==> make PREFIX=/home/waldyrious/.linuxbrew/Cellar/tldr/1.3.0 install
Last 15 lines from /home/waldyrious/.cache/Homebrew/Logs/tldr/01.make:

make
PREFIX=/home/waldyrious/.linuxbrew/Cellar/tldr/1.3.0
install

CC src/local.c
CC src/tldr.c
CC src/net.c
CC src/parser.c
CC src/utils.c
src/net.c:4:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
Makefile:119: recipe for target 'obj/net.o' failed
make: *** [obj/net.o] Error 1
```

**Comment by zmwangx** [comment]
Just submit a PR with this patch

```diff
diff --git a/Formula/tldr.rb b/Formula/tldr.rb
index 1601222..d5e1c44 100644
--- a/Formula/tldr.rb
+++ b/Formula/tldr.rb
@@ -15,6 +15,7 @@ class Tldr < Formula
 
   depends_on "pkg-config" => :build
   depends_on "libzip"
+  depends_on "curl" unless OS.mac?
 
   def install
     system "make", "PREFIX=#{prefix}", "install"
```

Shouldn't have been hard to figure out if you just 

```
grep -r curl
```

or better yet,

```
grep -r 'depends_on "curl"'
```

in this repo. I understand it might be very important for you, but I don't think mentioning a bunch of people from another repo is very polite.

**Comment by waldyrious** [comment]
@zmwangx I didn't mean to spam people, sorry about that -- my intention was to ping those who had participated in the previous discussion related to this formula.

Thanks for the solution, I'll submit a PR right away.

**Comment by zmwangx** [comment]
@waldyrious 

> I didn't mean to spam people

I'm sure you were well meaning, didn't assume malice. Just a suggestion: you could have waited for project maintainers to take a look, at their leisure, who in this case could have solved it right away; in the case that they couldn't, that's probably the time to escalate to a wider group of people.

By the way, I appreciate the credit, but could you please remove my handle from the commit message? Otherwise, I'll get an email whenever someone a rebased/cherry-picked version of this commit in their own fork...

**Comment by waldyrious** [comment]
I forget that not everyone has disabled email notifications from github -- indeed I can see how that could quickly become excessive. I'll remove the handle from the commit -- just testing the build first before opening the PR.
