### ISSUE TITLE
bazel formula requires jdk but bazel.rb doesn't

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/homebrew-core#1496]
Need to add dependency to [bazel.rb](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/bazel.rb)

[Currently lists java](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/bazel.rb#L15) but linuxbrew doesn't acknowledge the tag.

**Comment by rwhogg** [comment]
The Java requirement *should* default to installing `jdk` if you don't have Java installed.

Do you have Java installed on your system some other way (OpenJDK via apt/rpm, manual installation of the Oracle JDK, etc.)? If so, my understanding is `jdk` won't be installed in that case.

Could you post `brew config`? Thanks!

**Comment by carlorosati** [comment]
```brew config```
```
                                                                                    129
HOMEBREW_VERSION: 1.1.5-142-g1c88444
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 1c8844400d1cbe80f26b8195aae3d79e88c92173
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: b33d016e6d9936905aefa52b2d560be048f7c795
Core tap last commit: 19 hours ago
HOMEBREW_PREFIX: /tmp/brew
HOMEBREW_REPOSITORY: /tmp/brew
HOMEBREW_CELLAR: /tmp/brew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648 => /tmp/brew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.4.6 => /usr/local/x64/git-2.4.6/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.7.0_121
Kernel: Linux 2.6.32-642.6.2.el6.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
Codename: Santiago
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A
```

Looks like I have it.

The error is actually with the version.

```
ERROR: JDK version (1.7) is lower than 1.8, please set $JAVA_HOME.
```

Why didn't the formula catch that?

**Comment by rwhogg** [comment]
> The error is actually with the version.
ERROR: JDK version (1.7) is lower than 1.8, please set $JAVA_HOME.
Why didn't the formula catch that?

The Linuxbrew version of the Java requirement currently doesn't check versions. I'm working on fixing that: https://github.com/Homebrew/brew/pull/1632
