### ISSUE TITLE
bazel requires more than shell limit maxprocs to build

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/homebrew-core#1497]
Build fails with shell default maxprocs limit.

[```brew gist-logs bazel```](https://gist.github.com/194c0c1139721bd2e57cd7694760000a)

[Bazel issue](https://github.com/bazelbuild/bazel/issues/2177) has temporary fix ```ulimit -u 10000```. **Beware** this will clog or lock up your machine even though the "hard limit" may be higher.

**Comment by rwhogg** [comment]
As this isn't an issue specific to Linuxbrew and it's being tracked upstream, I think I'll close this issue. Nevertheless, thanks for bringing it up :smile_cat:

**Comment by carlorosati** [comment]
There is a bazel option listed for building tensorflow that will limit the resources. It works better than using ulimit.

```--local_resources 2048,.5,1.0```
