### ISSUE TITLE
Meta: Conflicts that don't exist on macOS

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#1526]
This is just a meta-issue to track all the separate conflicts_with issues that occur on Linux and/or Linuxbrew but not on macOS and/or Homebrew, so we can centralize discussion of them.

* #1447 (libarchive conflicts with gnu-tar and cpio)
* #942 (pod2man conflicts with perl)
* #1474 (clang-format conflicts with llvm)
* #848 (rename conflicts with util-linux)
* #233 (elfutils conflicts with libelf)
* truncate conflicts with coreutils
* base64 conflicts with coreutils

Not all of these issues exist for the same reason - most are caused by `keg_only :provided_by_osx`, but some are caused by conflicts with Linux-only formulae like `util-linux`.

I may have missed some; feel free to add more.

**Comment by sjackman** [comment]
Good idea, Bob. Can you add the formula names to the above list?

**Comment by iMichka** [comment]
Nobody is really working on this. I'll close the issue, and we will see on a case by case basis what needs to be done.
