### ISSUE TITLE
`brew gist-logs --new-issue ...` => raise_api_error': GitHub::HTTPNotFoundError

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1563]
```
brew gist-logs --new-issue mosh                                  
/home/timothee/temp/tmp/brew2/Library/Homebrew/utils/github.rb:218:in `raise_api_error': GitHub::HTTPNotFoundError
        from /home/timothee/temp/tmp/brew2/Library/Homebrew/utils/github.rb:184:in `open'
        from /home/timothee/temp/tmp/brew2/Library/Homebrew/cmd/gist-logs.rb:121:in `create_issue'
        from /home/timothee/temp/tmp/brew2/Library/Homebrew/cmd/gist-logs.rb:59:in `gistify_logs'
        from /home/timothee/temp/tmp/brew2/Library/Homebrew/cmd/gist-logs.rb:127:in `gist_logs'
        from /home/timothee/temp/tmp/brew2/Library/Homebrew/brew.rb:94:in `<main>'
```

my particular case was for mosh, for which i also submitted a bug report: https://github.com/Linuxbrew/homebrew-core/issues/1562

This was with a fresh linuxbrew clone

PS: i did set HOMEBREW_GITHUB_API_TOKEN

**Comment by sjackman** [comment]
Does `brew gist-logs mosh` without `--new-issue` work for you?

**Comment by timotheecour** [comment]
yes [and that one appears in  #1562]

**Comment by sjackman** [comment]
Okay, thanks for the bug report, Timothee. I probably won't get to it myself real soon as I'm leaving for a conference on Friday, but a pull request would be welcome if you'd like to take a stab at it.
