### ISSUE TITLE
brew gist-logs linuxbrew/xorg/libxtst => Error: No logs.

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1565]
I reported the fact that `brew install linuxbrew/xorg/libxtst` failed here: 
https://github.com/Linuxbrew/homebrew-xorg/issues/254

However, I am also reporting here the fact that `brew gist-logs` fails:
```
brew gist-logs linuxbrew/xorg/libxtst => Error: No logs.
```

this 2nd error seems to be linuxbrew specific (i would assume every formula (even broken) should automatically create a gist-logs and gist-logs shouldn't fail)

**Comment by sjackman** [comment]
```
==> Installing linuxbrew/xorg/libxtst dependency: xorg-protocols
```
It failed while building a dependency `xorg-protocols`, and so never even attempted to build `libxtst`, hence no logs for `libxtst`.
