### ISSUE TITLE
mongodb: error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1566]
even on a fresh linuxbrew clone
https://gist.github.com/e6aa391d94fe6d3bdde8088cecf1c324

**Comment by sjackman** [comment]
```
Building mongoreplay...
# github.com/google/gopacket/pcap
vendor/src/github.com/google/gopacket/pcap/pcap.go:19:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
```
https://gist.github.com/timotheecour/e6aa391d94fe6d3bdde8088cecf1c324#file-01-build-sh-L82
Please quote the relevant error and link directly to the line in the gist.
Does `brew install homebrew/dupes/libpcap mongodb` work?
See also related PR #235

**Comment by sjackman** [comment]
I have duplicated this issue in #235.
