### ISSUE TITLE
warn before `brew install` of a formula known to not work on Linuxbrew

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1582]
Proposed here: https://github.com/Linuxbrew/homebrew-core/issues/1568#issuecomment-272034351

Use case:
```
brew install mybrokenformula
```

Compiles for 1 hour until some error shows up. User consults existing issues, to see indeed formula is broken on linuxbrew. 

Would be nice to show a warning before to avoid this common frustration.

* refinement: filter by environment (eg error is only in ubuntu 14.04)
* refinement: also show warning if user tries to install A that depends on B that depends on mybrokenformula.

**Comment by sjackman** [comment]
Possibly as an opt-in feature `brew install` could check for install failure issues on GitHub with an API call before installing the formula.
