### ISSUE TITLE
why not use useradd in circle.yml and .travis.yml ?

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1585]
This seems cleaner: `useradd -ms /bin/bash linuxbrew`
instead of:

https://github.com/Linuxbrew/homebrew-core/blob/master/circle.yml
```
- sudo mkdir /home/linuxbrew
- sudo chown "$USER:" /home/linuxbrew
```

https://github.com/Linuxbrew/homebrew-core/blob/master/.travis.yml
```
 - HOME=/home/linuxbrew
  - sudo mkdir $HOME
  - sudo chown "$USER:" $HOME
```

**Comment by sjackman** [comment]
We do use `useradd` in the Linuxbrew [`Dockerfile`](https://github.com/Linuxbrew/brew/blob/master/Dockerfile#L10). For Travis and Circle I feel it's simpler to continue running as the default user for each system.
