### ISSUE TITLE
invalid Formula, invalid sytax in tap mod_suexec.rb

### ISSUE THREAD

**Issue by smeetsmeister** [Linuxbrew/homebrew-core#1591]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:
Brew upgraded results in the following error:
`brew upgrade
==> Upgrading 1 outdated package, with result:
homebrew/php/php56 5.6.29_5
==> Tapping homebrew/apache
Cloning into '/home/jelle/.linuxbrew/Library/Taps/homebrew/homebrew-apache'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 7), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.
Error: Invalid formula: /home/jelle/.linuxbrew/Library/Taps/homebrew/homebrew-apache/mod_suexec.rb
formulae require at least a URL
Error: Cannot tap homebrew/apache: invalid syntax in tap!
`
The same error occurs on tyring to install php71 

Gist of brew config:
[https://gist.github.com/smeetsmeister/0d9379ae7b78ab17a5c05f33f59fbc3c](url)

**Comment by sjackman** [comment]
`Homebrew/php` is not a supported tap of Linuxbrew. Please report this issue at https://github.com/homebrew/homebrew-php
