### ISSUE TITLE
Issue when installing node on debian 8 with full-icu

### ISSUE THREAD

**Issue by clement-escolano** [Linuxbrew/homebrew-core#1618]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

I am trying to install node with full-icu (all locales) with a freshly installed linuxbrew. I tried twice on my server (debian 8) and it failed twice. Here is the report : https://gist.github.com/anonymous/ba893377bea3d2279ed6e9e43421ef43
Installing node with default settings (small-icu) works fine.

I am available for more details !

Thank you :)

**Comment by alyssais** [comment]
I had a similar problem, and the reason was that the compiler ran out of memory and died.

You could either get more memory (or swap) somehow, _or_ run a deparallelized build. I noticed that the Node formula will already deparallelize itself if running on CIRCLECI for this reason, so I worked around the problem by running:

```sh
CIRCLECI=1 brew install node
```

Which is not a brilliant solution to this problem, but it worked.

**Comment by clement-escolano** [comment]
@alyssais Thank you for your answer !
I tried your solution and .... it did not work :( I don't know if my server has really a low amount of memory available or it is something else.

**Comment by nitinbansal1989** [comment]
HI, i have a request that can we have a bottle for node. Because it takes lots of time to build and node and the installation sometimes fails due to lack of resources.

**Comment by rwhogg** [comment]
Hi @nitinbansal1989: there is currently a bottle available for Node.

There's two (likely) reasons that you're not able to use it:

* The node bottle only works if Linuxbrew is installed in /home/linuxbrew/.linuxbrew
* The bottle will not be used if you install with any options, such as --with-full-icu as specified in this issue.

Hope that helps!

**Comment by nitinbansal1989** [comment]
On my linuxmint system, i have a user "nitin" and linuxbrew path is "/home/nitin/.linuxbrew/" and node is installed at "/home/nitin/.linuxbrew/Cellar/node/". Current node version is 7.5.0. I have not used any option while installation. Is there anything else to check. Thanks.

**Comment by alyssais** [comment]
@nitinbansal1989 To use Linuxbrew bottles, Linuxbrew has to be installed at /home/linuxbrew/.linuxbrew (not any other user).

**Comment by nitinbansal1989** [comment]
Thanks @alyssais . I have one doubt. shouldn't be the bottles user independent, as in homebrew. I don't think the bottles installation is linked to the linux user. Let me know if i am missing something or is there is any planned changes for this in the future.Thanks.

**Comment by alyssais** [comment]
@nitinbansal1989 quoting the [comment](https://github.com/Linuxbrew/homebrew-core/issues/1618#issuecomment-277282436) immediately above [yours](https://github.com/Linuxbrew/homebrew-core/issues/1618#issuecomment-277424279):

> - The node bottle only works if Linuxbrew is installed in /home/linuxbrew/.linuxbrew

**Comment by sjackman** [comment]
Relocatable bottles (marked with `cellar :any`) are known to work in any installation location. Non-relocatable bottles are not known to work in any prefix. You can install Linuxbrew in `/home/linuxbrew/.linuxbrew` to make use of non-relocatable bottles. If you're daring, you can try `brew install --force-bottle node`. It may or may not work, no promises.

**Comment by sjackman** [comment]
```
  /home/clement/.linuxbrew/bin/gcc-5 '-DU_ATTRIBUTE_DEPRECATED=' '-D_CRT_SECURE_NO_DEPRECATE=' '-DU_STATIC_IMPLEMENTATION=1' '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_HAVE_STD_STRING=0' '-DUCONFIG_NO_BREAK_ITERATION=0' '-DUCONFIG_NO_LEGACY_CONVERSION=1' -I../deps/icu/source/common  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -O3 -fno-omit-frame-pointer  -MMD -MF /tmp/node-20170123-20033-p5zfkh/node-v7.4.0/out/Release/.deps//tmp/node-20170123-20033-p5zfkh/node-v7.4.0/out/Release/obj.target/icudata/gen/icudt58_dat.o.d.raw -isystem/home/clement/.linuxbrew/include -Os -w -pipe -march=native -c -o /tmp/node-20170123-20033-p5zfkh/node-v7.4.0/out/Release/obj.target/icudata/gen/icudt58_dat.o /tmp/node-20170123-20033-p5zfkh/node-v7.4.0/out/Release/obj/gen/icudt58_dat.c
gcc-5: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
tools/icu/icudata.target.mk:144: recipe for target '/tmp/node-20170123-20033-p5zfkh/node-v7.4.0/out/Release/obj.target/icudata/gen/icudt58_dat.o' failed
make[1]: *** [/tmp/node-20170123-20033-p5zfkh/node-v7.4.0/out/Release/obj.target/icudata/gen/icudt58_dat.o] Error 4
make[1]: Leaving directory '/tmp/node-20170123-20033-p5zfkh/node-v7.4.0/out'
Makefile:73: recipe for target 'node' failed
make: *** [node] Error 2
```
https://gist.githubusercontent.com/anonymous/ba893377bea3d2279ed6e9e43421ef43/raw/510bf424fa7cdd0f43f91c671ec38b63104e0859/02.make

**Comment by nitinbansal1989** [comment]
@sjackman thanks.. great help. I have now moved my brew to /home/linuxbrew/.linuxbrew
