### ISSUE TITLE
nss: No such file or directory - /path/to/brew/Cellar/nss/3.28.1/lib/libssl.a

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/homebrew-core#1620]
[```brew gist-logs nss```](https://gist.github.com/e06280886011b79911fce4cfa37f2d54)

**Comment by carlorosati** [comment]
[Line 64](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/nss.rb#L64) has an rm with reference to #28258

What does that mean?

**Comment by carlorosati** [comment]
@sjackman The real issue here is that nss.rb is a mess.. It does not install any of the utilities because  of all of the ```Dir.glob("Darwin*/bin/*")```.

What is the proper course of action here? File an issue upstream?

**Comment by sjackman** [comment]
You can submit a PR to fix the issue to this repo. Try something like (just an untested example):
```ruby
os = OS.mac? ? "Darwin" : OS.linux? ? "Linux" : "generic"
Dir.glob("#{os}*/bin/*") do |file|
```

**Comment by carlorosati** [comment]
@sjackman [That](https://github.com/Homebrew/homebrew-core/pull/9935#issuecomment-279511419) was a no-go.

**Comment by carlorosati** [comment]
Fixed by https://github.com/Linuxbrew/homebrew-core/pull/1735
