### ISSUE TITLE
xmlto: checking for long options support in getopt... no

### ISSUE THREAD

**Issue by klmr** [Linuxbrew/homebrew-core#1650]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

Output from `brew gist-logs xmlto`: https://gist.github.com/klmr/e9abc14d1615b57fef883bfccc2a6dad

Thing is, `$(brew --prefix)/bin/getopt` *does* support long options:

```bash
⟩⟩⟩ $(brew --prefix)/bin/getopt --help 2>&1 | grep longopts
 -l, --longoptions <longopts>  the long options to be recognized
```

**Comment by sjackman** [comment]
```
checking for getopt... /lustre/scratch115/realdata/mdt2/teams/miska/users/kr15/linuxbrew/opt/gnu-getopt/bin/getopt
checking for long options support in /lustre/scratch115/realdata/mdt2/teams/miska/users/kr15/linuxbrew/opt/gnu-getopt/bin/getopt... no
configure: error: 
You need getopt from <http://software.frodo.looijaard.name/getopt/>, or
else some other implementation that supports --longoptions.
```
https://gist.github.com/klmr/e9abc14d1615b57fef883bfccc2a6dad#file-01-configure-L33

I'm afraid I haven't seen that error before, and I don't have a fix for you. Sorry.

**Comment by sjackman** [comment]
I'm attempting to reproduce the error at https://github.com/Linuxbrew/homebrew-core/pull/1742

**Comment by rwhogg** [comment]
@klmr there's now a precompiled bottle for `xmlto`; does that work for you?

**Comment by klmr** [comment]
Yes, the bottle works. Thank you very much.
