### ISSUE TITLE
llvm: --with-python --with-lldb conflicts with six.py library

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1705]
```
brew install llvm --with-python --with-lldb

==> Downloading http://llvm.org/releases/3.9.1/compiler-rt-3.9.1.src.tar.xz
Already downloaded: /home/timothee/.cache/Homebrew/llvm--compiler-rt-3.9.1.tar.xz
==> cmake -G Unix Makefiles /tmp/llvm-20170201-33218-vrbovw/llvm-3.9.1.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DC
==> make
==> make install
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /katrina/home/timothee/m/katrina/brew
Could not symlink lib/python2.7/site-packages/six.py
Target /katrina/home/timothee/m/katrina/brew/lib/python2.7/site-packages/six.py
already exists. You may want to remove it:
  rm '/katrina/home/timothee/m/katrina/brew/lib/python2.7/site-packages/six.py'

To force the link and overwrite all conflicting files:
  brew link --overwrite llvm

To list all files that would be deleted:
  brew link --overwrite --dry-run llvm

Possible conflicting files are:
/katrina/home/timothee/m/katrina/brew/lib/python2.7/site-packages/six.py
==> Caveats
LLVM executables are installed in /katrina/home/timothee/m/katrina/brew/opt/llvm/bin.
Extra tools are installed in /katrina/home/timothee/m/katrina/brew/opt/llvm/share/llvm.
```
https://gist.github.com/timotheecour/09b2dea789f2462583d6db706348b4fa

NOTE: I had initially run
`brew install llvm --with-python --with-lldb --with-clang` (as recommended somewhere) but --with-clang is a noop

**Comment by rwhogg** [comment]
It looks like `llvm` installed successfully except for conflicting with six.py. My recommendation: run `brew link --overwrite --dry-run llvm`. If the only file conflicting is the Python library, I'd just diff the two versions of them and overwrite it if they're the same.

If they aren't the same or there are other conflicting files, you'll have to make a judgement call as to whether you should overwrite or not. Feel free to post the list of conflicts here so we can help with that judgement call if necessary.

I've experienced this sort of issue fairly often; if you're using easy_install or pip with a brewed Python you'll eventually end up getting these sorts of conflicts. I have to admit it sucks :frowning_face:

**Comment by sjackman** [comment]
@timotheecour Please start the short description of an issue or pull request with the relevant formula name followed by a colon.
