### ISSUE TITLE
Mono formula throws certificate error

### ISSUE THREAD

**Issue by mxplusb** [Linuxbrew/homebrew-core#1802]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Linuxbrew/brew? If it's a general Linuxbrew/brew problem please file this issue at https://github.com/Linuxbrew/brew/issues/new

### Bug reports:

```shell
pcfdev@72bda668902f:~$ brew config
/home/pcfdev/.linuxbrew/Library/Homebrew/brew.sh: line 48: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: c12f7fdde281dc1090e04b5436fd708437784cdb
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: e2629e8fd158f51e39b8c4113255ee8667e939bf
Core tap last commit: in the future
HOMEBREW_PREFIX: /home/pcfdev/.linuxbrew
HOMEBREW_REPOSITORY: /home/pcfdev/.linuxbrew
HOMEBREW_CELLAR: /home/pcfdev/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: 1.8.0_112
Kernel: Linux 4.9.4-moby x86_64 GNU/Linux
OS glibc: 2.23
OS gcc: 5.4.0
Linuxbrew glibc: N/A
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A

pcfdev@72bda668902f:~$ brew gist-logs mono
/home/pcfdev/.linuxbrew/Library/Homebrew/brew.sh: line 48: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Error: No logs.

pcfdev@72bda668902f:~$ brew install -v mono
/home/pcfdev/.linuxbrew/Library/Homebrew/brew.sh: line 48: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/home/pcfdev/.linuxbrew/Library/Homebrew/brew.sh: line 48: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
==> Downloading https://download.mono-project.com/sources/mono/mono-4.6.2.16.tar.bz2
/home/pcfdev/.linuxbrew/opt/curl/bin/curl --remote-time --location --user-agent Linuxbrew/1.1.9 (Linux; x86_64 4.9.4-moby) curl/7.52.1 --fail https://download.mono-project.com/s
ources/mono/mono-4.6.2.16.tar.bz2 -C 0 -o /home/pcfdev/.cache/Homebrew/mono-4.6.2.16.tar.bz2.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (51) SSL: no alternative certificate subject name matches target host name 'download.mono-project.com'
Error: Failed to download resource "mono"
Download failed: https://download.mono-project.com/sources/mono/mono-4.6.2.16.tar.bz2
```

This is Linuxbrew specific, it works just fine on macOS, which uses Bintray for it's download.

**Comment by sjackman** [comment]
Try `brew install curl mono`
or
```sh
curl -kL -o /home/pcfdev/.cache/Homebrew/mono-4.6.2.16.tar.bz2 https://download.mono-project.com/sources/mono/mono-4.6.2.16.tar.bz2
```
You may wish to install Linuxbrew in `/home/linuxbrew/.linuxbrew` so that you can make use of precompiled binary bottles.

**Comment by mxplusb** [comment]
Curl was installed via `brew` beforehand, I just didn't include it in the report, sorry.

For some background, I have a a `setup.sh` script that sets up an environment with a bunch of tools for a Docker container. I have normally used Linuxbrew on a per-user basis by following the standard installation instructions. Can I elect to use pre-compiled binaries for a user instead of compiling from source?

While using the pre-compiled binaries is fine, I don't really want to have a `linuxbrew` user.

**Comment by sjackman** [comment]
I'm not able to reproduce your `curl` error. Sorry. You can try updating your CA certificates, but I'm not convinced that's the problem: https://curl.haxx.se/docs/caextract.html

**Comment by sjackman** [comment]
> Can I elect to use pre-compiled binaries for a user instead of compiling from source? While using the pre-compiled binaries is fine, I don't really want to have a linuxbrew user.

Some have no problem being moved from where they were originally installed, and their formulae are tagged with `cellar :any`. Some formulae don't like to be moved after they're installed, so those bottles can only be installed in `/home/linuxbrew/.linuxbrew`. Of the 447 bottled Linuxbrew formulae, 307 (69%) are relocatable (`cellar :any`).

**Comment by mxplusb** [comment]
Gotcha, I'll close this out since it seems unreproducible. Thanks.
