### ISSUE TITLE
go: not on latest stable version

### ISSUE THREAD

**Issue by tcby45** [Linuxbrew/homebrew-core#1817]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Linuxbrew/brew? If it's a general Linuxbrew/brew problem please file this issue at https://github.com/Linuxbrew/brew/issues/new

### Bug reports:

The current golang formula is for v1.7.5; v1.8 was released yesterday. If it helps, src is available at https://storage.googleapis.com/golang/go1.8.src.tar.gz, mirror at https://fossies.org/linux/misc/go1.8.src.tar.gz. I would file a PR myself, but I'm not sure how to get the sha256 sums for different versions of macOS.

If it at all helps, see [here](https://gist.github.com/anonymous/b1d5f6bb5f23d0630392e6c6efe390d9) for build info on my particular OS (from `brew gist-logs golang`). Most of the `brew doctor` stuff shouldn't pertain to this issue, as which version of gcc being used, etc. does not change the golang version.

**Comment by rwhogg** [comment]
Hi @tcby45!

Upstream Homebrew now includes Go 1.8, so we should be able to migrate to the new version when we do the next merge.

Closing, but thanks for submitting an issue. For formulae in upstream Homebrew, we wait for them to upgrade versions rather than doing it ourselves.
