### ISSUE TITLE
autojump test fails on Ubuntu

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#1826]
```
Testing autojump
sh: 2: source: not found
sh: 3: j: not found
sh: 4: j: not found
Error: autojump: failed
<"/tmp/autojump-test-20170218-8807-vc8zo2/foo/bar"> expected but was
<"/tmp/autojump-test-20170218-8807-vc8zo2">.

diff:
- /tmp/autojump-test-20170218-8807-vc8zo2/foo/bar
?                                        --------
+ /tmp/autojump-test-20170218-8807-vc8zo2
```

This is a surprisingly complicated problem:
1. The default shell /bin/sh is linked to dash
2. %x on Ruby uses the default shell (it doesn't seem to respect $SHELL or similar)
3. autojump doesn't support dash
4. There's a bashism in the test itself

Note that fixing problem 4 (eg. by changing "source" to ".") is insufficient; so long as Ruby insists on using the default shell for %x this can only be avoided by changing how the test is written.

**Comment by sjackman** [comment]
FWIW I use `z` to jump to frequently used directories, and it's great.

**Comment by rwhogg** [comment]
See https://github.com/Linuxbrew/homebrew-core/pull/2005
