### ISSUE TITLE
rust: glibc version not found for rustc

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/homebrew-core#1837]
the rustc provided by the cargoboostrap nightly build was built on a machine with a newer libc.

How do I change the formula to run patchelf on the rustc executable to use brew's libc?

**Comment by sjackman** [comment]
The `ghc` formula has a similar problem. See https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/ghc.rb#L157
