### ISSUE TITLE
`brew install dscanner` fails

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1838]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Linuxbrew/brew? If it's a general Linuxbrew/brew problem please file this issue at https://github.com/Linuxbrew/brew/issues/new

```
containers/experimental_allocator/src/std/experimental/allocator/package.d(1290): Error: std.experimental.allocator.common.Ternary at containers/experimental_allocator/src/std/experimental/allocator/common.d(14) conflicts with std.typecons.Ternary at brew/Cellar/dmd/2.073.1/include/dlang/dmd/std/typecons.d(7470)
```

https://gist.github.com/fb4729310c330605e5f66343fe9dcc04

FYI @Hackerpilot

**Comment by rwhogg** [comment]
It's worth pointing out that, for me at least, the devel version (0.4.0-beta.3) compiles fine.

The most appropriate fix here will likely be to submit dscanner 0.4.0 upstream, assuming that that release works well on macOS.

**Comment by rwhogg** [comment]
In the meantime, a PR to add a patch that fixes the compilation error would be welcome.

**Comment by sjackman** [comment]
Closing this issue as we're not actively working on it. Feel free to submit a PR.
