### ISSUE TITLE
automake and autoconf use system perl instead of linuxbrew

### ISSUE THREAD

**Issue by dalloliogm** [Linuxbrew/homebrew-core#1897]
The files installed by the automake and autoconf formulas point to the system level perl instead of the brew installation.

In particular the shebang in these scripts points to /usr/bin/perl
```
head .brew/Cellar/automake/1.15/bin/aclocal
#!/usr/bin/perl -w
# -*- perl -*-
# Generated from bin/aclocal.in; do not edit by hand.
```

This causes problems during some installations, specially when the version of the system perl is old, and the installation requires a library installed with a newer version of perl. It usually gives a Perl_xs_handshake error, which is what you get when trying to use a perl library compiled for a different version of perl. 

For example this is an error I get when installing rgl:

```
/usr/bin/perl: symbol lookup error: ~/.brew/lib/perl5//x86_64-linux-thread-multi/auto/List/Util/Util.so: undefined symbol: Perl_xs_handshake
```

See brew list automake and brew list autoconf for a list of files affected.

**Comment by sjackman** [comment]
A pull request to resolve this issue would be welcome. Try
```ruby
inreplace bin/"aclocal", "#!/usr/bin/perl -w", "#!/usr/bin/env perl"
```
