### ISSUE TITLE
highlight: SHA256 seems to have changed

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1911]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Linuxbrew/brew? If it's a general Linuxbrew/brew problem please file this issue at https://github.com/Linuxbrew/brew/issues/new

Example such error currently:
```
brew upgrade highlight
==> Upgrading 1 outdated package, with result:
highlight 3.35
==> Upgrading highlight
==> Downloading http://www.andre-simon.de/zip/highlight-3.35.tar.bz2
Already downloaded: /home/timothee/.cache/Homebrew/highlight-3.35.tar.bz2
Error: SHA256 mismatch
Expected: 29b2111531230317fc6228b5f15ad0839448f20d65256279ac68d08319fa7a75
Actual: 8a14b49f5e0c07daa9f40b4ce674baa00bb20061079473a5d386656f6d236d05
Archive: /home/timothee/.cache/Homebrew/highlight-3.35.tar.bz2
To retry an incomplete download, remove the file above.

brew gist-logs highlight
Error: No logs.
```

## similar issues:

This type of error has occurred a few times already:

* https://github.com/Linuxbrew/homebrew-core/pull/1744#issuecomment-279344655
* and these issues: https://github.com/Linuxbrew/homebrew-core/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22SHA256%20mismatch%22%20

## root cause

https://github.com/Linuxbrew/homebrew-core/commit/8e32cf0dcfe3e33aa93c1f05b2edad4f22cec078

```
-  url "http://www.andre-simon.de/zip/highlight-3.34.tar.bz2"
-  sha256 "1ea4ff989d192a0c2538f7b18683f41829596800e9f6fecf58d9d621218664bb"
+  url "http://www.andre-simon.de/zip/highlight-3.35.tar.bz2"
+  sha256 "29b2111531230317fc6228b5f15ad0839448f20d65256279ac68d08319fa7a75"
```

doesn't bump version, so the cache isn't updated, and the sha check fails.
As mentioned here: https://github.com/Linuxbrew/homebrew-core/pull/1744#issuecomment-279348086 `brew fetch --force` may be a workaround but it's not good enough, `brew upgrade` should `just work`.

## would be nice to have a general solution for this

* could that be done via `brew audit` detecting when sha256 changes but version is not?

**Comment by timotheecour** [comment]
EDIT: looks like for this particular issue of `brew upgrade highlight`, `/home/timothee/.cache/Homebrew/highlight-3.35.tar.bz2` didn't help

**Comment by rwhogg** [comment]
This is an upstream issue with the `highlight` formula: see https://github.com/Homebrew/homebrew-core/issues/10486

**Comment by sjackman** [comment]
Moved to https://github.com/Homebrew/homebrew-core/issues/10486
