### ISSUE TITLE
Emacs doesn't load default init.el (~/.emacs.d/init.el)

### ISSUE THREAD

**Issue by enzochiau** [Linuxbrew/homebrew-core#1941]
When try to run `emacs`, got error as below

    Error (initialization): User xxx has no home directory

And also the default ~/.emacs.d/init.el

When I try to run as `emacs -l ~/.emacs.d/init.el`, I got the same error, but the default configuration are all loaded.

**Comment by sjackman** [comment]
I suspect your user has no home directory. Please report
```sh
echo x $HOME x
echo x ~ x
whoami
echo x $USER x
grep `whoami` /etc/passwd
```

**Comment by enzochiau** [comment]
Thanks for reply. I just realize that the user does exist but just not a local user. It is `centrify` managed user. 

Any solution for that situation?

**Comment by sjackman** [comment]
I don't follow. Are you saying that it doesn't work when you pour the precompiled bottle of `emacs`, but does work when you build from source?

**Comment by enzochiau** [comment]
The user does have a home work. But it is set to some place like `/export/home/xxx` (not as normal user /home/xxx) and the home directory information is not stored at local machine's /etc/password file. It is on the AD server.

**Comment by sjackman** [comment]
The location doesn't matter. What matters is that `echo x ~ x` returns something sensible. If it doesn't, a lot of things are going to break.

**Comment by enzochiau** [comment]
whoami: echi
echo: echi
echo x ~ x: x /export/home/echi x
getent passed `whoami`: nothing here

**Comment by sjackman** [comment]
Please report the output of
```sh
which -a id
/bin/id
id
```

**Comment by enzochiau** [comment]
`which -a id`: `/usr/bin/id`

`/bin/id`: `uid=868294108(echi) gid=868294108(echi) groups=868294108(echi),868221441(domain_users),868244325(master_qa),868244326(master_dev),868244327(master_prod),868244330(master_pilot),868248514(allzonesgroup),868278658(alice_r),868278659(alice_w),868278679(clearing_r),868278680(clearing_w),868278697(media_r),868278698(media_w),868278706(photos_r),868280042(respacks_w),868280043(respacks_r),868289743(voicelog_r),868289745(voicelog_w),868289920(clifdata_w),868289921(clifdata_r)`

`id`: `uid=868294108(echi) gid=868294108(echi) groups=868294108(echi),868221441(domain_users),868244325(master_qa),868244326(master_dev),868244327(master_prod),868244330(master_pilot),868248514(allzonesgroup),868278658(alice_r),868278659(alice_w),868278679(clearing_r),868278680(clearing_w),868278697(media_r),868278698(media_w),868278706(photos_r),868280042(respacks_w),868280043(respacks_r),868289743(voicelog_r),868289745(voicelog_w),868289920(clifdata_w),868289921(clifdata_r)`

**Comment by sjackman** [comment]
Please report
```sh
brew install coreutils
brew gist-logs coreutils
$(brew --prefix)/bin/id
```

**Comment by enzochiau** [comment]
[https://gist.github.com/anonymous/9d101e471efa252227a602e8febccccf](https://gist.github.com/anonymous/9d101e471efa252227a602e8febccccf)

`$(brew --prefix)/bin/id`: 
    `uid=868294108 gid=868294108 groups=868294108,868221441,868244325,868244326,868244327,868244330,868248514,868278658,868278659,868278679,868278680,868278697,868278698,868278706,868280042,868280043,868289743,868289745,868289920,868289921`

**Comment by sjackman** [comment]
Do you know how/where your user database is stored? If not ask your systems group.

**Comment by enzochiau** [comment]
I just know I am login with centrify user and Current DC.

**Comment by iMichka** [comment]
I am not sure how we can help you. You should double check with either the `centrify` developers, or the `emacs` developers, or your sysadmin.

`emacs` is probably properly installed on your system. This is a "runtime" problem. Your use case is very specific to your setup, so not sure how much time we can spend debugging this.
