### ISSUE TITLE
cask failed to install on Ubuntu 16.04: undefined method 'rebuild'

### ISSUE THREAD

**Issue by dragonnie** [Linuxbrew/homebrew-core#1945]
brew install cask
```
Error: undefined method `rebuild' for #<BottleSpecification:0x00000002602c30>
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/vagrant/.Linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/emacs.rb:9:in `block in <class:Emacs>'
/home/vagrant/.Linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/home/vagrant/.Linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/home/vagrant/.Linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'
/home/vagrant/.Linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/emacs.rb:8:in `<class:Emacs>'
/home/vagrant/.Linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/emacs.rb:1:in `load_formula'
/home/vagrant/.Linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/vagrant/.Linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/vagrant/.Linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/vagrant/.Linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/vagrant/.Linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/vagrant/.Linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/vagrant/.Linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/vagrant/.Linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/vagrant/.Linuxbrew/Library/Homebrew/formula_installer.rb:323:in `block in expand_requirements'
/home/vagrant/.Linuxbrew/Library/Homebrew/requirement.rb:215:in `block in prune?'
/home/vagrant/.Linuxbrew/Library/Homebrew/requirement.rb:213:in `catch'
/home/vagrant/.Linuxbrew/Library/Homebrew/requirement.rb:213:in `prune?'
/home/vagrant/.Linuxbrew/Library/Homebrew/requirement.rb:201:in `block (2 levels) in expand'
/usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/lib/ruby/2.3.0/set.rb:306:in `each'
/home/vagrant/.Linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/home/vagrant/.Linuxbrew/Library/Homebrew/requirement.rb:200:in `block in expand'
/home/vagrant/.Linuxbrew/Library/Homebrew/requirement.rb:199:in `each'
/home/vagrant/.Linuxbrew/Library/Homebrew/requirement.rb:199:in `expand'
/home/vagrant/.Linuxbrew/Library/Homebrew/formula.rb:1229:in `recursive_requirements'
/home/vagrant/.Linuxbrew/Library/Homebrew/formula_installer.rb:313:in `expand_requirements'
/home/vagrant/.Linuxbrew/Library/Homebrew/formula_installer.rb:263:in `compute_dependencies'
/home/vagrant/.Linuxbrew/Library/Homebrew/formula_installer.rb:130:in `verify_deps_exist'
/home/vagrant/.Linuxbrew/Library/Homebrew/formula_installer.rb:123:in `prelude'
/home/vagrant/.Linuxbrew/Library/Homebrew/cmd/install.rb:231:in `install_formula'
/home/vagrant/.Linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/home/vagrant/.Linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/home/vagrant/.Linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/home/vagrant/.Linuxbrew/Library/brew.rb:84:in `<main>'
```
It's prevented me from install brew-cask on ubuntu 16.04

**Comment by rwhogg** [comment]
Can you run `brew update` (twice) and then try again? `rebuild` has been in brew for a while now, so it may be that your brew may be out of date.

If that doesn't work, please also run `brew config`, `brew doctor`, and `brew gist-logs cask` and paste the output of those here please.

Thanks!

**Comment by dragonnie** [comment]
After updated(twice):
brew install cask
Updating Homebrew...
Error: No available formula with the name "xz" (dependency of cask)
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

**Comment by dragonnie** [comment]
brew config
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: d8c8b867bf99c604c89bc848f58d1fae8afd599c
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 766dea4adfbc3f91682461985ade0e797592c471
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /home/vagrant/.Linuxbrew
HOMEBREW_REPOSITORY: /home/vagrant/.Linuxbrew
HOMEBREW_CELLAR: /home/vagrant/.Linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: dual-core 64-bit ivybridge
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: N/A
Kernel: Linux 4.4.0-57-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.1 LTS
Codename: xenial
OS glibc: 2.23
OS gcc: 5.4.0
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A

**Comment by dragonnie** [comment]
brew doctor
Error: No available formula with the name "pkg-config"

**Comment by dragonnie** [comment]
brew gist-logs cask
Error: No logs.

**Comment by dragonnie** [comment]
Hi,
it looked like a new error occurred after we updated to the latest brew.
My config seemed normal.
brew doctor caught one error.
As well no logs for cask yet.

Could you help to analyze it further?

Thanks

**Comment by dragonnie** [comment]
Hi, Shaun

I had just added more information in the issue comment just since new error occurred while I tried to fix the cask installation issue.
Please take care of ahead.

Thanks

**Comment by sjackman** [comment]
Does the directory output by `brew --repo homebrew/core` look good? Try
```sh
cd $(brew --repo homebrew/core)
ls Formula | wc # Should report 4046    4046   47072
git fetch origin
git reset --hard origin/master
ls Formula | wc
```

**Comment by dragonnie** [comment]
It works behind reset git repo.

Thx a lot
