### ISSUE TITLE
GMT4 failed to install at the last step

### ISSUE THREAD

**Issue by byron42bae** [Linuxbrew/homebrew-core#2002]
All the dependencies were able to be downloaded and installed, when it came to installing gmt4 itself the following error arose, and I have no idea what it means or how to fix it as I am not very experienced with homebrew or linux.

```
==> Installing gmt4 from homebrew/science
==> Downloading ftp://ftp.soest.hawaii.edu/gmt/gmt-4.5.15-src.tar.bz2
Already downloaded: /home/byron/.cache/Homebrew/gmt4-4.5.15.tar.bz2
==> ./configure --prefix=/home/byron/.linuxbrew/Cellar/gmt4/4.5.15_3 --datadir=/home/byron/.linuxbrew/Cellar/gmt4/4.5.15_3/share/gmt4 --enable-gdal=/ho
==> make
Last 15 lines from /home/byron/.cache/Homebrew/Logs/gmt4/02.make:
/home/byron/.linuxbrew/lib/libgdal.so: undefined reference to `curl_easy_perform@CURL_OPENSSL_3'
/home/byron/.linuxbrew/lib/libgdal.so: undefined reference to `curl_slist_append@CURL_OPENSSL_3'
/home/byron/.linuxbrew/lib/libgdal.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_3'
/home/byron/.linuxbrew/lib/libgdal.so: undefined reference to `curl_multi_info_read@CURL_OPENSSL_3'
/home/byron/.linuxbrew/lib/libgdal.so: undefined reference to `curl_multi_add_handle@CURL_OPENSSL_3'
/home/byron/.linuxbrew/lib/libgdal.so: undefined reference to `curl_easy_init@CURL_OPENSSL_3'
/home/byron/.linuxbrew/lib/libgdal.so: undefined reference to `curl_multi_init@CURL_OPENSSL_3'
/home/byron/.linuxbrew/lib/libgdal.so: undefined reference to `curl_multi_perform@CURL_OPENSSL_3'
/home/byron/.linuxbrew/lib/libgdal.so: undefined reference to `curl_multi_fdset@CURL_OPENSSL_3'
collect2: error: ld returned 1 exit status
Makefile:277: recipe for target 'blockmean' failed
make[1]: *** [blockmean] Error 1
make[1]: Leaving directory '/tmp/gmt4-20170307-20319-1oa5r86/gmt-4.5.15/src'
Makefile:104: recipe for target 'gmt' failed
make: *** [gmt] Error 2
```

**Comment by sjackman** [comment]
Do you specifically want `gmt4` or would `gmt` suffice?
I've opened a PR to attempt to build `gmt` at https://github.com/Homebrew/homebrew-science/pull/5235

**Comment by byron42bae** [comment]
Yeah I really need gmt4 specifically as I am working with scripts that were already written for gmt4

**Comment by sjackman** [comment]
The dependency `gdal` of both `gmt` and `gmt4` is failing to build with the same error message that you're seeing above. See https://github.com/Linuxbrew/homebrew-core/pull/1987
We'd be happy to accept a pull request that fixes this build failure if you have the time and inclination.

**Comment by byron42bae** [comment]
I'd be happy to spend the time fixing the build as I need it for my research. Although I only installed linuxbrew yesterday so I'm embarrassed to say that I am not sure what a pull request is...what do you need from me?

**Comment by sjackman** [comment]
A pull request is a GitHub term. It's a way of submitting a patch to the maintainers of a project. See https://help.github.com/articles/about-pull-requests/

The file that needs to be fixed is `gdal.rb`. Start with `brew edit gdal`
See https://github.com/Homebrew/homebrew-core/blob/master/Formula/gdal.rb
