### ISSUE TITLE
No curl available

### ISSUE THREAD

**Issue by alator21** [Linuxbrew/homebrew-core#2050]
Cant install on my system(i don't have installed curl and i'm not admin/root). I modified some lines and replaced curl with wget but the original script itself downloads prefixed another ones that use curl.any thoughts?

**Comment by rwhogg** [comment]
Your best option (IMO) is asking your administrator to install curl; failing that, you could manually install all the [necessary tools](https://github.com/linuxbrew/brew#debian-or-ubuntu) that you don't already have from source.

If you can install Git from source, you could do that, then you could clone the repository manually:

```bash
$ git clone https://github.com/linuxbrew/brew.git ~/.linuxbrew
```

**Comment by maxim-belkin** [comment]
Have a look at my [standalone linuxbrew script](https://gist.github.com/maxim-belkin/f9e4c4f98e2fc6de9f6673363919df42) There I deal with absence of `curl`. It is not finished yet but you'll get an idea what to do about it.

**Comment by sjackman** [comment]
`curl` is a hard dependency of Linuxbrew. As Maxim recommended, ask your sysadmin or install it from source.
You can get away without having `git` installed. See for example
https://github.com/Linuxbrew/brew/wiki/CentOS5#install-linuxbrew-on-centos-5
and look for `Tap Linuxbrew/core` and `Tap Linuxbrew/dupes`
