### ISSUE TITLE
glibc: Installs libraries in both lib and lib64

### ISSUE THREAD

**Issue by quasus** [Linuxbrew/homebrew-core#2119]
I install Linuxbrew using the command

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"

copied from the home page and I update environmental variables. I install GCC, so far so good. Then I try to install pkg-config and the installation fails with

    configure: error: C compiler cannot create executables

Logs: https://gist.github.com/anonymous/4fa2ab670632fe467f8e92ba9b8f9f08

**Comment by sjackman** [comment]
```
configure:3487: /users/extras/kondratyev/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -isystem/users/extras/kondratyev/.linuxbrew/include -L/users/extras/kondratyev/.linuxbrew/lib -Wl,--dynamic-linker=/users/extras/kondratyev/.linuxbrew/lib/ld.so -Wl,-rpath,/users/extras/kondratyev/.linuxbrew/lib conftest.c  >&5
/users/extras/kondratyev/.linuxbrew/bin/ld: cannot find -lc
```
https://gist.github.com/anonymous/4fa2ab670632fe467f8e92ba9b8f9f08#file-config-log-L191

Please report
```sh
brew test binutils glibc gcc
brew list glibc | grep libc.so
ls -l /users/extras/kondratyev/.linuxbrew/libc.so  /users/extras/kondratyev/.linuxbrew/libc.so.6
brew install hello
```

**Comment by quasus** [comment]
% brew test binutils glibc gcc
    Testing binutils
    ==> /users/extras/kondratyev/.linuxbrew/Cellar/binutils/2.28/bin/nm /users/extras/kondratyev/.linuxbrew/Cellar/binutils/2.28/bin/nm
    Testing glibc
    ==> /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib/ld-2.19.so 2>&1 |grep Usage
    ==> /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib/libc-2.19.so --version
    ==> /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/bin/locale --version
    Testing gcc
    ==> /users/extras/kondratyev/.linuxbrew/Cellar/gcc/5.3.0/bin/gcc-5 -o hello-c hello-c.c
    Last 15 lines from /users/extras/kondratyev/.cache/Homebrew/Logs/gcc/test.01.gcc-5:
    2017-03-20 21:18:55 +0000

    /users/extras/kondratyev/.linuxbrew/Cellar/gcc/5.3.0/bin/gcc-5
    -o
    hello-c
    hello-c.c

    /users/extras/kondratyev/.linuxbrew/bin/ld: cannot find -lc
    collect2: error: ld returned 1 exit status
    Failed executing: /users/extras/kondratyev/.linuxbrew/Cellar/gcc/5.3.0/bin/gcc-5 -o hello-c hello-c.c
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/formula.rb:1834:in `block in system'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/formula.rb:1772:in `open'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/formula.rb:1772:in `system'
    /users/extras/kondratyev/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb:284:in `block in <class:Gcc>'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/formula.rb:1671:in `block (2 levels) in run_test'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/formula.rb:884:in `with_logging'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/formula.rb:1670:in `block in run_test'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/formula.rb:1664:in `run_test'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    /users/extras/kondratyev/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'
    /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib/libc.so.6
    /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib64/libc.so
    % brew list glibc | grep libc.so
    /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib/libc.so.6
    /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib64/libc.so
    % ls -l /users/extras/kondratyev/.linuxbrew/libc.so /users/extras/kondratyev/.linuxbrew/libc.so.6
    ls: cannot access /users/extras/kondratyev/.linuxbrew/libc.so: No such file or directory
    ls: cannot access /users/extras/kondratyev/.linuxbrew/libc.so.6: No such file or directory
    % ls -l `brew list glibc | grep libc.so`
    -rw-r--r-- 1 kondratyev console 404 Mar 19 21:50 /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib64/libc.so
    lrwxrwxrwx 1 kondratyev console  12 Mar 19 21:50 /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib/libc.so.6 -> libc-2.19.so
    % brew install hello
    Branch master set up to track remote branch master from origin.
    ==> Auto-updated Homebrew!
    Updated 1 tap (homebrew/core).
    No changes to formulae.

    ==> Downloading https://linuxbrew.bintray.com/bottles/hello-2.10.x86_64_linux.bottle.tar.gz
    ==> Pouring hello-2.10.x86_64_linux.bottle.tar.gz
    🍺  /users/extras/kondratyev/.linuxbrew/Cellar/hello/2.10: 52 files, 595.5K
    % hello
    Hello, world!

**Comment by maxim-belkin** [comment]
Can you try this [standalone linuxbrew](https://gist.github.com/maxim-belkin/f9e4c4f98e2fc6de9f6673363919df42) script?

**Comment by sjackman** [comment]
That's very strange. You have libraries in both`lib` and `lib64`, and I'm not sure why.
Please report
```sh
ls /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib/
ls /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib64/
```

The following fix should work:
```sh
mv /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib64/* /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib/
rmdir /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib64
ln -s lib /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib64
```

**Comment by quasus** [comment]
The directories (while lib64 was still alive):

    /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib:
    getconf			 libmemusage.so		 libnss_nisplus.so.2
    ld-2.19.so		 libm.so.6		 libnss_nis.so.2
    ld-linux-x86-64.so.2	 libnsl-2.19.so		 libpcprofile.so
    libanl-2.19.so		 libnsl.so.1		 libpthread-2.19.so
    libanl.so.1		 libnss_compat-2.19.so	 libpthread.so.0
    libBrokenLocale-2.19.so  libnss_compat.so.2	 libresolv-2.19.so
    libBrokenLocale.so.1	 libnss_db-2.19.so	 libresolv.so.2
    libc-2.19.so		 libnss_db.so.2		 librt-2.19.so
    libcidn-2.19.so		 libnss_dns-2.19.so	 librt.so.1
    libcidn.so.1		 libnss_dns.so.2	 libSegFault.so
    libcrypt-2.19.so	 libnss_files-2.19.so	 libthread_db-1.0.so
    libcrypt.so.1		 libnss_files.so.2	 libthread_db.so.1
    libc.so.6		 libnss_hesiod-2.19.so	 libutil-2.19.so
    libdl-2.19.so		 libnss_hesiod.so.2	 libutil.so.1
    libdl.so.2		 libnss_nis-2.19.so	 locale
    libm-2.19.so		 libnss_nisplus-2.19.so

    /users/extras/kondratyev/.linuxbrew/Cellar/glibc/2.19/lib64:
    audit		    libc_nonshared.a  libnsl.so		      libresolv.so
    crt1.o		    libcrypt.a	      libnss_compat.so	      librpcsvc.a
    crti.o		    libcrypt.so       libnss_db.so	      librt.a
    crtn.o		    libc.so	      libnss_dns.so	      librt.so
    gconv		    libdl.a	      libnss_files.so	      libthread_db.so
    gcrt1.o		    libdl.so	      libnss_hesiod.so	      libutil.a
    libanl.a	    libg.a	      libnss_nisplus.so       libutil.so
    libanl.so	    libieee.a	      libnss_nis.so	      Mcrt1.o
    libBrokenLocale.a   libm.a	      libpthread.a	      Scrt1.o
    libBrokenLocale.so  libmcheck.a       libpthread_nonshared.a
    libc.a		    libm.so	      libpthread.so
    libcidn.so	    libnsl.a	      libresolv.a

The workaround didn't work, more logs here:
https://gist.github.com/anonymous/410ecc55e04e00eb36f91c80bef06437
I'm not sure, maybe pkg-config uses its own libc.

As for the weird distribution between lib and lib64, perhaps it has to do with the system site configuration.

The standalone-linuxbrew script worked fine, I'll keep on experimenting with it.  However, I can provide more information about this issue as well, if needed.

**Comment by sjackman** [comment]
I missed a step in the workaround.
```sh
brew unlink glibc
brew link glibc
```
If you've installed any formulae after `brew install glibc`, those formulae will likely not work until you `brew link glibc`.
