### ISSUE TITLE
llvm for Linuxbrew

### ISSUE THREAD

**Issue by maxim-belkin** [Linuxbrew/homebrew-core#2133]
TODO list for `llvm` formula for Linuxbrew:
- [ ] strip binaries to reduce bottle size
- [ ] resolve conflict with [libunwind](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/libunwind.rb):
    - [ ] disable libunwind resource within llvm itself
    - [ ] or add `conflicts_with`

**Comment by sjackman** [comment]
Is removing `libgomp.so` a good solution to that conflict?
```ruby
    # Remove conflicting libraries.
    # libgomp.so conflicts with gcc.
    # libunwind.so conflcits with libunwind.
    rm [lib/"libgomp.so", lib/"libunwind.so"] if OS.linux?
```
https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/llvm.rb#L326

**Comment by maxim-belkin** [comment]
From http://openmp.llvm.org:

>### Features and Goals
>
>- Support for the [OpenMP 3.1 standard (PDF)](http://www.openmp.org/mp-documents/OpenMP3.1.pdf) has been achieved in the Clang 3.8.0 release.
>- Support for the [OpenMP 4.0 standard (PDF)](http://www.openmp.org/mp-documents/OpenMP4.0.0.pdf) and [OpenMP 4.5 standard (PDF)](http://www.openmp.org/mp-documents/OpenMP4.5.pdf) is now being implemented. (Some OpenMP 4.0 and 4.5 features are already available).
>- High performance.
>- ABI compatibility with [Gcc](http://gcc.gnu.org/) and [Intel's existing OpenMP compilers](http://software.intel.com/en-us/intel-compilers). We currently have binary compatibility with OpenMP 3.1 code compiled by gcc 4.9, however we do not have support for OpenMP 4.0 code that uses task cancellation when compiled by gcc 4.9. How we will support such code remains a research issue.

**Comment by sjackman** [comment]
> ABI compatibility with Gcc and Intel's existing OpenMP compilers

🎉

**Comment by maxim-belkin** [comment]
well... the title says "Features **and Goals**"...
