### ISSUE TITLE
Qt5: please add bottle

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#214]
_From @alekseysidorov on May 6, 2016 11:26_

I want to use linuxbrew with Tavis to unify my build scripts. But the compile time too long and exceed the time limits in Travis. 

_Copied from original issue: Linuxbrew/brew#25_

**Comment by rwhogg** [comment]
I don't think `qt5` even builds correctly at the moment; see https://github.com/Linuxbrew/homebrew-core/issues/146 . Does it build correctly for you?

I apologize for the difficulty.

**Comment by sjackman** [comment]
Superseded by #681
