### ISSUE TITLE
Failed to install vendor Ruby on Ubuntu 12.04

### ISSUE THREAD

**Issue by tarah28** [Linuxbrew/homebrew-core#2141]
Hello, I'm ultimately trying to install gubbins on Ubuntu 12.04 system. At first I as getting issues with the python3 install, not being able to install dependencies. So I ran `brew update` twice and then `brew doctor` once. Now this is all I get:

```
tl@linus:~/.linuxbrew$ brew doctor
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.
```

I could not find this issue already but I do apologize if I missed a duplicate issue. This is actually the same issue that I was getting with the python dependency xz. I tried manually downloading and installing both xz and Ruby but it is still not recognizing. TIA!

**Comment by maxim-belkin** [comment]
Do
```wget -P ~/.cache/Homebrew https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz``` 
before `brew doctor`

**Comment by tarah28** [comment]
Thanks for the quick response @maxim-belkin! 

That worked for Ruby install. I ran `brew doctor` again and there are alot of warnings. Some of the library files I am not sure about but I know that there are quite a few that are needed for other programs not installed through homebrew. I attached the log file below. 

Also wondering if I need to put: `wget -P ~/.cache/Homebrew` when I get errors downloading which I am gettting again/still. This is the error I get trying to install git as the brew doctor result suggested that needed to be upgraded:

tl@linus:~$ brew install git
==> Installing dependencies for git: binutils, linux-headers, glibc, xz, gmp, mpfr, libmpc, isl, gcc, gpatch, openssl, pkg-config, curl, expat
==> Installing git dependency: binutils
==> Downloading https://linuxbrew.bintray.com/bottles/binutils-2.28.x86_64_linux.bottle.tar.gz

curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
Error: Failed to download resource "binutils"
Download failed: https://linuxbrew.bintray.com/bottles/binutils-2.28.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://ftpmirror.gnu.org/binutils/binutils-2.28.tar.gz

curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
Trying a mirror...
==> Downloading https://ftp.gnu.org/gnu/binutils/binutils-2.28.tar.gz

curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
Error: Failed to download resource "binutils"
Download failed: https://ftp.gnu.org/gnu/binutils/binutils-2.28.tar.gz
 



[brew_doctor_20170320.txt](https://github.com/Linuxbrew/homebrew-core/files/856515/brew_doctor_20170320.txt)

**Comment by sjackman** [comment]
@tarah28 Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
To disable SSL verification
```sh
echo insecure >> ~/.curlrc
git config --global http.sslVerify false
```
See https://github.com/Linuxbrew/brew/issues/298#issuecomment-287148729

**Comment by tarah28** [comment]
Thanks so much and sorry for being such a newbie :)

**Comment by sjackman** [comment]
No apologies needed. This problem has come up before, and now that we have a solution, it should go in a FAQ.

**Comment by sjackman** [comment]
Done. The Linuxbrew FAQ now has one entry!
https://github.com/Linuxbrew/brew/wiki/FAQ
:tada:

**Comment by tarah28** [comment]
Thanks @sjackman! The FAQ will be helpful  ;)
