### ISSUE TITLE
Formula: collada-dom.rb depends on libxml2

### ISSUE THREAD

**Issue by pvmilk** [Linuxbrew/homebrew-core#2184]
I tried to install collada-dom through 
$brew install collada-dom

The compiler cannot find -lxml2. 
Hence I add the following at line 31, and it solved the issue. 
   depends_on "libxml2" unless OS.mac?

(Sorry for not doing a proper pull-request).

**Comment by sjackman** [comment]
Thanks for the bug report. Would you like to submit a PR? You can do it from within your browser, if you like.
https://github.com/Linuxbrew/homebrew-core/edit/master/Formula/collada-dom.rb
