### ISSUE TITLE
SSL cert error (cURL) when installing THC AMAP

### ISSUE THREAD

**Issue by JohnScott623** [Linuxbrew/homebrew-core#2187]
I make sure that everything is up to date (I'm running on a fresh installation), I run the doctor, and this issue persists when attempting `brew install amap`.

`curl: (60) SSL certificate problem: unable to get local issuer certificate`
`More details here: https://curl.haxx.se/docs/sslcerts.html`

`curl performs SSL certificate verification by default, using a "bundle"`
` of Certificate Authority (CA) public keys (CA certs). If the default`
` bundle file isn't adequate, you can specify an alternate file`
` using the --cacert option.`
`If this HTTPS server uses a certificate signed by a CA represented in`
` the bundle, the certificate verification probably failed due to a`
` problem with the certificate (it might be expired, or the name might`
` not match the domain name in the URL).`
`If you'd like to turn off curl's verification of the certificate, use`
` the -k (or --insecure) option.`
`Error: Failed to download resource "amap"`
`Download failed: https://www.thc.org/releases/amap-5.4.tar.gz`

It looks like to be related to some related to cURL. [There is some discussion here on GitHub where a user has a very similar issue.](https://github.com/openssl/openssl/issues/2833) I'm not knowledgeable in SSL, so I can't do much investigating myself, unfortunately.

- From what I can tell, this is more likely an issue with cURL than an issue with the install script, as the needed certificates are not available. Still, this is a problem that installation scripts should work around. 

- Similar to how Brew will get you going with development tools and compilers if they are not installed beforehand, the root certificates should be regarded as dependencies of scripts that need them; it's not good to make assumptions.

Oh, and I'm using Debian Unstable. Debian's build of cURL is compiled as follows:

`curl 7.53.1 (x86_64-pc-linux-gnu) libcurl/7.53.1 OpenSSL/1.0.2k zlib/1.2.11`
`Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp` 
`Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy`

Oh, and the file downloads normally when the link is pasted into my browser, and it acknowledges the certificate as being valid. I also ensured that my root certificates were installed through my distro's package manager.

**Comment by sjackman** [comment]
Does this FAQ resolve your issue? https://github.com/Linuxbrew/brew/wiki/FAQ

**Comment by JohnScott623** [comment]
I suppose it would, but that's a silly workaround.

- If this isn't going to be corrected in the future and users are instead going to have to run the commands in the FAQ, why not just automate it and make installer scripts run those themselves (or, better yet, pass a flag to cURL to not worry about the certificate, or just not use https:// at all)? It seems like there are a lot of better options.
- Not using SSL makes for a bit of a security problem. It should be used as much as possible, but using an HTTP link or passing a flag to cURL to ignore the error would still be more convenient for users than making a universal change to cURL that affects other applications too.

**Comment by sjackman** [comment]
This failure is common, hence the FAQ, so automating a check for out-of-date certs in the installer script is a good idea. A PR would be welcome. See https://github.com/Linuxbrew/install

The FAQ should include directions on how to reverse the change. The FAQ is publicly editable. Feel free to update it.

**Comment by JohnScott623** [comment]
Alright, I have made [a pull request](https://github.com/Linuxbrew/brew/pull/309) and updated the wiki. I think that wraps this up.

**Comment by sjackman** [comment]
Thanks for your contribution to the wiki, John! I'll take a look at the PR.
