### ISSUE TITLE
vim fails to install due to missing ncurses dependency 

### ISSUE THREAD

**Issue by spacerodent** [Linuxbrew/homebrew-core#2223]
### Bug reports:

Fresh install of linuxbrew on Ubuntu 16.04 LTS fails to install vim due to missing ncurses dependency

Gist of failure https://gist.github.com/spacerodent/a680fada5bb83c06fc86bb2748fe4cf4

**Comment by sjackman** [comment]
Would you like to submit a PR to resolve this issue?
```ruby
depends_on "homebrew/dupes/ncurses" unless OS.mac?
```
I can do it if not, but a PR would be welcome.
