### ISSUE TITLE
error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument

### ISSUE THREAD

**Issue by zeneofa** [Linuxbrew/homebrew-core#223]
Hi,

I am having trouble running brew built binaries eg:

```
    `brew --prefix`/bin/bash
    /lustre/atlas1/bif102/proj-shared/.linuxbrew/bin/bash: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument
```

I have reinstalled glibc (with brew), so no idea what is going on now...

**Comment by sjackman** [comment]
Assuming that `brew install -s hello` fails, please report `brew gist-logs hello`.
Please also report
```sh
ldd `brew --prefix`/bin/bash
```

**Comment by zeneofa** [comment]
The gist: https://gist.github.com/aadaee989fb119cd0a0de10f04b8135f
and the ldd (no idea what that does)

	linux-vdso.so.1 =>  (0x00007fff733f3000)
	libreadline.so.6 => /lustre/atlas1/bif102/proj-shared/.linuxbrew/lib/libreadline.so.6 (0x00002aeb0c11c000)
	libhistory.so.6 => /lustre/atlas1/bif102/proj-shared/.linuxbrew/lib/libhistory.so.6 (0x00002aeb0c362000)
	libncursesw.so.6 => /lustre/atlas1/bif102/proj-shared/.linuxbrew/lib/libncursesw.so.6 (0x00002aeb0c56b000)
	libdl.so.2 => /lustre/atlas1/bif102/proj-shared/.linuxbrew/lib/libdl.so.2 (0x00002aeb0c7bf000)
	libc.so.6 => /lustre/atlas1/bif102/proj-shared/.linuxbrew/lib/libc.so.6 (0x00002aeb0c9c4000)
	/lib64/ld-linux-x86-64.so.2 (0x00002aeb0befa000)

I made a backup of the brew installation that gave the error (linuxbrew_backup) and reinstalled brew. So the above gist and ldd info is for that linuxbrew installtion.

For most of the libraries in this new brew, things seem to work out fine, it was just a nightmare to get the right gcc compiler working. So had to run:
    
    brew install <package> --env=inherit

after loading a module that contains gcc/4.9 (as some of the packages fail with gcc/5.3 , which is the one that linuxbrew installs as 'gcc'). The package that does however give the error after a successful install (ie when I try to run it), is homebrew/science/rna-star. This produces the exact same error as above.

    STAR: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument

**Comment by rwhogg** [comment]
> and the ldd (no idea what that does)

It tells you what shared libraries the given program depends on.

**Comment by sjackman** [comment]
> as some of the packages fail with gcc/5.3

You can post issues or even better pull requests annotating these formula as
```ruby
fails_with :gcc => "5"
```

If you both compiler installed in your `PATH` and named `gcc-4.9` and `gcc-5`, then Linuxbrew will pick the right compiler to use for each formula.

**Comment by sjackman** [comment]
Please report
```sh
patchelf --print-interpreter --print-rpath `brew --prefix`/bin/STAR
```
My best guess is that you're using your host system's dynamic linker `ld.so` from `glibc` 2.11 with Linuxbrew's `libc.so.6` from `glibc` 2.19, which won't work. If that's the case, then `brew patchelf homebrew/science/rna-star` should fix it.

**Comment by sjackman** [comment]
```
Warning: Setting LD_* vars can break dynamic linking.
Set variables:
    LD_LIBRARY_PATH: /opt/gcc/mpc/0.8.1/lib:/opt/gcc/mpfr/2.4.2/lib:/opt/gcc/gmp/4.3.2/lib:/opt/gcc/4.9.0/snos/lib64
```
https://gist.github.com/anonymous/aadaee989fb119cd0a0de10f04b8135f#file-00-doctor-out-L7

Mixing your host's libraries with Linuxbrew's libraries causes grief and creates difficult to troubleshoot situations. Before running Linuxbrew programs, please use
```
unset LD_LIBRARY_PATH
```

**Comment by sjackman** [comment]
I would like to package `gcc` 4.9 for Linuxbrew for formula that don't compile with `gcc` 5. You can also use `brew install llvm --with-clang` to see if those formula compile with `clang`. Thanks to the upstream work of Homebrew, everything *should* compile with `clang` (YMMV).

**Comment by zeneofa** [comment]
Hi Shaun,

The result was:

/lib64/ld-linux-x86-64.so.2
/lustre/atlas1/bif102/proj-shared/piet/.linuxbrew/lib

Your suggestion worked though, thnx a bunch.

**Comment by zeneofa** [comment]
I can't unfortunately unset the LD_LIBRARY_PATH, there are system libraries
that are loaded by modules that I need to run and interface with the HPC
environment that I am working on. I might be able to unset before I
install, as you suggest and then reset after that.

I will try to see if I can compile things with clang, as my current way of
compiling causes me unspeakable frustration.

**Comment by sjackman** [comment]
> I might be able to unset before I install, as you suggest and then reset after that.

That should work. You could create an alias or shell script to do that for you. Something like (untested)
```sh
alias brew="LD_LIBRARY_PATH= brew"
```
(note the space after `=` and before `brew`)
