### ISSUE TITLE
glibc postinstall error

### ISSUE THREAD

**Issue by ahundt** [Linuxbrew/homebrew-core#2245]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Linuxbrew/brew? If it's a general Linuxbrew/brew problem please file this issue at https://github.com/Linuxbrew/brew/issues/new

### Bug reports:

I tried running brew install gcc, of which glib is one of the dependencies and it failed to install on the machine, which is running CentOS.

https://gist.github.com/66f50ced1f0dfe30e8cd68f45545afa8

**Comment by sjackman** [comment]
```
/home-1/ahundt1@jhu.edu/.linuxbrew/Cellar/glibc/2.19/bin/localedef
-i
en_US
-f
UTF-8
en_US.UTF-8

Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!
```
https://gist.githubusercontent.com/anonymous/66f50ced1f0dfe30e8cd68f45545afa8/raw/29d3e04177bb3ffd599265bcb274ec992144fdc9/post_install.01.localedef

See the output of `brew doctor` and heed its warnings:
```
Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: /cm/shared/apps/ruby/2.4.1/lib:/cm/shared/apps/Intel/readline/-6.3-4-1-16/lib:/cm/shared/apps/parallel_studio_xe_2015_update2/impi/5.0.3.048/intel64/lib:/cm/shared/apps/parallel_studio_xe_2015_update2/composer_xe_2015.2.164/compiler/lib/intel64:/cm/shared/apps/parallel_studio_xe_2015_update2/composer_xe_2015.2.164/mkl/lib/intel64:/cm/shared/apps/gcc/4.9.2/lib64:/cm/shared/apps/gcc/4.9.2/lib:/cm/shared/apps/mpc/1.0.3/lib:/cm/shared/apps/gcc/4.9.2/gmp-6.0/lib:/cm/shared/apps/mpfr/3.1.3/lib:/cm/shared/apps/cudnn/5.1/lib64:/cm/shared/apps/cuda/8.0/lib64:/cm/shared/apps/java/jdk1.8.0_112/lib:/cm/shared/apps/python/3.6.6/lib:/cm/shared/apps/boost/1.60.0/lib:/cm/shared/apps/byobu/5.115/lib:/cm/shared/apps/libevent/2.1.5-beta/lib:/cm/shared/apps/git/2.6.4/lib:/cm/shared/apps/sed/4.4/lib:/cm/shared/apps/slurm/current/lib/slurm:/cm/shared/apps/slurm/current/lib:/cm/shared/apps/zsh/5.0.7/lib:/cm/shared/apps/Intel/openmpi/1.8.4/lib:/cm/shared/apps/binutils/2.25/src/lib:/home-1/ahundt1@jhu.edu/lib:/home-1/ahundt1@jhu.edu/lib:/home-1/ahundt1@jhu.edu/lib
  LD_RUN_PATH: /cm/shared/apps/parallel_studio_xe_2015_update2/impi/5.0.3.048/intel64/lib:/cm/shared/apps/parallel_studio_xe_2015_update2/composer_xe_2015.2.164/compiler/lib/intel64:/cm/shared/apps/parallel_studio_xe_2015_update2/composer_xe_2015.2.164/lib/mkl/lib/intel64:/cm/shared/apps/Intel/openmpi/1.8.4/lib
```
https://gist.github.com/anonymous/66f50ced1f0dfe30e8cd68f45545afa8#file-00-doctor-out-L5

Try
```sh
unset LD_LIBRARY_PATH LD_RUN_PATH
brew postinstall glibc
```

**Comment by ahundt** [comment]
hmm... that makes for quite an interesting problem! I'm on a [slurm cluster](https://slurm.schedmd.com/), in other words a supercomputing node with a standardized setup.

Setting the paths is how the slurm system & the admins provide access to all libraries and executables, including ruby... This means unsetting those variables will definitely mean I won't be able to use ruby, as per the first `LD_LIBRARY_PATH: /cm/shared/apps/ruby/2.4.1/lib`, so `brew doctor` and `brew install` wouldn't run!

Perhaps I should just ask the sysadmin what my options are here. What bad luck...

**Comment by sjackman** [comment]
`LD_LIBRARY_PATH` is a sledgehammer solution, because it affects all executable that you run, both the host system and Linuxbrew, and it takes precedence over the library search path encoded in the executable (called the `RPATH`) so it's basically guaranteed to break things.

It's better to encode the library search path needed for each executable in the executable itself, which is what Linxubrew does. You can use the tool `patchelf` to print and modify the `RPATH` of each executable. e.g. `patchelf --print-rpath $(which ruby)`

**Comment by sjackman** [comment]
That being said, you can selectively add selectively add items back into your `LD_LIBRARY_PATH` to get yourself a working system, such as `/cm/shared/apps/ruby/2.4.1/lib`. Try…
```sh
LD_LIBRARY_PATH=/cm/shared/apps/ruby/2.4.1/lib brew install ruby
```
