### ISSUE TITLE
findutils: /usr/bin/sort: No such file or directory

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#2263]
_From @parsibox on April 2, 2017 8:14_

hi
updatedb has error and locate show no results
```
[parsibox@localhost VSCode-linux-x64]$ updatedb
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/libexec/bin/updatedb: line 323: /usr/bin/sort: No such file or directory

[parsibox@localhost VSCode-linux-x64]$ which sort
~/.linuxbrew/bin/sort
```

_Copied from original issue: Linuxbrew/brew#322_

**Comment by rwhogg** [comment]
The sort program appears to be controlled by an autoconf variable for `findutils`, so we could probably make `findutils` depend on `coreutils` and rebuild the bottle.

Can you run `brew config` and paste the output here please? `/usr/bin/sort` is provided by `coreutils` on Debian/Ubuntu, and presumably by a similar package other systems. While coreutils isn't strictly speaking a dependency of Linuxbrew, other stuff could likely break if it's not available.

**Comment by parsibox** [comment]
[parsibox@localhost ~]$ brew config

HOMEBREW_VERSION: 1.1.10-568-gfab128714
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: fab128714d57af52c391db36ce9d91252bb2edb7
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 66a08e4aebaf90b202c552ba445b26364cc5c87e
Core tap last commit: 27 hours ago
HOMEBREW_PREFIX: /home/parsibox/.linuxbrew
HOMEBREW_REPOSITORY: /home/parsibox/.linuxbrew
HOMEBREW_CELLAR: /home/parsibox/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: single-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648 => /home/parsibox/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: 4.0 build 
Git: 2.12.2 => /home/parsibox/.linuxbrew/bin/git
Perl: /home/parsibox/.linuxbrew/bin/perl => /home/parsibox/.linuxbrew/Cellar/perl/5.24.1/bin/perl
Python: /home/parsibox/.linuxbrew/bin/python => /home/parsibox/.linuxbrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /home/parsibox/.linuxbrew/bin/ruby => /home/parsibox/.linuxbrew/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.7.0_131
Kernel: Linux 2.6.32-642.15.1.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.8 (Final)
Codename: Final
OS glibc: 2.12
OS gcc: 4.9.2
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A

**Comment by parsibox** [comment]
locate not work at all ==> no result for every thing
[parsibox@localhost ~]$ 
[parsibox@localhost ~]$ locate libglib
[parsibox@localhost ~]$ locate brew
[parsibox@localhost ~]$

**Comment by maxim-belkin** [comment]
you can't use `locate` for `brew`. Use
```sh
$ type -a brew
$ which -a brew
$ locate libglib
```

**Comment by parsibox** [comment]
locate not work at all ==> no result for every thing  ==>  libglib exist but not show in locate

[parsibox@localhost ~]$ type -a brew
brew is /home/parsibox/.linuxbrew/bin/brew
brew is /home/parsibox/.linuxbrew/bin/brew
[parsibox@localhost ~]$ which -a brew
~/.linuxbrew/bin/brew
~/.linuxbrew/bin/brew
[parsibox@localhost ~]$ locate libglib
[parsibox@localhost ~]$

**Comment by maxim-belkin** [comment]
```sh
echo -e ${PATH//\:/\\n}
```

**Comment by parsibox** [comment]
/home/parsibox/.linuxbrew/lib/libglib-2.0.so.0
/home/parsibox/.linuxbrew/lib/libglib-2.0.so
/home/parsibox/.linuxbrew/lib/libglib-2.0.so.0.5200.0
/home/parsibox/.linuxbrew/lib/libglib-2.0.a

**Comment by maxim-belkin** [comment]
I agree that referencing `/usr/bin/sort` is a bug. It should probably be `$(which sort)`. Thanks for the report, @parsibox. We'll fix that

**Comment by parsibox** [comment]
maxim-belkin  i do some work that fix this error but locate has no result
i create a symbol /usr/bin/sort to $(which sort)

[parsibox@localhost ~]$ which sort
~/.linuxbrew/bin/sort

/usr/bin/sort  ==>  /home/parsibox/.linuxbrew/bin/sort

that fix this error but no result ===> ( i run updatedb and then locate brew )


[parsibox@localhost ~]$ updatedb
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/root': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/opt/rh/devtoolset-3/root/root': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/opt/rh/python27/root/root': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/.dbus': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/lost+found': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/audit': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/lvm/archive': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/lvm/backup': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/lvm/cache': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/sssd': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/cups/ssl': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/audisp': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/pki/CA/private': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/pki/rsyslog': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/polkit-1/localauthority': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/named': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/ntp/crypto': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/ipsec.d': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/sudoers.d': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/selinux/targeted/modules/active': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/etc/dhcp': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/empty/sshd': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lock/lvm': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/abrt/ccpp-2017-04-01-21:32:58-3032': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/abrt/ccpp-2017-04-01-16:08:13-29928': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/abrt-upload': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/cups': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/public': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/defer': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/incoming': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/flush': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/bounce': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/maildrop': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/saved': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/deferred': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/private': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/corrupt': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/trace': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/active': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/postfix/hold': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/cron': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/spool/at': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/certmonger/requests': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/certmonger/cas': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/certmonger/local': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/pulse': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/sss/pipes/private': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/sss/db': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/sss/keytabs': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/postfix': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/nfs/statd': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/dav': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/php/wsdlcache': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/php/session': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/authconfig': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/mlocate': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/udisks': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/samba/winbindd_privileged': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/samba/private': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/polkit-1': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/45': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/26': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/56': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/2': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/25': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/27': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/22': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/47': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/24': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/3': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/38': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/37': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/29': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/30': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/13': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/40': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/52': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/53': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/12': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/35': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/10': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/33': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/19': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/16': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/20': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/23': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/57': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/54': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/51': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/43': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/49': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/9': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/21': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/42': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/34': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/7': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/48': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/28': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/1': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/39': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/55': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/32': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/31': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/18': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/5': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/50': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/46': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/6': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/41': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/11': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/44': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/14': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/4': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/36': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/15': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/58': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/8': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/59': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/yum/history/2016-05-22/17': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/rsyslog': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/lib/gdm': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/named': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/db/sudo': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/lvm': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/hald': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/cups/certs': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/certmonger/.config': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/pcscd.events': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/httpd': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/udisks': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/pluto': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/mdadm': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/run/gdm': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/gdm': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/cache/mod_proxy': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/cache/hald': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/cache/cups': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/cache/ldconfig': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/cache/rpcbind': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/log/audit': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/log/sssd': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/log/httpd': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/log/pluto/peer': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/log/samba': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/log/ppp': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/log/gdm': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/var/log/php-fpm': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/usr/lib64/audit': Permission denied
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/bin/find: '/boot/lost+found': Permission denied
mv: replace '/home/parsibox/.linuxbrew/var/locate/locatedb', overriding mode 0644 (rw-r--r--)? y






and after that 
[parsibox@localhost ~]$ locate brew
[parsibox@localhost ~]$ 

no result

**Comment by maxim-belkin** [comment]
```sh
$ hash -r
$ locatedb -d /home/parsibox/.linuxbrew/var/locate/locatedb brew
```

**Comment by parsibox** [comment]
[parsibox@localhost ~]$ hash -r
[parsibox@localhost ~]$ hash
hash: hash table empty
[parsibox@localhost ~]$ locatedb -d /home/parsibox/.linuxbrew/var/locate/locatedb brew
bash: locatedb: command not found
[parsibox@localhost ~]$

**Comment by parsibox** [comment]
[parsibox@localhost ~]$ brew install findutils
Warning: findutils-4.6.0 already installed

**Comment by parsibox** [comment]
i run this 
[parsibox@localhost ~]$ locate -d /home/parsibox/.linuxbrew/var/locate/locatedb brew

but after this also locate has no results

**Comment by maxim-belkin** [comment]
@parsibox please read carefully: https://guides.github.com/features/mastering-markdown/

it should've been
```
$ hash -r
$ locate -d /home/parsibox/.linuxbrew/var/locate/locatedb brew
```

**Comment by parsibox** [comment]
i run this
` [parsibox@localhost ~]$ locate -d /home/parsibox/.linuxbrew/var/locate/locatedb brew`
but after this also locate has no results
![eee](https://cloud.githubusercontent.com/assets/12513476/24598827/b9c67538-1862-11e7-97a0-533055b07423.PNG)

**Comment by maxim-belkin** [comment]
how about
```
locate -b -d /home/parsibox/.linuxbrew/var/locate/locatedb \\brew
```

**Comment by parsibox** [comment]
`
	[parsibox@localhost ~]$ locate -b -d /home/parsibox/.linuxbrew/var/locate/locatedb \\brew
	/home/parsibox/.linuxbrew/bin/brew
	/home/parsibox/.linuxbrew/completions/bash/brew
	/home/parsibox/.linuxbrew/etc/bash_completion.d/brew
	[parsibox@localhost ~]$ locate brew
	[parsibox@localhost ~]$ locate ram
	[parsibox@localhost ~]$ 

`

**Comment by maxim-belkin** [comment]
it should be `\\`, not `\`
try
```
locate -b -d /home/parsibox/.linuxbrew/var/locate/locatedb \\ram
```

**Comment by parsibox** [comment]
![llll](https://cloud.githubusercontent.com/assets/12513476/24599263/8edb4cf2-1864-11e7-9df5-b4417018a1cd.PNG)

**Comment by parsibox** [comment]
now it work!
what is the problem?
i must use this command for all my search? or you will fix it ?

**Comment by maxim-belkin** [comment]
I'm not sure what is the problem and, therefore, whether this is "fixable".

Are you using locate to find programs?

**Comment by parsibox** [comment]
no but i use locate for find files

**Comment by maxim-belkin** [comment]
use `find`
```
find /home/parsibox -iname "brew"
```

**Comment by parsibox** [comment]
I think this is not a good way
please fix this aloso

**Comment by sjackman** [comment]
Please report
```sh
locate -S
export LOCATE_PATH=~/.linuxbrew/var/locate/locatedb
locate -S
```

**Comment by parsibox** [comment]
```
[parsibox@localhost ~]$ locate -S
Database /home/parsibox/.linuxbrew/var/locate/locatedb is in the GNU LOCATE02 format.
Database was last modified at 2017:04:03 11:45:08.307714204 +0430
Locate database size: 4263004 bytes
All Filenames: 383880
File names have a cumulative length of 24055916 bytes.
Of those file names,

	66 contain whitespace, 
	0 contain newline characters, 
	and 0 contain characters with the high bit set.
Compression ratio 82.28% (higher is better)


```

but in other bash it not work

**Comment by sjackman** [comment]
> but in other bash it not work

Correct, you'll have to add that line to either your `.bashrc` or your `.bash_profile`

**Comment by parsibox** [comment]
thanks
