### ISSUE TITLE
lzo 2.10 only builds with --env=super

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/homebrew-core#2277]
* Mac:  `brew install lzo -s`  OK
* Linux: `brew install lzo -s` FAILS at `make check` step.
* Linux: `brew install lzo -s --env=super` OK
(There is no bottle for Linux)

https://gist.github.com/43b11f2d5c3bf05e1ab7bbb9c25c03af

**Comment by sjackman** [comment]
Thanks for the bug report, Torsten. We plan on making `--env-upser` the default for users with the next release of `brew`, which may be this week. So I won't myself look into fixing `lzo` for `--env=std`.
