### ISSUE TITLE
`pkg-config` doesn't find everything

### ISSUE THREAD

**Issue by alexanderadam** [Linuxbrew/homebrew-core#2306]
I'm running Ubuntu 16.10 and [by accident](https://github.com/crystal-lang/crystal/issues/4245#issuecomment-292282456) I found out that the `pkg-config` provided by homebrew doesn't find all available libraries.
On the other hand the pkg-config provided _by the distribution_ finds everything.

```bash

$ pkg-config --list-all | wc -l # or /home/user/.linuxbrew/bin/pkg-config
22
$ pkg-config --variable pc_path pkg-config
/home/alex/.linuxbrew/lib/pkgconfig:/home/alex/.linuxbrew/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/home/alex/.linuxbrew/Library/Homebrew/os/linux/pkgconfig

```

vs

```bash

$ /usr/bin/pkg-config --list-all | wc -l
202

$ /usr/bin/pkg-config --variable pc_path pkg-config
/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig

```

Setting `PKG_CONFIG_PATH` fixes this issue but I guess it would be much better if the path could be added as a default as well. So `pkg-config` won't "brake" for users that are using Linuxbrew.

**Comment by sjackman** [comment]
It's by design that Linuxbrew's `pkg-config` can only find packages installed by Linuxbrew. Linuxbrew can't control the versions of libraries installed by your host operating system, and mixing and matching the host system libraries with the Linuxbrew libraries cant create trouble. I recommend using only host libraries or only Linuxbrew libraries.

**Comment by alexanderadam** [comment]
Thank you for the fast response @sjackman,

allright, so in that case I should another Issue because Linuxbrew's `pkg-config` finds _too many_ libraries (because it's looking in `/usr/local/lib/pkgconfig` and `/usr/lib/pkgconfig`).

Either way the current default is inconsistent…

**Comment by sjackman** [comment]
Yes, that's a bug. A PR would be welcome to fix it.

**Comment by maxim-belkin** [comment]
@alexanderadam please try:
```
brew update
brew update
brew upgrade
brew remove --ignore-dependencies pkg-config
brew install -vds --env=super pkg-config
```

**Comment by alexanderadam** [comment]
@maxim-belkin works like charm.

PS: I didn't install `pkg-config` intentionally. I installed `pngquant` and `pkg-config` came as dependency. Which means that installing `pngquant` basically broke my global build environment. I have the feeling that this isn't something a user is expecting.
