### ISSUE TITLE
elfutils: conflicts with libelf

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#233]
Both install `libelf.so` and `libelf.a`.

`libelf` has 3 dependencies and `elfutils` has none. It's probably easiest to just make `elfutils` keg-only.

**Comment by sjackman** [comment]
See https://github.com/Linuxbrew/linuxbrew/pull/520#issuecomment-176455530

**Comment by sjackman** [comment]
> libelf has 3 dependencies and elfutils has none. It's probably easiest to just make elfutils keg-only.

Makes sense to me, since `libelf` is Mac/Linux and `elfutils` is Linux only. I usually defer to Debian in cases like this. See [packages.debian.org libelf.so](https://packages.debian.org/search?searchon=contents&keywords=libelf.so&mode=path&suite=stable&arch=any). These two packages appear to conflict, although I don't see this conflict listed explicitly.

See https://packages.debian.org/jessie/amd64/libelf-dev/filelist
and https://packages.debian.org/jessie/amd64/libelfg0-dev/filelist

**Comment by sjackman** [comment]
Are these two libraries API compatible?

**Comment by rwhogg** [comment]
I think so. Doing a `readelf` of both libraries shows substantial function duplication, but `elfutils` appears to have far more (not 100% sure it's a superset, but seems likely)

`libelf`'s interface is a bit of a de-facto standard used by both Linux and Solaris. From https://gnu.wildebeest.org/blog/mjw/2016/01/13/elf-libelf-compressed-sections-and-elfutils/ :

```
The libelf library is not really formally standardized but through the generic-abi mailinglist (and sometimes private emails between the maintainers) we try to keep the interfaces source compatible. It provides two sets of interfaces, the libelf.h interface, which mainly abstracts away the on-disk and native in-memory representations (so you can easily read and manipulate big endian ELF files on a little endian platform, or the other way around) and the gelf.h interface which abstracts away the differences between 32 bit and 64 bit ELF files. elfutils provides the libelf implementation for GNU/Linux, but there are also other implementations including for BSD and proprietary UNIX-like systems as Solaris.
```

The "other implementation" mentioned links to the homepage for Homebrew's `libelf` package.

**Comment by sjackman** [comment]
It sounds like `libelf` is more portable, and `elfutils` is more functional on Linux. Which should Linuxbrew use? To be more compatible with Homebrew, we should use `libelf`, to be more compatible with Debian and other distros, we should use `elfutils`.

**Comment by dholm** [comment]
When I added `elfutils` it was because I was working on a formula for `perf`.  I checked a recent version of `perf` and it seems like it can also use `libelf`, however I don't know if it also affects functionality.  If you want to remove `elfutils` it's ok by me.

**Comment by rwhogg** [comment]
> If you want to remove elfutils it's ok by me.

That shouldn't be necessary. We'll probably just make `elfutils` keg-only if necessary rather than outright delete it. (Homebrew never deletes formulae either to the best of my knowledge; their usual response is to move a formula to the Homebrew/homebrew-boneyard repository.)

> It sounds like libelf is more portable, and elfutils is more functional on Linux. Which should Linuxbrew use?

**Comment by rwhogg** [comment]
> To be more compatible with Homebrew, we should use libelf, to be more compatible with Debian and other distros, we should use elfutils.

I would personally rather minimize unnecessary divergence from Homebrew. Every change we make is one that we have to account for.

**Comment by sjackman** [comment]
Agreed.
