### ISSUE TITLE
mkvtoolnix: Depends on libxslt

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#2338]
_From @paradox460 on April 10, 2017 6:9_

I've been trying to install `mkvtoolnix`, and it keeps failing, with what appears to be a docbook related compile step.

Here's the gist of the output:  
https://gist.github.com/anonymous/d074fe4340506a13cc5fd886221e0b43

I've verified that its not the formula by installing it on OS X and it works fine.

_Copied from original issue: Linuxbrew/brew#339_

**Comment by rwhogg** [comment]
https://gist.github.com/anonymous/d074fe4340506a13cc5fd886221e0b43#file-01-configure-L150-L151

```
checking for xsltproc... no
configure: error: xsltproc wasn't found
```

This appears to be a formula-specific issue with `mkvtoolnix`. Would you like to create a PR to Linuxbrew/homebrew-core to add

```
depends_on "libxslt" unless OS.mac?
```

**Comment by paradox460** [comment]
Thanks @rwhogg.

Interestingly enough, if I manually install libxslt (`brew install libxslt`), it still fails with the same error.

**Comment by rwhogg** [comment]
> Interestingly enough, if I manually install libxslt (brew install libxslt), it still fails with the same error.

That's by design. Superenv, now the default for users, requires that all dependencies be listed (or get included recursively) in a formula before they can be used.

**Comment by sjackman** [comment]
You can try…
```sh
brew install libxslt
brew install --env=std mkvtoolnix
```

**Comment by paradox460** [comment]
@sjackman thank you, that got it working.
