### ISSUE TITLE
pango won't compile

### ISSUE THREAD

**Issue by alexstaj** [Linuxbrew/homebrew-core#2341]
```
tha@bioinfo:~$ brew upgrade
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
==> Upgrading 2 outdated packages, with result:
cmake 3.7.2_1, pango 1.40.5
==> Upgrading cmake
==> Downloading https://linuxbrew.bintray.com/bottles/cmake-3.7.2_1.x86_64_linux
######################################################################## 100.0%
==> Pouring cmake-3.7.2_1.x86_64_linux.bottle.tar.gz
==> Caveats

Emacs Lisp files have been installed to:
/home/tha/.linuxbrew/share/emacs/site-lisp/cmake
==> Summary
:beer: /home/tha/.linuxbrew/Cellar/cmake/3.7.2_1: 2,142 files, 60.3MB
==> Upgrading pango
==> Installing dependencies for pango: berkeley-db@4
==> Installing pango dependency: berkeley-db@4
==> Downloading https://linuxbrew.bintray.com/bottles/berkeley-db@4-4.8.30.x86_6
######################################################################## 100.0%
==> Pouring berkeley-db@4-4.8.30.x86_64_linux.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /home/tha/.linuxbrew.

This is an alternate version of another formula.

If you need to have this software first in your PATH run:
echo 'export PATH="/home/tha/.linuxbrew/opt/berkeley-db@4/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
LDFLAGS: -L/home/tha/.linuxbrew/opt/berkeley-db@4/lib
CPPFLAGS: -I/home/tha/.linuxbrew/opt/berkeley-db@4/include

==> Summary
:beer: /home/tha/.linuxbrew/Cellar/berkeley-db@4/4.8.30: 4,596 files, 82.2MB
==> Installing pango
==> Downloading https://download.gnome.org/sources/pango/1.40/pango-1.40.5.tar.x
==> Downloading from https://muug.ca/mirror/gnome/sources/pango/1.40/pango-1.40.
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/home/tha/.linuxbrew/Cellar/pang
==> make
Last 15 lines from /home/tha/.cache/Homebrew/Logs/pango/02.make:
distutils.errors.CompileError: command 'gcc-5' failed with exit status 1
/home/tha/.linuxbrew/Cellar/gobject-introspection/1.52.0_1/share/gobject-introspection-1.0/Makefile.introspection:159: recipe for target 'Pango-1.0.gir' failed
make[4]: *** [Pango-1.0.gir] Error 1
make[4]: Leaving directory '/tmp/pango-20170410-14108-3wp634/pango-1.40.5/pango'
Makefile:1299: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/tmp/pango-20170410-14108-3wp634/pango-1.40.5/pango'
Makefile:1042: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/pango-20170410-14108-3wp634/pango-1.40.5/pango'
Makefile:580: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/pango-20170410-14108-3wp634/pango-1.40.5'
Makefile:469: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
```

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Try
```sh
brew install --env=std pango
```
I'll be curious to hear if that resolves the issue for you.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `pango`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by alexstaj** [comment]
brew upgrade --env=std pango worked.  thanks.  but what does --env=std do?


tha@bioinfo:~$ brew upgrade --env=std pango
==> Upgrading 1 outdated package, with result:
pango 1.40.5
==> Upgrading pango 
==> Downloading https://download.gnome.org/sources/pango/1.40/pango-1.40.5.tar.x
Already downloaded: /home/tha/.cache/Homebrew/pango-1.40.5.tar.xz
==> ./configure --disable-silent-rules --prefix=/home/tha/.linuxbrew/Cellar/pang
==> make
==> make install
🍺  /home/tha/.linuxbrew/Cellar/pango/1.40.5: 107 files, 5.1MB, built in 20 seconds
tha@bioinfo:~$ brew update
Already up-to-date.
tha@bioinfo:~$ brew upgrade
tha@bioinfo:~$ brew info pango
pango: stable 1.40.5, HEAD
Framework for layout and rendering of i18n text
http://www.pango.org/
/home/tha/.linuxbrew/Cellar/pango/1.40.3 (128 files, 5.3MB)
  Built from source on 2016-12-09 at 16:34:33
/home/tha/.linuxbrew/Cellar/pango/1.40.4 (107 files, 5MB)
  Built from source on 2017-03-03 at 17:39:42
/home/tha/.linuxbrew/Cellar/pango/1.40.5 (107 files, 5.1MB) *
  Built from source on 2017-04-12 at 18:57:43
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/pango.rb
==> Dependencies
Build: xz ✔, pkg-config ✔
Required: glib ✔, cairo ✔, harfbuzz ✔, fontconfig ✔, gobject-introspection ✔
==> Requirements
Required: x11 ✔

**Comment by sjackman** [comment]
See https://github.com/Linuxbrew/brew/issues/1#issuecomment-293142447
