### ISSUE TITLE
Not able to install GCC after fresh installation

### ISSUE THREAD

**Issue by andre-92** [Linuxbrew/homebrew-core#2350]
Hi all
I've just installed Linuxbrew with this script:

[https://raw.githubusercontent.com/Linuxbrew/install/master/install
](https://raw.githubusercontent.com/Linuxbrew/install/master/install
)

However, I'm not able to install gcc or any other package that needs gcc.
When trying to install gcc with `brew install gcc`
I got the following error message:

```==> Installing dependencies for gcc: glibc, xz, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: glibc
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc
```

This is the output of `brew doctor`:

```
~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: An outdated version (1.7.1) of Git was detected in your PATH.
Git 1.7.10 or newer is required to perform checkouts over HTTPS from GitHub.
Please upgrade:
  brew install git
```

But actually I can't install git inside Linuxbrew without gcc, and I can't update the system version of git since it's a server machine and I don't (and shouldn't) have root permissions.

**Comment by maxim-belkin** [comment]
Could you please try [standalone linuxbrew](https://gist.github.com/maxim-belkin/f9e4c4f98e2fc6de9f6673363919df42) and let us know if it works for you?

**Comment by sjackman** [comment]
Also see this wiki: https://github.com/Linuxbrew/brew/wiki/Symlink-GCC

**Comment by andre-92** [comment]
@maxim-belkin Already tried, it gives an error while downloading Ruby (not the explicit download in the script, apparentrly it tries to download it a second time internally)

@sjackman It seems to work now, but I had already tried to create the same symlink 'manually' and then setting the 'HOMEBREW_CC' environment variable with gcc-4.4 and for some reason it didn't work

**Comment by maxim-belkin** [comment]
@andre-92 I'm not sure what you mean. What error message do you get?

Don't set `HOMEBREW_CC`. Instead, to trick Linuxbrew into thinking that it has `gcc-4.4` create two symlinks: one  in Linuxbrew's bin folder:
```
gccversion="$(gcc -dumpversion | cut -d. -f1,2)"
ln -v -s $(which gcc) "$(brew --repo)"/bin/gcc-$gccversion
```
and another one in one of the `git`'s dependencies, _e.g._ `curl`:
```
ln -v -s $(which gcc) $(brew --prefix curl)/bin/gcc-$gccversion
```

**Comment by sjackman** [comment]
@andre-92 `brew install --env=std gcc` should get you a working Linuxbrew compiler.

**Comment by sjackman** [comment]
Closing this issue. Please comment if it's still a relevant issue for you, Andrea.

**Comment by andre-92** [comment]
Sorry for the late in the answer. I managed to install the packages, but I still have some gcc related problems.
Apparently, I was linking an external gcc in a wrong way. When I tried with:

`gccversion="$(gcc -dumpversion | cut -d. -f1,2)"
ln -v -s $(which gcc) "$(brew --repo)"/bin/gcc-$gccversion`

suggested by @maxim-belkin it worked.

However, every time I try to install a package, I still have to link/unlink different versions of gcc in order to make it work.

**Comment by maxim-belkin** [comment]
That's not right. You should install Linuxbrew's gcc, remove the symlinks created manually, and relink  gcc, if necessary. After that, you should not need to specify gcc version

**Comment by sjackman** [comment]
Linuxbrew also creates these symlinks now automatically. Linuxbrew uses the most recent `gcc` compiler that it knows about by default.

**Comment by andre-92** [comment]
@maxim-belkin  I installed Linuxbrew gcc (i.e. gcc 5.3.0), removed the symlinks that I created and unlink/relink gcc again. At this point, Linuxbrew was actually behaving as @sjackman said, using the most recent version available (its own). 
However, for some packages I had to relink other versions of gcc because the one from Linuxbrew was not working properly (compilation/linking errors), and this happened many times, almost 50% of the time.

@sjackman I know that you can override the default one with the `--cc` option, but what do you mean with 'it knows about'? Is it possible to tell Linuxbrew to look for binaries in some specific directory without manually creating symlinks?

Thank you both for your help!

**Comment by sjackman** [comment]
Linuxbrew "knows about" compilers that have appropriate symlinks in `$(brew --prefix)/bin`. It now creates symlinks for `/usr/bin/gcc` if they don't already exist. Once these symlinks are created, it should not be necessary to add/remove/change them. You can select which compiler you want to use using the `brew install --cc=gcc-X` option.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `glibc`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar
