### ISSUE TITLE
Problem installing gcc 

### ISSUE THREAD

**Issue by vkyt** [Linuxbrew/homebrew-core#2351]
# Please always follow these steps:
- [x] Confirmed this is a problem with Linuxbrew and not Homebrew. Problems that affect both Homebrew and Linuxbrew must be reported in the appropriate Homebrew repository https://github.com/Homebrew
- [x] Confirmed this is a problem with only one, specific formula and not Linuxbrew/brew? If it's a general Linuxbrew/brew problem please file this issue at https://github.com/Linuxbrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/vkyt/f801d2aa7380990328f318611914d9b3

Did a fresh install of linuxbrew and followed by brew install gcc. 

gcc seems to have been installed but the output shows:
`
Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!
`
env | grep LD_  is empty for me

**Comment by maxim-belkin** [comment]
can you try removing `glibc` and installing it again with `--env=std`?
```
brew remove --ignore-dependencies glibc
brew install --env=std glibc
```
and see if that helps?

**Comment by vkyt** [comment]
It worked!  Thanks so much.

**Comment by maxim-belkin** [comment]
Thanks, @vkyt! We'll fix that soonish :)

**Comment by sjackman** [comment]
I pushed a747c27aa5 which adds `env :std` to `glibc.rb`
