### ISSUE TITLE
cairo : cannot install on Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by retokromer** [Linuxbrew/homebrew-core#2366]
- [x] Confirmed this is a problem with Linuxbrew and not Homebrew.

It works fine on macOS.

- [x] Confirmed this is a problem with only one, specific formula and not Linuxbrew/brew?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/a1c70dabed0e9e9189728ed352c80e9f

**Comment by PR1YANKPAT3L** [comment]
I am having the same issue with Ubuntu 16.10 when installing cario

https://gist.github.com/anonymous/4087ed9209dc62795eb902fa763e6168

**Comment by sjackman** [comment]
Try…
```sh
brew install --env=std cairo
```

**Comment by retokromer** [comment]
Thank you!

I didn’t see https://github.com/Linuxbrew/homebrew-core/pull/2302 when opening this one, sorry for that!

**Comment by sjackman** [comment]
No worries, Reto. Maxim has merged #2302.
