### ISSUE TITLE
brew install wine failed!

### ISSUE THREAD

**Issue by gttiankai** [Linuxbrew/homebrew-core#2387]
brew gist-logs wine:

https://gist.github.com/anonymous/46d5cfe1cb5a5baaa972b81e52e5a1bc

**Comment by sjackman** [comment]
I'm attempting to reproduce this issue at PR https://github.com/Linuxbrew/homebrew-core/pull/2397

**Comment by sjackman** [comment]
```
making all in crypto...
make[1]: Entering directory `/tmp/wine--openssl-20170417-8434-jxldhi/openssl-1.0.2k/crypto'
/usr/bin/perl ../util/mkbuildinf.pl "cc -I. -I.. -I../include  -O" "dist" >buildinf.h
make[1]: *** No rule to make target `../include/openssl/bio.h', needed by `cryptlib.o'.  Stop.
make[1]: Leaving directory `/tmp/wine--openssl-20170417-8434-jxldhi/openssl-1.0.2k/crypto'
make: *** [build_crypto] Error 1
```
https://gist.github.com/anonymous/46d5cfe1cb5a5baaa972b81e52e5a1bc#file-01-make-L9

**Comment by sjackman** [comment]
Try…
```sh
HOMEBREW_MAKE_JOBS=1 brew install wine
```

**Comment by sjackman** [comment]
I've made some progress, but wine is not building yet. If you have the inclination to continue this work, a PR would be most welcome.
