### ISSUE TITLE
python3: build error

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/homebrew-core#239]
_From @seanjensengrey on May 10, 2016 15:58_

It reliably takes two invocations of 

```
brew install python3
```

to install python3. The first invocation only installs the dependencies. The second invocation actually installs `python3`

platform: Ubuntu 14.04 LTS installed via

```
echo "export HOMEBREW_MAKE_JOBS=4" >> ~/.profile

# linuxbrew
echo | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
echo 'PATH=~/.linuxbrew/bin:$PATH' >> ~/.profile

. $HOME/.profile

brew update
brew install python3
```

_Copied from original issue: Linuxbrew/brew#36_

**Comment by sjackman** [comment]
After the first invocation of `brew install python3`, please report the output of `brew gist-logs python3`

**Comment by seanjensengrey** [comment]
ug.

```
ubuntu@ip-10-1-10-53:~$ brew gist-logs python3
Error: No logs.
```

This is on a fresh ec2 instance with `14.04 LTS`

```
    4  cat inst-brew.sh 
    5  echo "export HOMEBREW_MAKE_JOBS=4" >> ~/.bashrc
    6  echo | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
    8  echo 'PATH=~/.linuxbrew/bin:$PATH' >> ~/.bashrc
    9  . $HOME/.bashrc
   10  brew update
   11  brew install python3
   12  brew gist-logs python3
```

You should be able to ssh into the instnace

```
ssh ubuntu@52.201.220.156
```

If you can't, drop your pub key into a comment.

**Comment by sjackman** [comment]
If there's no logs for `python3` then one of its dependencies must have failed to build. Please report the stdout output of the first failed invocation of `brew install python3` to determine which package is failing to install.

**Comment by sjackman** [comment]
I wasn't able to reproduce the issue by logging into the above machine. Running `brew install python3` succeeded.

**Comment by seanjensengrey** [comment]
Confirm no repro with ed51201cf1dc88f9bc9881b01641c2003b5374b6

It does repro if I move back to 5f8f6c9d273186c26753d016682540a91cf54b25

The `keg_relocate` commits fix the issue.

**Comment by sjackman** [comment]
Great. Glad to hear it! @DoomHammer
