### ISSUE TITLE
abi-compliance-checker: test fails

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#25]
The abi-compliance-checker test fails because it's trying to run `gcc-5.3`, but the executable that gets built is called just `gcc-5`.

See https://travis-ci.org/Linuxbrew/homebrew-core/builds/126359174#L1156 :
> ERROR: can't access 'gcc-5.3'

Spun off from #23.

**Comment by rwhogg** [comment]
I think it's best to fix this just by changing what regex it uses on Linux.

I was originally going to suggest that we make GCC install a symlink `gcc-5.3` on Linux that would just point to `gcc-5`, only to discover that by sheer coincidence [GCC 5.4 was released yesterday](https://gcc.gnu.org/ml/gcc-announce/2016/msg00001.html). With that in mind, it's too risky IMO to make GCC install such a symlink, because if it did we would then have to remove it on upgrade.

Agree @sjackman?

**Comment by sjackman** [comment]
Yes, I agree.
