### ISSUE TITLE
hugo failed to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by nazavode** [Linuxbrew/homebrew-core#2587]
# Please always follow these steps:
- [x] Confirmed this is a problem with Linuxbrew and not Homebrew.
- [x] Confirmed this is a problem with only one, specific formula and not Linuxbrew/brew?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

`brew gist-logs hugo` replied with: `Error: No logs.`

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew doctor` gives no errors/warnings. Attached [brewconfig.txt](https://github.com/Linuxbrew/homebrew-core/files/969790/brewconfig.txt)

To help us debug your issue please explain:
- What you were trying to do (and why)

Install `hugo` formula

- What happened (include command output)

```
$ brew install hugo                           
==> Downloading https://github.com/spf13/hugo/archive/v0.20.6.tar.gz
==> Downloading from https://codeload.github.com/spf13/hugo/tar.gz/v0.20.6
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 857655b69fb3e7f174011fd6774501194f1241bbb833256fd63b585b6d7a3cc0
Actual: 692e08b009430d27064821d498f1454152cbfd5f26d019c29002e6fbff8fc387
Archive: /home/montag/.cache/Homebrew/hugo-0.20.6.tar.gz
To retry an incomplete download, remove the file above.
```

- What you expected to happen

...ehm, install the formula?

- Step-by-step reproduction instructions (by running `brew install` commands)

Reported above.

**Please note we may immediately close your issue without comment if you do not fill out the issue template and provide ALL the requested information.**

**Comment by maxim-belkin** [comment]
Thanks for the report! This is indeed a bug. It was introduced upstream. Please report it to [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/issues/new) and mention commit Homebrew/homebrew-core@6717334820b755a851e86f24c24e95f4e2125b99 Steps to reproduce on a mac: `brew fetch -s hugo`

P.S. 
> - [x] Confirmed this is a problem with Linuxbrew and not Homebrew.

🤧

**Comment by nazavode** [comment]
I ran `brew update && brew upgrade` (while having `hugo` installed and outdated) on a Mac without issues, that's why I checked the "Confirmed..." item.
