### ISSUE TITLE
ruby: libruby.so.2.4.1: final close failed: Invalid operation

### ISSUE THREAD

**Issue by Treri** [Linuxbrew/homebrew-core#2620]
# Please always follow these steps:
- [x] Confirmed this is a problem with Linuxbrew and not Homebrew. Problems that affect both Homebrew and Linuxbrew must be reported in the appropriate Homebrew repository https://github.com/Homebrew
- [x] Confirmed this is a problem with only one, specific formula and not Linuxbrew/brew? If it's a general Linuxbrew/brew problem please file this issue at https://github.com/Linuxbrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
    https://gist.github.com/anonymous/fc8003d6660840acab390d8876a703ac
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
    install ruby on my linux
- What happened (include command output)
    make error
- What you expected to happen
    ruby installed successfully
- Step-by-step reproduction instructions (by running `brew install` commands)

```sh
$ brew install ruby
Updating Homebrew...
==> Downloading https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.bz2
Already downloaded: /home/treri/.cache/Homebrew/ruby-2.4.1.tar.bz2
==> ./configure --prefix=/home/treri/.linuxbrew/Cellar/ruby/2.4.1_1 --enable-shared --disable-silent-rules --with-sitedir=/home/treri/.linuxbrew/lib/ruby/site_ruby --with-vendord
==> make
Last 15 lines from /home/treri/.cache/Homebrew/Logs/ruby/02.make:
verconf.h updated
compiling loadpath.c
making srcs under enc
make[1]: Entering directory '/tmp/ruby-20170505-12991-1rddmfr/ruby-2.4.1'
make[1]: Nothing to be done for 'srcs'.
make[1]: Leaving directory '/tmp/ruby-20170505-12991-1rddmfr/ruby-2.4.1'
generating transdb.h
linking static-library libruby-static.a
transdb.h updated
verifying static-library libruby-static.a
linking shared-library libruby.so.2.4.1
libruby.so.2.4.1: final close failed: Invalid operation
collect2: error: ld returned 1 exit status
Makefile:245: recipe for target 'libruby.so.2.4.1' failed
make: *** [libruby.so.2.4.1] Error 1

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

These open issues may also help:
MacVim: Link mvim with brewed ruby & perl https://github.com/Homebrew/homebrew-core/pull/10951
```
<img width="1414" alt="dx-20170505 2x" src="https://cloud.githubusercontent.com/assets/2631733/25734810/3700e944-3199-11e7-8edd-9b35728a84b5.png">

**Comment by sjackman** [comment]
```
verifying static-library libruby-static.a
linking shared-library libruby.so.2.4.1
libruby.so.2.4.1: final close failed: Invalid operation
collect2: error: ld returned 1 exit status
Makefile:245: recipe for target 'libruby.so.2.4.1' failed
make: *** [libruby.so.2.4.1] Error 1
```
https://gist.github.com/anonymous/fc8003d6660840acab390d8876a703ac#file-02-make-L116

Please report
```sh
which -a ld
ld --version
brew list --versions binutils
```

Try…
```sh
brew install binutils
brew install node
```

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `ruby`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by Treri** [comment]
![image](https://cloud.githubusercontent.com/assets/2631733/25832192/b9f28cfe-349b-11e7-81a3-8c3a6759f194.png)

**Comment by sjackman** [comment]
Copy and pasting is preferred to screenshots, so that the text is searchable.
Try `brew install binutils node`
Or preferably install Linuxbrew in `/home/linuxbrew/.linuxbrew`
```sh
mkdir /home/linuxbrew

**Comment by Treri** [comment]
I reinstalled linuxbrew to /home/linuxbrew/.linuxbrew, all works well.

Thanks very much

**Comment by sjackman** [comment]
Fantastic. We hope to make `/home/linuxbrew/.linuxbrew` the default installation in the future.

**Comment by maxim-belkin** [comment]
I don't think it will be possible on all platforms :)

**Comment by sjackman** [comment]
Whenever the user has write permissions to `/home/linuxbrew/.linuxbrew`. We'll continue to support `~/.linuxbrew` for those who don't.
