### ISSUE TITLE
crystal-lang failed to build on openSUSE Tumbleweed 20170505

### ISSUE THREAD

**Issue by develop7** [Linuxbrew/homebrew-core#2624]
# Please always follow these steps:
- [x] Confirmed this is a problem with Linuxbrew and not Homebrew. Problems that affect both Homebrew and Linuxbrew must be reported in the appropriate Homebrew repository https://github.com/Homebrew
- [x] Confirmed this is a problem with only one, specific formula and not Linuxbrew/brew? If it's a general Linuxbrew/brew problem please file this issue at https://github.com/Linuxbrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): install Crystal language compiler
- What happened (include command output): it failed, [console output](https://gist.github.com/anonymous/311c05660cdf50b8d1223bc952eebefa#gistcomment-2088740)
- What you expected to happen: it should succeed
- Step-by-step reproduction instructions (by running `brew install` commands): `brew install crystal-lang`

[`brew gist-logs crystal-lang`](https://gist.github.com/anonymous/311c05660cdf50b8d1223bc952eebefa)

**Comment by sjackman** [comment]
Attempting to reproduce this issue over at https://github.com/Linuxbrew/homebrew-core/pull/2626

**Comment by sjackman** [comment]
```
Using compiled compiler at .build/crystal
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: cannot find -lgc
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `gcc-6 -o "/tmp/crystal-lang-20170509-29149-1x56ump/crystal-0.22.0/.build/shards" "${@}"  -rdynamic  -lyaml -lpcre -lm -lgc -lpthread /tmp/crystal-lang-20170509-29149-1x56ump/crystal-0.22.0/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```
https://gist.github.com/anonymous/311c05660cdf50b8d1223bc952eebefa#file-02-crystal-L10-L13

**Comment by sjackman** [comment]
Those errors don't look specific to Linuxbrew. Can you reproduce this issue when compiling `crystal-lang` outside of Linuxbrew?

**Comment by sjackman** [comment]
Building `crystal-lang` on CI unfortunately timed out after 10m0s without outputting anything. See PR #2626.
