### ISSUE TITLE
vim: configure: error: cannot compute sizeof (off_t)

### ISSUE THREAD

**Issue by bkbncn** [Linuxbrew/homebrew-core#2630]
When I upgrade vim, it failed, error message is

```
checking size of off_t... configure: error: in `/tmp/vim-20170510-58906-1ftwlfu/vim-8.0.0596/src':
configure: error: cannot compute sizeof (off_t)
See `config.log' for more details
```

And I don't know where is confil.log. I try to install `--keep-tmp`, but I still can't find config.log.

**Comment by sjackman** [comment]
The `config.log` should be in `/tmp/vim-20170510-58906-1ftwlfu/vim-8.0.0596/src`
Please report `brew gist-logs vim`

**Comment by bkbncn** [comment]
config.log is not there, I can't find it. and gist-logs is following
http://gist.github.com/anonymous/00d84b184c23511d36be8726f6e75b16

**Comment by sjackman** [comment]
The `config.log` isn't in the gist either. Try
```sh
brew install --keep-tmp vim
find /tmp/vim-*/vim-8.0.0596 -name config.log
```
Can you reproduce this error compiling `vim` outside of Linuxbrew?

**Comment by sjackman** [comment]
```
configure:13313: checking size of off_t
configure:13318: gcc-5 -o conftest -g -O2  -L. -Wl,-search_paths_first -rdynamic -Wl,-export-dynamic -L/home/linuxbrew/.linuxbrew/opt/portable-readline/lib  -Wl,-R/home/linuxbrew/.linuxbrew/opt/portable-readline/lib -L/home/linuxbrew/.linuxbrew/opt/portable-libyaml/lib  -Wl,-R/home/linuxbrew/.linuxbrew/opt/portable-libyaml/lib -L/home/linuxbrew/.linuxbrew/opt/portable-openssl/lib  -Wl,-R/home/linuxbrew/.linuxbrew/opt/portable-openssl/lib -L/home/linuxbrew/.linuxbrew/opt/portable-ncurses/lib  -Wl,-R/home/linuxbrew/.linuxbrew/opt/portable-ncurses/lib  -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib conftest.c -lm -lnsl   -lncurses >&5
/home/eng/x/xxx110230/.linuxbrew/bin/ld: warning: cannot find entry symbol arch_paths_first; defaulting to 0000000000400820
configure:13318: $? = 0
configure:13318: ./conftest
auto/configure: line 1779: 20333 Segmentation fault      (core dumped) ./conftest$ac_exeext
```
https://gist.github.com/bkbncn/55b2a2b496f2d5f5eb74827614d74d60#file-config-log-L6858-L6863

**Comment by sjackman** [comment]
I'm not sure that it'll help, but try
```sh
brew install --env=std vim
```
or
```sh
brew install --cc=gcc-4.4 vim
```

I'm afraid that I don't have the time available to troubleshoot this issue. If you already have `vim` installed, I suggest you use `brew pin vim` to continue using that version of `vim`. I'll create a precompiled binary bottle for `vim` once PR #2628 is merged.
