### ISSUE TITLE
flex: ar: error while loading shared libraries: libfl.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by RazerM** [Linuxbrew/homebrew-core#2658]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew gist-logs`:
https://gist.github.com/anonymous/dd6430f1d27c116d8c49ebba89a1721a

Upgrading flex from 2.6.3 to 2.6.4 fails as shown in the logs above. I used `brew upgrade`, flex is the only outdated package.

**Comment by sjackman** [comment]
```
gcc-4.9 -DHAVE_CONFIG_H -I.  -DLOCALEDIR=\"/home/fmclean/.linuxbrew/Cellar/flex/2.6.4/share/locale\"   -g -O2 -c -o stage1flex-yylex.o `test -f 'yylex.c' || echo './'`yylex.c
/bin/bash ../libtool  --tag=CC   --mode=link gcc-4.9  -g -O2 -version-info 2:0:0  -o libfl.la -rpath /home/fmclean/.linuxbrew/Cellar/flex/2.6.4/lib libmain.lo libyywrap.lo  -lm 
libtool: link: gcc-4.9 -shared  -fPIC -DPIC  .libs/libmain.o .libs/libyywrap.o   -lm  -g -O2   -Wl,-soname -Wl,libfl.so.2 -o .libs/libfl.so.2.0.0
libtool: link: (cd ".libs" && rm -f "libfl.so.2" && ln -s "libfl.so.2.0.0" "libfl.so.2")
libtool: link: (cd ".libs" && rm -f "libfl.so" && ln -s "libfl.so.2.0.0" "libfl.so")
libtool: link: ar cru .libs/libfl.a  libmain.o libyywrap.o
ar: error while loading shared libraries: libfl.so.2: cannot open shared object file: No such file or directory
Makefile:631: recipe for target 'libfl.la' failed
make[1]: *** [libfl.la] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/flex-20170516-22910-3t343w/flex-2.6.4/src'
```
https://gist.github.com/anonymous/dd6430f1d27c116d8c49ebba89a1721a#file-02-make-L60

**Comment by sjackman** [comment]
I haven't seen that error before. Try
```sh
HOMEBREW_MAKE_JOBS=1 brew upgrade flex
```
or try this patch
```diff
diff --git a/Formula/flex.rb b/Formula/flex.rb
index 04fb17e9ec..a01f8e6a0e 100644
--- a/Formula/flex.rb
+++ b/Formula/flex.rb
@@ -25,6 +25,8 @@ class Flex < Formula
                           "--disable-silent-rules",
                           "--enable-shared",
                           "--prefix=#{prefix}"
+    system "make"
+    ENV.deparallelize
     system "make", "install"
     bin.install_symlink "flex" => "lex" unless OS.mac?
   end
```

**Comment by RazerM** [comment]
I get the same error with `HOMEBREW_MAKE_JOBS=1`

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `flex`.
Another possible workaround for you is `brew install --force-bottle flex`, but no promises.

```sh
sudo mkdir /home/linuxbrew
sudo chown $USER: /home/linuxbrew
git clone https://github.com/Linuxbrew/brew /home/linuxbrew/.linuxbrew
PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
brew install pkg-config
```

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by wangpeiwen** [comment]
i have same problem when upgrade flex from 2.6.3 to 2.6.4
the key reason is brewed `ar` depend libfl.so.2 and read it from $HOME/.linuxbrew/lib
but when we upgrade flex, brewed flex was unlinked temporarily
```
ldd ~/.linuxbrew/bin/ar       
        linux-gate.so.1 =>  (0xbfffe000)
        /lib/libonion.so (0xb7faa000)
        libfl.so.2 => /data/home/okhowang/.linuxbrew/lib/libfl.so.2 (0xb7fa8000)
        libdl.so.2 => /lib/libdl.so.2 (0xb7f99000)
        libc.so.6 => /lib/libc.so.6 (0xb7e58000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xb7e41000)
        libm.so.6 => /lib/libm.so.6 (0xb7e19000)
        /data/home/okhowang/.linuxbrew/lib/ld.so (0xb7fbb000)
```
```
readelf -d ~/.linuxbrew/bin/ar                                                                                                                                                                       

Dynamic section at offset 0x597014 contains 24 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libfl.so.2]
 0x00000001 (NEEDED)                     Shared library: [libdl.so.2]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x0000000f (RPATH)                      Library rpath: [/data/home/okhowang/.linuxbrew/lib:/data/home/okhowang/.linuxbrew/opt/zlib/lib]
 0x0000001d (RUNPATH)                    Library runpath: [/data/home/okhowang/.linuxbrew/lib:/data/home/okhowang/.linuxbrew/opt/zlib/lib]
 0x0000000c (INIT)                       0x8049830
 0x0000000d (FINI)                       0x84b935c
 0x00000004 (HASH)                       0x80481b8
 0x00000005 (STRTAB)                     0x8048e30
 0x00000006 (SYMTAB)                     0x80485e0
 0x0000000a (STRSZ)                      1171 (bytes)
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000015 (DEBUG)                      0x0
 0x00000003 (PLTGOT)                     0x85df104
 0x00000002 (PLTRELSZ)                   920 (bytes)
 0x00000014 (PLTREL)                     REL
 0x00000017 (JMPREL)                     0x8049498
 0x00000011 (REL)                        0x8049460
 0x00000012 (RELSZ)                      56 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffe (VERNEED)                    0x80493d0
 0x6fffffff (VERNEEDNUM)                 2
 0x6ffffff0 (VERSYM)                     0x80492c4
 0x00000000 (NULL)                       0x0
```

**Comment by wangpeiwen** [comment]
can we build binutils without flex?

**Comment by sjackman** [comment]
Well that's super curious. I'm guessing that you both have built `binutils` from source, as the bottled `binutils` `ar` depends on `libc.so.6 libdl.so.2 libz.so.1` but not `libfl.so.2`

```sh
$ patchelf --print-needed ~/.linuxbrew/bin/ar
libz.so.1
libdl.so.2
libc.so.6
```

I'd recommend using the bottled `binutils`
```sh
brew reinstall binutils
```

Alternatives would be
+ to link statically against `libfl.so.2` rather than dynamically. I'd consider accepting this PR.
+ add a `depends_on "flex" => :run` dependency to `binutils`. I won't merge this PR, but it would resolve your issue (after rebuilding and reinstalling binutils).

**Comment by sjackman** [comment]
Thanks for your bug report Frazer and help trouble shooting, @wangpeiwen!
