### ISSUE TITLE
brew install john-jumbo SHA error

### ISSUE THREAD

**Issue by mpeele1** [Linuxbrew/homebrew-core#2684]
brew update - check twice
brew doctor - check twice 
brew upgrade - check
brew install hello - check
Note:  Debian system running current Debian Jessie with updates. 

`brew list`
> archey	gmp  gpatch  hello  john  openssl  patchelf  pkg-config  xz  zlib

# Start problem...  
`brew install john-jumbo `
  1st run it told me to unlink john, so I did that.  
`brew doctor `
   tells me that the only issue is that john is unlinked. 

`brew install john-jumbo `
It runs and installs all sorts of stuff, then 
```
==> Downloading https://github.com/magnumripper/JohnTheRipper/commit/d29ad8aabaa9726eb08f440001c37611fa072e0c.diff
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: de5c09397f3666d0592e0f418f26a78a6624c5a947347ec2440e141c8915ae82
Actual: 29660e4fb33e01730b5650094b872b416b36565501acfca2eb94ee2217525e0c
Archive: /home/user/.cache/Homebrew/john-jumbo--patch-de5c09397f3666d0592e0f418f26a78a6624c5a947347ec2440e141c8915ae82.diff
To retry an incomplete download, remove the file above.
user@pve2:~/.cache/Homebrew$ brew gist-logs john-jumbo
Error: No logs.
```
I removed the .diff file, and tried again.  Same error.  And, again.  And again after brew update, upgrade, doctor.  
MacOS john-jumbo installed fine (though I installed it a while back). 

**brew config:**
```brew config
HOMEBREW_VERSION: 1.1.13
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 1d16368a177807663e1b3146d71fcd69e2061e27
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 501c656e81770ff64f12131a20535795e9229e44
Core tap last commit: 30 hours ago
HOMEBREW_PREFIX: /home/user/.linuxbrew
HOMEBREW_REPOSITORY: /home/user/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/user/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.1.5 => /usr/bin/ruby2.1
Clang: N/A
Git: 2.1.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.1
Java: N/A
Kernel: Linux 4.4.59-1-pve x86_64 GNU/Linux
OS: N/A
Host glibc: 2.19
/usr/bin/gcc: 4.9.2
glibc: N/A
gcc: N/A
xorg: N/A
```

# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
_Check - "brew install john"  "brew install hello" work fine._
- [ ] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
_Check - Mac version installed_
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [_no gist log_] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
_check, stated above_

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
_Install john-jumbo (because I want to use john-jumbo)_
- What happened (include command output)
_shown above_
- What you expected to happen
_I expected john-jumbo to be installed_
- Step-by-step reproduction instructions (by running `brew install` commands)
_shown above_

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get a new formula that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get a new formula that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare

**Comment by sjackman** [comment]
Homebrew/core is merged regularly into Linuxbrew/core. This issue is fixed upstream should be resolved by the next merge.
