### ISSUE TITLE
binutils: tar: binutils/2.28/bin/ar: Cannot hard link

### ISSUE THREAD

**Issue by seisdrum** [Linuxbrew/homebrew-core#2685]
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/5e01cd8148c92adeaf08a85bf3b858fb
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I was trying to upgrade binutils. Installation of the bottle fails with the following message:

```
> brew upgrade binutils
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
binutils 2.28
==> Upgrading binutils 
==> Downloading https://linuxbrew.bintray.com/bottles/binutils-2.28.x86_64_linux.bottle.tar.gz
Already downloaded: /home/chug/.cache/Homebrew/binutils-2.28.x86_64_linux.bottle.tar.gz
==> Pouring binutils-2.28.x86_64_linux.bottle.tar.gz
tar: binutils/2.28/bin/ar: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/ar': Operation not permitted
tar: binutils/2.28/bin/ld: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/ld': Operation not permitted
tar: binutils/2.28/bin/strip: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/strip': Operation not permitted
tar: binutils/2.28/bin/dlltool: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/dlltool': Operation not permitted
tar: binutils/2.28/bin/ranlib: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/ranlib': Operation not permitted
tar: binutils/2.28/bin/objcopy: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/objcopy': Operation not permitted
tar: binutils/2.28/bin/ld.gold: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/ld.gold': Operation not permitted
tar: binutils/2.28/bin/ld.bfd: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/ld': Operation not permitted
tar: binutils/2.28/bin/as: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/as': Operation not permitted
tar: binutils/2.28/bin/objdump: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/objdump': Operation not permitted
tar: binutils/2.28/bin/readelf: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/readelf': Operation not permitted
tar: binutils/2.28/bin/nm: Cannot hard link to `binutils/2.28/x86_64-pc-linux-gnu/bin/nm': Operation not permitted
tar: Exiting with failure status due to previous errors
Error: Failure while executing: tar xzf /home/chug/.cache/Homebrew/binutils-2.28.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

The installation from source also fails, link to the brew gist-logs output: https://gist.github.com/5e01cd8148c92adeaf08a85bf3b858fb

It appears that this is an issue with /usr/bin/ld not supporting the -plugin flag. It is super old:

```
> /usr/bin/ld --version
GNU ld version 2.20.51.0.2-5.46.el6 20100205
Copyright 2009 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

Any ideas how I could fix this?

**Comment by sjackman** [comment]
It looks as though the file system on which you have Linuxbrew installed does not support hard links, for example `touch foo; ln foo bar`. A few packages such as binutils and gcc require hard links. You may want to open a ticket with your system administrator.

**Comment by Sinan81** [comment]
I'am having the exact same problem? Should I reopen the ticket? In my case 'touch foo ; ln foo bar' works hence problem is something else than a 'no-hard links allowed situation'

**Comment by sjackman** [comment]
Are you able to create hard link in the `Cellar` directory? Try…
```sh
cd $(brew --cellar)
touch foo
ln foo bar
rm foo bar
```

**Comment by sjackman** [comment]
Also try…
```sh
cd $(brew --cellar)
mkdir tmp
cd tmp
tar xf $(brew --cache binutils)
rm -rf cd $(brew --cellar)/tmp
```

**Comment by seisdrum** [comment]
In my case the problem was indeed the file system (https://en.wikipedia.org/wiki/BeeGFS), which supports hard-linking within the same directory but not between different directories.

Installation from source eventually worked though.

**Comment by sjackman** [comment]
Good to know. Thanks for the follow up, @seisdrum.
@Sinan81 Please report…
```
cd $(brew --cellar)
touch foo
mkdir tmp
ln foo tmp/bar
rm -r foo tmp
```

**Comment by Sinan81** [comment]
under Cellar folder I am getting 'Operation not permitted' error.

**Comment by Sinan81** [comment]
In my case, installation from the source is not working either it seems

**Comment by sjackman** [comment]
@Sinan81 It looks as though the file system on which you have Linuxbrew installed does not support hard links. A few packages, such as `binutils` and `gcc`, require hard links. You may want to open a ticket with your system administrator.
