### ISSUE TITLE
Can't install ncdu with Homebrew on a fresh machine

### ISSUE THREAD

**Issue by revolter** [Linuxbrew/homebrew-core#2744]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to install `ncdu` using linuxbrew.

- What happened (include command output)

It crashed with the error `configure: error: required header file not found`.

- What you expected to happen

Install required dependencies then complete the `ncdu` installation successfully.

- Step-by-step reproduction instructions (by running `brew install` commands)

Run `brew install ncdu` on a fresh machine.

I noticed that if I install `neovim` beforehand, `ncdu` installs correctly, so I thought that the spec doesn't list its required dependencies. A related issue can be found [here](https://dev.yorhel.nl/ncdu/bug/97).

Moved from https://github.com/Homebrew/homebrew-core/issues/13880.

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get a new formula that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get a new formula that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare

**Comment by sjackman** [comment]
This issue will be resolved by PR #2752 once it's merged.
