### ISSUE TITLE
Can't install mpg123. Problems during make install.

### ISSUE THREAD

**Issue by JuPlutonic** [Linuxbrew/homebrew-core#2766]
```
src/libout123/modules/coreaudio.c:14:39: fatal error: CoreServices/CoreServices.h: File o directory doesn't exist
Makefile:3245: set of instruction for "src/libout123/modules/src_libout123_modules_libdefaultmodule_la-coreaudio.lo" successful
make: *** [src/libout123/modules/src_libout123_modules_libdefaultmodule_la-coreaudio.lo] Error 1
```

So,
1. Can't install mpg123 'cause in process were errors around MacOSX's CoreAudio
2. Found brew audit --strict --online mpg123 problems 
2. SNAFU! no Bottle found for mpg123 on bintray

- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ no ] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` x2
- [X] Ran `brew doctor`, fixed nearly all problems
- [X] Ran `brew gist-logs <formula>([V] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor`)
[https://gist.github.com/anonymous/ee9b1078601cfe21beb640e5c79423f1](url)
- [X] Ran brew audit --strict --online mpg123
_The URL https://www.mpg123.de/ is not reachable
Stable: The URL https://www.mpg123.de/download/mpg123-1.23.8.tar.bz2 is not reachable
Error: 2 problems in 1 formula_

**Comment by sjackman** [comment]
Would you be interested in submitting a pull request to fix `mpg123`? Try…
```diff
diff --git a/Formula/mpg123.rb b/Formula/mpg123.rb
index 9b943ee666..f7d9a7a8c5 100644
--- a/Formula/mpg123.rb
+++ b/Formula/mpg123.rb
@@ -17,9 +17,9 @@ class Mpg123 < Formula
       --disable-debug
       --disable-dependency-tracking
       --prefix=#{prefix}
-      --with-default-audio=coreaudio
       --with-module-suffix=.so
     ]
+    args << "--with-default-audio=coreaudio" if OS.mac?
 
     if MacOS.prefer_64_bit?
       args << "--with-cpu=x86-64"
```

**Comment by JuPlutonic** [comment]
Thanx! Will edit formula!

**Comment by JuPlutonic** [comment]
Thanks I would like to... see the Ruby logic
