### ISSUE TITLE
ncurses-6.0-20160910-patch.sh: line 16: patch: command not found

### ISSUE THREAD

**Issue by Sinan81** [Linuxbrew/homebrew-core#2915]
Hi all,

it seems there is a problem with the ncurses patch formula. I am wondering if anyone could suggest a way to solve this. 

I get the error indicated in the title by doing 'brew install ncurses'

The gist log is:
https://gist.github.com/anonymous/02f11706499017c592ad3bb432308c3f
OS: aws linux version 2017.03 using the vagrant box: https://atlas.hashicorp.com/mvbcoding/boxes/awslinux

Thanks,
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [NA] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
   https://gist.github.com/anonymous/02f11706499017c592ad3bb432308c3f
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get a new formula that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get a new formula that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare

**Comment by Sinan81** [comment]
Update: At first glance it seems this is a missing dependency problem so following the result of 'brew search patch' I installed the package gpatch via 'brew install gpatch' but the above error is still persisting!

**Comment by Sinan81** [comment]
Update: I installed the 'patch' command provided by the system by doing 'sudo yum install patch' and now I confirm that 'ncurses' installation 'brew install ncurses' proceeds without errors.

**Comment by palday** [comment]
This is a duplicate (but contains additional valuable information) of/for #2842

**Comment by Sinan81** [comment]
Ok. Thanks. For some reason I wasn't able to find the above mentioned related ticket before issuing my own.

**Comment by sjackman** [comment]
Please open a PR that adds to `ncurses`
```ruby
  depends_on "gpatch" => :build
```
