### ISSUE TITLE
cairo fails to link (against zlib, a dependency of libpng)

### ISSUE THREAD

**Issue by epipping** [Linuxbrew/homebrew-core#2917]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I tried to install cairo yet it failed to link:
```
% brew install cairo --keep-tmp
==> Downloading https://cairographics.org/releases/cairo-1.14.8.tar.xz
Already downloaded: /home/mi/pipping/.cache/Homebrew/cairo-1.14.8.tar.xz
==> ./configure --prefix=/home/mi/pipping/.linuxbrew/Cellar/cairo/1.14.8 [..] # line cut off
==> make install
Last 15 lines from /home/mi/pipping/.cache/Homebrew/Logs/cairo/02.make:
collect2: error: ld returned 1 exit status
Makefile:590: recipe for target 'cairo-sphinx' failed
make[4]: *** [cairo-sphinx] Error 1
make[4]: Leaving directory '/tmp/cairo-20170612-12129-9nrmb2/cairo-1.14.8/util/cairo-sphinx'
Makefile:975: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/tmp/cairo-20170612-12129-9nrmb2/cairo-1.14.8/util'
Makefile:1287: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/tmp/cairo-20170612-12129-9nrmb2/cairo-1.14.8/util'
Makefile:897: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/tmp/cairo-20170612-12129-9nrmb2/cairo-1.14.8'
Makefile:1351: recipe for target 'install' failed
make: *** [install] Error 2
==> Kept temporary files
Temporary files retained at /tmp/cairo-20170612-12129-9nrmb2
```

Full log: https://gist.github.com/4d3bf96d411ab7f25db13addca59227f

The issue:
```
  CCLD     cairo-sphinx
/home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29/lib/libpng16.so: undefined reference to `inflateValidate@ZLIB_1.2.9'
collect2: error: ld returned 1 exit status
```

Preliminary diagnosis: This is how gcc-5 tried to link:
```
% cd /tmp/cairo-20170612-12129-9nrmb2/cairo-1.14.8/util/cairo-sphinx
% make V=1
/bin/bash ../../libtool  --tag=CC   --mode=link gcc-5 -D_REENTRANT      -I/home/mi/pipping/.linuxbrew/Cellar/pixman/0.34.0/include/pixman-1    -I/home/mi/pipping/.linuxbrew/opt/freetype/include/freetype2 -I/home/mi/pipping/.linuxbrew/Cellar/expat/2.2.0/include -I/home/mi/pipping/.linuxbrew/Cellar/fontconfig/2.12.3/include -I/home/mi/pipping/.linuxbrew/Cellar/expat/2.2.0/include -I/home/mi/pipping/.linuxbrew/opt/freetype/include/freetype2 -I/home/mi/pipping/.linuxbrew/opt/freetype/include/freetype2  -I/home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29/include/libpng16 -I/usr/include/valgrind   -Wall -Wextra -Wmissing-declarations -Werror-implicit-function-declaration -Wpointer-arith -Wwrite-strings -Wsign-compare -Wpacked -Wswitch-enum -Wmissing-format-attribute -Wvolatile-register-var -Wstrict-aliasing=2 -Winit-self -Wunsafe-loop-optimizations -Wno-missing-field-initializers -Wno-unused-parameter -Wno-attributes -Wno-long-long -Winline -fno-strict-aliasing -fno-common -Wp,-D_FORTIFY_SOURCE=2 -Wno-unused-but-set-variable                   -D_REENTRANT  -I/home/mi/pipping/.linuxbrew/Cellar/pcre/8.40/include -I/home/mi/pipping/.linuxbrew/Cellar/glib/2.52.2/include/glib-2.0 -I/home/mi/pipping/.linuxbrew/Cellar/glib/2.52.2/lib/glib-2.0/include -g -O2   -o cairo-sphinx cairo_sphinx-sphinx.o -lpthread ../../util/cairo-script/libcairo-script-interpreter.la ../../boilerplate/libcairoboilerplate.la ../../src/libcairo.la -L/home/mi/pipping/.linuxbrew/Cellar/glib/2.52.2/lib -lglib-2.0  -lrt -lrt  -lm
libtool: link: gcc-5 -D_REENTRANT -I/home/mi/pipping/.linuxbrew/Cellar/pixman/0.34.0/include/pixman-1 -I/home/mi/pipping/.linuxbrew/opt/freetype/include/freetype2 -I/home/mi/pipping/.linuxbrew/Cellar/expat/2.2.0/include -I/home/mi/pipping/.linuxbrew/Cellar/fontconfig/2.12.3/include -I/home/mi/pipping/.linuxbrew/Cellar/expat/2.2.0/include -I/home/mi/pipping/.linuxbrew/opt/freetype/include/freetype2 -I/home/mi/pipping/.linuxbrew/opt/freetype/include/freetype2 -I/home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29/include/libpng16 -I/usr/include/valgrind -Wall -Wextra -Wmissing-declarations -Werror-implicit-function-declaration -Wpointer-arith -Wwrite-strings -Wsign-compare -Wpacked -Wswitch-enum -Wmissing-format-attribute -Wvolatile-register-var -Wstrict-aliasing=2 -Winit-self -Wunsafe-loop-optimizations -Wno-missing-field-initializers -Wno-unused-parameter -Wno-attributes -Wno-long-long -Winline -fno-strict-aliasing -fno-common -Wp,-D_FORTIFY_SOURCE=2 -Wno-unused-but-set-variable -D_REENTRANT -I/home/mi/pipping/.linuxbrew/Cellar/pcre/8.40/include -I/home/mi/pipping/.linuxbrew/Cellar/glib/2.52.2/include/glib-2.0 -I/home/mi/pipping/.linuxbrew/Cellar/glib/2.52.2/lib/glib-2.0/include -g -O2 -o .libs/cairo-sphinx cairo_sphinx-sphinx.o  ../../util/cairo-script/.libs/libcairo-script-interpreter.so ../../boilerplate/.libs/libcairoboilerplate.a /tmp/cairo-20170612-12129-9nrmb2/cairo-1.14.8/src/.libs/libcairo.so -L/home/mi/pipping/.linuxbrew/Cellar/pixman/0.34.0/lib -L/home/mi/pipping/.linuxbrew/opt/freetype/lib -L/home/mi/pipping/.linuxbrew/Cellar/fontconfig/2.12.3/lib -L/home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29/lib -lpthread -lpixman-1 -lfontconfig -lfreetype -lpng16 -lz -ldl ../../src/.libs/libcairo.so -L/home/mi/pipping/.linuxbrew/Cellar/glib/2.52.2/lib -lglib-2.0 -lrt -lm -Wl,-rpath -Wl,/home/mi/pipping/.linuxbrew/Cellar/cairo/1.14.8/lib
/home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29/lib/libpng16.so: undefined reference to `inflateValidate@ZLIB_1.2.9'
collect2: error: ld returned 1 exit status
Makefile:590: recipe for target 'cairo-sphinx' failed
make: *** [cairo-sphinx] Error 1
% 
```

The issue is with libpng16: We know from the config.log lines
```
configure:26754: $PKG_CONFIG --exists --print-errors "$png_REQUIRES"
configure:26757: $? = 0
```
(where `png_REQUIRES=libpng`) that pkg-config is used to check for libpng. The pkg-config file
```
% cat /home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29/lib/pkgconfig/libpng16.pc 
prefix=/home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/libpng16

Name: libpng
Description: Loads and saves PNG files
Version: 1.6.29
Libs: -L${libdir} -lpng16
Libs.private: -lm -lz -lm 
Cflags: -I${includedir}
```
produces
```
pkg_cv_png_CFLAGS=-I/home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29/include/libpng16
pkg_cv_png_LIBS='-L/home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29/lib -lpng16'
```

This already looks like a bit of a problem because there is no `-lz` anywhere to be found and no path to zlib (not sure how pkg-config's `Libs.private` works).

But cairo also checks for `-lz` on its own for the surface backends ps, pdf, xml, as seen here in config.log:
```
configure:20598: checking for compress in -lz
configure:20623: gcc-5 -o conftest -g -O2   conftest.c -lz  -lrt  -lm >&5
configure:20623: $? = 0
configure:20632: result: yes
configure:20635: checking zlib.h usability
configure:20635: gcc-5 -c -g -O2  conftest.c >&5
configure:20635: $? = 0
configure:20635: result: yes
configure:20635: checking zlib.h presence
configure:20635: gcc-5 -E  conftest.c
configure:20635: $? = 0
configure:20635: result: yes
configure:20635: checking for zlib.h
configure:20635: result: yes
```
As a result, the following variables are set:
```
    ps_NONPKGCONFIG_LIBS=-lz
    pdf_NONPKGCONFIG_LIBS=-lz
    xml_NONPKGCONFIG_LIBS=-lz
```
and then later
```
CAIRO_NONPKGCONFIG_LIBS='           -lz -lz     '
```
and finally
```
CAIRO_LIBS='   -lpthread      -L/home/mi/pipping/.linuxbrew/Cellar/pixman/0.34.0/lib -lpixman-1    -L/home/mi/pipping/.linuxbrew/opt/freetype/lib -L/home/mi/pipping/.linuxbrew/Cellar/fontconfig/2.12.3/lib -lfontconfig -lfreetype -L/home/mi/pipping/.linuxbrew/opt/freetype/lib -lfreetype  -L/home/mi/pipping/.linuxbrew/Cellar/libpng/1.6.29/lib -lpng16             -lz -lz     '
```

The result is that in trying to link against libpng16, it does also try to link against -lz, coincidentally (a missing dep?) but it will use the system version (which is too old, hence the error!) because configure does not use pkg-config to look for zlib and thus never learns about linuxbrew's version of zlib (configure also does have a `--with-zlib=...` flag or something like that).

**Comment by jsorah** [comment]
What happens if you run `brew install --env=std cairo` ? 

I had this exact issue and that seemed to solve it for me.   https://github.com/Homebrew/legacy-homebrew/issues/16361#issuecomment-12464345

**Comment by epipping** [comment]
@jsorah yes, `brew install --env=std cairo` appears to make it work.

**Comment by epipping** [comment]
I believe the issue boils down to the following behaviour:
```
% echo 'int main() { return 0; }' > t.c;
% ~/.linuxbrew/bin/gcc-5 t.c $(pkg-config --libs libpng) # works
% ~/.linuxbrew/bin/gcc-5 t.c $(pkg-config --libs libpng) $(pkg-config --libs zlib) # works
% ~/.linuxbrew/bin/gcc-5 t.c $(pkg-config --libs libpng) -lz # fails
```
where the last command produces
```
~/.linuxbrew/Cellar/libpng/1.6.29/lib/libpng16.so: undefined reference to `inflateValidate@ZLIB_1.2.9'
```

**Comment by sjackman** [comment]
```
❯❯❯  brew linkage cairo
Possible undeclared dependencies:
…
  lzo
  zlib
```
It looks to me that `cairo` is missing a dependency on `zlib` and possible also `lzo`, though I'm less sure about that one.
Please open a PR to add to `cairo`
```ruby
depends_on "zlib" unless OS.mac?
```

**Comment by epipping** [comment]
I'm afraid just adding zlib as a dependency is not a solution: The issue is having cairo find linuxbrew's zlib. One could argue that the proper fix would be to have configure.ac use pkg-config to carry out the check (that would work because the PKG_CONFIG_PATH would contain zlib) but that would be a patch that upstream wouldn't accept since macOS (without linuxbrew) has zlib (headers and lib) but no pkg-config.

Instead, this works for me:
```diff
diff --git a/Formula/cairo.rb b/Formula/cairo.rb
index 933b2dce42..256c02a210 100644
--- a/Formula/cairo.rb
+++ b/Formula/cairo.rb
@@ -37,6 +37,7 @@ class Cairo < Formula
   depends_on "libpng"
   depends_on "pixman"
   depends_on "glib"
+  depends_on "zlib" unless OS.mac?
 
   def install
     args = %W[
@@ -50,6 +51,13 @@ class Cairo < Formula
       --enable-quartz-image
     ] if OS.mac?
 
+
+    unless OS.mac?
+      zlib = Formula["zlib"]
+      ENV.append "CPPFLAGS", "-I#{zlib.opt_include}"
+      ENV.append "LDFLAGS", "-L#{zlib.opt_lib}"
+    end
+
     if build.with? "x11"
       args << "--enable-xcb=yes" << "--enable-xlib=yes" << "--enable-xlib-xrender=yes"
     else
```

I cannot judge if that's an acceptable fix. If it is, I'll open a PR for it.

As for lzo: The fact that lzo isn't found does not represent a problem in itself. I think hardly anyone cares about lzo. The slightly annoying feature of cairo's configure script is that there's no flag to disable lzo detection, making it an automagic dependency. So somebody who happens to have lzo installed would end up building a different cairo than somebody who doesn't and linuxbrew would not warn her if she uninstalled lzo (although it has the potential to break her cairo installation)

Making lzo a hard dependency instead is one way of handling that situation. Maybe the easiest since it has no deps on its own.

**Comment by sjackman** [comment]
The dependencies of a formula are already added to both `CPPFLAGS` and `LDFLAGS` by `Superenv`.
See https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/shims/linux/super/cc#L247
and https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/shims/linux/super/cc#L254

> The slightly annoying feature of cairo's configure script is that there's no flag to disable lzo detection

That's an annoying feature, for reproducibility of builds, of many build systems. 😖

In the same PR in a separate commit, please add `liblzo2-dev` to the list of packages to be removed by `sudo apt-get remove` in both `.travis.yml` and `circle.yml`.

**Comment by epipping** [comment]
Hm. I see what you're saying (I'm taking `Superenv` to be something that automatically runs for any installation). It all looks good, too. But then how come config.log from the [gist I pasted earlier](https://gist.github.com/anonymous/4d3bf96d411ab7f25db13addca59227f) contains
```
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
CPPFLAGS=''
LDFLAGS=''
```
which means that `CPPFLAGS` and `LDFLAGS` end up being empty/unset.

I only proposed the change that appended to `CPPFLAGS` and `LDFLAGS` because adding the dependency without doing anything else did not solve the problem. Indeed, [here's a new gist](https://gist.github.com/40d6da9f0fb271f5195657d64dbfd857) that shows what happens if I apply nothing but the change
```diff
diff --git a/Formula/cairo.rb b/Formula/cairo.rb
index 933b2dce42..36e0db5ef1 100644
--- a/Formula/cairo.rb
+++ b/Formula/cairo.rb
@@ -37,6 +37,7 @@ class Cairo < Formula
   depends_on "libpng"
   depends_on "pixman"
   depends_on "glib"
+  depends_on "zlib" unless OS.mac?
 
   def install
     args = %W[
```
(namely, nothing: the log is exactly the same).

**Comment by sjackman** [comment]
Superenv puts the shell script `Library/Homebrew/shims/linux/super/gcc-5` ahead of the real `gcc-5` executable in the `PATH`, and that shell scripts adds flags to the command line. There should be a log file named `02.make.cc` that shows which shows the flags added by Superenv. I'm not seeing that file however in your gist. Can you check your local `~/.cache/Homebrew/Logs/cairo` directory for a file named `*.cc`?

**Comment by epipping** [comment]
Nope, I don't have such a file. I do have
```
/home/mi/pipping/.cache/Homebrew/Logs/git/01.make.cc
/home/mi/pipping/.cache/Homebrew/Logs/git/03.make.cc
/home/mi/pipping/.cache/Homebrew/Logs/util-linux/02.make.cc
/home/mi/pipping/.cache/Homebrew/Logs/util-linux/01.configure.cc
/home/mi/pipping/.cache/Homebrew/Logs/libpng/02.make.cc
/home/mi/pipping/.cache/Homebrew/Logs/libpng/03.make.cc
/home/mi/pipping/.cache/Homebrew/Logs/libpng/01.configure.cc
/home/mi/pipping/.cache/Homebrew/Logs/fontconfig/02.make.cc
/home/mi/pipping/.cache/Homebrew/Logs/fontconfig/01.configure.cc
```
so I suppose that suggests the mechanisms is generally working, just not for cairo for me?

**Comment by sjackman** [comment]
It seems that way, yes, though I couldn't say why. It'll require some troubleshooting. If the build script invokes the full path to the compiler (e.g. `~/.linuxbrew/bin/gcc-5`) rather than simply `gcc-5` the Superenv script will be bypassed. Try adding `V=1` to the `make` line and see if that's informative.

**Comment by epipping** [comment]
It looks like gcc-5 is properly invoked; that's not the issue. With the diff
```diff
diff --git a/Formula/cairo.rb b/Formula/cairo.rb
index 933b2dce42..8356bd9cc0 100644
--- a/Formula/cairo.rb
+++ b/Formula/cairo.rb
@@ -37,6 +37,7 @@ class Cairo < Formula
   depends_on "libpng"
   depends_on "pixman"
   depends_on "glib"
+  depends_on "zlib" unless OS.mac?
 
   def install
     args = %W[
@@ -61,7 +62,7 @@ class Cairo < Formula
     else
       system "./configure", *args
     end
-    system "make", "install"
+    system "make", "install", "V=1"
   end
 
   test do
```
here's the [gist I get](https://gist.github.com/e4c2752bee27a0edf24056596aeb062e).

**Comment by sjackman** [comment]
```
libtool: finish: PATH="/home/mi/pipping/.linuxbrew/bin:/home/mi/pipping/.linuxbrew/Library/Homebrew/shims/linux/super:/home/mi/pipping/.linuxbrew/opt/xz/bin:/home/mi/pipping/.linuxbrew/opt/pkg-config/bin:/home/mi/pipping/.linuxbrew/opt/libpng/bin:/home/mi/pipping/.linuxbrew/opt/bzip2/bin:/home/mi/pipping/.linuxbrew/opt/freetype/bin:/home/mi/pipping/.linuxbrew/opt/expat/bin:/home/mi/pipping/.linuxbrew/opt/fontconfig/bin:/home/mi/pipping/.linuxbrew/opt/libxml2/bin:/home/mi/pipping/.linuxbrew/opt/ncurses/bin:/home/mi/pipping/.linuxbrew/opt/gettext/bin:/home/mi/pipping/.linuxbrew/opt/pcre/bin:/home/mi/pipping/.linuxbrew/opt/util-linux/bin:/home/mi/pipping/.linuxbrew/opt/glib/bin:/home/mi/pipping/.linuxbrew/opt/python/bin:/home/mi/pipping/.linuxbrew/opt/binutils/bin:/home/mi/pipping/.linuxbrew/opt/gpatch/bin:/home/mi/pipping/.linuxbrew/opt/gawk/bin:/home/mi/pipping/.linuxbrew/opt/check/bin:/home/mi/pipping/.linuxbrew/opt/libxpm/bin:/home/mi/pipping/.linuxbrew/opt/font-util/bin:/home/mi/pipping/.linuxbrew/opt/m4/bin:/home/mi/pipping/.linuxbrew/opt/autoconf/bin:/home/mi/pipping/.linuxbrew/opt/automake/bin:/home/mi/pipping/.linuxbrew/opt/gperf/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/mi/pipping/.linuxbrew/opt/gcc/bin:/sbin" ldconfig -n /home/mi/pipping/.linuxbrew/Cellar/cairo/1.14.8/lib
```
https://gist.github.com/anonymous/e4c2752bee27a0edf24056596aeb062e#file-02-make-L458

`/home/mi/pipping/.linuxbrew/bin` is in front of `/home/mi/pipping/.linuxbrew/Library/Homebrew/shims/linux/super` in your `PATH`. Check your `~/.bashrc` for a line that modifies your `PATH`. If you find it, move that line from `~/.bashrc` to `~/.bash_profile`. You can use `brew sh <<<'which -a cc'` to ensure that `shims/linux/super/cc` is first in your PATH.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `cairo`.
Another possible workaround for you is `brew install --force-bottle cairo`, but no promises.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by epipping** [comment]
Hm. Okay first off, since it's starting to look like I did something stupid to cause this: I'd like to say sorry and thank you for your time.

What I was doing actually: I set the path in `~/.profile` but had `~/.zshrc` source that file (\*).

However, also with my setup I was actually getting the right output here:
```
% brew sh <<<'which -a cc'
Your shell has been configured to use Homebrew's build environment;
this should help you build stuff. Notably though, the system versions of
gem and pip will ignore our configuration and insist on using the
environment they were built under (mostly). Sadly, scons will also
ignore our configuration.
When done, type `exit'.
~/.linuxbrew/Library/Homebrew/shims/linux/super/cc
~/.linuxbrew/bin/cc
/usr/bin/cc
```
And I would not expect the fact whether I set something in my .zshrc or .zprofile to affect linuxbrew either because linuxbrew should never spawn instances of zsh on its own (I mean, it could of course learn about my shell from $SHELL but my shell could be anything... bourne-shell-compatible, tcsh, or something else entirely).

I've now moved the PATH adjustment to ~/.zprofile but the outcome is [the same](https://gist.github.com/167be9fa5aad225ad18d5dabfc1f3eb5) I'm afraid: The output of `brew sh <<<'which -a cc'` is unchanged but the libtool line is also still
```
libtool: finish: PATH="~/.linuxbrew/bin:~/.linuxbrew/Library/Homebrew/shims/linux/super:..." ...
```


-----

(I'm not a privileged user on the system in question so /home/linuxbrew is unfortunately not an option).

(I replaced my actual $HOME with a tilde in all the output)

(\*) I think I did that so that logins shell and non-login shells would see that path and also other shells like bash; probably for graphical instances of emacs. It was a while ago. I didn't care much about the downside of have appended to the PATH twice if I ran zsh inside zsh since that's something I never do.

**Comment by sjackman** [comment]
> Hm. Okay first off, since it's starting to look like I did something stupid to cause this: I'd like to say sorry and thank you for your time.

No worries. I think an issue like this has come up before, so really we need a `brew doctor` test to check for it. It's also still possible that somehow the build script of `cairo` is somehow adding `~/.linuxbrew/bin` to the front of your `PATH`.

To troubleshoot, try
```sh
echo $PATH
PATH=/foo:$PATH
bash
echo $PATH
```
and check that `/foo` is still at the front of your `PATH`.

**Comment by epipping** [comment]
Yes, that's what happens:
```
% echo $PATH
/home/mi/pipping/.linuxbrew/bin:/home/mi/pipping/.linuxbrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/games
% PATH=/foo:$PATH
% bash
$ echo $PATH
/foo:/home/mi/pipping/.linuxbrew/bin:/home/mi/pipping/.linuxbrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/games
$

**Comment by epipping** [comment]
Update: cairo itself isn't to blame here, apparently. If I add
```
system "echo PATH=$PATH"
```
to the formula, I get the following log:
```
% cat 01.echo 
2017-06-17 00:02:43 +0200

echo PATH=$PATH

PATH=/home/mi/pipping/.linuxbrew/bin:/home/mi/pipping/.linuxbrew/Library/Homebrew/shims/linux/super:/home/mi/pipping/.linuxbrew/opt/xz/bin:/home/mi/pipping/.linuxbrew/opt/pkg-config/bin:/home/mi/pipping/.linuxbrew/opt/libpng/bin:/home/mi/pipping/.linuxbrew/opt/bzip2/bin:/home/mi/pipping/.linuxbrew/opt/freetype/bin:/home/mi/pipping/.linuxbrew/opt/expat/bin:/home/mi/pipping/.linuxbrew/opt/fontconfig/bin:/home/mi/pipping/.linuxbrew/opt/libxml2/bin:/home/mi/pipping/.linuxbrew/opt/ncurses/bin:/home/mi/pipping/.linuxbrew/opt/gettext/bin:/home/mi/pipping/.linuxbrew/opt/pcre/bin:/home/mi/pipping/.linuxbrew/opt/util-linux/bin:/home/mi/pipping/.linuxbrew/opt/glib/bin:/home/mi/pipping/.linuxbrew/opt/python/bin:/home/mi/pipping/.linuxbrew/opt/binutils/bin:/home/mi/pipping/.linuxbrew/opt/gpatch/bin:/home/mi/pipping/.linuxbrew/opt/gawk/bin:/home/mi/pipping/.linuxbrew/opt/check/bin:/home/mi/pipping/.linuxbrew/opt/libxpm/bin:/home/mi/pipping/.linuxbrew/opt/font-util/bin:/home/mi/pipping/.linuxbrew/opt/m4/bin:/home/mi/pipping/.linuxbrew/opt/autoconf/bin:/home/mi/pipping/.linuxbrew/opt/automake/bin:/home/mi/pipping/.linuxbrew/opt/gperf/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/mi/pipping/.linuxbrew/opt/gcc/bin
% 
```

**Comment by epipping** [comment]
All the while, my .zprofile does seem to be the culprit although I don't know why. If I remove the PATH adjustment from my .zprofile so that
```
% which cairo
cairo not found
% 
```
and I run
```
~/.linuxbrew/bin/brew reinstall cairo
```
then my PATH in there is indeed correct: `PATH=~/.linuxbrew/Library/Homebrew/shims/linux/super:...` and I **do** get a `0x-make.cc` log file and sure enough the entire installation all of a sudden works (with zlib added as a dep)

**Comment by epipping** [comment]
(Deleting my previous comment and adding a new one because I wrote nonsense in a few places and you might otherwise miss the edits; I need sleep, apparently)

All the while, my .zprofile does seem to be the culprit although I don't know why. If I remove the PATH adjustment from my .zprofile so that 
```
% which brew
brew not found
% 
```
and I run
```
~/.linuxbrew/bin/brew reinstall cairo
```
then my PATH in there is indeed correct: `PATH=~/.linuxbrew/Library/Homebrew/shims/linux/super:...` and I **do** get a `02-make.cc` log file and sure enough the entire installation all of a sudden works even **without** adding zlib as a dep.

**Comment by sjackman** [comment]
Superenv works in wonderful and mysterious ways, when it works. 😝
I'm not sure why `~/.zprofile` is being sourced. What is the value of `$SHELL` and `readlink /bin/sh`? Is `/bin/sh` a symlink to `/bin/zsh`, and does `~/.zshrc` source `~/.zprofile`?

**Comment by epipping** [comment]
Well, `SHELL=/bin/zsh` ~/.zprofile is supposed to be sourced. But only once (when I log in via ssh); and the PATH that cairo was seeing differed from the PATH that I was seeing when I logged in not just by a prefix or suffix but by paths which were added between the beginning and the end...

**Comment by sjackman** [comment]
> I'm not a privileged user on the system in question so /home/linuxbrew is unfortunately not an option.

If it's an option for you, you can open a ticket with your system department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew` for sharing software installed by your group.
