### ISSUE TITLE
p11-kit failed to build on Debian Jessie 8.8

### ISSUE THREAD

**Issue by okuuva** [Linuxbrew/homebrew-core#2921]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

I tried installing Weechat with linuxbrew, but it fails to install one of the dependencies, p11-kit. I verified that installation works both from the bottle and source using homebrew on macOS Sierra. What's more interesting that I'm able to install it on my desktop machine but not on the server I would like to install Weechat on.

Here's the output of `brew install p11-kit`:
```
$ brew install p11-kit
==> Downloading https://github.com/p11-glue/p11-kit/releases/download/0.23.7/p11-kit-0.23.7.tar.gz
Already downloaded: /home/users/spikeb/.cache/Homebrew/p11-kit-0.23.7.tar.gz
==> ./configure --disable-silent-rules --disable-trust-module --prefix=/home/users/spikeb/.linuxbrew/Cellar/p11-kit/0.23.7 --sy
==> make
==> make check
Last 15 lines from /home/users/spikeb/.cache/Homebrew/Logs/p11-kit/03.make:
ok 45 /transport/test_random
ok 46 /transport/unix/basic
PASS: test-transport
============================================================================
1 of 29 tests failed
Please report to https://bugs.freedesktop.org/enter_bug.cgi?product=p11-glue
============================================================================
Makefile:3994: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 1
make[2]: Leaving directory '/tmp/p11-kit-20170612-628-6ihbw3/p11-kit-0.23.7'
Makefile:4278: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/tmp/p11-kit-20170612-628-6ihbw3/p11-kit-0.23.7'
Makefile:3894: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
```
Here's the output of `brew gist-logs p11-kit` on the server where the installation fails: https://gist.github.com/anonymous/9f0ddad6e48dcf772dd7772b96c3a9d0

And here's the output of `brew gist-logs p11-kit` on the desktop where the installation is successful:
https://gist.github.com/anonymous/db1029b66eaaef178ae32c9cebe80a2b

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `p11-kit`.
Another possible workaround for you is `brew install --force-bottle p11-kit `, but no promises.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
A hack workaround option for you is to
`brew edit p11-kit`
and delete the line
`system "make", "check"`
