### ISSUE TITLE
protobuf: ImportError: No module named site

### ISSUE THREAD

**Issue by jq2252** [Linuxbrew/homebrew-core#2922]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

```
brew gist-logs protobuf
https://gist.github.com/anonymous/69d8b21e0beeb191c107731641df0fc7
brew install protobuf
The log is as following:
==> Downloading https://github.com/google/protobuf/archive/v3.3.0.tar.gz
Already downloaded: /home/310290145/.cache/Homebrew/protobuf-3.3.0.tar.gz
==> Downloading https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/googlemock/gmock-1.7.0.zi
Already downloaded: /home/310290145/.cache/Homebrew/protobuf--gmock-1.7.0.zip
==> ./autogen.sh
==> ./configure --prefix=/home/310290145/.linuxbrew/Cellar/protobuf/3.3.0 --with-zlib
==> make
==> make install
==> Downloading https://pypi.python.org/packages/48/69/d87c60746b393309ca30761f8e2b49473d43450b150cb08f3c6df5c11be5/appdi
Already downloaded: /home/310290145/.cache/Homebrew/protobuf--appdirs-1.4.3.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf-20170613-28626-jkrjq6/protobuf-3.3.0/home
Last 15 lines from /home/310290145/.cache/Homebrew/Logs/protobuf/05.python:
2017-06-13 10:03:00 -0400

python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/protobuf-20170613-28626-jkrjq6/protobuf-3.3.0/homebrew
--single-version-externally-managed
--record=installed.txt

ImportError: No module named site

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
```

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Attempting to reproduce this issue at PR https://github.com/Linuxbrew/homebrew-core/pull/2936
