### ISSUE TITLE
raptor install failed at RedHat 6.9

### ISSUE THREAD

**Issue by jq2252** [Linuxbrew/homebrew-core#2923]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [X] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
brew gist-logs raptor
```
https://gist.github.com/b1ee91de13dd68b646dec73a15c4bd3b

```
brew install raptor
==> Downloading http://download.librdf.org/source/raptor2-2.0.15.tar.gz
Already downloaded: /home/310290145/.cache/Homebrew/raptor-2.0.15.tar.gz
==> ./configure --prefix=/home/310290145/.linuxbrew/Cellar/raptor/2.0.15
==> make install
Last 15 lines from /home/310290145/.cache/Homebrew/Logs/raptor/02.make:
../src/.libs/libraptor2.so: undefined reference to `xsltFreeStylesheet@LIBXML2_1.0.11'
../src/.libs/libraptor2.so: undefined reference to `xsltCleanupGlobals@LIBXML2_1.0.11'
../src/.libs/libraptor2.so: undefined reference to `xsltGetDefaultSecurityPrefs@LIBXML2_1.0.22'
../src/.libs/libraptor2.so: undefined reference to `xsltSetTransformErrorFunc@LIBXML2_1.0.22'
../src/.libs/libraptor2.so: undefined reference to `xsltNewTransformContext@LIBXML2_1.0.11'
../src/.libs/libraptor2.so: undefined reference to `xsltGenericErrorContext@LIBXML2_1.0.24'
../src/.libs/libraptor2.so: undefined reference to `xsltParseStylesheetDoc@LIBXML2_1.0.11'
../src/.libs/libraptor2.so: undefined reference to `xsltSetDefaultSecurityPrefs@LIBXML2_1.0.22'
../src/.libs/libraptor2.so: undefined reference to `xsltGenericError@LIBXML2_1.0.24'
collect2: error: ld returned 1 exit status
make[1]: *** [rdfdiff] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [rapper] Error 1
make[1]: Leaving directory `/tmp/raptor-20170613-89930-swdwys/raptor2-2.0.15/utils'
make: *** [install-recursive] Error 1

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
```

**Comment by sjackman** [comment]
Attempting to reproduce this issue at PR https://github.com/Linuxbrew/homebrew-core/pull/2937
