### ISSUE TITLE
llvm: Cannot find source file: libomp.rc

### ISSUE THREAD

**Issue by jq2252** [Linuxbrew/homebrew-core#2939]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [X] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
brew gist-logs llvm
https://gist.github.com/a2af52471dad144f781f98cd61d9ef32

I try to run brew install llvm at redhat 6.9
```
==> Downloading http://releases.llvm.org/4.0.0/llvm-4.0.0.src.tar.xz
Already downloaded: /home/310290145/.cache/Homebrew/llvm-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/cfe-4.0.0.src.tar.xz
Already downloaded: /home/310290145/.cache/Homebrew/llvm--clang-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/clang-tools-extra-4.0.0.src.tar.xz
Already downloaded: /home/310290145/.cache/Homebrew/llvm--clang-extra-tools-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/openmp-4.0.0.src.tar.xz
Already downloaded: /home/310290145/.cache/Homebrew/llvm--openmp-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/libunwind-4.0.0.src.tar.xz
Already downloaded: /home/310290145/.cache/Homebrew/llvm--libunwind-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/lld-4.0.0.src.tar.xz
Already downloaded: /home/310290145/.cache/Homebrew/llvm--lld-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/polly-4.0.0.src.tar.xz
Already downloaded: /home/310290145/.cache/Homebrew/llvm--polly-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/compiler-rt-4.0.0.src.tar.xz
Already downloaded: /home/310290145/.cache/Homebrew/llvm--compiler-rt-4.0.0.tar.xz
==> cmake -G Unix Makefiles /tmp/llvm-20170615-43032-1le3rj5/llvm-4.0.0.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELE
Last 15 lines from /home/310290145/.cache/Homebrew/Logs/llvm/01.cmake:
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG - Failed
-- LLD version: 4.0.0
-- Configuring done
CMake Error at projects/openmp/runtime/src/CMakeLists.txt:143 (add_library):
  Cannot find source file:

    libomp.rc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


-- Generating done
-- Build files have been written to: /tmp/llvm-20170615-43032-1dw1bg4
```

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `llvm`.
Another possible workaround for you is `brew install --force-bottle llvm`, but no promises.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
I'm afraid that I don't have the time available to troubleshoot this issue. Sorry that I can't be of further help. If you're able to reproduce this issue compiling `llvm` either outside of Linuxbrew or within `brew sh`, you may wish to consider opening an issue upstream with the `llvm` developers.

**Comment by jq2252** [comment]
Thanks a lot for your help.
When you say  /home/linuxbrew/.linuxbrew/, does  "linuxbrew" in the middle mean a username?
In my account the .linuxbrew fold is under the ~/ path.  
And I try 
```
brew install --force-bottle llvm
```
And the log is as following:
```
==> Downloading https://linuxbrew.bintray.com/bottles/llvm-4.0.0_1.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring llvm-4.0.0_1.x86_64_linux.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /home/310290145/.linuxbrew
Could not symlink lib/libunwind.a
Target /home/310290145/.linuxbrew/lib/libunwind.a
is a symlink belonging to libunwind. You can unlink it:
  brew unlink libunwind

To force the link and overwrite all conflicting files:
  brew link --overwrite llvm

To list all files that would be deleted:
  brew link --overwrite --dry-run llvm

Possible conflicting files are:
/home/310290145/.linuxbrew/lib/libunwind.a -> /home/310290145/.linuxbrew/Cellar/libunwind/1.2/lib/libunwind.a
==> Summary
🍺  /home/310290145/.linuxbrew/Cellar/llvm/4.0.0_1: 2,083 files, 4.4GB
```

**Comment by sjackman** [comment]
> When you say /home/linuxbrew/.linuxbrew/, does "linuxbrew" in the middle mean a username?

No, I mean literally `/home/linuxbrew/.linuxbrew`. If you have `sudo` access, the installer script uses that directory as the default installation directory. See http://linuxbrew.sh/#install-linuxbrew

**Comment by sjackman** [comment]
Try…
```sh
brew unlink libunwind
brew link llvm
```
