### ISSUE TITLE
jemalloc 5.0.0 causes neovim to crash

### ISSUE THREAD

**Issue by kronos29296** [Linuxbrew/homebrew-core#2996]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

jemalloc version 5.0.0 causes neovim version 0.2 to crash. This does not happen in version 4.5.0. Please provide additional version 4.5.0 in the formula for jemalloc as I cleaned the older install and cannot downgrade.

Information about the bug:
[Same bug in Arch linux for the same version](https://bugs.archlinux.org/task/54447)
[Issue for the bug in Github for jemalloc](https://github.com/jemalloc/jemalloc/issues/907)
[Github issue for the bug in neovim](https://github.com/neovim/neovim/issues/6895)

**Comment by sjackman** [comment]
Thanks for the bug report, @kronos29296.

This bug may be fixed upstream in `neovim`. Check out the relevant thread at https://github.com/Homebrew/homebrew-core/pull/14485
https://github.com/Homebrew/homebrew-core/pull/14485#discussion_r121921111
You may also try `brew install neovim/neovim --without-jemalloc` as a workaround.

Please report this bug upstream at https://github.com/neovim/homebrew-neovim
