### ISSUE TITLE
Instructions for using on a HPC?

### ISSUE THREAD

**Issue by cmdcolin** [Linuxbrew/homebrew-core#3027]
If I try to execute linuxbrew installed programs on my university's high performance computing(HPC) system, I will generally get errors about "illegal instruction" which I suspect is due to the fact that the way the software is compiled in linuxbrew ends up conflicting with the runtime that is used on the HPC.

It is a tricky problem because the HPC environment does seem to try and adopt some of the user's home variables, so for example it will find linuxbrew binaries in the PATH without me changing anything in the qsub script, but I am suspecting that the linuxbrew GCC libraries are not somehow linked and that ends up causing the "illegal instruction" errors

To give an example, I was using the fermi program from homebrew-science and it gave me errors like this when it was run (not when it was installed, but when it is run via a qsub script)

```
/bin/sh: line 1: 117513 Illegal instruction     (core dumped) fermi fltuniq fmdef.ec.fq.gz 2> fmdef.fltuniq.log
     117514                       (core dumped) | fermi ropebwt -a bcr -v3 -btf fmdef.ec.tmp - > fmdef.ec.fmd 2> fmdef.ec.fmd.log
make: *** [fmdef.ec.fmd] Error 132

```

If I compiled fermi myself though, then it ran without errors, which I suspect is because manually compiling it used the default HPC system compilers and therefore no runtime is out of place. I am thinking that if maybe some  system variables about linuxbrew were in place like maybe LDFLAGS or something then the linuxbrew would run on the hpc

**Comment by sjackman** [comment]
Hi, Colin. The likely cause of the `Illegal instruction` is that the CPUs of your HPC compute nodes don't support certain newer CPU instructions. What year was your HPC cluster installed? What is the output of `brew config` on the head node of your cluster? Submit a job to your HPC cluster that runs `brew config`; what is the output?

**Comment by sjackman** [comment]
```
Illegal instruction (core dumped)
```

If you're able to find that `core` file, then you can run
```sh
gdb $(which fermi) core
bt
x/i $pc
```
which will help trouble shooting.

**Comment by sjackman** [comment]
By default Linuxbrew uses precompiled binary executables. A possible workaround for you is to reinstall `fermi` from source.
```sh
brew reinstall -s fermi
```

**Comment by cmdcolin** [comment]
It I fixed it. It looks like the important thing is to do a special job submission to make sure it goes onto the same type of machine that I compiled it on

So for example, I login to computers called dev-intel16 and use linuxbrew on those to compile a program, and then to make sure it stays on these, I need to make sure my PBS script has something such as

    #PBS -l nodes=1:ppn=16,walltime=04:00:00,mem=64gb,feature=intel16

If I used feature=intel11 which is a different set of machines, it causes the Illegal instruction errors.


Anyone else would probably need to refer to their own hpcc guide to figure it out I imaging since the "intel16" thing is probably very specific to our compute cluster (ref https://wiki.hpcc.msu.edu/display/hpccdocs/HPCC+Quick+Reference+Sheet)

**Comment by sjackman** [comment]
Another solution for you is to specify the target architecture when you compile software from source.
```sh
HOMEBREW_ARCH=core2 brew install …
```

**Comment by cmdcolin** [comment]
interesting, I'll give that a shot!
