### ISSUE TITLE
openssl@1.1 Makefile:150: recipe for target 'tests' failed (wget dep)

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/homebrew-core#3046]
It seems `openssl@1.1` is a dep of `wget`

Gist-logs:

https://gist.github.com/9d5ec0fcf8a02c6c7ab54bcf0ad74bbf

Error:

```
brew install wget
==> Installing dependencies for wget: openssl@1.1, util-linux
==> Installing wget dependency: openssl@1.1
sudo: unable to resolve host jaconclimb
==> Downloading https://www.openssl.org/source/openssl-1.1.0f.tar.gz
######################################################################## 100.0%
==> perl ./Configure --prefix=/home/ubuntu/.linuxbrew/Cellar/openssl@1.1/1.1.0f --openssldir=/home/ubuntu/.linuxbrew/etc/openssl@1.1 no-s
==> make



==> make test
Last 15 lines from /home/ubuntu/.cache/Homebrew/Logs/openssl@1.1/03.make:
../test/recipes/90-test_threads.t .......... ok
../test/recipes/90-test_v3name.t ........... ok

Test Summary Report
-------------------
../test/recipes/90-test_shlibload.t      (Wstat: 768 Tests: 3 Failed: 3)
  Failed tests:  1-3
  Non-zero exit status: 3
Files=95, Tests=548, 69 wallclock secs ( 0.35 usr  0.11 sys + 31.02 cusr  1.57 csys = 33.05 CPU)
Result: FAIL
Makefile:152: recipe for target '_tests' failed
make[1]: *** [_tests] Error 3
make[1]: Leaving directory '/tmp/openssl@1.1-20170623-8472-1hls4ch/openssl-1.1.0f'
Makefile:150: recipe for target 'tests' failed
make: *** [tests] Error 2
```

**Comment by sjackman** [comment]
Are you able to use `curl` rather than `wget` in this case as a workaround?
There's a non-relocatable bottle for `openssl@1.1`.
`brew install openssl@1.1 --without-test` will skip the tests, and may work as a workaround.
As a hack workaround you could `brew install --force-bottle openssl@1.1` and then afterward configure it (somehow) to tell it where to find the `cacerts` file.
As for the failed tests, I'm not sure whether that's an upstream issue or a Linuxbrew issue.

**Comment by sjackman** [comment]
I also see this same `make test` failure on my local Linuxbrew development box.

**Comment by harper357** [comment]
I just had this problem, too. I used @sjackman 's suggestion to install without tests. wget appears to be working.

**Comment by NickTseng** [comment]
brew upgrade --force-bottle openssl@1.1

**Comment by tseemann** [comment]
I eventually just got it to install with `brew upgrade openssl@1.1` -- there seemed to be a bottle, which worked.
