### ISSUE TITLE
brew install gcc, errors in RHEL6 with centos6 repository

### ISSUE THREAD

**Issue by kaji331** [Linuxbrew/homebrew-core#306]
```
➜ brew install gcc

==> Installing dependencies for gcc: gmp, mpfr, libmpc, isl
==> Installing gcc dependency: gmp
==> Downloading https://linuxbrew.bintray.com/bottles/gmp-6.1.0.x86_64_linux.bot
Already downloaded: /home/cancer/.cache/Homebrew/gmp-6.1.0.x86_64_linux.bottle.tar.gz
==> Pouring gmp-6.1.0.x86_64_linux.bottle.tar.gz
/home/cancer/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Error: Failure while executing: /home/cancer/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf --set-rpath /home/cancer/.linuxbrew/lib 
Warning: Bottle installation failed: building from source.
==> Downloading https://gmplib.org/download/gmp/gmp-6.1.0.tar.xz
Already downloaded: /home/cancer/.cache/Homebrew/gmp-6.1.0.tar.xz
==> ./configure --prefix=/home/cancer/.linuxbrew/Cellar/gmp/6.1.0 --enable-cxx
Last 15 lines from /home/cancer/.cache/Homebrew/Logs/gmp/01.configure:
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking compiler /usr/bin/gcc -Os -w -pipe -march=native -isystem/home/cancer/.linuxbrew/include... no, program does not run
checking ABI=x32
checking compiler /usr/bin/gcc -Os -w -pipe -march=native -isystem/home/cancer/.linuxbrew/include... no, program does not run
checking ABI=32
checking compiler /usr/bin/gcc -Os -w -pipe -march=native -isystem/home/cancer/.linuxbrew/include... no, program does not run
configure: error: could not find a working compiler, see config.log for details

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
https://github.com/Linuxbrew/homebrew-core/issues

These open issues may also help:
Update missing gmp 6.1.0 file #1053
```
# 

I tried many times~I installed libstdc++ in this RHEL6.

**Comment by rwhogg** [comment]
Hi @kaji331, can you please do a `brew gist-logs gcc` and report the output here? Thanks!

**Comment by kaji331** [comment]
I am sorry. I am an beginner, so I don't know how to get the report of brew gist-logs...

________________________________
发件人: Bob W. Hogg <notifications@github.com>
发送时间: 2016年5月23日 9:20
收件人: Linuxbrew/homebrew-core
抄送: kaji331; Mention
主题: Re: [Linuxbrew/homebrew-core] brew install gcc, errors in RHEL6 with centos6 repository (#306)


Hi @kaji331<https://github.com/kaji331>, can you please do a brew gist-logs gcc and report the output here? Thanks!

―

**Comment by rwhogg** [comment]
> I am sorry. I am an beginner, so I don't know how to get the report of brew gist-logs...

No worries!

I just meant to run "brew gist-logs gmp" in your terminal and paste the URL it displays here.

**Comment by kaji331** [comment]
@rwhogg https://gist.github.com/4e97978be044a5aeaff07aa5d1fa6247

**Comment by rwhogg** [comment]
GCC-compiled programs appear to be segfaulting: `./configure: line 5829: 16716 Segmentation fault (core dumped) ./a.out`.

Does GCC work at all for you?

Can you try compiling this program in two different ways and see what happens when you run it?

```c
#include <stdio.h>
int main(int argc, char** argv)
{
    printf("Hi");
}
```

First way: `gcc file.c`
Second way: `gcc -Os -w -pipe -march=native -isystem/home/cancer/.linuxbrew/include file.c`

**Comment by kaji331** [comment]
@rwhogg Maybe my gcc is ok. Both of two methods showed nothing and generated an a.out file. If I execute a.out, the zsh showed:
Hi%

Thanks for your help :+1:

**Comment by rwhogg** [comment]
No problem. Unfortunately, I don't have any further ideas about how to fix this. My apologies.

**Comment by sjackman** [comment]
```
==> Pouring gmp-6.1.0.x86_64_linux.bottle.tar.gz
/home/cancer/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Error: Failure while executing: /home/cancer/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf --set-rpath /home/cancer/.linuxbrew/lib 
```
Please report
```sh
which -a patchelf
brew test patchelf
patchelf --version
brew reinstall patchelf
which -a patchelf
brew test patchelf
patchelf --version
ldd `which patchelf`
```

**Comment by jrevillard** [comment]
I'm expecting the exact same issue when building everything from source on SL6 (I don't have the patchelf issue as I'm forcing installation from source).

Do you have an idea?

Best,
Jerome

**Comment by sjackman** [comment]
@kaji331 `patchelf` has recently been updated with a statically linked bottle that should resolve your issue. `brew update && brew reinstall patchelf && brew install gcc`

**Comment by sjackman** [comment]
@jrevillard Please report the error message that you're seeing and `brew gist-logs FORMULA` where `FORMULA` is the formula or dependency that failed to install.

**Comment by jrevillard** [comment]
@sjackman here it is: https://gist.github.com/anonymous/3172b3646e876c0df9aee10751f1a5c4

(as you can see I use my own repo but it's up to date with your today changes)

Best,
Jerome

**Comment by sjackman** [comment]
The relevant error is
```
configure:5820: /usr/bin/gcc -Os -w -pipe -march=native -isystem/cvmfs/neugrid.egi.eu/software/x86_64/test/linuxbrew/include conftest.c >&5
configure:5823: $? = 0
configure:5828: ./a.out || ./b.out || ./a.exe || ./a_out.exe || ./conftest
./configure: line 5829: 11740 Segmentation fault      (core dumped) ./a.out
```
https://gist.github.com/anonymous/3172b3646e876c0df9aee10751f1a5c4#file-config-log-L73-L76

Not a good situation. Is there a reason that you're compiling `gmp` from source rather than installing the precompiled binary bottle? Try
```
unset HOMEBREW_BUILD_FROM_SOURCE
brew install gmp
```

**Comment by sjackman** [comment]
When did this segfault issue start?

**Comment by jrevillard** [comment]
I'm compiling everything from source to see if it solve this other issue I just reported here: https://github.com/Linuxbrew/brew/issues/66

I don't know exactly when it started. The last time I tried to compile from source was more than a year ago....
