### ISSUE TITLE
Cannot build anything from source.

### ISSUE THREAD

**Issue by zkanda** [Linuxbrew/homebrew-core#307]
I cannot seem to build anything from source. I'm trying to install zsh from a fresh ubuntu 14.04.

https://gist.github.com/anonymous/e9ee006389eb2f2d14b34e4db5c195f0

**Comment by rwhogg** [comment]
From https://gist.github.com/anonymous/e9ee006389eb2f2d14b34e4db5c195f0#file-01-configure-L15-L19

```
checking for gcc... /usr/bin/gcc-4.8
checking whether the C compiler works... no
configure: error: in `/tmp/gdbm-20160516-20156-s31fqz/gdbm-1.11':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

From https://gist.github.com/anonymous/e9ee006389eb2f2d14b34e4db5c195f0#file-config-log-L91-L92

```
configure:3659: /usr/bin/gcc-4.8 -Os -w -pipe -march=prescott -isystem/home/zkanda/.linuxbrew/include -L/home/zkanda/.linuxbrew/lib -Wl,--dynamic-linker=/home/zkanda/.linuxbrew/lib/ld.so -Wl,-rpath,/home/zkanda/.linuxbrew/lib conftest.c  >&5
conftest.c:1:0: error: CPU you selected does not support x86-64 instruction set
```

**Comment by rwhogg** [comment]
@zkanda, can I ask for some clarification about your computer architecture? The gist says you're running this on an Intel Prescott.

According to [Wikipedia](https://en.wikipedia.org/wiki/Pentium_4#Prescott), there are both 32-bit and 64-bit versions of the Prescott. Which one are you using? We unfortunately don't support 32-bit at this time (but would welcome assistance if you'd like to help support it).

From [GCC's web site]():

```
‘prescott’
    Improved version of Intel Pentium 4 CPU with MMX, SSE, SSE2 and SSE3 instruction set support. 
```

Is that part of your CFLAGS variable or did Linuxbrew insert it itself?

Thanks a bunch!

By the way, I'll probably move this issue to Linuxbrew/brew if I determine that it's a bug in Linuxbrew itself and not just `gdbm` in particular.

**Comment by zkanda** [comment]
Yes, this is not just about gdbm, everything that I need to compile is having this issue. This is running in VM in our server which is supposed to be 64-bit.

Here is the output of `uname -a`
```
→ uname -a
Linux dev-server 3.19.0-59-generic #65~14.04.1-Ubuntu SMP Tue Apr 19 18:57:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I didn't change any CFLAGS settings as I don't even know how to do that but I would be willing to help on whatever I can.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/brew#40
