### ISSUE TITLE
fontconfig fails to build on Ubuntu 16.04 and CentOS6

### ISSUE THREAD

**Issue by drbenmorgan** [Linuxbrew/homebrew-core#3082]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
#
I'm having an issue building fontconfig from source - the binary bottle works fine, but am supporting users who have to install linuxbrew somewhere other than `$HOME/.linuxbrew`. The problem appears to be due to a mismatch between the Automake version fontconfig expects, and the one installed by linuxbrew as a `:build` dependency. I've confirmed the issue on both Ubuntu 16.04 and CentOS 6 docker containers with the recommended linuxbrew setup and the steps:

```
$ brew install fontconfig --only-dependencies
...
$ brew install fontconfig --build-from-source
```

The errors happen at the `make` step - gists show the same error for [Ubuntu 16.04](https://gist.github.com/anonymous/5be2016c83b386735859e70ebccff634) and [CentOS 6](https://gist.github.com/anonymous/bf1be734b90f29848405ce9c9ce04b46). The key line is [here](https://gist.github.com/anonymous/5be2016c83b386735859e70ebccff634#file-02-make-L61) warning about an Automake version mismatch.

I tried editing the fontconfig Formula to add `system "aclocal" unless OS.mac?` just before the `system "./configure" ...` line and that does resolve the issue. I can submit a PR with that in, but wanted to check first as I'm not an expert on Autotools (`autoreconf` might be better, but would add a `libtool` dependency?) or if there could be anything else going on.

**Comment by sjackman** [comment]
Thanks for the excellent bug report, Ben. It's very helpful.

I'm not sure why `fontconfig` depends on `autotools`. I don't believe it should, and it doesn't on macOS, but let's take it as a given that it does. I suggest changing
```diff
-    system "autoreconf", "-iv" if build.head?
+    system "autoreconf", "-iv" if build.head? || !OS.mac?
```
Please open a PR. If it fails because it needs `libtool`, I'm okay with adding a dependency on `libtool`.
