### ISSUE TITLE
Error: undefined method `exitstatus' for nil:NilClass

### ISSUE THREAD

**Issue by luceat-lux-vestra** [Linuxbrew/homebrew-core#3106]
I tried to install `elixir` but I got this error and I can't solve it.

```
Error: undefined method `exitstatus' for nil:NilClass
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elixir.rb:9:in `block in <class:Erlang18Requirement>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:58:in `instance_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:58:in `block in satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:198:in `block in yielder'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/ENV.rb:25:in `with_build_environment'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:198:in `yielder'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:58:in `satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:413:in `install_requirement_formula?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:433:in `block in expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:230:in `block in prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:228:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:228:in `prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:219:in `block (2 levels) in expand'
/usr/lib64/ruby/2.2.0/set.rb:283:in `each_key'
/usr/lib64/ruby/2.2.0/set.rb:283:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependencies.rb:68:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:218:in `block in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:217:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:217:in `expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1534:in `recursive_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:426:in `expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:368:in `compute_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:135:in `verify_deps_exist'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:128:in `prelude'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:372:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:223:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:221:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:221:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by palday** [comment]
Potentially related [`brew` issue ](https://github.com/Linuxbrew/brew/issues/412).

**Comment by luceat-lux-vestra** [comment]
I think `/home/linuxbrew/.linuxbrew/bin/` shoud be included on `PATH` on {{something??}} which `make` refer or  passed to `make`.

I made it work with some dirty jobs.

1. Install erlang with native package manager(zypper on openSUSE)
2. remove `depends_on Erlang18Requirement` on `/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
/elixir.rb`(This doesn't work with `erl` installed by `zypper` too which located in `/usr/bin/`)
3. run `brew install elixir`

I don't know how `ruby` or `linuxbrew`, `make` works well,  
but I think there's two suspicious point on `elixir` formula.

1. `Erlang18Requirement` can't recognize both `erl`(installed with zypper and linuxbrew)
2. make only recognize `erl` command installed with zypper(`/usr/bin/erl`).

Here's a log file content which named `01.make` generated after run `brew install elixir` without `sudo zypper in erlang`, `/usr/bin/erl`.

I got a hint from `PATH` on this log.  
I looked every paths listed in `PATH` but there's no path that include `erl` command.

Sorry for my bad English, but I wish this may help.

2017-07-05 14:51:32 +0900

make

/bin/sh: erl: command not found
At least Erlang 18.0 is required to build Elixir
make: *** [Makefile:62: lib/elixir/src/elixir.app.src] Error 1

HOMEBREW_VERSION: 1.2.2
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: bb5882475eb142f93ae36de158a07550f91372e2
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: f821eb810062afda93e331319191d12c9203e904
Core tap last commit: 36 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.2.6 => /usr/bin/ruby.ruby2.2
Clang: 4.0 build 
Git: 2.13.2 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby.ruby2.2
Java: openjdk version "1.8.0_131"
Kernel: Linux 4.11.7-1-default x86_64 GNU/Linux
OS: openSUSE Tumbleweed (n/a)
Host glibc: 2.25
/usr/bin/gcc: 7.1.1
glibc: N/A
gcc: 5.3.0
xorg: 20170115

HOMEBREW_CC: gcc-7
HOMEBREW_CXX: g++-7
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /home/linuxbrew/.linuxbrew
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig
ACLOCAL_PATH: /home/linuxbrew/.linuxbrew/share/aclocal
PATH: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/binutils/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/linuxbrew/.linuxbrew/opt/gcc/bin

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
As a hack workaround `brew edit elixir` and add the following line to the top of the file:
```ruby
require "English"
```
I'll work on a better fix.

**Comment by sjackman** [comment]
This bug will be fixed by PR https://github.com/Linuxbrew/brew/pull/415
