### ISSUE TITLE
regression: `brew install grpc` fails

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#3107]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/b39f8db2a7222889397628493d1a5414

NOTE: not sure where this bug belongs, see also https://github.com/grpc/homebrew-grpc/issues/101

**Comment by sjackman** [comment]
```
[HOSTLD]  Linking /tmp/grpc-20170703-13113-jb6gqt/grpc-1.4.1/bins/opt/grpc_ruby_plugin
/tmp/grpc-20170703-13113-jb6gqt/grpc-1.4.1/libs/opt/libgrpc_plugin_support.a(python_generator.o): In function `ProtoBufPrinter::Print(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, char const*)':
/tmp/grpc-20170703-13113-jb6gqt/grpc-1.4.1/./src/compiler/protobuf_plugin.h:155: undefined reference to `google::protobuf::io::Printer::Print(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, char const*)'
```
https://gist.github.com/anonymous/b39f8db2a7222889397628493d1a5414#file-01-make-L407

**Comment by sjackman** [comment]
I'm attempting to reproduce this build failure over at PR https://github.com/Linuxbrew/homebrew-core/pull/3140
