### ISSUE TITLE
errors while installing `erlang` on `Kubuntu`

### ISSUE THREAD

**Issue by luceat-lux-vestra** [Linuxbrew/homebrew-core#3113]
https://gist.github.com/e0d79906244542abf3a4b7517fd34ce2

I solved first `configure: error: No dtrace utility found.` by install `systemtap-sdt-dev`.
But I can't solve these errors on make phase.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get a new formula that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get a new formula that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare

**Comment by sjackman** [comment]
```
gcc-5  -Werror=undef -Werror=implicit -Werror=return-type  -g  -O3 -fomit-frame-pointer -I/tmp/erlang-20170704-8177-1dyrprz/otp-OTP-20.0/erts/x86_64-unknown-linux-gnu   -fno-tree-copyrename  -D_GNU_SOURCE -DERTS_SMP -DHAVE_CONFIG_H -Wall -Wstrict-prototypes -Wmissing-prototypes -Wdeclaration-after-statement -DUSE_THREADS -D_THREAD_SAFE -D_REENTRANT -DPOSIX_THREADS -D_POSIX_THREAD_SAFE_FUNCTIONS -DERTS_DIRTY_SCHEDULERS   -Ix86_64-unknown-linux-gnu/opt/smp -Ibeam -Isys/unix -Isys/common -Ix86_64-unknown-linux-gnu -Ipcre -Ihipe -I../include -I../include/x86_64-unknown-linux-gnu -I../include/internal -I../include/internal/x86_64-unknown-linux-gnu -c beam/beam_bp.c -o obj/x86_64-unknown-linux-gnu/opt/smp/beam_bp.o
beam/beam_bp.c: In function 'bp_hash_put':
beam/beam_bp.c:1386:5: internal compiler error: Illegal instruction
     if (r > 0.7f) {
     ^
```
https://gist.github.com/anonymous/e0d79906244542abf3a4b7517fd34ce2#file-03-make-L109

**Comment by sjackman** [comment]
Your `penryn` CPU from circa 2007 is missing a CPU instruction that `gcc` is trying to use. This issue has come up once before, and I believe the workaround was to install `gmp` from source.
```sh
brew reinstall -s gmp
```

**Comment by sjackman** [comment]
Duplicate of https://github.com/Linuxbrew/homebrew-core/issues/1683
See also PR https://github.com/Linuxbrew/homebrew-core/pull/1771 which went stale and was not merged.
