### ISSUE TITLE
rustup-init: error: failed to run custom build command for `openssl-sys v0.9.6`

### ISSUE THREAD

**Issue by dant3** [Linuxbrew/homebrew-core#3143]
# Please always follow these steps:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
  brew install rustup
- What happened (include command output)
 build failed, see gist with output
- What you expected to happen
  it compiles & works
- Step-by-step reproduction instructions (by running `brew install` commands)
  brew install rust && brew install rustup

See gist for full output
https://gist.github.com/dant3/8b0d4d15bb9093e53116d78ac58766d9

**Comment by sjackman** [comment]
`rust` unfortunately is not able to build on the CircleCI resource limits of 4 GB of RAM and 2 hours of build time, so I'm not able to replicate this issue. A PR to resolve the issue would be most welcome if you're able to figure it out.

**Comment by dant3** [comment]
I'll take a look if I can find a workaround. Unfortunately I'm not familiar with Homebrew development, so making a PR will be tricky.

**Comment by sjackman** [comment]
The docs for users and contributors are up at http://docs.brew.sh
Most of that documentation is relevant to both Homebrew and Linuxbrew.

**Comment by ilovezfs** [comment]
Stupid question: does `depends_on "openssl"` fix it?

**Comment by dant3** [comment]
@ilovezfs seems like adding `depends_on "openssl"` helps indeed

**Comment by sjackman** [comment]
Would you like to submit a PR to add `depends_on "openssl"` to `rustup-init`?

**Comment by dant3** [comment]
Sure, just created #3668
