### ISSUE TITLE
flac failed to build on slackware -current

### ISSUE THREAD

**Issue by MarioMaster100** [Linuxbrew/homebrew-core#317]
I was trying to install moc via brew install moc and it failed to build flac. Log: https://gist.github.com/MarioMaster100/b4d282d44ad68a6bc8db16d93c6d43ca

**Comment by rwhogg** [comment]
From https://gist.github.com/MarioMaster100/b4d282d44ad68a6bc8db16d93c6d43ca#file-02-make-L2-L699

```
/usr/bin/ginstall: cannot remove '/usr/lib64/xmms/Input/libxmms-flac.so': Permission denied
```

Looks like it's not determining the installation prefix correctly, even though HOMEBREW_PREFIX is /home/todd/.linuxbrew

**Comment by MarioMaster100** [comment]
Alright well I was actually trying to install ncmpcpp but the error was on flac. This time before I did brew install ncmpcpp I did [code]export HOMEBREW_PREFIX=/home/todd/.linuxbrew[/code] and now I have this error [code]Error: The selected compiler doesn't support C++11: gcc
[/code]

**Comment by rwhogg** [comment]
I'm attempting to bottle both `moc` and `flac`. With any luck, they won't have any build errors and you'll be able to install them via bottle.

In the meantime I recommend doing `brew install gcc --with-glibc` if possible, rather than relying on the host system's GCC.

I can't see why it would think GCC 5.3 doesn't support C++11 - my apologies.

**Comment by rwhogg** [comment]
`flac` has been bottled. `moc` may take longer, since the `jack` dependency is complaining about Debian's packaging of it, but hopefully that won't affect Slackware :smile_cat:

**Comment by MarioMaster100** [comment]
Ok well gcc --with-glibc doesn't work out. 
`checking for C compiler default output file name... a.out
checking whether the C compiler works... configure: error: in `/tmp/gcc-20160524-6942-1rpggou/gcc-5.3.0/build/x86_64-unknown-linux-gnu/libgomp':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details.
Makefile:18493: recipe for target 'configure-stage1-target-libgomp' failed
make[2]: *** [configure-stage1-target-libgomp] Error 1
make[2]: Leaving directory '/tmp/gcc-20160524-6942-1rpggou/gcc-5.3.0/build'
Makefile:20406: recipe for target 'stage1-bubble' failed
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory '/tmp/gcc-20160524-6942-1rpggou/gcc-5.3.0/build'
Makefile:20726: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2`

**Comment by sjackman** [comment]
Try `brew install gcc`

**Comment by MarioMaster100** [comment]
That worked, but ncmpcpp still won't build

checking whether the C++ compiler works... no
configure: error: in `/tmp/ncmpcpp-20160531-31239-1ko5mdx/ncmpcpp-0.7.3':
configure: error: C++ compiler cannot create executables
See `config.log' for more details

**Comment by sjackman** [comment]
Please report `brew gist-logs ncmpcpp`

**Comment by sjackman** [comment]
Superseded by #370
