### ISSUE TITLE
Postinstalling python3 fails: Input/output error

### ISSUE THREAD

**Issue by albertz** [Linuxbrew/homebrew-core#3218]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

[Gist-logs here](https://gist.github.com/anonymous/467227a7c6558ef8c5717fddebb0d24a).

To help us debug your issue please explain:
- What you were trying to do (and why)

`brew install python3`. That went mostly through, except the post-installation.
Then I just did (repeatedly, at least 4 times) `brew postinstall python3`.

- What happened (include command output)

That always fails with:
```
$ brew postinstall python3
==> Postinstalling python3
==> /u/zeyer/.linuxbrew/Cellar/python3/3.6.1/bin/python3 -s setup.py --no-user-cfg install --f
Last 15 lines from /u/zeyer/.cache/Homebrew/Logs/python3/post_install.01.python3:
byte-compiling /u/zeyer/.linuxbrew/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/__about__.py to __about__.cpython-36.pyc
byte-compiling /u/zeyer/.linuxbrew/lib/python3.6/site-packages/pkg_resources/extern/__init__.py to __init__.cpython-36.pyc
running install_egg_info
running egg_info
writing setuptools.egg-info/PKG-INFO
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
writing requirements to setuptools.egg-info/requires.txt
writing top-level names to setuptools.egg-info/top_level.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'setuptools/_vendor'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
Copying setuptools.egg-info to /u/zeyer/.linuxbrew/lib/python3.6/site-packages/setuptools-32.2.0-py3.6.egg-info
error: [Errno 5] Input/output error: '/u/zeyer/.linuxbrew/lib/python3.6/site-packages/setuptools-32.2.0-py3.6.egg-info/requires.txt'
```
https://gist.githubusercontent.com/anonymous/467227a7c6558ef8c5717fddebb0d24a/raw/5e3a3ec92966d23a627e8c1354ed7788a5d38f56/post_install.01.python3

- What you expected to happen

No error.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install python3`

---

I'm not sure if this is this is related to Homebrew/Linuxbrew, although all other things so far installed without problems. The installation destination directory is on a NFS share - maybe that causes the problem somehow. But I'm not able to reproduce the problem by hand. E.g. this succeeds:

    echo "hello" >> /u/zeyer/.linuxbrew/lib/python3.6/site-packages/setuptools-32.2.0-py3.6.egg-info/requires.txt

It would be more helpful to see the stacktrace when this IO error happens, so that I can debug this further and try to reduce it to a simple test case.

---

My current workaround for this problem: As I need setuptools and pip, I just installed it via the bootstrap script, i.e. I did:
```
wget https://bootstrap.pypa.io/ez_setup.py
python3 ez_setup.py --user
easy_install-3.6 --user pip
```

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `python3`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
I'm afraid that I haven't run into this particular error message before. To aid your troubleshooting with a stack trace, try…
```sh
brew postinstall python3 -dv
```
`-d` for `debug` and `-v` for verbose.

**Comment by albertz** [comment]
Did you mean `$HOME/.linuxbrew/`? I actually have it installed there but this is a symlink. I reported that a while ago [here](https://github.com/Linuxbrew/legacy-linuxbrew/issues/681). I cannot really put the files on my home-FS because we have a very strict and very low quota there.

**Comment by sjackman** [comment]
I meant specifically `/home/linuxbrew/.linuxbrew`. If it's an option for you, you could open a ticket with your systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew` for the purpose of sharing software that is used by your group.

**Comment by sjackman** [comment]
Getting back to your original `postinstall` error, to troubleshoot try
```sh
brew postinstall python3 -dv
```
