### ISSUE TITLE
emacs failing to buil in linuxbrew

### ISSUE THREAD

**Issue by rambalachandran** [Linuxbrew/homebrew-core#328]
# Please follow the general troubleshooting steps first:

- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs  emacs --with-cocoa --with-gnutls`
(where `<formula>` is the name of the formula that failed to build).
The gist-logs is available at https://gist.github.com/anonymous/dcedbec04985227cbb6487f265dd053e

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by rwhogg** [comment]
Hi @rambalachandran - are you trying to build the Cocoa UI? That only works on OS X.

**Comment by rambalachandran** [comment]
So whats the GUI for emacs in linux. Just installing emacs only opens it inside the terminal

**Comment by rwhogg** [comment]
> Oops my bad.
No worries!

Please pass the option `--with-x11` when installing Emacs if you want the GUI.

If you have any build failures after this happens, also try doing this and then retrying:

```
brew install linuxbrew/xorg/xorg
```

**Comment by rambalachandran** [comment]
Yup that worked. Awesome Thanks.
