### ISSUE TITLE
Packages with a hdf5 dependency no longer install

### ISSUE THREAD

**Issue by andrewyatz** [Linuxbrew/homebrew-core#3294]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

Over the weekend hfd5 was moved from `homebrew/science` into `homebrew/core` as shown here https://github.com/Homebrew/homebrew-science/commit/745ed551833fa1268c405af7eebaa1f97ae2e8c8 and https://github.com/Homebrew/homebrew-core/commit/572c470a149b7873e55f834a2566849d541123cf by @MikeMcQuaid. I now get the following error:

```bash
$ brew install -vd sratoolkit
==> Installing sratoolkit from homebrew/science
Error: stack level too deep
/usr/share/ruby/pathname.rb:48
```

The issue is limited to those formulas depending on `hdf5` existing as a formula. Neither the tapped `homebrew-science` and `Linxbrew/homebrew-core` have a hdf5 formula present. 

Hope someone can help.

**Comment by sjackman** [comment]
Sorry for this breakage, Andrew. We'll get it fixed up just as soon as we can, today or tomorrow hopefully.

**Comment by sjackman** [comment]
A workaround in the mean time to install `hdf5` is:
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-science/c1e773df259eb6bcb841f38a33cf63e0f31ece4a/hdf5.rb
```

**Comment by andrewyatz** [comment]
Much appreciated @sjackman and thanks for picking up on the issue so quickly :+1:

**Comment by andrewyatz** [comment]
This has gone in now so I'll close the issue
