### ISSUE TITLE
wrk fails to build on ubuntu 16.04

### ISSUE THREAD

**Issue by mercer** [Linuxbrew/homebrew-core#3303]
Please see https://gist.github.com/mercer/cbdafa0376bb671bd4dbad8d37eaefd5

> make[1]: Leaving directory '/tmp/wrk-20170718-14068-6ccxni/wrk-4.0.2/obj/openssl-1.0.2g'
> Makefile:90: recipe for target 'obj/lib/libssl.a' failed
> make: *** [obj/lib/libssl.a] Error 2

` brew gist-logs wrk` gave https://gist.github.com/8844441e5e8b2243236b8c2c01454448

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

**Comment by rwhogg** [comment]
The issue appears to be `../util/domd: 31: ../util/domd: makedepend: not found` at https://gist.github.com/anonymous/8844441e5e8b2243236b8c2c01454448#file-01-make-L468.

Can you try adding 

```ruby
depends_on "makedepend" => :build unless OS.mac?
```

to the formula and see if that fixes it? If it does, would you like to submit a PR containing that change?

**Comment by rwhogg** [comment]
This should be fixed by #3346. Thanks for the bug report!

You should be able to compile `wrk` now.
