### ISSUE TITLE
python postinstall importerror - setuptools

### ISSUE THREAD

**Issue by JonBoyleCoding** [Linuxbrew/homebrew-core#3305]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
[Gist-Log](https://gist.github.com/anonymous/c603610e4551c76203d2df82bcc92255)
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Was installing the neovim package, which installs the python package as a dependency

- What happened (include command output)
The python package fails in it's post-install step brew postinstall python

> brew postinstall python
> ==> Postinstalling python
> ==> /home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --ins
> Last 15 lines from /home/nx902260/.cache/Homebrew/Logs/python/post_install.01.python:
> --install-scripts=/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/bin
> --install-lib=/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages
> 
> Traceback (most recent call last):
>   File "setup.py", line 11, in <module>
>     import setuptools
>   File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/libexec/setuptools/setuptools/__init__.py", line 14, in <module>
>     from setuptools.dist import Distribution, Feature
>   File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/libexec/setuptools/setuptools/dist.py", line 20, in <module>
>     from setuptools import windows_support
>   File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/libexec/setuptools/setuptools/windows_support.py", line 2, in <module>
>     import ctypes
>   File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/ctypes/__init__.py", line 7, in <module>
>     from _ctypes import Union, Structure, Array
> ImportError: /home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/lib-dynload/_ctypes.so: undefined symbol: PyUnicodeUCS2_FromUnicode
> 
> READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
> Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
> 
> These open issues may also help:
> python-dbus 1.2.0 (new formula) https://github.com/Linuxbrew/homebrew-core/pull/1516

- What you expected to happen
No error

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew postinstall python`

The installed python appears to work when running it, but is unable to import the setuptools package. The system installed version of python can import setuptools perfectly fine.

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
See the warnings output by `brew doctor`. Unset the environment variable `LD_LIBRARY_PATH`.
```
Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: :/usr/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
```
https://gist.github.com/anonymous/c603610e4551c76203d2df82bcc92255#file-00-doctor-out-L5-L7
