### ISSUE TITLE
Chromebook (Crouton) crashes while installing rg.

### ISSUE THREAD

**Issue by trusktr** [Linuxbrew/homebrew-core#3327]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

`brew install rg` inside Crouton (Ubuntu LTS 16.04 Xenial, via chroot from my Chromium crosh shell)

- What happened (include command output)

It hangs on a make command, then eventually my Samsung Chromebook Pro browser tabs crash (out of memory) and finally the OS crashes and restarts after a while.

Seems like this happens while building Rust.

- What you expected to happen

I just want to have ripgrep.

- Step-by-step reproduction instructions (by running `brew install` commands)

brew install rg 

---

I'll provide more info once I get back to the machine. It just seems like the install process has to do sooooooo much just to install ripgrep. Maybe ripgrep can be installed as a binary rather than built from source (including building Rust).

For now, I think I will download a pre=built binary and plop into my filesystem, but this obviously isn't ideal (I will loose track of what I've installed if I do everything that way).

**Comment by trusktr** [comment]
There's not really a problem here, just that it seems the install prcess is too heavy for the poor little Chromebook Pro. I don't have experience making bottles. Maybe it is easy to modify rg to be binary install?

**Comment by sjackman** [comment]
We build bottles on CircleCI, and unfortunately we're not able to build `rust` in the 4 GB memory limit or the 2 hour time limit of CircleCI. See PR https://github.com/Linuxbrew/homebrew-core/pull/1953
If you have any ideas on how to make `rust` build faster, I'd very much appreciate a PR to resolve this situation.
Here's two old PRs related to `ripgrep`: #1762 #1997
