### ISSUE TITLE
mpfr: deprecated call used

### ISSUE THREAD

**Issue by tilda** [Linuxbrew/homebrew-core#3334]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new (yes - this is related to a specific formula)
- [x] Ran `brew update` and retried your prior step? (was up to date)
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? (only produced untapped libs that I installed on purpose)
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (this is irrelevant to the issue at hand)
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? (irrelevant)

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

-----------------

- Was trying to compile GCC

```
==> Installing gcc dependency: mpfr
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/m/mpfr4/mpfr4_3.1.5.orig.tar.xz
######################################################################## 100.0%
Warning: Calling build.build_32_bit? is deprecated!
There is no replacement.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb:30:in `install'
Please report this to the homebrew/core tap!
```

- mpfr should go through with no warnings present

- `brew install gcc`, wait until it gets to mpfr dependency, right after downloading and configuring it emits a warning

**Comment by sjackman** [comment]
This issue has been resolved upstream in Homebrew and will be merged into Linuxbrew.
https://github.com/Homebrew/homebrew-core/commit/6dc8fddd0fa226aea797b8bd2391ef467bf0ed3b

**Comment by bryaan** [comment]
Still a problem?

```
==> Installing mpfr
==> Downloading https://ftp.gnu.org/gnu/mpfr/mpfr-4.0.0.t
Already downloaded: /home/bryan/.cache/Homebrew/mpfr-4.0.0.tar.xz
Warning: Calling build.build_32_bit? is deprecated!
There is no replacement.
/home/bryan/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb:21:in `install'
Please report this to the homebrew/core tap!

==> ./configure --prefix=/home/bryan/.linuxbrew/Cellar/mp
==> make
==> make check
Last 15 lines from /home/bryan/.cache/Homebrew/Logs/mpfr/03.make:
# SKIP:  0
# XFAIL: 0
# FAIL:  180
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/tmp/mpfr-20180112-14143-1ev8hfo/mpfr-4.0.0/tests'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/tmp/mpfr-20180112-14143-1ev8hfo/mpfr-4.0.0/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/tmp/mpfr-20180112-14143-1ev8hfo/mpfr-4.0.0/tests'
make: *** [check-recursive] Error 1
```

**Comment by iMichka** [comment]
I opened a pull request to cleanup the cruft which was probably wrongly committed during one of the merges: #5536

For the make test failing, I have no clue what is going on. The log file does not really help ... Please open a new issue for that (and fill out the full issue template). Thanks.
