### ISSUE TITLE
suite-sparse.rb is not in Linuxbrew Core

### ISSUE THREAD

**Issue by andrewyatz** [Linuxbrew/homebrew-core#3359]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to install Augustus, which depends on `suite-sparse`

- What happened (include command output)

Reported that the formula `suite-sparse.rb` is not in Linuxbrew. This is in homebrew's version of `homebrew-core`. Could this be brought across.

**Comment by sjackman** [comment]
Thanks for the bug report, Andrew. Some formulae are currently being moved from Homebrew/science to Homebrew/core, and we're a bit behind in merging these formulae in from Homebrew/core to Linuxbrew/core. We're working on it, and sorry for the delay.

**Comment by sjackman** [comment]
I've opened a tracking issue at https://github.com/Linuxbrew/homebrew-core/issues/3374
