### ISSUE TITLE
glibc install failed because etc/ld.so.conf not found

### ISSUE THREAD

**Issue by sandeep-gh** [Linuxbrew/homebrew-core#3361]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
The output of brew doctor
```
Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: /home/sandeep/easybuild/software/shadowfax-westmere/binutils/2.28-GCCcore-7.1.0/lib:/home/sandeep/easybuild/soft\
ware/shadowfax-westmere/GCCcore/7.1.0/lib/gcc/x86_64-pc-linux-gnu/7.1.0:/home/sandeep/easybuild/software/shadowfax-westmere/GCCcore\
/7.1.0/lib64:/home/sandeep/easybuild/software/shadowfax-westmere/GCCcore/7.1.0/lib:/cm/shared/apps/torque/4.2.10/lib/:/usr/lpp/mmfs\
/lib

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /cm/shared/apps/torque/4.2.10/bin/pbs-config
```
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
https://gist.github.com/9f7c5792b769adfe7da4c83488bfdfc1
```
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install glibc and gcc.

- What happened (include command output)
Installation failed. When invoked with verbose mode following message/error was reported:
```
rm -f /tmp/glibc-20170727-29593-1pxoujp/glibc-2.19/build/stubs.h
/tmp/glibc-20170727-29593-1pxoujp/glibc-2.19/build/elf/sln /tmp/glibc-20170727-29593-1pxoujp/glibc-2.19/build/elf/symlink.list
rm -f /tmp/glibc-20170727-29593-1pxoujp/glibc-2.19/build/elf/symlink.list
test ! -x /tmp/glibc-20170727-29593-1pxoujp/glibc-2.19/build/elf/ldconfig || LC_ALL=C LANGUAGE=C \
  /tmp/glibc-20170727-29593-1pxoujp/glibc-2.19/build/elf/ldconfig  \
       /home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Cellar/glibc/2.19/lib /home/sandeep/NDSSL-Software/install_t\
ensorflow_using_brew/brew/Cellar/glibc/2.19/lib
/tmp/glibc-20170727-29593-1pxoujp/glibc-2.19/build/elf/ldconfig: Warning: ignoring configuration file that cannot be opened: /home/\
sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Cellar/glibc/2.19/etc/ld.so.conf: No such file or directory
make[1]: Leaving directory `/tmp/glibc-20170727-29593-1pxoujp/glibc-2.19'
Error: Failure while executing: [#<Pathname:/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Cellar/glibc/2.19/bin/l\
dd>, "/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Cellar/glibc/2.19/bin/gencat"]
```

- Step-by-step reproduction instructions (by running `brew install` commands)
After cloning brew and setting up the right PATH, LD_LIB* variables, executed following commands:
```
brew update
brew install hello
brew install glibc
```

It seems like glibc gives out warning about /etc/ld.conf.so not found, which brew is interpreting as hard failure.

**Comment by rwhogg** [comment]
Sorry to hear you're having trouble @sandeep-gh!

> After cloning brew and setting up the right PATH, LD_LIB* variables, executed following commands:

I wouldn't recommend setting LD_LIBRARY_PATH as it can cause substantial problems. If you need it for some other software you have to run, I'd recommend at least temporarily unsetting it when installing software through Linuxbrew.

I'd also recommend installing Linuxbrew in /home/linuxbrew/.linuxbrew if possible, as it will allow you to use a precompiled version of `glibc` and may allow you to avoid the problem you're experiencing.

You mentioned in one of your closed issues that using HOMEBREW_CC was causing brew to complain; can you say what the error was?

Finally, I noticed that you're using a SUSE operating system; once you get this working I'd welcome any feedback about it as we don't have SUSE-specific installation steps on our homepage.

**Comment by sandeep-gh** [comment]
Thanks for taking a look.
 
for HOMEBREW_CC, I get following errors:
```
==> Installing glibc
Error: Invalid value for HOMEBREW_CC: gcc
```
I am not able to use /home/linuxbrew/.linuxbrew as I am on a cluster. 

Even after unsetting the LD_LIBRARY_PATH, I get the same issue. 

For workaround, is there anyway to direct brew to not delete the temporary files. 
I can manually create te /etc/ld.so.conf and resume compile/install and that might 
fix the problem. 

I think this is the issue at hand (from http://www.linuxfromscratch.org/lfs/view/development/chapter06/glibc.html):
```
 Though it is a harmless message, the install stage of Glibc will complain about the absence of /etc/ld.so.conf. Prevent this warning with:

touch /etc/ld.so.conf
```

**Comment by rwhogg** [comment]
> Error: Invalid value for HOMEBREW_CC: gcc

For HOMEBREW_CC, it has to be given as "gcc-4.x" or "gcc-y", so "gcc-4.5" or "gcc-7" for example.

> For workaround, is there anyway to direct brew to not delete the temporary files.
I can manually create te /etc/ld.so.conf and resume compile/install and that might
fix the problem.

You can try `brew install --keep-tmp glibc`.

Another thing you may wish to try is `brew install --debug glibc`. When it fails, you'll be brought to a menu; choose option 2 ("ignore") to allow the installation to continue.

**Comment by sjackman** [comment]
See the output of `brew doctor`
```
Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: /home/sandeep/easybuild/software/shadowfax-westmere/binutils/2.28-GCCcore-7.1.0/lib:/home/sandeep/easybuild/software/shadowfax-westmere/GCCcore/7.1.0/lib/gcc/x86_64-pc-linux-gnu/7.1.0:/home/sandeep/easybuild/software/shadowfax-westmere/GCCcore/7.1.0/lib64:/home/sandeep/easybuild/software/shadowfax-westmere/GCCcore/7.1.0/lib:/cm/shared/apps/torque/4.2.10/lib/:/usr/lpp/mmfs/lib
```
If you're still seeing a build failure after `unset LD_LIBRARY_PATH`, please post a gist of the new build.

**Comment by sandeep-gh** [comment]
I tried ```brew install -v --debug glibc```, but for some reason 
it didn't return to prompt after failure and didn't keep the glibc files in Cellar directory.
So, I couldn't do the fix of manually create ld.conf.so file. 
 

HOMEBREW_CC is now set to gcc-7 and LD_LIBRARY_PATH is unset. 
gist is posted at https://gist.github.com/36f512f4b05fb0d0086d2540cfd13871

**Comment by sjackman** [comment]
```
/tmp/glibc-20170729-689-6qi4ca/glibc-2.19/build/elf/ldconfig: Warning: ignoring configuration file that cannot be opened: /home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Cellar/glibc/2.19/etc/ld.so.conf: No such file or directory
```
I think that warning is innocuous and can be ignored.

**Comment by sjackman** [comment]
I don't see an error message in that gist. It looks to me as though `glibc` installed correctly. What's printed at the terminal after `brew install glibc` ?

**Comment by sjackman** [comment]
How did you install GCC 7?

**Comment by sandeep-gh** [comment]
Below is output of installing gcc which first tries to install glibc. I get the same error as before:

```
brew install gcc
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
artifactory        cmake              gtk+3              jdk                mysql-sandbox      pioneer            v8@3.15
assimp             gdk-pixbuf         harfbuzz           jhipster           osc                rocksdb            wireshark

==> Installing dependencies for gcc: glibc, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: glibc
==> Downloading https://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
Already downloaded: /home/sandeep/.cache/Homebrew/glibc-2.19.tar.bz2
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/sandeep/NDSSL-Software/install_
==> make
==> make install
Error: Failure while executing: [#<Pathname:/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Cellar/glibc/2.19/bin/ldd>, "/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Cellar/glibc/2.19/bin/gencat"] 
```

Installed gcc-7 using easybuild.

**Comment by sjackman** [comment]
Does `brew install -d glibc` give you the interactive option of starting a shell?

**Comment by sandeep-gh** [comment]
```brew install -d glibc``` doesn't give me a shell prompt. Below is the output snippet:

```
==> Kept temporary files
Temporary files retained at /tmp/glibc-20170730-29564-197wpow
Error: Failure while executing: [#<Pathname:/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Cellar/glibc/2.19/bin/ldd>, "/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Cellar/glibc/2.19/bin/gencat"] 
/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Library/Homebrew/debrew.rb:11:in `raise'
/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Library/Homebrew/os/linux/elf.rb:58:in `initialize'
/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Library/Homebrew/os/linux/elf.rb:99:in `new'
/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Library/Homebrew/os/linux/elf.rb:99:in `metadata'
/home/sandeep/NDSSL-Software/install_tensorflow_using_brew/brew/Library/Homebrew/os/linux/elf.rb:110:in `dynamically_linked_libraries'
...
...
````

**Comment by sandeep-gh** [comment]
Any closing suggestion/ideas on regarding  as to prevent brew from deleting files in Cellar on warning.
If not, then I will abandon this approach. 

I guess alternative is to compile glibc/gcc outside of brew and set HOMEBREW_CC accordingly.

**Comment by sjackman** [comment]
It's difficult to troubleshoot since I'm not able to reproduce the issue myself. If you're able to reproduce this issue inside a Docker container of `SUSE Linux Enterprise Server 11`, it'd be a great help, because we could then debug the issue.

A workaround for you that may help you get `glibc` installed is to comment-out or delete the following line:
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/os/linux/elf.rb#L58
```ruby
raise ErrorDuringExecution, command unless $CHILD_STATUS.success?
```

**Comment by nickjhathaway** [comment]
So I have a related problem in that glibc is failing to install but for a different issue. The only problem I can find is the following message when running 

```
brew install glibc -v 
```

```
setenv.c: In function ‘__unsetenv’:
setenv.c:279:6: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
   if (ep != NULL)
      ^
```

gist here https://gist.github.com/anonymous/989d3ffe6b983a4d0d1c85914d6d0e3b 

A confounding problem I'm running into is that when I run 

```
brew install glibc -v -d
```

I choose the option to ignore since this is just an error about dangerous syntax in glibc but when I choose ignore I get the following error from brew 

```
FormulaUnavailableError: No available formula with the name "xorg" 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 2
/data/home/hathawan/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:25:in `formula_version'
NoMethodError: undefined method `linked_version' for nil:NilClass
1. raise
2. backtrace
3. shell

```

So there seems to be a problem in getting brew to choose the ignore problem. 

But anyways an easy work around is using an older gcc than gcc7 since this warning is a new one
So using the below command here I was able to avoid the warning which was being treated as an error to get glibc to install 

```
HOMEBREW_CC=gcc-5 brew install glibc
```
 
I am posting here since this issue is referenced when glibc failed to install for me and so hopefully this helps anyone who comes across a similar issue and is directed here

**Comment by sjackman** [comment]
Thanks for the workaround, Nick! You could if you liked open a PR to add…
```ruby
# Fix setenv.c:279:6: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
fails_with :gcc => "7"
```
