### ISSUE TITLE
Graphviz compile issue. Wrong libgd.so is linked when compiling dot

### ISSUE THREAD

**Issue by andrewyatz** [Linuxbrew/homebrew-core#3366]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to install graphviz on a non-home installation of Linuxbrew

- What happened (include command output)

When compiling the code moves to building the `dot` binary. All libraries up until this point have compiled fine. When starting the `dot` build the following is emitted

```
make[3]: Entering directory `/tmp/graphviz-20170728-46453-1jhk8tb/graphviz-2.40.1/cmd/dot'
  CC       dot_builtins-dot.o
  CC       dot-dot.o
  CC       dot-no_builtins.o
  CC       dot_builtins-dot_builtins.o
dot.c: In function 'intr':
dot.c:43:22: warning: unused parameter 's' [-Wunused-parameter]
 static void intr(int s)
                      ^
dot.c: In function 'intr':
dot.c:43:22: warning: unused parameter 's' [-Wunused-parameter]
 static void intr(int s)
                      ^
  CCLD     dot_builtins
  CCLD     dot
/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/bin/ld: warning: libjpeg.so.62, needed by /usr/lib64/libgd.so, not found (try using -rpath or -rpath-link)
/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/bin/ld: warning: libpng15.so.15, needed by /usr/lib64/libgd.so, not found (try using -rpath or -rpath-link)
/usr/lib64/libgd.so: undefined reference to `png_get_rowbytes@PNG15_0'
/usr/lib64/libgd.so: undefined reference to `png_write_image@PNG15_0'
/usr/lib64/libgd.so: undefined reference to `png_set_strip_16@PNG15_0'
```

There's also a lot more, which you can see in the gist logs from https://gist.github.com/0fb4545ca73dbd5ac12338f940fbe9ae. 

What I don't quite understand is that for some reason graphviz has decided to use `/usr/lib/libgd.so` rather than `$LINUXBREW_HOME/lib/libgd.so`. A quick `ldd` of the linuxbrew gd library shows that it's been compiled correctly.

```
$ ldd /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libgd.so
        linux-vdso.so.1 (0x00007fff167fe000)
        libm.so.6 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libm.so.6 (0x00007efdc9ee1000)
        libz.so.1 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libz.so.1 (0x00007efdc9ccb000)
        libpng16.so.16 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libpng16.so.16 (0x00007efdc9a97000)
        libfontconfig.so.1 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libfontconfig.so.1 (0x00007efdc9853000)
        libfreetype.so.6 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libfreetype.so.6 (0x00007efdc95ac000)
        libjpeg.so.8 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libjpeg.so.8 (0x00007efdc937a000)
        libtiff.so.5 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libtiff.so.5 (0x00007efdc9103000)
        libwebp.so.7 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libwebp.so.7 (0x00007efdc8eb3000)
        libc.so.6 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libc.so.6 (0x00007efdc8b08000)
        libexpat.so.1 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libexpat.so.1 (0x00007efdc88db000)
        libpthread.so.0 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libpthread.so.0 (0x00007efdc86bd000)
        libbz2.so.1.0 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libbz2.so.1.0 (0x00007efdc84ab000)
        /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/glibc/2.19/lib64/ld-linux-x86-64.so.2 (0x00007efdca444000)
        libbsd.so.0 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/libbsd.so.0 (0x00007efdc8298000)
        librt.so.1 => /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/lib/librt.so.1 (0x00007efdc808f000)
```

I'm assuming that somehow `/usr/lib64` is taking a higher precedence on pkg-config somehow than the Linxbrew directories but this just seems a bit odd TBH. Any help is appreciated.

- What you expected to happen

Graphviz would install.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install graphviz --with-pango`

The error appears even without the pango bindings coming in.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `graphviz`.
Another possible workaround for you is `brew install --force-bottle graphviz`, but no promises.

**Comment by sjackman** [comment]
That sounds like a bug. As a workaround, if you have sudo on the box, I'd suggest removing the package that provides `gd.so`, perhaps named something like `graphviz-devel`.

I likely won't have time to tackle this issue myself real soon. A PR would be very welcome if you're able to find a solution to this issue. I'd suggest checking the build logs for an offending line that looks like `-L/usr/lib`

**Comment by andrewyatz** [comment]
Unfortunately my install requires me to compile to a non-default location for Linuxbrew. Otherwise the bottle would have been a good solution. 

I'll try to force the bottle in and see what happens though once I'm back on a terminal. 

In the mean time if there's any other ideas about how to get graphviz to use the Linuxbrew libs that would be fantastic news (irritatingly as well they've been picked up for pretty much every other part of the installation).

**Comment by andrewyatz** [comment]
Sorry @sjackman our messages crossed over in the clacks! Okay will give it a shot

**Comment by sjackman** [comment]
No worries. Good luck!

**Comment by andrewyatz** [comment]
Just writing an update here. I can't remove the existing `graphviz-devel` package as I don't have root on the system. I did some hunting around and couldn't find any odd/bad use of `-L/usr/lib64` or equivalent. What I did find was `/usr/lib/pkgconfig` was injected into `PKG_CONFIG_LIB` and there is a `gdlib.pc` in that directory (found out by echo'ing ENVs and `pkg-config` information out to screen in the build).

A bit more Googling brought up this old issue https://github.com/Linuxbrew/legacy-linuxbrew/issues/47 and got me looking for where `PKG_CONFIG_LIB` is set. I think superenv is the cause of my issue. https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/ENV/super.rb#L142 sets `/usr/lib/pkgconfig` as the first location to check rather than the standard environment, which sets this as the last option. I'm not totally sure what the use-case behind superenv is (so I won't comment on the order of `PKG_CONFIG_LIB` dirs being a good or bad thing) but specifying `--env=std` works a treat.

**Comment by andrewyatz** [comment]
Sorry when I say standard I mean the Linuxbrew lib dir and I think I was wrong in saying this ever appears on the path in superenv

**Comment by sjackman** [comment]
Yikes! That's a bug, and I'm surprised that it hasn't come up before. Would you like to submit a PR to remove `"/usr/lib/pkgconfig"` from
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/ENV/super.rb#L144
and add it instead to
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/os/mac/extend/ENV/super.rb#L30

**Comment by andrewyatz** [comment]
Sure thing I assume it's a PR going into http://github.com/Homebrew/brew

**Comment by andrewyatz** [comment]
Okay PR nearly there. https://github.com/Homebrew/brew/compare/master...andrewyatz:bugfix/pkgconfiglibdir. Can you take a quick look and make sure that I've done this as you expected

**Comment by sjackman** [comment]
Nearly there. To ensure the previous behaviour as before on macOS, `/usr/lib/pkg-config` should come before `"#{HOMEBREW_LIBRARY}/Homebrew/os/mac/pkgconfig/#{MacOS.version}"`

**Comment by sjackman** [comment]
Resolved by https://github.com/Homebrew/brew/pull/2998
