### ISSUE TITLE
Migrate formulae from Homebrew/science

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/homebrew-core#3374]
These formulae are being migrated from Homebrew/science to Homebrew/core.

- [x] 24550df0ba scalapack
- [x] 40d0219285 octave
- [x] 1b09b47adb suite-sparse
- [x] 498e5aedff arpack
- [x] cdacbf0316 metis
- [x] be49d50988 openblas
- [x] 56ddb73cf2 qrupdate
- [x] 0f6784e54f qhull
- [x] 8f63ea756b glpk
- [x] 5873f07185 veclibfort
- [x] 5e469ac0d7 transfig

**Comment by dpo** [comment]
Is there a point to including `veclibfort` here? Its only purpose is to fix a BLAS-related bug on OSX.

**Comment by iMichka** [comment]
It's just in the list because it has been migrated from science to core, but in fact it is mac only, and has been marked as such in linuxbrew-core (https://github.com/Linuxbrew/homebrew-core/pull/3416).

All the `depends_on "veclibfort" lines in Linux formulae just need to be safeguarded by a "unless OS.mac?" call.

**Comment by andrewyatz** [comment]
I saw that `suite-sparse.rb` is in Linuxbrew core but the formula has changed significantly from the version in homebrew-science and uses macOS frameworks. Not sure of the best way forward to fix that one

**Comment by iMichka** [comment]
The version in science was working, so a diff needs to be made between the core and old science version, and the needed changes need to be done here so we can build bottles. Any help would be welcome :)

**Comment by iMichka** [comment]
In fact there is already a PR open for that here that you can follow: #3452

**Comment by andrewyatz** [comment]
:+1:

**Comment by dpo** [comment]
I opened the PR and wanted opinions about that. What's the policy in linuxbrew/core? Keep the formula similar to what's in homebrew/core, or restore the useful options that were stripped out during the migration?

**Comment by iMichka** [comment]
We keep the same options/functionality. If some were stripped during the migrations and are needed, they need to be added back to homebrew-core. We try to keep the formulae as similar as possible.

**Comment by dpo** [comment]
All done!

**Comment by sjackman** [comment]
Thanks for your help, Dominique!
