### ISSUE TITLE
node: Segmentation fault: Node.js on Ubuntu 16.04

### ISSUE THREAD

**Issue by sholladay** [Linuxbrew/homebrew-core#343]
- [✓] Ran `brew update` and retried your prior step?
- [✓] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [✓] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

[Node.js](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/node.rb) fails to build for me on a brand new Ubuntu 16.04 x64 box from [DigitalOcean](https://www.digitalocean.com/) using a [standalone installation](https://github.com/Linuxbrew/linuxbrew/wiki/Standalone-Installation) of Linuxbrew.

See the output here: https://gist.github.com/sholladay/ebc91f9f9e020d0924c837db3873c0c9

Note that the installed formulae shown by `brew list` are due to the standalone installation procedure.

I ran `brew gist-logs node`, but it did not complete for over half an hour. I eventually cancelled it. That seems suspicious.

As an experiment, I then attempted to `brew install node4-lts` from the homebrew/versions tap and that completed successfully. The official binary also works, but that doesn't tell us very much. I have not tried to compile from source without `brew`.

**Comment by sjackman** [comment]
```
  LD_LIBRARY_PATH=/tmp/node-20160523-9386-nwmcab/node-v6.1.0/out/Release/lib.host:/tmp/node-20160523-9386-nwmcab/node-v6.1.0/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../tools/icu; mkdir -p /tmp/node-20160523-9386-nwmcab/node-v6.1.0/out/Release/obj/gen/icutmp; python icutrim.py -P "/tmp/node-20160523-9386-nwmcab/node-v6.1.0/out/Release" -D ../../deps/icu/source/data/in/icudt56l.dat --delete-tmp -T "/tmp/node-20160523-9386-nwmcab/node-v6.1.0/out/Release/obj/gen/icutmp" -F icu_small.json -O icudt56l.dat -v -L en,root
Segmentation fault (core dumped)
```
https://gist.github.com/sholladay/ebc91f9f9e020d0924c837db3873c0c9#file-gistfile1-txt-L25

**Comment by sjackman** [comment]
It looks to me like `python` is segfaulting? I'm afraid I don't know what to make of this. Sorry that I can't be of more help.
