### ISSUE TITLE
mercurial fails to find python

### ISSUE THREAD

**Issue by VonUniGE** [Linuxbrew/homebrew-core#3451]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ]  If brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

After installing `mercurial`, running `hg` gives:
```
bash: /home/linuxbrew/.linuxbrew/bin/hg: /home/linuxbrew/.linuxbrew/bin/python: bad interpreter: No such file or directory
```
The first line of  `/home/linuxbrew/.linuxbrew/bin/hg` is:
```
#!/home/linuxbrew/.linuxbrew/bin/python
```
but python is now installed at:
```
/home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python
```
On macOS, the first line of `/usr/local/bin/hg` is:
```
#!/usr/local/opt/python/bin/python2.7
```
which is correct.

**Comment by rwhogg** [comment]
Thanks for the bug report @VonUniGE! I've opened #3455 which should resolve this.

**Comment by rwhogg** [comment]
This should work now after you upgrade `mercurial`. Thanks again for the report!
