### ISSUE TITLE
can anyone fix gcc@6 and add gcc@7?

### ISSUE THREAD

**Issue by buaasun** [Linuxbrew/homebrew-core#3461]
can anyone fix gcc@6 and add gcc@7?

**Comment by jonchang** [comment]
Hi @buaasun, I'm not sure what you mean by fixing `gcc@6`. Could you please open a new issue and fill out the [issue template](https://github.com/Linuxbrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE.md) this time so we know exactly what problem you're encountering? Thanks!
