### ISSUE TITLE
install gcc@6 or gcc@7 failed

### ISSUE THREAD

**Issue by buaasun** [Linuxbrew/homebrew-core#3523]
# template steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
for gcc@6:  https://gist.github.com/e823196fbf6e9dbbe8e47715dbf58354
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
# my problems
## gcc@6
when I install gcc@6 by `brew install gcc@6`, it fails.  the gist-logs link is 
 https://gist.github.com/e823196fbf6e9dbbe8e47715dbf58354
## gcc@7
when I install gcc@7 by `brew install gcc@7`, it actually installs gcc 5.3, this is because gcc@7 is an alias of gcc, and gcc's current version is 5.3.

**Comment by sjackman** [comment]
I'm afraid that Linuxbrew does not currently support `gcc@6` or `gcc@7`. A pull request would be welcome if you have the time and inclination to submit one.
