### ISSUE TITLE
brew path interfering with system path

### ISSUE THREAD

**Issue by MarioMaster100** [Linuxbrew/homebrew-core#353]
I can't run steam or playonlinux because of brew's pythonpath and libc. How do I fix this?

**Comment by rwhogg** [comment]
I run into this problem occasionally too (albeit not with steam or playonlinux).

The trick I use is to run the program I want directly under `/usr/bin/python`, like this (the program it happens most frequently for with me is `meld`, so I'll use that as an example):

```bash
$ /usr/bin/python /usr/bin/meld
```

If there's a specific Python file that always fails like this for you, you can edit it directly:

```diff
- #!/usr/bin/env python
+ #!/usr/bin/python
```

**Comment by MarioMaster100** [comment]
Well unfortunately playonlinux is not a python program but it does need wxpython which it can't find because it's looking in ~/.linuxbrew/ which is not where that is installed to. I have tried PYTHONPATH=$PTHONPATH:/usr/lib64/python2.7/site-packages and then run playonlinux but it still can't find it because of brew. Steam is always looking for libc.so.6 and I've tried export LD_LIBRARY_PATH=/usr/lib64/libc.so.6 before I run steam and it's the same error every time. I've made a test user and it loads playonlinux and steam fine because it doesn't have the brew path. I'd rather not have 2 copies of my playonlinux and steam games just so I can use them though.

**Comment by rwhogg** [comment]
Can you show the error messages that occur for `playonlinux` and `steam` respectively? That would make it far easier to debug.

You can try using the environment variable `PYTHONHOME` instead of `PYTHONPATH` (note that I've never tried this myself); see `man python` for how to do so.

Unfortunately, `wxpython` doesn't build correctly on Linux at the moment, but I know how to fix it - I'll try to do so this weekend.

**Comment by rwhogg** [comment]
See https://github.com/Linuxbrew/homebrew-core/issues/130

**Comment by MarioMaster100** [comment]
I have wxpython properly installed on slackware from slackbuilds.org. Here's the steam error `steam
/home/todd/.steam/steam.sh: line 622:  6243 Segmentation fault      "$STEAMDEPS" $STEAMROOT/steamdeps.txt
Running Steam on slackware 14.2 64-bit
STEAM_RUNTIME is enabled automatically
Error: You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
ERROR: ld.so: object '/lib64/libc.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
Installing breakpad exception handler for appid(steam)/version(1461972496)
[2016-05-27 16:46:42] Startup - updater built Apr 29 2016 22:18:33
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2016-05-27 16:46:42] Checking for update on startup
[2016-05-27 16:46:42] Checking for available updates...
[2016-05-27 16:46:43] Download skipped: /client/steam_client_ubuntu12 version 1461972496, installed version 1461972496
[2016-05-27 16:46:43] Nothing to do
[2016-05-27 16:46:43] Verifying installation...
[2016-05-27 16:46:43] Performing checksum verification of executable files
[2016-05-27 16:46:43] Verification complete
[2016-05-27 16:46:45] Shutdown`

the playonlinux error is
` playonlinux
Looking for python... 2.7.11 - Traceback (most recent call last):
  File "/usr/share/playonlinux/python/check_python.py", line 1, in <module>
    import os, wxversion
ImportError: No module named wxversion
failed tests
Looking for python2.7... 2.7.11 - Traceback (most recent call last):
  File "/usr/share/playonlinux/python/check_python.py", line 1, in <module>
    import os, wxversion
ImportError: No module named wxversion
failed tests
Looking for python2.6... which: no python2.6 in (/home/todd/.linuxbrew/bin:/home/todd/.linuxbrew/bin:/usr/bin/32:/home/todd/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lib64/java/bin:/usr/lib64/java/jre/bin:/usr/lib64/qt/bin:/usr/share/texmf/bin:/usr/lib64/java/bin:/usr/lib64/java/jre/bin:/usr/bin/32)

Looking for python2... 2.7.11 - Traceback (most recent call last):
  File "/usr/share/playonlinux/python/check_python.py", line 1, in <module>
    import os, wxversion
ImportError: No module named wxversion
failed tests
Please install python before trying to run this program`

I have both python 2.7.11 and wxPython 2.8.12 installed on slack in their regular system locations for slackware.

**Comment by rwhogg** [comment]
Can you try running `PYTHONHOME=/usr playonlinux` and report the output here? Thanks a bunch!

Also, just an FYI, Github prefers three backticks ("```") when doing multiline quoting.

**Comment by MarioMaster100** [comment]
`PYTHONHOME=/usr playonlinux
Looking for python... 2.7.11 - ImportError: No module named site
failed tests
Looking for python2.7... 2.7.11 - ImportError: No module named site
failed tests
Looking for python2.6... which: no python2.6 in (/home/todd/.linuxbrew/bin:/home/todd/.linuxbrew/bin:/usr/bin/32:/home/todd/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lib64/java/bin:/usr/lib64/java/jre/bin:/usr/lib64/qt/bin:/usr/share/texmf/bin:/usr/lib64/java/bin:/usr/lib64/java/jre/bin:/usr/bin/32)

Looking for python2... 2.7.11 - ImportError: No module named site
failed tests
Please install python before trying to run this program`

**Comment by rwhogg** [comment]
My bad - the `ImportError: No module named site` error probably means PYTHONHOME is incorrect.

I've never used Slackware, so I'm not sure where the Python libraries are installed by default on that distribution, but you may be able to get this to work by trying different values for PYTHONHOME. One possibility: remove Homebrew's directories from your PATH, do `which python`, and remove "bin/python" from the end.

I apologize, but I'm not going to be able to debug this further tonight. I can still answer questions tomorrow though.

**Comment by MarioMaster100** [comment]
Ok well after removing ~/.linuxbrew and related from the path it runs playonlinux right. I'm getting an error from playonlinux when I try to run something but I'm pretty sure that's a playonlinux issue and not related to the previous issue. Steam also runs fine after removing that stuff from my path. I guess I'll just stick to running brew things from a script pointing to ~/.linuxbrew/bin if I need to run something from brew.

**Comment by rwhogg** [comment]
> I guess I'll just stick to running brew things from a script pointing to ~/.linuxbrew/bin if I need to run something from brew.

Sorry, all I meant by "remove Homebrew's directories from your PATH" was to do so *so you could figure out what PYTHONHOME needs to be set to*. I suspect that once you get PYTHONHOME correct, it should not be necessary to remove `brew` from the path.

**Comment by sjackman** [comment]
You could if you wanted put `~/.linuxbrew/bin` at the end of your PATH after `/usr/bin`.
