### ISSUE TITLE
llvm: clang installed from linuxbrew is not able to link binary executable

### ISSUE THREAD

**Issue by mikeandmore** [Linuxbrew/homebrew-core#360]
I installed clang and gcc-5 from linuxbrew. gcc-5 is able to work flawlessly. However, when trying to use clang, I always get this error.

```
/home/mike/.linuxbrew/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib64/libstdc++.so: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
```

After I ran -v with clang, I spotted this error.

```
 "/home/mike/.linuxbrew/bin/ld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o server-sample /lib/../lib64/crt1.o /lib/../lib64/crti.o /home/mike/.linuxbrew/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/crtbegin.o -L/home/mike/.linuxbrew/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0 -L/home/mike/.linuxbrew/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/home/mike/.linuxbrew/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../.. -L/home/mike/.linuxbrew/Cellar/llvm/3.6.2/bin/../lib -L/lib -L/usr/lib /tmp/gopp-15b2c0.o /tmp/epoll-channel-e67418.o /tmp/server-sample-7fa3a6.o -lpthread -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /home/mike/.linuxbrew/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/crtend.o /lib/../lib64/crtn.o
/home/mike/.linuxbrew/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib64/libstdc++.so: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
```

Notice that there is a `-dynamic-linker /lib64/ld-linux-x86-64.so.2` in the linker flag. This means, it will always link with the base system's glibc, which in my case, it's a glibc-2.17. Linuxbrew needs glibc-2.19 to run gcc-5.

I wonder, is there a way to tell clang to use the glibc from linuxbrew? I think this should be the default behaviour too.

**Comment by sjackman** [comment]
Hi, Mike. Yes, this is definitely a bug. I'm not terribly familiar with `clang` on Linux though. I fixed up `gcc` to tell it which dynamic loader to use. I'm not sure myself how to do the same for `clang`. I'd appreciate a pull request if you figure it out. Sorry that I couldn't be of more help.

**Comment by mikeandmore** [comment]
@sjackman I can take a look at this bug. Could you give me a pointer on how did you fix this in gcc-5? Thank you!

**Comment by sjackman** [comment]
@maxim-belkin Is quite familiar with LLVM and Clang. He may be helpful.

Here's the code for GCC:
https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/gcc.rb#L273

**Comment by mikeandmore** [comment]
clang doesn't seem to like spec files. I kind of give up on this issue.

I guess the only workaround here would be disable bottle and do not install linuxbrew's glibc.

**Comment by maxim-belkin** [comment]
This issue should be resolved now. Please reopen if you still see this problem with the latest `llvm` formulae.
