### ISSUE TITLE
libiomp: fails to build, missing exports/mac_32e/lib.thin/libiomp5.dylib

### ISSUE THREAD

**Issue by lorenzschmid** [Linuxbrew/homebrew-core#365]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

----

Having not root access to my web host, I wanted to use `linuxbrew` to install `clang`. Unfortunately it fails while installing one of its dependencies, `libiomp`, missing a particular file:

````
brew install clang-omp
==> Installing dependencies for clang-omp: libiomp
==> Installing clang-omp dependency: libiomp
==> Downloading https://www.openmprtl.org/sites/default/files/libomp_20150701_oss.tgz
######################################################################## 100.0%
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/lorenzli/.linuxbrew/Cellar/libiomp/20150701 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_WITH_INSTALL_RPATH=1 -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=1 -DLIBOMP_ARCH=32e
==> make all
Error: No such file or directory - exports/mac_32e/lib.thin/libiomp5.dylib
````

Googling didn't help me and unfortunately I have only little experience in building source on my own so excuse me if my problem is trivial.

You can find my corresponding [gist-log here](https://gist.github.com/anonymous/64355bf2aafa56f7588a585ab8ea5e19) (please ignore the many `brew doctor` errors due to the fact that my web hosting company installed many packages on their own which now makes `brew` complain).

**Comment by sjackman** [comment]
Gnu GCC has OpenMP support. Why are you trying to install Intel OpenMP?
I'd suggest instead using `brew install gcc`.

**Comment by sjackman** [comment]
PR #372 should fix this issue.

**Comment by sjackman** [comment]
Fixed by #372.

**Comment by lorenzschmid** [comment]
That was super quick and indeed using gcc seems much simpler. Thanks a lot for your help!

**Comment by sjackman** [comment]
No worries!
