### ISSUE TITLE
mysql 5.7.19 build error (make: *** [all] Error 2)

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/homebrew-core#3708]
Not quite sure what is going on here, sorry!

https://gist.github.com/5c7db742ba4d16a190c1d3937309bb72

```
[ 68%] Built target mysqlx
make[1]: Leaving directory `/tmp/mysql-20170808-36705-51v398/mysql-5.7.19'
make: *** [all] Error 2
```

**Comment by sjackman** [comment]
There's an open bottle PR for `mysql` that built successfully. https://github.com/Linuxbrew/homebrew-core/pull/3709. We can merge that tomorrow after the merge PR https://github.com/Linuxbrew/homebrew-core/pull/3670 is merged.

I'm not able to find that error in the gist. The log seems to stop at 51%, but doesn't indicate that it's truncated.
https://gist.github.com/anonymous/5c7db742ba4d16a190c1d3937309bb72#file-02-make-L947

**Comment by tseemann** [comment]
I had to click "Raw" to find it.  But there was no obvious gcc error around it.

**Comment by sjackman** [comment]
`mysql` is bottled for Linuxbrew.

**Comment by tseemann** [comment]
@sjackman I confirm bottle installed fine. thank you!

**Comment by sjackman** [comment]
Glad to hear it, Torsten!
