### ISSUE TITLE
py3cairo fails on Ubuntu 17.04

### ISSUE THREAD

**Issue by half2me** [Linuxbrew/homebrew-core#3723]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- I was trying to `brew install gst-python --with-python3 --without-python`
- What happened: The install failed installing dep `py3cairo`
- gist: https://gist.github.com/anonymous/2adb53fc8441fce6848ce55e55ceff08
- This fixed my problem! `export PYTHON_CONFIG=/home/linuxbrew/.linuxbrew/lib/python3.6/config-3.6m-x86_64-linux-gnu/python-config.py`

**Comment by rwhogg** [comment]
I've opened #3724 to reproduce this problem.

The issue appears to be that `py3cairo` is using Python 3 to run `python3.6-config`, which is a shell script, so it complains about invalid syntax. Which means your solution makes a lot of sense 😄 

Would you like to open a PR to add that environment variable to the formula? Getting it right for all users might be a little tricky, but we can help you out with it along the way. If not, no worries 😄

**Comment by iMichka** [comment]
@half2me what is that status of this for you now? I see that we have a `py3cairo` bottle now.

**Comment by half2me** [comment]
@iMichka I have not had a chance to solve this yet. Not quite sure how it should be done.

**Comment by iMichka** [comment]
I opened a pull request for that: #4204

**Comment by iMichka** [comment]
Patch pushed and bottle built with #4204

@half2me please test

**Comment by half2me** [comment]
ah nice, thanks @iMichka, I'll test tomorrow

**Comment by half2me** [comment]
@iMichka confirmed working from source, and with bottle.
