### ISSUE TITLE
a2ps: cannot open file `/home/linuxbrew/.linuxbrew/etc/a2ps.cfg'

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#373]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

`a2ps source_file.java` fails if it is built from a bottle and relocated. However, it works fine if built from source.

Error message:

```
a2ps: cannot open file `/home/linuxbrew/.linuxbrew/etc/a2ps.cfg': No such file or directory
a2ps: cannot find file `level1.ppd': No such file or directory
```

`a2ps` is `cellar :any_skip_relocation`, but from what I've observed it should probably not do that.

**Comment by sjackman** [comment]
```ruby
"--sysconfdir=#{etc}",
```
I'm curious why this formula is marked as `cellar :any` on Mac if it hardcodes the path to the config file. I suspect this issue may also affect Mac.

**Comment by rwhogg** [comment]
It looks like Mike just fixed this on the Mac side: https://github.com/Homebrew/brew/issues/2005
