### ISSUE TITLE
libtool: has /usr/bin/gcc-4.8 as default compiler

### ISSUE THREAD

**Issue by fwalch** [Linuxbrew/homebrew-core#376]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Formula-installed libtool has /usr/bin/gcc-4.8 as default compiler.

The libtool from the Homebrew formula has a strange default compiler of /usr/bin/gcc-4.8, causing it to fail when used on my system because I don't have gcc-4.8 installed. Output from formula-installed `libtool --help`:

```
       host-triplet:   x86_64-unknown-linux-gnu
       shell:          /bin/bash
       compiler:       /usr/bin/gcc-4.8
       compiler flags: -Os -w -pipe -march=core2
       linker:         /usr/bin/ld -m elf_x86_64 (gnu? yes)
       version:        libtool (GNU libtool) 2.4.6
       automake:       automake (GNU automake) 1.15
       autoconf:       autoconf (GNU Autoconf) 2.69
```

If I compile libtool manually (`./configure && make`), it has:

```
       host-triplet:   x86_64-unknown-linux-gnu
       shell:          /bin/sh
       compiler:       gcc
       compiler flags: -g -O2
       linker:         /usr/bin/ld -m elf_x86_64 (gnu? yes)
       version:        libtool (GNU libtool) 2.4.6
       automake:       automake (GNU automake) 1.15
       autoconf:       autoconf (GNU Autoconf) 2.69
```

**Comment by sjackman** [comment]
This issue is a bug. As a workaround, use `brew reinstall -s libtool`

**Comment by rwhogg** [comment]
@sjackman,  I suspect this is the same problem we encountered on #764
