### ISSUE TITLE
ncurses: ginstall: cannot stat '../lib/libncursesw.a': No such file or directory

### ISSUE THREAD

**Issue by jzjsuper** [Linuxbrew/homebrew-core#377]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

ncurses fails to build on ubuntu 14.04

https://gist.github.com/db755912b2234368951e216ec643e84d

**Comment by sjackman** [comment]
```
installing ../lib/libncursesw.a as /home/jzjsuper/.linuxbrew/Cellar/ncurses/6.0_1/lib/libncursesw.a
/home/jzjsuper/.linuxbrew/bin/ginstall -c -m 644 ../lib/libncursesw.a /home/jzjsuper/.linuxbrew/Cellar/ncurses/6.0_1/lib/libncursesw.a
/home/jzjsuper/.linuxbrew/bin/ginstall: cannot stat '../lib/libncursesw.a': No such file or directory
make[1]: *** [Makefile:1879: install] Error 1
make[1]: Leaving directory '/tmp/ncurses-20160602-17669-1ohvgkj/ncurses-6.0/ncurses'
make: *** [Makefile:115: install] Error 2
```
https://gist.github.com/anonymous/db755912b2234368951e216ec643e84d#file-02-make-L1099

**Comment by sjackman** [comment]
Weird. I haven't seen that error. Shot in the dark, but try:
```
HOMEBREW_MAKE_JOBS=1 brew install homebrew/dupes/ncurses
```

**Comment by jzjsuper** [comment]
I gave up my attempt on standalone installation and switched back to using host system's gcc. 

`ncurses` can be built now.

**Comment by sjackman** [comment]
Okay. I'll close this issue for now. Glad to hear that you got it working. `brew install gcc` (without `glibc`) should work for you as well.
