### ISSUE TITLE
Unable to install glibc

### ISSUE THREAD

**Issue by nicholasfay** [Linuxbrew/homebrew-core#3846]
I was trying to do `brew install node` and when I got to the glibc dependency I got the below error. I have ran brew doctor and fixed any errors, I have ran brew update several times and it is "already up to date"

```
==> Installing node dependency: glibc
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.19.tar.bz2

curl: (7) Failed to connect to 2001:4830:134:3::b: Network is unreachable
Error: Failed to download resource "glibc"
Download failed: https://ftp.gnu.org/gnu/glibc/glibc-2.19.tar.bz2
[nfay@oc8665877830 YoutubePaper]$ brew install node
Updating Homebrew...
```

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `glibc`.

**Comment by sjackman** [comment]
```
curl: (7) Failed to connect to 2001:4830:134:3::b: Network is unreachable
```
That error message related to network trouble seems unrelated to Linuxbrew.

Try…
```sh
brew fetch -v glibc
brew install glibc
```

**Comment by sjackman** [comment]
That's an IPv6 network address that it's trying to connect to. I'd suggest bringing up this issue with your system administrator.
