### ISSUE TITLE
gcc-7: command not found [Fedora 26]

### ISSUE THREAD

**Issue by chauncey-garrett** [Linuxbrew/homebrew-core#3865]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/anonymous/aab41b4251cc948f7569403cb775933e

`brew install pkg-config` fails.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `pkg-config`.
Another possible workaround for you is `brew install --force-bottle pkg-config`, but no promises.

**Comment by sjackman** [comment]
```
gcc-7: command not found
```
https://gist.github.com/anonymous/aab41b4251cc948f7569403cb775933e#file-config-log-L68

Please report…
```sh
ls -l ~/.linuxbrew/bin/gcc-7 ~/.linuxbrew/bin/g++-7
which -a gcc-7
gcc-7 --version
```

**Comment by chauncey-garrett** [comment]
![2017-08-17 at 15 18](https://user-images.githubusercontent.com/302358/29432004-9781316c-835f-11e7-8318-02d4823f67ff.png)

**Comment by chauncey-garrett** [comment]
I did try `brew reinstall gcc` but it didn't fix things.

I may also start over with /home/linuxbrew as suggested -- that must be new since I started using `linuxbrew` a good while back -- but I can wait if you'd like to troubleshoot why it's not currently working.

**Comment by sjackman** [comment]
A new installation of Linuxbrew using the installer script at http://linuxbrew.sh/#install-linuxbrew will use `/home/linuxbrew/.linuxbrew` by default if you have `sudo` access. Let's see if that works for you.

**Comment by chauncey-garrett** [comment]
Installed linuxbrew as suggested and was able to install most things but still having an issue with gcc.

Here, installation of `nodenv` failed from similar gcc failures:

https://gist.github.com/anonymous/da62e40db322b89f9366910b74ca5a18

But you can see it's available in my `PATH`:

![screen shot 2017-08-17 at 17 44 46](https://user-images.githubusercontent.com/302358/29436981-d765e0ca-8373-11e7-9b5a-b6db6a6b7fb2.png)

It also fails when installing `hadolint`, `rust`, and `the_silver_searcher`.

`hadolint` didn't provide any logs:

![2017-08-17 at 17 46](https://user-images.githubusercontent.com/302358/29437041-29eba460-8374-11e7-916a-89c65dffc16d.png)

`rust`:

https://gist.github.com/anonymous/251aee8ad373dd79fa4b2d1367438896

`the_silver_searcher`:

https://gist.github.com/anonymous/3064a9c88d69480c62ac6e5ee9c777d0

**Comment by sjackman** [comment]
I've opened PRs #3868 and #3869 to build bottles for `hadolint` and `the_silver_searcher`.
The last build of `rust` on CircleCI timed out, but I'm giving it another shot at PR #3870.

**Comment by sjackman** [comment]
Please report the output of…
```sh
brew sh <<<'echo $PATH; which -a gcc-7'
```

**Comment by sjackman** [comment]
`hadolint` and `the_silver_searcher` are bottled now. I didn't unfortunately have any luck with `rust`.

**Comment by chauncey-garrett** [comment]
![2017-08-17 at 22 27](https://user-images.githubusercontent.com/302358/29443111-7d069890-839b-11e7-8bd9-9d458f2ccbe5.png)

**Comment by sjackman** [comment]
That looks as expected.

**Comment by chauncey-garrett** [comment]
`hadolint` and `the_silver_searcher` work as expected. 👍

**Comment by sjackman** [comment]
I've bottled `rust` for Linuxbrew. I had to build it in Docker on my local machine, because it exceeded CircleCI's memory limit of 4 GB.

**Comment by chauncey-garrett** [comment]
+1 for docker! I downloaded rust but got a warning I've never seen before:

```
==> Downloading https://linuxbrew.bintray.com/bottles/rust-1.19.0.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring rust-1.19.0.x86_64_linux.bottle.tar.gz
warning: working around a Linux kernel bug by creating a hole of 2093056 bytes in ‘/home/linuxbrew/.linuxbrew/Cellar/rust/1.19.0/bin/rustc’
warning: working around a Linux kernel bug by creating a hole of 2093056 bytes in ‘/home/linuxbrew/.linuxbrew/Cellar/rust/1.19.0/bin/rustdoc’
🍺  /home/linuxbrew/.linuxbrew/Cellar/rust/1.19.0: 5,461 files, 373.3MB
```

Other than that, `rust` (and `cargo`) appear to be working.

**Comment by chauncey-garrett** [comment]
From the original items I was trying to install, I think that leaves `nodenv` which still has the `gcc-7` error.

**Comment by sjackman** [comment]
As a workaround, the following should work.
```sh
brew install nodenv --without-bash-extension
```

**Comment by chauncey-garrett** [comment]
Works! Thank you for the help!

**Comment by sjackman** [comment]
Should be resolved by https://github.com/Linuxbrew/brew/pull/484 when it's merged.
