### ISSUE TITLE
Error: No available formula with the name "linuxbrew/xorg/xorg" 

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/homebrew-core#387]
```
Error: No available formula with the name "linuxbrew/xorg/xorg" 
Please tap it and then try again: brew tap linuxbrew/xorg
```

**Comment by rwhogg** [comment]
Traced this to `FormulaLoader::load_file`: `raise FormulaUnavailableError.new(name) unless path.file?`

Which fails since the xorg tap is not tapped.

It's done by `Satisfier::yielder` in `requirement.rb`.

Not yet sure where it's correct to tap the xorg tap, but I'll figure it out eventually.

**Comment by rwhogg** [comment]
For reference, the original related issue is https://github.com/Homebrew/legacy-homebrew/issues/50271

**Comment by sjackman** [comment]
I believe this issue affects only `brew fetch`. It is I think already fixed for `brew install` by @xu-cheng.

**Comment by fibric** [comment]
I got this error today when running `brew install <package> -d`

```bash
$ brew -v
Homebrew 0.9.9 (git revision 8d18; last commit 2016-07-28)
Homebrew/homebrew-core (git revision a7dc; last commit 2016-07-31)
```

**Comment by sjackman** [comment]
@fibric Yeah, it's a bug. The workaround is `brew tap linuxbrew/xorg`.

**Comment by fibric** [comment]
What's the reason? I mean why does running specs beed x.org?

**Comment by fibric** [comment]
Can you tell me why `-d` requires xorg?

**Comment by sjackman** [comment]
I'm not sure. I don't see anything in the dependency tree of `crystal-lang` that requires `:x11`.

**Comment by sjackman** [comment]
```
/home/fibric/.linuxbrew/Library/Homebrew/build.rb (Formulary::TapLoader): loading /home/fibric/.linuxbrew/Library/Taps/linuxbrew/homebrew-xorg/xorg.rb
/home/fibric/.linuxbrew/Library/Homebrew/debrew.rb:11:in `raise'
FormulaUnavailableError: No available formula with the name "xorg" 
```

It looks like you already have `linuxbrew/xorg` tapped though.

**Comment by fibric** [comment]
Only today morning, 15 min ago. Ot wasnt when I joined this issue.
