### ISSUE TITLE
Cannot install Ansible. Conflicting version recursive dependencies

### ISSUE THREAD

**Issue by andrewyatz** [Linuxbrew/homebrew-core#3928]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

I was attempting to install Ansible into a fresh non-default location i.e. not into `~linuxbrew/linuxbrew`. The install command failed to run because of recursive dependency problems. I'm not sure how to proceed to resolve it

- What happened (include command output)

```
$ brew install ansible
Error: ansible contains conflicting version recursive dependencies:
  openssl@1.1, openssl
View these with `brew deps --tree ansible`.
```

Output of the suggested command confirms this

```
brew deps --tree ansible
ansible (required dependencies)
├── :python
├── pkg-config
├── unzip
│   ├── gpatch
│   │   └── xz
│   ├── xz
│   └── bzip2
├── unzip
│   ├── gpatch
│   │   └── xz
│   ├── xz
│   └── bzip2
├── libyaml
├── openssl@1.1
│   └── :perl
├── libffi
├── krb5
│   ├── openssl
│   │   ├── :perl
│   │   ├── gpatch
│   │   │   └── xz
│   │   └── zlib
│   └── bison
│       └── m4
│           └── xz
└── libxslt
    └── libxml2
        ├── :python
        ├── gpatch
        │   └── xz
        ├── xz
        └── zlib
```

Seems that `krb5` brings in openssl and Ansible brings in `openssl@1.1`. 

- What you expected to happen

I expected that Ansible would have installed itself. I tried this on my macOS machine and the error did not appear. I assume because there isn't the krb5 dependency in their formula.

- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by rwhogg** [comment]
@iMichka is working on a related problem at #3897

**Comment by sjackman** [comment]
Try `brew edit krb5` and change `openssl` to `openssl@1.1` then
```sh
brew install -s krb5
brew install ansible
```
If that works, can you please submit a PR to change `krb5`?

**Comment by andrewyatz** [comment]
Just tried. Openssl barfs

```
brew install openssl@1.1
==> Downloading https://www.openssl.org/source/openssl-1.1.0f.tar.gz
Already downloaded: /homes/ensw/.cache/Homebrew/openssl@1.1-1.1.0f.tar.gz
==> perl ./Configure --prefix=/nfs/software/ensembl/ANSIBLE-dev/brew/Cellar/openssl@1.1/1.1.0f_1 --openssldir=/nfs/software/ensembl/ANSIBLE-dev/brew/etc/openssl@1.1 no-ssl3 no-ssl3-method no-zlib  linux-x86_64
==> make
==> make test
Last 15 lines from /homes/ensw/.cache/Homebrew/Logs/openssl@1.1/03.make:
../test/recipes/90-test_srp.t .............. ok
../test/recipes/90-test_sslapi.t ........... ok
../test/recipes/90-test_threads.t .......... ok
../test/recipes/90-test_v3name.t ........... ok

Test Summary Report
-------------------
../test/recipes/90-test_shlibload.t      (Wstat: 768 Tests: 3 Failed: 3)
  Failed tests:  1-3
  Non-zero exit status: 3
Files=95, Tests=547, 46 wallclock secs ( 0.31 usr  0.08 sys + 31.65 cusr 12.76 csys = 44.80 CPU)
Result: FAIL
make[1]: *** [_tests] Error 3
make[1]: Leaving directory `/tmp/openssl@1.1-20170822-54660-1yxlzux/openssl-1.1.0f'
make: *** [tests] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

These open issues may also help:
curl: Build with openssl@1.1 for Linuxbrew https://github.com/Linuxbrew/homebrew-core/pull/3897
```

**Comment by sjackman** [comment]
Try removing the `krb5` dependency from `ansible`.

**Comment by andrewyatz** [comment]
The current ansible still has the openssl 1.1 dependency that fails same as above

**Comment by sjackman** [comment]
Try…
```sh
brew install https://raw.githubusercontent.com/sjackman/homebrew-core/a4495c570233feff2a1b3263d9920ced3b191413/Formula/ansible.rb
```

**Comment by andrewyatz** [comment]
Just tried that and still nothing. The openssl 1.1 build is still the issue. Feels like I should be opening an issue with openssl now as this seems like it's beyond just a linuxbrew issue. Not sure why others have not seen this before

```
../test/recipes/90-test_shlibload.t ........
1..3
Unable to load ssl symbols
../util/shlib_wrap.sh ./shlibloadtest -crypto_first libcrypto.so libssl.so => 1
not ok 1 - running shlibloadtest -crypto_first

#   Failed test 'running shlibloadtest -crypto_first'
#   at ../test/recipes/90-test_shlibload.t line 30.
Unable to load ssl symbols
../util/shlib_wrap.sh ./shlibloadtest -ssl_first libcrypto.so libssl.so => 1
not ok 2 - running shlibloadtest -ssl_first

#   Failed test 'running shlibloadtest -ssl_first'
#   at ../test/recipes/90-test_shlibload.t line 32.
Unable to load crypto symbols
../util/shlib_wrap.sh ./shlibloadtest -just_crypto libcrypto.so libssl.so => 1
not ok 3 - running shlibloadtest -just_crypto

#   Failed test 'running shlibloadtest -just_crypto'
#   at ../test/recipes/90-test_shlibload.t line 34.
# Looks like you failed 3 tests of 3.
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/3 subtests
```

**Comment by sjackman** [comment]
Thanks for the output of `HARNESS_VERBOSE=yes make test`. That's helpful. Here's the source code for `util/shlib_wrap.sh`. Running it interactively could be useful for troubleshooting.
https://github.com/openssl/openssl/blob/master/util/shlib_wrap.sh.in

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `openssl@1.1`.
Another possible workaround for you is `brew install --force-bottle openssl@1.1`, but no promises.

**Comment by andrewyatz** [comment]
Output from `shlib_wrap.sh.in`

```bash
$ ./util/shlib_wrap.sh.in
++ echo ./util/shlib_wrap.sh.in
++ sed -e 's|[^/]*$||'
+ THERE=./util/..
+ '[' -d ./util/.. ']'
+ LIBCRYPTOSO=./util/../libcrypto.so
+ '[' -f ./util/../libcrypto.so ']'
+ '[' -h ./util/../libcrypto.so ']'
++ ls -l ./util/../libcrypto.so
++ sed -e 's|.*\-> ||'
+ LIBCRYPTOSO=./util/../libcrypto.so.1.1
+ '[' -h ./util/../libcrypto.so.1.1 ']'
++ echo ./util/../libcrypto.so.1.1
++ sed -e 's|.*\.so||'
+ SOSUFFIX=.1.1
+ LIBSSLSO=./util/../libssl.so.1.1
+ SYSNAME=Linux
+ case "$SYSNAME" in
+ LD_LIBRARY_PATH=./util/..:
+ DYLD_LIBRARY_PATH=./util/..:
+ SHLIB_PATH=./util/..:
+ LIBPATH=./util/..:
+ export LD_LIBRARY_PATH DYLD_LIBRARY_PATH SHLIB_PATH LIBPATH
+ '[' linux-gnu '!=' msdosdjgpp ']'
+ PATH=./util/..:/nfs/software/ensembl/ANSIBLE-dev/brew/Cellar/ansible/2.3.2.0/bin:/nfs/software/ensembl/ANSIBLE/brew/opt/ansible/bin:/usr/lib64/qt-3.3/bin:/ebi/lsf/ebi/ppm/9.1/bin:/ebi/lsf/ebi/ppm/9.1/linux2.6-glibc2.3-x86_64/bin:/ebi/lsf/ebi/9.1/linux2.6-glibc2.3-x86_64/etc:/ebi/lsf/ebi/9.1/linux2.6-glibc2.3-x86_64/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/lpp/mmfs/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/bin:/usr/bin
+ export PATH
./util/shlib_wrap.sh.in: line 84: syntax error near unexpected token `('
./util/shlib_wrap.sh.in: line 84: `{- output_off() if $config{ex_libs} !~ /,-rpath,/; ""; -}'
```

**Comment by sjackman** [comment]
Try running `shlib_wrap.sh` as in the failed test above:
```sh
brew install -dv openssl@1.1
# when it fails select the shell option
../util/shlib_wrap.sh ./shlibloadtest -crypto_first libcrypto.so libssl.so
../util/shlib_wrap.sh ./shlibloadtest -ssl_first libcrypto.so libssl.so
../util/shlib_wrap.sh ./shlibloadtest -just_crypto libcrypto.so libssl.so
```

**Comment by sjackman** [comment]
I've bottled `ansible` in PR #3962 and removed the `krb5` dependency. Are you able to install Linuxbrew in `/home/linuxbrew/.linuxbrew/`? That's the default now if you have `sudo` access.

**Comment by andrewyatz** [comment]
Output from shlib_wrap.sh

```
++ echo ./util/shlib_wrap.sh
++ sed -e 's|[^/]*$||'
+ THERE=./util/..
+ '[' -d ./util/.. ']'
+ LIBCRYPTOSO=./util/../libcrypto.so
+ '[' -f ./util/../libcrypto.so ']'
+ '[' -h ./util/../libcrypto.so ']'
++ ls -l ./util/../libcrypto.so
++ sed -e 's|.*\-> ||'
+ LIBCRYPTOSO=./util/../libcrypto.so.1.1
+ '[' -h ./util/../libcrypto.so.1.1 ']'
++ echo ./util/../libcrypto.so.1.1
++ sed -e 's|.*\.so||'
+ SOSUFFIX=.1.1
+ LIBSSLSO=./util/../libssl.so.1.1
+ SYSNAME=Linux
+ case "$SYSNAME" in
+ LD_LIBRARY_PATH=./util/..:
+ DYLD_LIBRARY_PATH=./util/..:
+ SHLIB_PATH=./util/..:
+ LIBPATH=./util/..:
+ export LD_LIBRARY_PATH DYLD_LIBRARY_PATH SHLIB_PATH LIBPATH
+ '[' linux-gnu '!=' msdosdjgpp ']'
+ PATH=./util/..:/nfs/software/ensembl/ANSIBLE-dev/brew/Cellar/ansible/2.3.2.0/bin:/nfs/software/ensembl/ANSIBLE/brew/opt/ansible/bin:/usr/lib64/qt-3.3/bin:/ebi/lsf/ebi/ppm/9.1/bin:/ebi/lsf/ebi/ppm/9.1/linux2.6-glibc2.3-x86_64/bin:/ebi/lsf/ebi/9.1/linux2.6-glibc2.3-x86_64/etc:/ebi/lsf/ebi/9.1/linux2.6-glibc2.3-x86_64/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/lpp/mmfs/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/bin:/usr/bin
+ export PATH
+ cmd=
+ '[' -x '' ']'
+ cmd=
+ shift
+ '[' 0 -eq 0 ']'
+ exec ''
./util/shlib_wrap.sh: line 89: exec: : not found
```

**Comment by andrewyatz** [comment]
Also I'm not able to test the ansible bottle if it requires to be installed in `/home/linuxbrew/.linuxbrew` as I'm installing into a compute farm environment. So linuxbrew isn't really a user I can install to and I don't have sudo access

**Comment by sjackman** [comment]
If it's an option for you, you could open a ticket with your systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew` for the purpose of sharing software that is used by your group.

**Comment by iMichka** [comment]
As there was no progress here, and this seems to be a problem with your setup, I'll close this issue. If you find out why openssl@1.1 does not build, we would be pleased to hear it, especially if we need to change something in our build setup.
