### ISSUE TITLE
Fix various test failures

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/homebrew-core#3930]
See @rwhogg 's comments at https://github.com/Linuxbrew/homebrew-core/pull/3927
- [x] alot #3956
- [x] boost #4174
- [x] gl2ps #4068 
- [x] gnudatalanguage https://github.com/Homebrew/homebrew-science/pull/6179
- [ ] graphviz
- [x] gst-python #3929
- [x] insighttoolkit (fixed by migrating opencv to core)
- [ ] libgit2-glib
- [ ] littler
- [x] mir-prefer https://github.com/Homebrew/homebrew-science/pull/6181
- [ ] oce
- [ ] opencascade
- [ ] openni2
- [x] plplot Homebrew/homebrew-science#6179
- [x] statismo (fixed by migrating opencv to core)
- [ ] swrcfit

**Comment by iMichka** [comment]
This list is probably not up to date anymore. I will just close it because I am not actively working on this.

I am fixing tests here and there though, when I have time.
