### ISSUE TITLE
Cannot install source-to-image formula in Linux: No such file or directory - _output/local/bin/darwin/amd64/s2i

### ISSUE THREAD

**Issue by gastaldi** [Linuxbrew/homebrew-core#3954]
-  [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Brew Gist Logs: https://gist.github.com/anonymous/2ea1ca88d3cc12e4cba25754adad557c

Output:
```
➜  brew install source-to-image
==> Installing dependencies for source-to-image: go
==> Installing source-to-image dependency: go
==> Downloading https://linuxbrew.bintray.com/bottles/go-1.8.3.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ggastald/.cache/Homebrew/go-1.8.3.x86_64_linux.bottle.tar.gz
==> Pouring go-1.8.3.x86_64_linux.bottle.tar.gz
==> Caveats
A valid GOPATH is required to use the `go get` command.
If $GOPATH is not specified, $HOME/go will be used by default:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/home/linuxbrew/.linuxbrew/opt/go/libexec/bin

==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/go/1.8.3: 7,035 files, 287.2MB
==> Installing source-to-image
==> Cloning https://github.com/openshift/source-to-image.git
Updating /home/ggastald/.cache/Homebrew/source-to-image--git
==> Checking out tag v1.1.7
==> hack/build-go.sh
Error: No such file or directory - _output/local/bin/darwin/amd64/s2i

```

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/3957 to hopefully address this build failure.
