### ISSUE TITLE
OpenCV: build error with 3, but 2 work well

### ISSUE THREAD

**Issue by hotkidfamily** [Linuxbrew/homebrew-core#4029]
https://gist.github.com/anonymous/46f6ae73dcaab2f4a9ccbb93820002dc#file-opencv-2017-08-28_18-20-44-txt

**Comment by iMichka** [comment]
I just built bottles (#4016). Please update an tell me if it works for you. Thanks

**Comment by iMichka** [comment]
I'll just close this for the moment, as I think OpenCV builds fine. If note; please provide a new gist log so I can investigate. Thanks
