### ISSUE TITLE
perl 5.22.1: Cannot find errno.h at Errno_pm.PL line 131.

### ISSUE THREAD

**Issue by tomas** [Linuxbrew/homebrew-core#405]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

When trying to build perl on a Chrome OS with Linuxbrew I get "Cannot find errno.h at Errno_pm.PL line 131." and the build fails. Something must have changed with the formula (or Linuxbrew) because I *was* able to build perl before in this very same machine.

Here's the log file:

https://gist.github.com/anonymous/62a0bf3e1706bb0540727bac0bd80e62

**Comment by sjackman** [comment]
```
OS glibc: 2.19
OS gcc: 
Linuxbrew glibc: 2.19
Linuxbrew gcc: N/A
```
This is strange. Which `gcc` are you using? `brew install gcc perl` may help.

**Comment by sjackman** [comment]
This may be the source of your trouble:
```
Warning: Broken symlinks were found. Remove them with `brew prune`:
    /usr/local/linuxbrew/bin/g++-4.8
    /usr/local/linuxbrew/bin/gcc-4.8
```

**Comment by tomas** [comment]
I think that's because I have gcc 5.3.0 installed.

```
$ brew info gcc
gcc: stable 5.3.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org
/usr/local/linuxbrew/Cellar/gcc/5.1.0 (1,344 files, 874.4M) *
  Built from source on 2015-07-19 at 02:33:35 with: --with-glibc
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/gcc.rb
...
```

**Comment by tomas** [comment]
And I think those symlinks are broken because they were left [after building the toolchain out of Chromebrew](https://github.com/Linuxbrew/linuxbrew/wiki/Chromebook-Install-Instructions).

**Comment by sjackman** [comment]
Odd then that `brew config` report `Linuxbrew gcc: N/A`. Can you please report `brew config` again?

**Comment by tomas** [comment]
Here you go:

```
$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 007e645b42c4d1af45788d4b32570dbae865a74a
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: f7304c0ee59a96cc935521dceb32c6048b374875
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local/linuxbrew
HOMEBREW_REPOSITORY: /usr/local/linuxbrew
HOMEBREW_CELLAR: /usr/local/linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit ivybridge
Kernel: Linux 3.8.11 x86_64 GNU/Linux
OS glibc: 2.19
OS gcc: 
Linuxbrew glibc: 2.19
Linuxbrew gcc: N/A
Clang: N/A
X11: N/A
System Ruby: 2.2.2 => /usr/local/linuxbrew/Cellar/ruby/2.2.2/bin/ruby
Perl: N/A
Python: /usr/local/linuxbrew/bin/python => /usr/local/linuxbrew/Cellar/python/2.7.10_2/bin/python2.7
Ruby: /usr/local/linuxbrew/bin/ruby => /usr/local/linuxbrew/Cellar/ruby/2.2.2/bin/ruby
Java: N/A
```

I don't think the problem with the perl build lies here, though. I can build other stuff without any problems, and the perl build process only fails in that specific part. The rest of the source compiles like butter.

**Comment by sjackman** [comment]
Please report the output of `brew install gcc`

**Comment by sjackman** [comment]
There is a binary bottle for Perl, but it's compiled for the prefix `/home/linuxbrew/.linuxbrew`. Would you like to try giving a new installation of Linuxbrew a shot in that prefix? Oh wait, `/home` is mounted non-executable on Chrome OS, isn't it?

**Comment by sjackman** [comment]
You can also try `brew install --force-bottle perl`, but it may not work due to its paths being all wrong.

**Comment by sjackman** [comment]
Please report the output of `brew list gcc | grep specs`

**Comment by DoomHammer** [comment]
`perl` expects `errno.h` to be in one of predefined system locations. If you don't have system-wide includes this becomes a problem. I have dealt with in in `brewstrap` with a workaround: https://github.com/DoomHammer/brewstrap/pull/7/files#diff-a4a8b02a861c11cadeebb2a3a5f799fcR68 . It appends Linuxbrew include dir to the list of searched directories.

Now the question is: should this workaround become an official part of `perl` formula?

**Comment by tomas** [comment]
@sjackman 

```
$ brew list gcc | grep specs
/usr/local/linuxbrew/Cellar/gcc/5.1.0/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/specs.orig
/usr/local/linuxbrew/Cellar/gcc/5.1.0/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/specs
```

@DoomHammer thanks for the heads up. I do have a copy of errno.h on the `linuxbrew/include` directory, which apparently comes from the `glibc` package. Would your hack help in this scenario?

``` 
$ pwd
/usr/local/linuxbrew/include
$ ls -al errno.h 
lrwxrwxrwx 1 chronos chronos 36 Jul 19  2015 errno.h -> ../Cellar/glibc/2.19/include/errno.h
```

**Comment by DoomHammer** [comment]
You need to run `HOMEBREW_DIR=$(brew --prefix) sed -i -e 's@-Dprefix=#{prefix}@-Dprefix=#{prefix}\n-Dlocincpth=#{Formula["glibc"].include}@' $HOMEBREW_DIR/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb` as per https://github.com/DoomHammer/brewstrap/pull/7/files#diff-a4a8b02a861c11cadeebb2a3a5f799fcR68 in order for `perl` to install correctly.

@sjackman what do you think of making this hack official part of `perl` formula (using `inreplace` and probably `--with-brewed-glibc`)?

**Comment by sjackman** [comment]
How about changing `-Dlocincpth=#{Formula["glibc"].include}` to `-Dlocincpth=#{HOMEBREW_PREFIX}/include` so that it can be independent of `glibc`?

**Comment by DoomHammer** [comment]
You are right. I set it to `glibc` explicitely as I had it unlinked in `brewstrap` scenario. Proceed with the PR then?

**Comment by sjackman** [comment]
Yes, please.

**Comment by DoomHammer** [comment]
#432 then

**Comment by DoomHammer** [comment]
Should be fixed now. Could you test it, @tomas? In case it doesn't meet your expectations, do not hesitate to reopen the issue.
