### ISSUE TITLE
Revisions after boost update for gcc5

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/homebrew-core#4065]
- [x] cgal https://github.com/Linuxbrew/homebrew-core/pull/4063
- [ ] ome-files https://github.com/Homebrew/homebrew-science/pull/6254
- [ ] rapsearch2 https://github.com/Homebrew/homebrew-science/pull/6201
- [x] trinity https://github.com/Homebrew/homebrew-science/pull/6263
- [ ] ome-common https://github.com/Homebrew/homebrew-science/pull/6258
- [ ] pykep https://github.com/Homebrew/homebrew-science/pull/6256
- [ ] ome-xml https://github.com/Homebrew/homebrew-science/pull/6255
- [x] shark https://github.com/Homebrew/homebrew-science/pull/6262
- [x] statismo https://github.com/Homebrew/homebrew-science/pull/5916
- [x] express https://github.com/Homebrew/homebrew-science/pull/6261
- [ ] cufflinks https://github.com/Homebrew/homebrew-science/pull/6204
- [ ] nixio https://github.com/Homebrew/homebrew-science/pull/6232
- [x] dgtal https://github.com/Homebrew/homebrew-science/pull/6260
- [ ] lobstr https://github.com/Homebrew/homebrew-science/pull/5861
- [ ] mlpack https://github.com/Homebrew/homebrew-science/pull/5660
- [x] delly https://github.com/Homebrew/homebrew-science/pull/6259

**Comment by sjackman** [comment]
Thanks, Michka!

**Comment by iMichka** [comment]
Closing here. PRs are open in science, and a lot of stuff has still to be fixed ..
