### ISSUE TITLE
ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.

### ISSUE THREAD

**Issue by iarkaroy** [Linuxbrew/homebrew-core#4120]
Failed to install phantomjs.
Tried by running (as per phantomjs build instruction).
```
sudo apt-get install build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev
```
brew gist-logs phantomjs
[https://gist.github.com/anonymous/8c6c3f037e4e7ca786816d8d0c3f1ef1](https://gist.github.com/anonymous/8c6c3f037e4e7ca786816d8d0c3f1ef1)

**Comment by sjackman** [comment]
```
The ICU library support cannot be enabled.
ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.
```
https://gist.github.com/anonymous/8c6c3f037e4e7ca786816d8d0c3f1ef1#file-01-build-py-L37
See https://github.com/Linuxbrew/homebrew-core/pull/3824

In principle it should be resolved by
```ruby
depends_on "icu4c" unless OS.mac?
```
but that didn't work. You may have to specify the location of the `icu4c` library to the `configure` script. If you're able to resolve this issue, a pull request would be welcome.
