### ISSUE TITLE
glibc and gmp: circular dependency makes brew-upgrade impossible

### ISSUE THREAD

**Issue by zmwangx** [Linuxbrew/homebrew-core#4198]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? (https://gist.github.com/anonymous/3f8b947205117027584007d4248eee35: nothing interesting)
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (N/A)
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

---

OS: RHEL 7.4
brew-config: https://gist.github.com/anonymous/a502eed2c08dc97fd0bfc2c8295824be
brew-doctor: https://gist.github.com/anonymous/3f8b947205117027584007d4248eee35

For some reason I'm facing a circular dependency when trying to upgrade glibc and gmp:

```
$ brew info glibc
glibc: stable 2.23
The GNU C Library
https://www.gnu.org/software/libc/
/home/zhimingw/.linuxbrew/Cellar/glibc/2.19 (1,406 files, 42.5MB) *
  Built from source on 2016-10-17 at 11:09:08
...
```

```
$ brew info gmp
gmp: stable 6.1.2 (bottled)
GNU multiple precision arithmetic library
https://gmplib.org/
/home/zhimingw/.linuxbrew/Cellar/gmp/6.1.1 (20 files, 3.5MB) *
  Poured from bottle on 2017-09-11 at 12:04:35
...
```

```
$ brew deps gmp
m4
```

```
$ brew deps glibc
binutils
linux-headers
zlib
```

```
$ brew upgrade gmp
==> Upgrading 1 outdated package, with result:
gmp 6.1.2
==> Upgrading gmp
==> Installing dependencies for gmp: glibc
==> Installing gmp dependency: glibc
==> Installing dependencies for glibc: gmp, mpfr
==> Installing glibc dependency: gmp
==> Installing dependencies for gmp: glibc
==> Installing gmp dependency: glibc
==> Installing dependencies for glibc: gmp, mpfr
...
^C
```

```
$ brew upgrade glibc
brew upgrade glibc
==> Upgrading 1 outdated package, with result:
glibc 2.23
==> Upgrading glibc
==> Installing dependencies for glibc: gmp, mpfr
==> Installing glibc dependency: gmp
==> Installing dependencies for gmp: glibc
==> Installing gmp dependency: glibc
==> Installing dependencies for glibc: gmp, mpfr
==> Installing glibc dependency: gmp
==> Installing dependencies for gmp: glibc
...
^C
```

I haven't looked into what exactly is going on, but it seems that the compiler, `gcc-5`, depends on both, and maybe that's causing the trouble?

A couple additional remarks:

- `--force-bottle` doesn't help;
- If I uninstall both, I won't be able to install either afterwards (same circular dep), so this issue isn't limited to upgrade;
- A known good commit is d5d8600e0a03574cb485d406b6faf339e8ab7808, where I can install both.

**Comment by iMichka** [comment]
We bumped gmp a few hours ago, in #4157, which also added the m4 dependency. This worked correctly for us in a clean build environment. We will have to dig a little bit more to see what happens here.

**Comment by rakeshbala** [comment]
I am facing the same issue. Temporarily made the change mentioned here https://github.com/Linuxbrew/homebrew-core/commit/d5d8600e0a03574cb485d406b6faf339e8ab7808 manually to get things working.

**Comment by zmwangx** [comment]
@iMichka I finally looked into this and tracked down the root of the issue (almost). The key is the `gawk` formula.

Simple repro from a fresh Linuxbrew installation (basically you only need to install a single formula, `gawk`, from an old commit with outdated `glibc` and `gmp`:

```sh
# Inside homebrew/core
$ git checkout d5d8600
$ brew install gawk
...
$ git checkout master  # currently 31071ba
$ brew upgrade glibc
...
==> Installing dependencies for glibc: m4, gmp, mpfr
==> Installing glibc dependency: m4
==> Installing dependencies for m4: glibc
==> Installing m4 dependency: glibc
==> Installing dependencies for glibc: m4, gmp, mpfr
==> Installing glibc dependency: m4
...
```

There problem lies in `expand_requirements` in `formula_installer`: https://github.com/Linuxbrew/brew/blob/a04f14336a38d4ab0bec01686ae7f242d92a2eed/Library/Homebrew/formula_installer.rb#L424-L453

When `gawk` is not installed, system gawk satisfies the `GawkDependency` in `glibc.rc` and no extra dep is collected. When `gawk` is installed, though, the `GawkDependency` is still satisfied, but `req_dependency` becomes `gawk` rather than `nil`, and `install_requirement_formula?(req_dependency, req, install_bottle_for_dependent)` now returns `true` for whatever reason (I stopped my investigation there due to time constraint), pushing `gawk` back onto the deps stack. `gawk` then pulls in `gmp` resulting in the recursive deps situation.

I was never familiar with the requirements resolution part of brew and AFAIK it has always been a pain... Someone will need to take a look, but I bow out here :joy: I uninstalled gawk and called it a day. Honestly I have no idea what pulled in gawk in the past on my affected server.

**Comment by zmwangx** [comment]
Hmm, isn't GitHub now supposed turn the link https://github.com/Linuxbrew/brew/blob/a04f14336a38d4ab0bec01686ae7f242d92a2eed/Library/Homebrew/formula_installer.rb#L424-L453 into an inline code snippet? Doesn't work cross repo?

Anyway, a copy of the snippet:

```rb
  def expand_requirements
    unsatisfied_reqs = Hash.new { |h, k| h[k] = [] }
    deps = []
    formulae = [formula]


    while f = formulae.pop
      runtime_requirements = runtime_requirements(f)
      f.recursive_requirements do |dependent, req|
        build = effective_build_options_for(dependent)
        install_bottle_for_dependent = install_bottle_for?(dependent, build)
        use_default_formula = install_bottle_for_dependent || build_bottle?
        req_dependency = req.to_dependency(use_default_formula: use_default_formula)


        if (req.optional? || req.recommended?) && build.without?(req)
          Requirement.prune
        elsif req.build? && install_bottle_for_dependent
          Requirement.prune
        elsif install_requirement_formula?(req_dependency, req, install_bottle_for_dependent)
          deps.unshift(req_dependency)
          formulae.unshift(req_dependency.to_formula)
          Requirement.prune
        elsif req.satisfied?
          Requirement.prune
        elsif !runtime_requirements.include?(req) && install_bottle_for_dependent
          Requirement.prune
        else
          unsatisfied_reqs[dependent] << req
        end
      end
    end
```

---

Test: https://github.com/Linuxbrew/homebrew-core/blob/59b343a86689531bc59702e376654821f766b1c8/Formula/glibc.rb#L16-L31

**Comment by iMichka** [comment]
I think @sjackman is more comptent for that part of the code. I can have a look later too.

**Comment by sjackman** [comment]
I'm not quite sure what's going on here. Perhaps this PR to make the `m4` dependency of `gmp` build only will help:
https://github.com/Linuxbrew/homebrew-core/pull/4391

**Comment by iMichka** [comment]
@zmwangx Could you please test again?

**Comment by jwhite007** [comment]
I'm getting the same infinite loop. Has there been any progress on a solution?

**Comment by zmwangx** [comment]
>  Perhaps this PR to make the m4 dependency of gmp build only will help: #4391

It doesn't seem to help.

> Has there been any progress on a solution?

As I pointed out in [this analysis](https://github.com/Linuxbrew/homebrew-core/issues/4198#issuecomment-331112599), the "solution" is to uninstall gawk.

**Comment by jwhite007** [comment]
@zmwangx

Thanks. I just skimmed most of the comments. Sorry about that. I'll try the uninstall-gawk solution.

Cheers

**Comment by sjackman** [comment]
I believe this cyclic dependency between `glibc` and `gawk` bug is fixed by PR https://github.com/Linuxbrew/homebrew-core/pull/5252.

**Comment by zmwangx** [comment]
Cool, thanks.
