### ISSUE TITLE
openssl@1.1 failed to build on Red Hat Enterprise Linux Server release 7.3 (Maipo)

### ISSUE THREAD

**Issue by davidlday** [Linuxbrew/homebrew-core#4244]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Attempting to install git on a fresh install. Failed when it hit openssl. Went back and attempted install of openssl and openssl@1.1.
- What happened (include command output)
OpenSSL:
```
Last 15 lines from /home/dayd3/.cache/Homebrew/Logs/openssl/03.make:
cryptlib.c: In function 'CRYPTO_memcmp':
cryptlib.c:1030:1: internal compiler error: Illegal instruction
 }
 ^
0x7f3cc03c108f ???
        /tmp/glibc-20170913-11274-iykgxs/glibc-2.23/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7f3cc03ae824 __libc_start_main
        ../csu/libc-start.c:289
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
make[1]: *** [cryptlib.o] Error 1
make[1]: Leaving directory `/tmp/openssl-20170913-29554-lum914/openssl-1.0.2l/crypto'
make: *** [build_crypto] Error 1
```
OpenSSL@1.1:
```
Last 15 lines from /home/dayd3/.cache/Homebrew/Logs/openssl@1.1/02.make:
crypto/aes/aes_ige.c: In function 'AES_ige_encrypt':
crypto/aes/aes_ige.c:284:1: internal compiler error: Illegal instruction
 }
 ^
0x7f9bf1c8f08f ???
        /tmp/glibc-20170913-11274-iykgxs/glibc-2.23/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7f9bf1c7c824 __libc_start_main
        ../csu/libc-start.c:289
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
make[1]: *** [crypto/aes/aes_ige.o] Error 1
make[1]: Leaving directory `/tmp/openssl@1.1-20170913-32625-c966t2/openssl-1.1.0f'
make: *** [all] Error 2
```
- What you expected to happen
I expected git to install (initially).
- Step-by-step reproduction instructions (by running `brew install` commands)
```brew install git```
```brew install openssl```
[Resulting GIST](https://gist.github.com/anonymous/7e822ef143708757f2d660965f520669)
```brew install openssl@1.1```
[Resulting GIST](https://gist.github.com/anonymous/ad806f845f7b99b2300540e4159bdaad)

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by davidlday** [comment]
I came across [Issue #488](https://github.com/Linuxbrew/brew/issues/488) on Linuxbrew/brew and thought I'd give the following a shot:

`HOMEBREW_BUILD_FROM_SOURCE=1 brew install openssl`

This worked. I also tried for openssl@1.1 but it didn't work. I don't have a need for openssl@1.1, but figured this info might be useful.

**Comment by andrewyatz** [comment]
I'm seeing a similar problem now but linked into compiling anything on the most recent version of Linuxbrew. Lots of internal instruction errors appearing. I'm on RHEL7.2 but this was working more than a week ago. It looks like it's gone wrong over the past week.

**Comment by andrewyatz** [comment]
I've also tried to go back to glibc 2.19 and this has resulted in the same error

**Comment by andrewyatz** [comment]
I've just tried working on this again and reverted back to using glibc 2.19 and gmp 6.1.1. Compilation now works for pkg-config and hello. I think something has gone badly wrong in the gmp 6.1.2 bottle

**Comment by sjackman** [comment]
```
internal compiler error: Illegal instruction

**Comment by andrewyatz** [comment]
Think you're right there from reading that issue

**Comment by sjackman** [comment]
You can downgrade to the 6.1.1 bottle, or you can build `gmp` 6.1.2 from source.
```
brew remove gcc
brew reinstall -s gmp
```

**Comment by iMichka** [comment]
We pushed new gmp bottles (https://github.com/Linuxbrew/brew/issues/488)

Please `brew update && brew uninstall gmp @@ brew install gmp`

**Comment by andrewyatz** [comment]
:+1: this works! My environment is working again. Thank you!

**Comment by iMichka** [comment]
Nice. Thanks for your patience. Closing here.

**Comment by davidlday** [comment]
Thank you, @iMichka & @andrewyatz ! I'll give it another go in the next day or so, but I trust it's fixed. :)

**Comment by davidlday** [comment]
Problem fixed for me as well. Thank you!
