### ISSUE TITLE
linux-headers: Any chance of kernel v2.6 support, linux-headers in particular?

### ISSUE THREAD

**Issue by anemator** [Linuxbrew/homebrew-core#433]

**Comment by sjackman** [comment]
What problem are you trying to solve? Linuxbrew supports kernels as old as 2.6.19. If you are experiencing an error message, please report the command that your ran and the error message.

**Comment by anemator** [comment]
The problem arises when gcc-5.3 is installed but unlinked since I don't want to use that as my default compiler. I believe I've seen a few issues because of this, but the only one I can recall is clang complaining about missing libatomic.so. Is there a simple way for linuxbrew to use gcc-5.3 unlinked but the rest of the system use the standard install (gcc-4.4.7 on RedHat6)? The only way I can see to do this is to have gcc-5.3 unlinked, then append ~/.linuxbrew/opt/gcc/... to PATH, LD_LIBRARY_PATH, etc. for each of the commands that was built using gcc-5.3. Thanks for your help and for linuxbrew!

**Comment by sjackman** [comment]
Unlinking `gcc` is definitely not supported and will break things, as you've seen. My best suggestion is to
```sh
brew link gcc
ln -s /usr/bin/gcc44 `brew --prefix`/bin/gcc-4.4
ln -s /usr/bin/g++44 `brew --prefix`/bin/g++-4.4
ln -s /usr/bin/gfortran44 `brew --prefix`/bin/gfortran-4.4
export HOMEBREW_CC=gcc-4.4
```

**Comment by sjackman** [comment]
> Thanks for your help and for linuxbrew!

My pleasure! :smile:

**Comment by anemator** [comment]
Closing this since its more an issue with my environment. Thanks!
