### ISSUE TITLE
libsoup on Ubuntu 17.04 server

### ISSUE THREAD

**Issue by half2me** [Linuxbrew/homebrew-core#4347]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I tried installing libsoup with `brew install libsoup`
My gist-logs: https://gist.github.com/anonymous/6be730c79057880249d5d61fdc0fdd22
Its failing here: `checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool`
I did this: `sudo apt install libxml-parser-perl` Its working fine now.
I know ruby is listed as a dependency for brew, but maybe we should mention this as well?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. It is a somewhat know problem.

I am working on a solution, see #4451.

**Comment by half2me** [comment]
cool, shall I close this Issue, or lets leave it open until its resolved?

**Comment by iMichka** [comment]
I'm working on a fix here: #4448

I'll run a normal build to confirm that it fails first, and then I'll update the formulae, as we have now a strategy on how to fix this. I'll close here, we can discuss further in #4448
