### ISSUE TITLE
Swig failed to build on CentOS

### ISSUE THREAD

**Issue by keyavi** [Linuxbrew/homebrew-core#435]
https://gist.github.com/anonymous/402518f12cf54f1466dc6de75993f37e

Problem was in glibc

https://gist.github.com/anonymous/f54d67a42cd988007de44aca7c84fd67

**Comment by keyavi** [comment]
@sjackman any idea?

**Comment by sjackman** [comment]
It looks as though `swig` installed correclty. Do you have any problem with `swig`?

I haven't seen this `glibc` error message before:
```
/remote/home/srivaa11/.linuxbrew/bin/gcc-5 -B/remote/home/srivaa11/.linuxbrew/Cellar/binutils/2.26/bin/ /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_main.o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_hout.o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_cout.o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_parse.o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_scan.o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_util.o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_svcout.o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_clntout.o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_tblout.o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpc_sample.o  -o /tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpcgen
/remote/home/srivaa11/.linuxbrew/Cellar/binutils/2.26/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: *** [/tmp/glibc-20160620-10071-7nj4ye/glibc-2.19/build/sunrpc/cross-rpcgen] Error 1
```

@DoomHammer Is this the error message you see when brewing `glibc` without the host's `glibc` devel package installed?

Try…
```
sudo yum groupinstall 'Development Tools' 
brew install glibc
```

You have Linuxbrew `gcc` installed but not `glibc`, which is unusual. I would recommend starting over with a clean installation of Linuxbrew (if possible installed in `/home/linuxbrew/.linuxbrew`) and run
```sh
brew install gcc swig
```

**Comment by keyavi** [comment]
Thanks for the reply!!
Actually, the problem is I am working on non-admin environment and cannot use yum.
But I found a way out using conda to install swig and clean installation of Linuxbrew.

Thanks again!!

**Comment by sjackman** [comment]
Glad to hear that you found a workaround.

**Comment by keyavi** [comment]
Just curious how do you came to know that there was a problem with glibc?
Because there was no such lines (posted by you above) in the gist which I have forwarded.

**Comment by sjackman** [comment]
The error message was in this truncated log:
https://gist.github.com/anonymous/f54d67a42cd988007de44aca7c84fd67#file-02-make-L1
https://gist.github.com/anonymous/f54d67a42cd988007de44aca7c84fd67/raw/12635f84f19e4551dd1897b051f7079cb28666ae/02.make

**Comment by keyavi** [comment]
ohhh got it!!!
stupid of me.
You are awesome!!!

**Comment by sjackman** [comment]
@DoomHammer How do you build `glibc` when the host system does not provide `libc.so`?

**Comment by DoomHammer** [comment]
@sjackman That is the problem. I still haven't found a good solution.

Tried `brew install --force-bottle glibc && brew unlink glibc`, then build a new one but it has its own problems.

Tried installing "less-demanding" libc (`musl`) first, but `glibc` requires `glibc` to compile and no other will do.

Still working on it, unfortunately :(
