### ISSUE TITLE
gst-python (--with-python3) cannot find pygobject-3.0

### ISSUE THREAD

**Issue by half2me** [Linuxbrew/homebrew-core#4356]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I tried installing gst-python with `brew install --with-python3 --without-python gst-python`
It says `No package 'pygobject-3.0' found`
Here are the logs: https://gist.github.com/2d2abc3a3b56ab210a7e1c56ca067965
I tried `brew reinstall --with-python3 --without-python pygobject3` but it did not fix the problem.

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by iMichka** [comment]
I tested this, and it fails on mac too. It is good that you reported this here first.

Could you please open an issue here: https://github.com/Homebrew/homebrew-core/
Make sure to fill out the issue template there too, and tell them that it is broken on mac too. Add me as cc so I can follow the discussion. Won't have time to fix this myself in the next days; but upstream has maybe some time to spare.

I'll close this issue as this is not a Linuxbrew issue per-se, as it needs to be fixed on mac first.

**Comment by half2me** [comment]
strange, I've been using gst-python on my mac for quite awhile now, and never had any problems. (Sierra)

**Comment by half2me** [comment]
Seems like I built it when it was still building. I've filed an Issue, with a proposed fix included:
https://github.com/Homebrew/homebrew-core/issues/18709

**Comment by half2me** [comment]
@iMichka This has been fixed upstream. Could you pull it in?

**Comment by iMichka** [comment]
It will come in with the regular updates, but it may take some days. I have currently a little bit less time so we are lagging behind upstream a little bit. I hope things will settle down in the next days.
