### ISSUE TITLE
Error: Failed to install vendor ruby

### ISSUE THREAD

**Issue by JeffWScott** [Linuxbrew/homebrew-core#4389]
I have done both installs (auto and manual) on the main page and afterwards I get 
Error: Failed to install vendor ruby.
Error: Failed to install vendor Ruby
no matter what brew command I use.

I googled those errors and ran a few commands to install pre-recs but still I get those errors.

Can someone help please?

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

thanks!

**Comment by iMichka** [comment]
Hi. Could you please fill out the issue template? I do not have enough information to help you. Thanks.

**Comment by iMichka** [comment]
I'll reopen this if the needed information is provided. Thanks for your comprehension.
