### ISSUE TITLE
brew install dub

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#439]
./build.sh

Generating version file...
fatal: Not a git repository (or any of the parent directories): .git
Running dmd...
Error: cannot find source code for runtime library file 'object.d'
       dmd might not be correctly installed. Run 'dmd -man' for installation instructions.
import path[0] = source
...

**Comment by rwhogg** [comment]
Building a bottle for this at https://github.com/Linuxbrew/homebrew-core/pull/440

**Comment by rwhogg** [comment]
The bottle was successfully built!

The bottle for `dub` will only work if Linuxbrew is installed in `/home/linuxbrew/.linuxbrew`, so you may wish to reinstall there (if you haven't already done so) and then try installing again.

Thanks for the bug reports!

**Comment by timotheecour** [comment]
linuxbrew was indeed installed in ~/.linuxbrew, however this still failed because I had another dmd in my PATH:
which dmd
some_other_path/dmd
~/.linuxbrew/bin/dmd

removing some_other_path from $PATH did the trick, however linuxbrew/brew should work regardless of user's PATH and be as self contained as possible methinks

**Comment by rwhogg** [comment]
Not sure, but it might be possible to have `dub` build in the super, rather than standard, environment.

I'll do my best to take a look at that pull request this weekend (sorry, really busy with school this week).

**Comment by timotheecour** [comment]
ok, it' just a 1 liner

**Comment by sjackman** [comment]
Does Linuxbrew not add `$HOMEBREW_PREFIX/bin` to the front of its path in `ENV.std`? If not, it probably should.

**Comment by rwhogg** [comment]
```
unless ORIGINAL_PATHS.include? HOMEBREW_PREFIX/"bin"
      base.prepend_path "PATH", "#{HOMEBREW_PREFIX}/bin"
    end
```

It looks like it does. My guess is the problem is that Linuxbrew's not the first place searched in his PATH.

@timotheecour, can you please print your PATH variables both before and after accomodating for Linuxbrew please? Thanks a bunch!

**Comment by sjackman** [comment]
The above looks like a design choice not to place `$HOMEBREW_PREFIX/bin` in the path. I can understand that choice to allow the user to override a few executables provided by Linuxbrew, but `brew doctor` should definitely give a warning if `$HOMEBREW_PREFIX/bin` is not first in `PATH`, and it does not.
