### ISSUE TITLE
brew upgrade fail

### ISSUE THREAD

**Issue by yzhzu** [Linuxbrew/homebrew-core#4444]
hello, all, today, I want to upgrade homebrew in our server. however, I tried several times, it still failed. can someone help me to deal with the error ? thanks very much.the error information  as following:   

Upgrading sphinx-doc 
==> Installing dependencies for sphinx-doc: binutils, linux-headers, glibc, gmp, mpfr, isl, gcc, sqlite, tcl-tk, python
==> Installing sphinx-doc dependency: binutils
==> Downloading https://linuxbrew.bintray.com/bottles/binutils-2.29.x86_64_linux.bottle.tar.gz

curl: (77) error setting certificate verify locations:
  CAfile: /home/rcmm/.linuxbrew/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
Error: Failed to download resource "binutils"
Download failed: https://linuxbrew.bintray.com/bottles/binutils-2.29.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://ftp.gnu.org/gnu/binutils/binutils-2.29.tar.gz
Already downloaded: /home/rcmm/.cache/Homebrew/binutils-2.29.tar.gz
==> ./configure  --with-sysroot=/ --enable-deterministic-archives --prefix=/home/rcmm/.linuxbrew/Cellar/binutils/2.29 --infodir=/home/rcmm/.linuxbrew/Cellar/binutils/2.29/share/info --mandir=
==> make
Last 15 lines from /home/rcmm/.cache/Homebrew/Logs/binutils/02.make:
gcc-5 -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/home/rcmm/.linuxbrew/Cellar/binutils/2.29/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=TRUE -g -O2 -c earmelfb.c
gcc-5 -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/home/rcmm/.linuxbrew/Cellar/binutils/2.29/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=TRUE -g -O2 -c earmelfb_fbsd.c
/bin/sh ./libtool --tag=CC   --mode=link gcc-5 -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=TRUE -g -O2  -static-libstdc++ -static-libgcc  -o ld-new ldgram.o ldlex-wrapper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o ldwrite.o ldexp.o ldemul.o ldver.o ldmisc.o ldfile.o ldcref.o plugin.o ldbuildid.o eaix5ppc.o eaix5rs6.o eaixppc.o eaixrs6.o ealpha.o ealphavms.o earcv2elf.o earcv2elfx.o earcelf.o earcelf_prof.o earclinux.o earclinux_nps.o earclinux_prof.o earm_epoc_pe.o earm_wince_pe.o earmaoutb.o earmaoutl.o earmcoff.o earmelf.o earmelf_fbsd.o earmelf_fuchsia.o earmelf_linux.o earmelf_linux_eabi.o earmelf_nacl.o earmelf_nbsd.o earmelf_phoenix.o earmelf_vxworks.o earmelfb.o earmelfb_fbsd.o earmelfb_fuchsia.o earmelfb_linux.o earmelfb_linux_eabi.o earmelfb_nacl.o earmelfb_nbsd.o earmnbsd.o earmnto.o earmpe.o earmsymbian.o eavr1.o eavr2.o eavr25.o eavr3.o eavr31.o eavr35.o eavr4.o eavr5.o eavr51.o eavr6.o eavrxmega1.o eavrxmega2.o eavrxmega3.o eavrxmega4.o eavrxmega5.o eavrxmega6.o eavrxmega7.o eavrtiny.o ecoff_i860.o ecoff_sparc.o ecrisaout.o ecriself.o ecrislinux.o ed10velf.o ed30v_e.o ed30v_o.o ed30velf.o edelta68.o eelf32_dlx.o eelf32_i860.o eelf32_i960.o eelf32_sparc.o eelf32_sparc_sol2.o eelf32_sparc_vxworks.o eelf32_spu.o eelf32_tic6x_be.o eelf32_tic6x_le.o eelf32_tic6x_linux_be.o eelf32_tic6x_linux_le.o eelf32_tic6x_elf_be.o eelf32_tic6x_elf_le.o eelf32am33lin.o eelf32bfin.o eelf32bfinfd.o eelf32cr16.o eelf32cr16c.o eelf32crx.o eelf32epiphany.o eelf32epiphany_4x4.o eelf32fr30.o eelf32frv.o eelf32frvfd.o eelf32ft32.o eelf32i370.o eelf32ip2k.o eelf32iq10.o eelf32iq2000.o eelf32lm32.o eelf32lm32fd.o eelf32lppc.o eelf32lppclinux.o eelf32lppcnto.o eelf32lppcsim.o eelf32m32c.o eelf32mb_linux.o eelf32mbel_linux.o eelf32mcore.o eelf32mep.o eelf32metag.o eelf32microblazeel.o eelf32microblaze.o eelf32moxie.o emoxiebox.o eelf32mt.o eelf32or1k.o eelf32or1k_linux.o eelf32ppc.o eelf32ppc_fbsd.o eelf32ppclinux.o eelf32ppcnto.o eelf32ppcsim.o eelf32ppcvxworks.o eelf32ppcwindiss.o eelf32lriscv.o eelf32rl78.o eelf32rx.o eelf32tilegx.o eelf32tilegx_be.o eelf32tilepro.o eelf32vax.o eelf32visium.o eelf32xc16x.o eelf32xc16xl.o eelf32xc16xs.o eelf32xstormy16.o eelf32xtensa.o eelf_i386.o eelf_i386_be.o eelf_i386_chaos.o eelf_i386_fbsd.o eelf_i386_ldso.o eelf_i386_nacl.o eelf_i386_sol2.o eelf_i386_vxworks.o eelf_iamcu.o eelf_s390.o egld960.o egld960coff.o eh8300.o eh8300elf.o eh8300elf_linux.o eh8300h.o eh8300helf.o eh8300helf_linux.o eh8300hn.o eh8300hnelf.o eh8300s.o eh8300self.o eh8300self_linux.o eh8300sn.o eh8300snelf.o eh8300sx.o eh8300sxelf.o eh8300sxelf_linux.o eh8300sxn.o eh8300sxnelf.o eh8500.o eh8500b.o eh8500c.o eh8500m.o eh8500s.o ehp300bsd.o ehp3hpux.o ehppaelf.o ehppalinux.o ehppanbsd.o ehppaobsd.o ei386aout.o ei386beos.o ei386bsd.o ei386coff.o ei386go32.o ei386linux.o ei386lynx.o ei386mach.o ei386moss.o ei386msdos.o ei386nbsd.o ei386nto.o ei386nw.o ei386pe.o ei386pe_posix.o elnk960.o em32relf.o em32relf_linux.o em32rlelf.o em32rlelf_linux.o em68hc11elf.o em68hc11elfb.o em68hc12elf.o em68hc12elfb.o em68k4knbsd.o em68kaout.o em68kaux.o em68kcoff.o em68kelf.o em68kelfnbsd.o em68klinux.o em68knbsd.o em68kpsos.o em88kbcs.o emcorepe.o emn10200.o emn10300.o emsp430elf.o emsp430X.o ends32elf.o ends32elf16m.o ends32elf_linux.o ends32belf.o ends32belf16m.o ends32belf_linux.o enews.o ens32knbsd.o enios2elf.o enios2linux.o epc532macha.o epdp11.o epjelf.o epjlelf.o eppclynx.o eppcmacos.o eppcnw.o eppcpe.o epruelf.o eriscix.o escore3_elf.o escore7_elf.o esh.o eshelf.o eshelf32.o eshelf32_linux.o eshelf32_nbsd.o eshelf_fd.o eshelf_linux.o eshelf_nbsd.o eshelf_nto.o eshelf_uclinux.o eshelf_vxworks.o eshl.o eshlelf.o eshlelf32.o eshlelf32_linux.o eshlelf32_nbsd.o eshlelf_fd.o eshlelf_linux.o eshlelf_nbsd.o eshlelf_nto.o eshlelf_vxworks.o eshlsymbian.o eshpe.o esparcaout.o esparclinux.o esparcnbsd.o est2000.o esun3.o esun4.o etic30aout.o etic30coff.o etic3xcoff.o etic3xcoff_onchip.o etic4xcoff.o etic54xcoff.o etic80coff.o ev850.o ev850_rh850.o evanilla.o evax.o evaxnbsd.o evsta.o ew65.o exgateelf.o ez80.o ez8001.o ez8002.o eaarch64elf.o eaarch64elf32.o eaarch64elfb.o eaarch64elf32b.o eaarch64cloudabi.o eaarch64cloudabib.o eaarch64fbsd.o eaarch64fbsdb.o eaarch64linux.o eaarch64linuxb.o eaarch64linux32.o eaarch64linux32b.o eelf32_x86_64.o eelf32_x86_64_nacl.o eelf32b4300.o eelf32bmip.o eelf32bmipn32.o eelf32bsmip.o eelf32btsmip.o eelf32btsmip_fbsd.o eelf32btsmipn32.o eelf32btsmipn32_fbsd.o eelf32ebmip.o eelf32ebmipvxworks.o eelf32elmip.o eelf32elmipvxworks.o eelf32l4300.o eelf32lmip.o eelf32lr5900.o eelf32lr5900n32.o eelf32lsmip.o eelf32ltsmip.o eelf32ltsmip_fbsd.o eelf32ltsmipn32.o eelf32ltsmipn32_fbsd.o eelf32mipswindiss.o eelf64_aix.o eelf64_ia64.o eelf64_ia64_fbsd.o eelf64_ia64_vms.o eelf64_s390.o eelf64_sparc.o eelf64_sparc_fbsd.o eelf64_sparc_sol2.o eelf64alpha.o eelf64alpha_fbsd.o eelf64alpha_nbsd.o eelf64bmip.o eelf64btsmip.o eelf64btsmip_fbsd.o eelf64hppa.o eelf64lppc.o eelf64lriscv.o eelf64ltsmip.o eelf64ltsmip_fbsd.o eelf64mmix.o eelf64ppc.o eelf64ppc_fbsd.o eelf64rdos.o eelf64tilegx.o eelf64tilegx_be.o eelf_l1om.o eelf_l1om_fbsd.o eelf_k1om.o eelf_k1om_fbsd.o eelf_x86_64.o eelf_x86_64_cloudabi.o eelf_x86_64_fbsd.o eelf_x86_64_nacl.o eelf_x86_64_sol2.o ehppa64linux.o ei386pep.o emmo.o eshelf64.o eshelf64_nbsd.o eshlelf64.o eshlelf64_nbsd.o deffilep.o pe-dll.o pep-dll.o ../bfd/libbfd.la ../libiberty/libiberty.a  -ldl -ldl 
libtool: link: gcc-5 -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=TRUE -g -O2 -static-libstdc++ -static-libgcc -o ld-new ldgram.o ldlex-wrapper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o ldwrite.o ldexp.o ldemul.o ldver.o ldmisc.o ldfile.o ldcref.o plugin.o ldbuildid.o eaix5ppc.o eaix5rs6.o eaixppc.o eaixrs6.o ealpha.o ealphavms.o earcv2elf.o earcv2elfx.o earcelf.o earcelf_prof.o earclinux.o earclinux_nps.o earclinux_prof.o earm_epoc_pe.o earm_wince_pe.o earmaoutb.o earmaoutl.o earmcoff.o earmelf.o earmelf_fbsd.o earmelf_fuchsia.o earmelf_linux.o earmelf_linux_eabi.o earmelf_nacl.o earmelf_nbsd.o earmelf_phoenix.o earmelf_vxworks.o earmelfb.o earmelfb_fbsd.o earmelfb_fuchsia.o earmelfb_linux.o earmelfb_linux_eabi.o earmelfb_nacl.o earmelfb_nbsd.o earmnbsd.o earmnto.o earmpe.o earmsymbian.o eavr1.o eavr2.o eavr25.o eavr3.o eavr31.o eavr35.o eavr4.o eavr5.o eavr51.o eavr6.o eavrxmega1.o eavrxmega2.o eavrxmega3.o eavrxmega4.o eavrxmega5.o eavrxmega6.o eavrxmega7.o eavrtiny.o ecoff_i860.o ecoff_sparc.o ecrisaout.o ecriself.o ecrislinux.o ed10velf.o ed30v_e.o ed30v_o.o ed30velf.o edelta68.o eelf32_dlx.o eelf32_i860.o eelf32_i960.o eelf32_sparc.o eelf32_sparc_sol2.o eelf32_sparc_vxworks.o eelf32_spu.o eelf32_tic6x_be.o eelf32_tic6x_le.o eelf32_tic6x_linux_be.o eelf32_tic6x_linux_le.o eelf32_tic6x_elf_be.o eelf32_tic6x_elf_le.o eelf32am33lin.o eelf32bfin.o eelf32bfinfd.o eelf32cr16.o eelf32cr16c.o eelf32crx.o eelf32epiphany.o eelf32epiphany_4x4.o eelf32fr30.o eelf32frv.o eelf32frvfd.o eelf32ft32.o eelf32i370.o eelf32ip2k.o eelf32iq10.o eelf32iq2000.o eelf32lm32.o eelf32lm32fd.o eelf32lppc.o eelf32lppclinux.o eelf32lppcnto.o eelf32lppcsim.o eelf32m32c.o eelf32mb_linux.o eelf32mbel_linux.o eelf32mcore.o eelf32mep.o eelf32metag.o eelf32microblazeel.o eelf32microblaze.o eelf32moxie.o emoxiebox.o eelf32mt.o eelf32or1k.o eelf32or1k_linux.o eelf32ppc.o eelf32ppc_fbsd.o eelf32ppclinux.o eelf32ppcnto.o eelf32ppcsim.o eelf32ppcvxworks.o eelf32ppcwindiss.o eelf32lriscv.o eelf32rl78.o eelf32rx.o eelf32tilegx.o eelf32tilegx_be.o eelf32tilepro.o eelf32vax.o eelf32visium.o eelf32xc16x.o eelf32xc16xl.o eelf32xc16xs.o eelf32xstormy16.o eelf32xtensa.o eelf_i386.o eelf_i386_be.o eelf_i386_chaos.o eelf_i386_fbsd.o eelf_i386_ldso.o eelf_i386_nacl.o eelf_i386_sol2.o eelf_i386_vxworks.o eelf_iamcu.o eelf_s390.o egld960.o egld960coff.o eh8300.o eh8300elf.o eh8300elf_linux.o eh8300h.o eh8300helf.o eh8300helf_linux.o eh8300hn.o eh8300hnelf.o eh8300s.o eh8300self.o eh8300self_linux.o eh8300sn.o eh8300snelf.o eh8300sx.o eh8300sxelf.o eh8300sxelf_linux.o eh8300sxn.o eh8300sxnelf.o eh8500.o eh8500b.o eh8500c.o eh8500m.o eh8500s.o ehp300bsd.o ehp3hpux.o ehppaelf.o ehppalinux.o ehppanbsd.o ehppaobsd.o ei386aout.o ei386beos.o ei386bsd.o ei386coff.o ei386go32.o ei386linux.o ei386lynx.o ei386mach.o ei386moss.o ei386msdos.o ei386nbsd.o ei386nto.o ei386nw.o ei386pe.o ei386pe_posix.o elnk960.o em32relf.o em32relf_linux.o em32rlelf.o em32rlelf_linux.o em68hc11elf.o em68hc11elfb.o em68hc12elf.o em68hc12elfb.o em68k4knbsd.o em68kaout.o em68kaux.o em68kcoff.o em68kelf.o em68kelfnbsd.o em68klinux.o em68knbsd.o em68kpsos.o em88kbcs.o emcorepe.o emn10200.o emn10300.o emsp430elf.o emsp430X.o ends32elf.o ends32elf16m.o ends32elf_linux.o ends32belf.o ends32belf16m.o ends32belf_linux.o enews.o ens32knbsd.o enios2elf.o enios2linux.o epc532macha.o epdp11.o epjelf.o epjlelf.o eppclynx.o eppcmacos.o eppcnw.o eppcpe.o epruelf.o eriscix.o escore3_elf.o escore7_elf.o esh.o eshelf.o eshelf32.o eshelf32_linux.o eshelf32_nbsd.o eshelf_fd.o eshelf_linux.o eshelf_nbsd.o eshelf_nto.o eshelf_uclinux.o eshelf_vxworks.o eshl.o eshlelf.o eshlelf32.o eshlelf32_linux.o eshlelf32_nbsd.o eshlelf_fd.o eshlelf_linux.o eshlelf_nbsd.o eshlelf_nto.o eshlelf_vxworks.o eshlsymbian.o eshpe.o esparcaout.o esparclinux.o esparcnbsd.o est2000.o esun3.o esun4.o etic30aout.o etic30coff.o etic3xcoff.o etic3xcoff_onchip.o etic4xcoff.o etic54xcoff.o etic80coff.o ev850.o ev850_rh850.o evanilla.o evax.o evaxnbsd.o evsta.o ew65.o exgateelf.o ez80.o ez8001.o ez8002.o eaarch64elf.o eaarch64elf32.o eaarch64elfb.o eaarch64elf32b.o eaarch64cloudabi.o eaarch64cloudabib.o eaarch64fbsd.o eaarch64fbsdb.o eaarch64linux.o eaarch64linuxb.o eaarch64linux32.o eaarch64linux32b.o eelf32_x86_64.o eelf32_x86_64_nacl.o eelf32b4300.o eelf32bmip.o eelf32bmipn32.o eelf32bsmip.o eelf32btsmip.o eelf32btsmip_fbsd.o eelf32btsmipn32.o eelf32btsmipn32_fbsd.o eelf32ebmip.o eelf32ebmipvxworks.o eelf32elmip.o eelf32elmipvxworks.o eelf32l4300.o eelf32lmip.o eelf32lr5900.o eelf32lr5900n32.o eelf32lsmip.o eelf32ltsmip.o eelf32ltsmip_fbsd.o eelf32ltsmipn32.o eelf32ltsmipn32_fbsd.o eelf32mipswindiss.o eelf64_aix.o eelf64_ia64.o eelf64_ia64_fbsd.o eelf64_ia64_vms.o eelf64_s390.o eelf64_sparc.o eelf64_sparc_fbsd.o eelf64_sparc_sol2.o eelf64alpha.o eelf64alpha_fbsd.o eelf64alpha_nbsd.o eelf64bmip.o eelf64btsmip.o eelf64btsmip_fbsd.o eelf64hppa.o eelf64lppc.o eelf64lriscv.o eelf64ltsmip.o eelf64ltsmip_fbsd.o eelf64mmix.o eelf64ppc.o eelf64ppc_fbsd.o eelf64rdos.o eelf64tilegx.o eelf64tilegx_be.o eelf_l1om.o eelf_l1om_fbsd.o eelf_k1om.o eelf_k1om_fbsd.o eelf_x86_64.o eelf_x86_64_cloudabi.o eelf_x86_64_fbsd.o eelf_x86_64_nacl.o eelf_x86_64_sol2.o ehppa64linux.o ei386pep.o emmo.o eshelf64.o eshelf64_nbsd.o eshlelf64.o eshlelf64_nbsd.o deffilep.o pe-dll.o pep-dll.o  ../bfd/.libs/libbfd.a -L/tmp/binutils-20170924-27696-1l7uelr/binutils-2.29/zlib -lz ../libiberty/libiberty.a -ldl
make[4]: leaving diretory “/tmp/binutils-20170924-27696-1l7uelr/binutils-2.29/ld”
make[3]: leaving diretory“/tmp/binutils-20170924-27696-1l7uelr/binutils-2.29/ld”
make[2]: leaving diretory“/tmp/binutils-20170924-27696-1l7uelr/binutils-2.29/ld”
make[4]: leaving diretory“/tmp/binutils-20170924-27696-1l7uelr/binutils-2.29/gold”
make[3]: *** [all-recursive] error 1
make[3]: leaving diretory “/tmp/binutils-20170924-27696-1l7uelr/binutils-2.29/gold”
make[2]: *** [all] error 2
make[2]: leaving diretory “/tmp/binutils-20170924-27696-1l7uelr/binutils-2.29/gold”
make[1]: *** [all-gold] error 2
make[1]: leaving diretory“/tmp/binutils-20170924-27696-1l7uelr/binutils-2.29”
make: *** [all] error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

Error: curl failed! 
curl: (77) error setting certificate verify locations:
  CAfile: /home/rcmm/.linuxbrew/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
curl: (3) <url> malformed

**Comment by iMichka** [comment]
Looks like #236

I think I broke it during on of the last merges. Here is a fix: #4457

**Comment by iMichka** [comment]
Fix merged, please test again.

**Comment by iMichka** [comment]
I'll close this. Please tell me if it not fixed for you. In that case I'll reopen this issue. Thanks.
