### ISSUE TITLE
GCC 6.1

### ISSUE THREAD

**Issue by zbeekman** [Linuxbrew/homebrew-core#447]
### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

What needs to happen to get GCC 6.1 from upstream? It doesn't appear that any dependencies need updating...

On OS X I have:

```
 brew list --versions $(brew deps gcc) xz
gmp 6.1.0
isl 0.15
libmpc 1.0.3
mpfr 3.1.4
xz 5.2.2
```

And on Linux (Ubuntu-precise 64) I have:

```
brew list --versions $(brew deps gcc) xz
binutils 2.26
glibc 2.19
gmp 6.1.0
isl 0.15
libmpc 1.0.3
linux-headers 3.18.27
mpfr 3.1.4
zlib 1.2.8
xz 5.2.2
```

**Comment by sjackman** [comment]
Linuxbrew is unfortunately a month behind upstream Homebrew at the moment. There's an unusually large patch upstream that causes lots of merge conflicts, and I haven't yet had the time to resolve it, as I'm exceptionally busy at work. 😕 Sorry. Hopefully soon.

**Comment by zbeekman** [comment]
@sjackman let me know if there's anything I can do to help.

**Comment by sjackman** [comment]
Will do. Thanks for the offer, Izaak.

**Comment by sjackman** [comment]
@dholm opened a PR at https://github.com/Linuxbrew/homebrew-core/pull/2650 to add GCC 6

**Comment by zbeekman** [comment]
any chance we'll get 7 too?

**Comment by sjackman** [comment]
That's the plan, after gcc 6 is merged.
