### ISSUE TITLE
New install: w3m, socat failing due to trouble with openssl@1.1

### ISSUE THREAD

**Issue by DiagonalArg** [Linuxbrew/homebrew-core#4538]
New install, CentOS 7.  After the install, I tried installing some other things, including w3m and socat.  They both failed on openssl@1.1.  Error is:

==> Installing w3m dependency: openssl@1.1      
==> Downloading https://www.openssl.org/source/openssl-1.1.0f.tar.gz
######################################################################## 100.0%
==> perl ./Configure --prefix=/home/user/.linuxbrew/Cellar/openssl@1.1/1.1.0f_1 --openssldir=/home/user/.linuxbrew/etc/openssl@1.1 no-ssl3 no-ssl3-method no-zlib  linux-x86_64             
==> make
==> make test                                   
Last 15 lines from /home/user/.cache/Homebrew/Logs/openssl@1.1/03.make:                       
make[1]: Leaving directory `/home/user/tmp/openssl@1.1-20170930-101365-a2dksl/openssl-1.1.0f' 
make[1]: Entering directory `/home/user/tmp/openssl@1.1-20170930-101365-a2dksl/openssl-1.1.0f'                                                                                                 
( cd test; \
  SRCTOP=../. \
  BLDTOP=../. \
  PERL="/usr/bin/perl" \
  EXE_EXT= \                                    
  OPENSSL_ENGINES=.././engines \
  OPENSSL_DEBUG_MEMORY=on \                     
    /usr/bin/perl .././test/run_tests.pl  )     
Can't locate Module/Load/Conditional.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/sha\
re/perl5 .) at .././test/run_tests.pl line 20.  
BEGIN failed--compilation aborted at .././test/run_tests.pl line 20.                             
make[1]: *** [_tests] Error 2                   
make[1]: Leaving directory `/home/user/tmp/openssl@1.1-20170930-101365-a2dksl/openssl-1.1.0f'
make: *** [tests] Error 2

**Comment by DiagonalArg** [comment]
gist is located here:  https://gist.github.com/DiagonalArg/b9e8aa0fd4fed39981423cb8e8df8ee0

Let me know if you need anything more.

**Comment by iMichka** [comment]
Hi. Thanks for reporting. The error is:

> Can't locate Module/Load/Conditional.pm in @inc

This means that the Conditional perl module is missing. It needs to be added to the formula. You can have a look at the `dnsrend` formula on how to vendor perl modules (resource block + resources/stage block). Would you like to open a pull request for that?

**Comment by DiagonalArg** [comment]
I think you're telling me I need to add something like this, except for the conditional.pm resource, rather than "Net::Pcap::Reassemble"; and then add a resources/stage block, like below. If I follow that path, might I get there?

```
  resource "Net::Pcap::Reassemble" do
    url "https://cpan.metacpan.org/authors/id/J/JR/JRAFTERY/Net-Pcap-Reassemble-0.04.tar.gz"
    mirror "http://search.cpan.org/CPAN/authors/id/J/JR/JRAFTERY/Net-Pcap-Reassemble-0.04.tar.gz"
    sha256 "0bcba2d4134f6d412273a75663628b08b0a164e0a5ecb8a2fd14cdf5237629c4"
  end
```

```
  def install
    resources.each do |r|
      r.stage do
        system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
        system "make"
        system "make", "install"
      end
    end
```

**Comment by iMichka** [comment]
Yes, exactly. That should fix that error. You will need to find out the right URL on can and the sha256. Of course other perl modules may be needed, and you will need to add those accordingly.

**Comment by DiagonalArg** [comment]
Ok, I believe I did what you suggested, which meant just adding the two snippets below - but I'm getting exactly the same error.    

```
  resource "Module::Load::Conditional" do
    # homepage "http://search.cpan.org/~bingos/Module-Load-Conditional-0.68/lib/Module/Load/Conditional.pm"                                                                                       
    url "http://search.cpan.org/CPAN/authors/id/B/BI/BINGOS/Module-Load-Conditional-0.68.tar.gz"
    sha256 "7627b55cd94a2f1a4667f9203e2c990cad015bf34ec6b41b4f73af848f0698fd"
  end
```

And, inserted before the other perl command:

```
    resource("Module::Load::Conditional").stage do
      system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
      system "make"
      system "make", "install"
    end
```

**Comment by tundratim** [comment]
I am seeing a similar problem.  It looks like part of the issue is that git it installed and it needs curl.  Curl installed openssl 1.0.1n.  Now I want to install socat and it wants openssl 1.1.0g.

**Comment by tundratim** [comment]
@iMichka 

OK I think I've found at least part of the problem.  linuxbrew base ships with openssl 1.0.1n.  The socat formula is demanding 1.1.0g.  When brew tries to build this dependency, if the newer openssl fails its unit tests.  There is something about having both of these versions coexist that is causing the issue.

I went into the socat formula and told it to just use the older version and then compiled from source.  The compilation and installation worked just find ,but I don't know if the binary actually works correctly.

Finding a way for both these versions to coexist on the same machine (because you still need the older one due to the way the newer versions break the API) would be the best approach, but I'm not quire sure how to proceed to do that with your framework.

**Comment by iMichka** [comment]
Since f97db1388d2603b6fe225969fd147bca9908dca5, `socat` was switched back top an older version of openssl.

Hombrew (and Linuxbrew) gave up on migrating to openssl 1.1.x, because most of the packages are broken when using it. Maybe in 10 years, when everybody is ready, we will be able to update to a newer version.

Installing `socat` should be OK now.
