### ISSUE TITLE
Can't get `brew gist-logs` info locally, and running it uploads personal info to git.

### ISSUE THREAD

**Issue by DiagonalArg** [Linuxbrew/homebrew-core#4548]
I would run brew gist-logs <formula> for reports here, but running it places personal information up on github.  I can't find a way to get that info locally and edit it out. So instead I just run `brew config` and `brew doctor`.  If you guys can fix this, it could be helpful.

**Comment by iMichka** [comment]
You can find the logs in ~/.cache/Homebrew/Logs, edit them, and upload them to gist manually.  Not sure what personal information you are talking about. If that is the case, this is more a thing that needs to be cleared with upstream (the hombrew team). We just use the same commands / features as them.

**Comment by DiagonalArg** [comment]
Ok.  Personal information includes username.

**Comment by iMichka** [comment]
Is it empty? You need to install a formula first. @sjackman the path to the logs is `~/.cache/Homebrew/Logs`, right?

**Comment by sjackman** [comment]
Yep. What's the output of `brew --cache`? Look for a `Logs` subdirectory in there.

**Comment by DiagonalArg** [comment]
Well, 

```
$ brew --cache                 
/home/dev/.cache/Homebrew 
```

but the Logs subdirectory, which exists, is empty!

(This is on my old install that's been working but developed the glibc/gcc problem #4388)

**Comment by sjackman** [comment]
`brew install glibc` should produce log files in that directory. As for the original issue, we don't have plans to remove the username from the log file.

**Comment by DiagonalArg** [comment]
This attempt with installing glibc (since I found there was an update) left me with a glibc/ directory.  Not sure why previous attempts left it empty.
