### ISSUE TITLE
postgis install fails due to scfgal

### ISSUE THREAD

**Issue by sandeep-gh** [Linuxbrew/homebrew-core#4569]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/72d9cd28be5fd8a5c860679eba804ef7
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I was install postgis which fails with following error:
```
Last 15 lines from /home/sandeep/.cache/Homebrew/Logs/postgis/02.make:
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `sfcgal_triangle_set_vertex_from_xyz'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `sfcgal_linestring_num_points'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `sfcgal_polyhedral_surface_polygon_n'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `sfcgal_solid_num_shells'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `sfcgal_triangulated_surface_num_triangles'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `sfcgal_polyhedral_surface_add_polygon'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `sfcgal_point_y'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `sfcgal_linestring_add_point'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `sfcgal_polygon_create'
collect2: error: ld returned 1 exit status
make[2]: *** [raster2pgsql] Error 1
make[2]: Leaving directory `/tmp/postgis-20171004-133427-xs8up7/postgis-2.3.2/raster/loader'
make[1]: *** [rtloader] Error 2
make[1]: Leaving directory `/tmp/postgis-20171004-133427-xs8up7/postgis-2.3.2/raster'
make: *** [all] Error 1
```
The way I was able to fix it was to keep the tmp folder and run 
```

export LD_LIBRARY_PATH=/home/sandeep/.linuxbrew/Cellar/sfcgal/1.3.2/lib64:$LD_LIBRARY_PATH '

```

followed by  ./configure; make; make install

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. I opened a pull request to build a bottle for postgis: #4696

Let's see first if we can reproduce this in our docker container. If that is the case I'll try to work on a fix.
