### ISSUE TITLE
postgres installs but initdb fails

### ISSUE THREAD

**Issue by sandeep-gh** [Linuxbrew/homebrew-core#4581]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/26731eb706bc3e69f449a3acbc06512a

Initidb after installation fails with error message
```
initdb: could not look up effective user ID 21073: user does not exist
```

When I install postgres using system gcc, I don't get this error.

**Comment by iMichka** [comment]
Hi. Thanks for reporting. I have no clue what is going on.

I also saw you asked you question there
https://stackoverflow.com/questions/46567468/postgres-init-could-not-look-effective-user-id-user-does-not-exists

Maybe you could ask on the `postgres` mailing list if they can help you? We did just the packaging, and until proven wrong, I think this is more a setup/runtime problem on your side or on `postgres` side. Not sure how we can help.
