### ISSUE TITLE
Brew install haskell-stack failed (Not enough room for program headers).

### ISSUE THREAD

**Issue by w9** [Linuxbrew/homebrew-core#4609]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/anonymous/760bc6d111df4470e81c826d74232b19
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

`brew install haskell-stack`

- What happened (include command output)

Failed with the above logs. Specifically:

```
strip: /tmp/ghc-20171009-238201-1c3qvuy/ghc-8.2.1/binary/lib/ghc-8.2.1/ghc-prim-0.5.1.0/stGktmgz: Not enough room for program headers, try linking with -N
strip:/tmp/ghc-20171009-238201-1c3qvuy/ghc-8.2.1/binary/lib/ghc-8.2.1/ghc-prim-0.5.1.0/stGktmgz[.note.gnu.build-id]: Bad value
make[1]: *** [install_packages] Error 1
make: *** [install] Error 2
```

- What you expected to happen

The Stack package be installed.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install haskell-stack --verbose`

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. We got exactly the same error here: #4413 

This is why I said to that user:

> I have the feeling that this is an upstream problem, or a problem with your setup. Difficult to say.

> We do not call that strip command. It would be interesting to see if you can build ghc from source outside of homebrew, to see if we are doing something wrong, or if this is an upstream bug. You could also report this error upstream to the ghc people and try to get some help here.

**Comment by iMichka** [comment]
Closing here. Nothing I can do to help you for the moment. Somebody from the community will need to step up and try to fix this with the ghc people. Thanks for your comprehension.
