### ISSUE TITLE
"brew install id3lib" fails on Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by malexander99** [Linuxbrew/homebrew-core#4634]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [Yes] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [Yes] Ran `brew update` and retried your prior step?
- [Yes] Ran `brew doctor`, fixed all issues and retried your prior step?
- [Yes] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
[gist log](https://gist.github.com/anonymous/6cfc7e074116ac7b788c66993ecf9389)

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Tried running "brew install id3lib" 
Here is output:

malexander@malexander-ThinkPad-T440:~/eurowings$ brew install id3lib
==> Downloading https://downloads.sourceforge.net/project/id3lib/id3lib/3.8.3/id3lib-3.8.3.tar.gz
Already downloaded: /home/malexander/.cache/Homebrew/id3lib-3.8.3.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e223e971/id3lib/id3lib-vbr-overflow.patch
Already downloaded: /home/malexander/.cache/Homebrew/id3lib--patch-0ec91c9d89d80f40983c04147211ced8b4a4d8a5be207fbe631f5eefbbd185c2.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e223e971/id3lib/id3lib-main.patch
Already downloaded: /home/malexander/.cache/Homebrew/id3lib--patch-83c8d2fa54e8f88b682402b2a8730dcbcc8a7578681301a6c034fd53e1275463.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e223e971/id3lib/no-iomanip.h.patch
Already downloaded: /home/malexander/.cache/Homebrew/id3lib--patch-da0bd9f3d17f1dd054720c17dfd15062eabdfc4d38126bb1b2ef5e8f39904925.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e223e971/id3lib/automake.patch
Already downloaded: /home/malexander/.cache/Homebrew/id3lib--patch-c1ae2aa04baee7f92301cbed120340682e62e1f839bb61f8f6d3c459a7faf097.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e223e971/id3lib/boolcheck.patch
Already downloaded: /home/malexander/.cache/Homebrew/id3lib--patch-a7881dc25665f284798934ba19092d1eb45ca515a34e5c473accd144aa1a215a.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e223e971/id3lib/patch_id3lib_3.8.3_UTF16_writing_bug.diff
Already downloaded: /home/malexander/.cache/Homebrew/id3lib--patch-71c79002d9485965a3a93e87ecbd7fed8f89f64340433b7ccd263d21385ac969.diff
==> Patching
==> Applying id3lib-vbr-overflow.patch
patching file src/mp3_parse.cpp
==> Applying id3lib-main.patch
patching file examples/demo_convert.cpp
patching file examples/demo_copy.cpp
patching file examples/demo_info.cpp
patching file examples/demo_tag.cpp
patching file examples/findeng.cpp
patching file examples/findstr.cpp
==> Applying no-iomanip.h.patch
patching file configure.in
Hunk #1 succeeded at 227 (offset -1 lines).
==> Applying automake.patch
patching file configure.in
Hunk #6 succeeded at 296 (offset -1 lines).
patching file Makefile.am
==> Applying boolcheck.patch
patching file m4/id3_cxx.m4
==> Applying patch_id3lib_3.8.3_UTF16_writing_bug.diff
patching file ChangeLog
patching file src/io_helpers.cpp
==> autoreconf -fvi
==> ./configure --prefix=/home/malexander/.linuxbrew/Cellar/id3lib/3.8.3_1
==> make install
Last 15 lines from /home/malexander/.cache/Homebrew/Logs/id3lib/03.make:
Makefile:561: recipe for target 'field_integer.lo' failed
make[1]: *** [field_integer.lo] Error 1
field.cpp: In function ‘ID3_FrameID ID3_FindFrameID(const char*)’:
field.cpp:1095:29: error: ‘strlen’ was not declared in this scope
   const int slen = strlen(id);
                             ^
field.cpp:1099:53: error: ‘strcmp’ was not declared in this scope
     if (((strcmp(ID3_FrameDefs[cur].sShortTextID, id) == 0) &&
                                                     ^
Makefile:561: recipe for target 'field.lo' failed
make[1]: *** [field.lo] Error 1
libtool: compile:  g++-5 -DHAVE_CONFIG_H -I. -I.. -I../include/id3 -I../include -g -O2 -Wall -Wno-unused -Wno-inline -Woverloaded-virtual -Wmissing-declarations -c field_binary.cpp -o field_binary.o >/dev/null 2>&1
make[1]: Leaving directory '/tmp/id3lib-20171011-32548-13bg2wp/id3lib-3.8.3/src'
Makefile:448: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

**Comment by iMichka** [comment]
Hi; thanks for reporting. Seems we never built a bottle for `id3lib`, so this formula is sort of "untested" from our side. We are still in the process to package everything for Linux.

Looks like there is some compilation problem here. Maybe you could ask upstream (the `id3lib` people) if they could help you. This will probably need a patch to be able to compile.
