### ISSUE TITLE
brew  install curl , then curl report error: curl: (77) error setting certificate verify locations:

### ISSUE THREAD

**Issue by netroby** [Linuxbrew/homebrew-core#4636]
While using linuxbrew to install swift, i got problem with curl error setting certificate verify locations. 

The solution 

brew postinstall openssl 
brew install curl
Have fun

 

For reference:https://github.com/Linuxbrew/homebrew-core/pull/2924

https://github.com/Linuxbrew/legacy-linuxbrew/issues/238

can we make brew install curl auto postinstall openssl?

**Comment by iMichka** [comment]
Hi. Thanks for reporting. We just had a small discussion about this problem lately, see #4601
Adding @sjackman as cc

I have currently no time to look for a proper solution, so any pull request - ideas are welcome.

**Comment by sjackman** [comment]
`brew install curl` will `brew install openssl`, and that will `brew postinstall openssl`, so it's supposed to work. In your case it didn't. To troubleshoot further we'd need to know the error message of the original `brew install openssl` command.

**Comment by iMichka** [comment]
Without the initial error message, this will be hard to debug. Closing here. If somebody hits a similar error, we have a FAQ entry for a workaround:
https://github.com/Linuxbrew/brew/wiki/FAQ#why-does-curl-fail

Of course if we could get information about what made the postinstall fail would be great.
