### ISSUE TITLE
postgresql: error no list on ubuntu

### ISSUE THREAD

**Issue by dimwael** [Linuxbrew/homebrew-core#4651]
I have installed brew postgresql. but when i use the command : 
brew services start postgresql
I get the error : 
sh: 1: list: not found
Error: Failure while executing:  load -w /home/djappaman/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. Please always fill out the full issue template to help us fix this.

Seems to look similar to this error:
https://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell
Of course there the missing command is `source`, whereas here it is `list`. What shell are you using?

**Comment by khiav223577** [comment]
I got same error. I use bash.
```bash
$ brew services start postgresql
sh: 1: list: not found
sh: 1: list: not found
Error: Failure while executing; `'' load -w /home/khiav/Library/LaunchAgents/homebrew.mxcl.postgresql.plist` exited with 1.
```

**Comment by iMichka** [comment]
> brew services

That command is not working on Linux, only on mac. We need to disable it for Linux, but never had time to do so.

You need to read the postgresql documentation to see how to start the server.
