### ISSUE TITLE
Error: Invalid formula ... version missing for "gotools" resource

### ISSUE THREAD

**Issue by szeck87** [Linuxbrew/homebrew-core#4668]
# Please fill out the issue checklist below, and provide all of the requested information.
This happens with `brew doctor` and `brew update` at the very least, but the error is specific to homebrew-core.  If this is incorrect, please let me know and I'll open an issue under Linuxbrew/brew.

# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Run `brew update` for Travis build
- What happened (include command output)
It errored out almost immediately.  Full build can be viewed here:  https://travis-ci.org/Glavin001/atom-beautify/jobs/287986224

```
Error: Invalid formula: /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
go: version missing for "gotools" resource!
Error: Invalid formula: /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.5.rb
go@1.5: version missing for "gotools" resource!
Error: Invalid formula: /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.8.rb
go@1.8: version missing for "gotools" resource!
Error: Invalid formula: /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/platypus.rb
invalid attribute for formula 'platypus': version (nil)
Error: Invalid formula: /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.7.rb
go@1.7: version missing for "gotools" resource!
Error: Invalid formula: /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.6.rb
go@1.6: version missing for "gotools" resource!
Error: Invalid formula: /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/smlnj.rb
smlnj: version missing for "cm" resource!
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/travis/.linuxbrew/bin/brew tap homebrew/core
```

- What you expected to happen
To update brew formulas without an error

- Step-by-step reproduction instructions (by running `brew install` commands)
I don't have a Linux machine, so this step-by-step relies on Travis. 

1. In the `before_install` step, clone Linuxbrew
2. Run `brew update`

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by takumiabe** [comment]
I don't know why, but it fixed by:

```shell-session
cd $HOME/.linuxbrew/Homebrew/Library/Taps/
mkdir homebrew
git clone git@github.com:Linuxbrew/homebrew-core.git
cd homebrew-core
git checkout be52f8ab6d0e5c088888abbf73566d844e5eb2f3
```

and 
`brew update`

**Comment by szeck87** [comment]
@takumiabe that's just checking out a commit from before the versions were removed.

**Comment by szeck87** [comment]
Fixed with https://github.com/Linuxbrew/homebrew-core/commit/a56e73a398908e5831d00ab70044ecd5ed7fc374. Thanks @iMichka
