### ISSUE TITLE
mongodb: Erroneous 2to3 command

### ISSUE THREAD

**Issue by ckanibal** [Linuxbrew/homebrew-core#4674]
## Troubleshooting checklist
- [x] Run brew update twice.
- [x] Run brew doctor and fix all the warnings (outdated Xcode/CLT and unbrewed dylibs are very likely to cause problems).
- [x] Check that Command Line Tools for Xcode (CLT) and Xcode are up to date.
- [x] If commands fail with permissions errors, check the permissions of /usr/local's subdirectories. If you’re unsure what to do, you can run cd /usr/local && sudo chown -R $(whoami) bin etc include lib sbin share var Frameworks.
- [x] Read through the Common Issues.

## Problem description
The `mongodb`-formula fails to build on a CentOS 6 with native `python3` installed.

## Additional information
The last change-set to the mongodb-formula (ad8466119503443fde2ec013a4b56b18b63c9255) changed the system-call to the `2to3`-command:
https://github.com/Linuxbrew/homebrew-core/blob/4c1cb9590fc6aeb7d4320fb3701442db15b60794/Formula/mongodb.rb#L80

This also applies to a few other formulas. However, those recipes are currently not working for that reason on most distros (checked for CentOS, Ubuntu and Debian) since the binary is usually called `2to3` (without the dash!).

I suggest either reverting those changes or having the python3-formula install a `2to3-` binary.
For now I fixed it by running `$ alias 2to3-=2to3` before the `brew`-command.

@ilovezfs Can you please give us a short comment on your commit? Is there a distribution where the command has a trailing dash?

**Comment by iMichka** [comment]
I think upstream has already removed that dash, see commit dc56a1ea89419226a9cdb4045cd61a7002e96c06 in homebrew-core.

In theory this fix will be merged to linuxbrew during the day (I hope).

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/19319
https://github.com/Homebrew/homebrew-core/pull/19322

**Comment by ckanibal** [comment]
Ah, okay. I didn't see those changes. Feel free to close this issue then!
Thank you @iMichka, @ilovezfs

**Comment by iMichka** [comment]
@ckanibal Should be fixed now. Please update and tell us if it works for you.
