### ISSUE TITLE
Error: No locks available @ rb_file_flock

### ISSUE THREAD

**Issue by albertz** [Linuxbrew/homebrew-core#468]
I just updated and it seemed to have migrated to Homebrew v0.9.9.

Now, whenever I try to install anything, I get this error:

```
$ brew install python3
Error: No locks available @ rb_file_flock - /work/asr2/zeyer/linuxbrew/Library/Locks/python3.brewing
```

This is on a NFS drive. I found some related issues, e.g. [here for RubyGems](https://github.com/rubygems/rubygems/issues/1176). Their solution is basically to ignore the exception ([here](https://github.com/rubygems/rubygems/pull/1327/files)).

**Comment by albertz** [comment]
My workaround for now: I have created a directory on a local disk and symlinked linuxbrew/Library/Locks to it.

**Comment by sjackman** [comment]
I also use use Linuxbrew on NFS and haven't yet encountered this issue. Please report `brew config`. Which version of Ruby are you using? Try `brew install ruby` to upgrade to a recent version of Ruby.

**Comment by iMichka** [comment]
This issue is now 1 year old. Not sure how much support we want to put in supporting NFS drives. I'm closing this, maybe it has already been solved by one of the brew/ruby updates. Anyway, if somebody wants to work on this, pull requests are welcome. Thanks.
