### ISSUE TITLE
brew install jdk fails with 404 errors on the downloads

### ISSUE THREAD

**Issue by AlexanderOMara** [Linuxbrew/homebrew-core#4716]
**Checklist:**
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`?
- [x] This formula is not available on macOS.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs jdk`, said `Error: No logs.` because it didn't get that far.
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.3.3
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 8b51137282a7276d0b349eb5bc70687e7af66d9e
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: def70b693fe43e2312ed5adcd581bb8977bb66b3
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: N/A
Kernel: Linux 4.4.0-97-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.3 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: 20170115
$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
  - Install jdk
- What happened (include command output)
  - Got 404 errors on the downloads:
```
$ brew install jdk
==> Downloading https://linuxbrew.bintray.com/bottles/jdk-9+181.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "jdk"
Download failed: https://linuxbrew.bintray.com/bottles/jdk-9+181.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz
==> Downloading from https://edelivery.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "jdk"
Download failed: http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz
```
- What you expected to happen
  - The downloads to work and install to complete.
- Step-by-step reproduction instructions (by running `brew install` commands)
  - `brew install jdk`

I tried checking the URL's, and I got the following:

https://linuxbrew.bintray.com/bottles/jdk-9+181.x86_64_linux.bottle.tar.gz

> The requested path was not found.

http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz

Redirects to: http://download.oracle.com/errors/download-fail-1505220.html

> Sorry!
>
> In order to download products from Oracle Technology Network you must agree to the OTN license terms.

**Comment by iMichka** [comment]
cc @VonUniGE who worked on this lately. I have not much time to look after this at the moment. Pull requests are welcome!

**Comment by VonUniGE** [comment]
A new version of jdk9 has been released and now Oracle remove old versions from public download. We should maybe cache them? 
I will provide a PR for updating the URL and checksum.

**Comment by VonUniGE** [comment]
Here is the PR : https://github.com/Linuxbrew/homebrew-core/pull/4719

**Comment by iMichka** [comment]
This should be fixed now. Closing.
