### ISSUE TITLE
Invalid formula...Resource "druntime" is defined more than once

### ISSUE THREAD

**Issue by szeck87** [Linuxbrew/homebrew-core#4740]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Run brew update in Travis CI
- What happened (include command output)
Errored out
```
Error: Invalid formula: /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/dmd.rb
Resource "druntime" is defined more than once
Error: Cannot tap homebrew/core: invalid syntax in tap!
```

- What you expected to happen
Not error out
- Step-by-step reproduction instructions (by running `brew install` commands)
1. Start a Travis build against Linux that includes running `brew update`

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by szeck87** [comment]
Build can be viewed here:  https://travis-ci.org/szeck87/atom-beautify/jobs/289746939

**Comment by iMichka** [comment]
Hi. Thanks for reporting. I have opened a pull request to fix this: #4744
The devel block of the dmd formula was there twice, it probably broke during one of the latest merges and I did not directly see it.

**Comment by iMichka** [comment]
> Fixed:  iMichka's build (#10051; push) in Linuxbrew/homebrew-core (master)
> dmd: update 2.076.1_1 bottle for Linuxbrew. (d08d2c2 by LinuxbrewTestBot)

**Comment by iMichka** [comment]
Please update and test, should be good now.

**Comment by szeck87** [comment]
It's working now, thanks!
