### ISSUE TITLE
systemd failed to compile due to "plugin needed to handle lto object"

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#4765]
Building systemd from source failed during linking with a lot of "plugin needed to handle lto object" errors. I follow the suggestion from: https://gcc.gnu.org/ml/gcc-help/2016-01/msg00061.html and found the build system failed to find gcc-nm, gcc-ranlib and gcc-ar at the configure step because these binaries are suffixed with "-5" in the brew installed gcc 5.4.0. The compilation when smoothly if I manually symlink:
gcc-ar -> gcc-ar-5
gcc-nm -> gcc-nm-5
gcc-ranlib -> gcc-ranlib-5
in gcc 5.4.0 and run brew switch gcc 5.4.0

Can someone fix this in installing gcc?

**Comment by iMichka** [comment]
Hi. Please always fill out the full issue template. Especially `brew doctor` and so on.

On what OS is this happening?

**Comment by Char-Aznable** [comment]
I was in a hurry and didn't fill out the template. 
# Please always follow these steps:
- [1 ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [1 ] Ran `brew update` and retried your prior step?
- [1 ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew doctor complains nothing. My OS is CentOS release 6.9. I'm pretty sure the aforementioned binaries are the problems since it's a known issue of systemd build so I didn't bother to run gist-logs
