### ISSUE TITLE
build graphviz from source failed due to missing LDFLAGS

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#4778]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
brew install graphviz by building from source
- What happened (include command output)
installation failed with error messages that look exactly the same as seen by other people: https://github.com/ellson/MOTHBALLED-graphviz/issues/1230
- What you expected to happen
successful installation
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install graphviz --build-from-source

This is a known issue: https://github.com/ellson/MOTHBALLED-graphviz/issues/1230

The solution is to manually set LDFLAGS:

```
diff --git a/Formula/graphviz.rb b/Formula/graphviz.rb
index 852a96680c..fa592705c9 100644
--- a/Formula/graphviz.rb
+++ b/Formula/graphviz.rb
@@ -80,6 +80,7 @@ class Graphviz < Formula
     args << "--without-x" if build.without? "x11"
     args << "--without-rsvg" if build.without? "librsvg"
 
+    ENV.prepend_path "LDFLAGS", "-L#{HOMEBREW_PREFIX}/lib"
     if build.head?
       system "./autogen.sh", *args
     else
```

Can someone fix this in the repository?

**Comment by iMichka** [comment]
Hi. 

I put the patch part inside triple ticks (```) , to make it more readable.

Could you please fill out the full issue template? I tested to build from source in a clean docker container and it worked nicely. There may be something special in your setup.

**Comment by Char-Aznable** [comment]
OK. I filled out the template. I've seen a lot of issues with linuxbrew due to various environment variables not set correctly. The thing to note is that my linuxbrew installation is not in the recommended /home/linuxbrew directory because the system admin doesn't allow such setup. Can these be the reason why I've seen a lot of issues with linuxbrew build-from-source installation having something to do with environment variables not being set up correctly?

**Comment by tueda** [comment]
Indeed this patch was useful when I tried to install `graphviz` to my machine. Without the patch I got errors like `02.make` in https://gist.github.com/43f1d5d4c33dd402c36f4f2f35baac9d.
