### ISSUE TITLE
Error: failed to install vendor Ruby

### ISSUE THREAD

**Issue by enith2478** [Linuxbrew/homebrew-core#4804]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.

- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.

- [ ] Ran `brew update` and retried your prior step? 
Yes
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
Yes
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
Yes
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
Yes

To help us debug your issue please explain:
- What you were trying to do (and why)
I read other entries about the subject but I couldn't find a solution to my problem. I spent many hour without results. I copied the path in the prompt window and it always stops when its gonna pour Ruby.

- What happened (include command output)
I get the following message.
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
Already downloaded: /home/pi/.cache/Homebrew/portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
==> Pouring portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
Error: Failed to install vendor ruby.
Error: Failed to install vendor Ruby.

- What you expected to happen

- Step-by-step reproduction instructions (by running `brew install` commands)

pi@Luz:~/.linuxbrew $ ls
bin           CODE_OF_CONDUCT.md  _config.yml      Dockerfile       docs     LICENSE.txt  README.md
CHANGELOG.md  completions         CONTRIBUTING.md  docker.test.yml  Library  manpages     var

pi@Luz:~/.linuxbrew $ ls -al
total 92
drwxr-xr-x 11 pi pi 4096 Oct 26 02:09 .
drwxr-xr-x 26 pi pi 4096 Oct 26 02:18 ..
drwxr-xr-x  2 pi pi 4096 Oct 26 02:07 bin
-rw-r--r--  1 pi pi   98 Oct 26 02:07 CHANGELOG.md
drwxr-xr-x  2 pi pi 4096 Oct 26 02:07 .circleci
-rw-r--r--  1 pi pi 3161 Oct 26 02:07 CODE_OF_CONDUCT.md
drwxr-xr-x  4 pi pi 4096 Oct 26 02:07 completions
-rw-r--r--  1 pi pi   26 Oct 26 02:07 _config.yml
-rw-r--r--  1 pi pi 1530 Oct 26 02:07 CONTRIBUTING.md
-rw-r--r--  1 pi pi  790 Oct 26 02:07 Dockerfile
-rw-r--r--  1 pi pi  187 Oct 26 02:07 docker.test.yml
drwxr-xr-x  6 pi pi 4096 Oct 26 02:07 docs
drwxr-xr-x  8 pi pi 4096 Oct 26 02:26 .git
drwxr-xr-x  2 pi pi 4096 Oct 26 02:07 .github
-rw-r--r--  1 pi pi 1330 Oct 26 02:07 .gitignore
drwxr-xr-x  3 pi pi 4096 Oct 26 02:07 Library
-rw-r--r--  1 pi pi 1334 Oct 26 02:07 LICENSE.txt
drwxr-xr-x  2 pi pi 4096 Oct 26 02:07 manpages
-rw-r--r--  1 pi pi 7618 Oct 26 02:07 README.md
-rw-r--r--  1 pi pi 2155 Oct 26 02:07 .travis.yml
drwxr-xr-x  3 pi pi 4096 Oct 26 02:09 var
-rw-r--r--  1 pi pi  291 Oct 26 02:07 .yardopts

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by iMichka** [comment]
In principle this issue should have been opened here: https://github.com/Linuxbrew/brew, as this is a more general brew question.

> Error: Failed to install vendor ruby

That's not really helpful as error message. On way to debug this would be to go through the install scripts and put print statements to see where it fails.
