### ISSUE TITLE
post install error in brew install perl on ubuntu 17.10

### ISSUE THREAD

**Issue by cfblaeb** [Linuxbrew/homebrew-core#4808]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [*] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

"brew gist-logs perl" output:
Error: source sequence is illegal/malformed utf-8
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:146:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/gist-logs.rb:114:in `create_gist'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/gist-logs.rb:46:in `gistify_logs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/gist-logs.rb:127:in `gist_logs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'

"brew config" output:
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: b39b60a4bfd51e5f2e83f5dc927cdb1f67310686
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 9fedcbccaeb5a6cb00e55a2dba4cf1910f66a26d
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.14.1 => /usr/bin/git
Perl: /home/linuxbrew/.linuxbrew/bin/perl => /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: N/A
Java: N/A
Kernel: Linux 4.13.0-16-generic x86_64 GNU/Linux
OS: Ubuntu 17.10 (artful)
Host glibc: 2.26
/usr/bin/gcc: 7.2.0
glibc: N/A
gcc: 5.4.0
xorg: 20170115

"brew doctor" output:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /home/laeb/.pyenv/shims/python-config
  /home/laeb/.pyenv/shims/python3.6m-config
  /home/laeb/.pyenv/shims/python3.6-config
  /home/laeb/.pyenv/shims/python3-config

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /home/linuxbrew/.linuxbrew/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/home/linuxbrew/.linuxbrew/sbin:$PATH"' >> ~/.bash_profile

Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
    echo 'export XDG_DATA_DIRS="/home/linuxbrew/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile

To help us debug your issue please explain:
- What you were trying to do (and why)
Install perl....to use perl
- What happened (include command output)
I ran "brew install perl" and it gave an error in the post-install step:
==> Installing dependencies for perl: berkeley-db
==> Installing perl dependency: berkeley-db
==> Downloading https://linuxbrew.bintray.com/bottles/berkeley-db-6.2.32.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/71/7196de20ffd4fd1a38268d246bf07f9ffe91adf1a41983b4c6e0941edfaf2
######################################################################## 100,0%w
==> Pouring berkeley-db-6.2.32.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/berkeley-db/6.2.32: 5,632 files, 128.3MB
==> Installing perl
==> Downloading https://linuxbrew.bintray.com/bottles/perl-5.26.1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/e7/e71c9ab3ab09749d88434f13b8fd4b3dac7a4121111c2f9183c9d9ce9afab
######################################################################## 100,0%
==> Pouring perl-5.26.1.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/bin/cpan -i XML::Parser
Last 15 lines from /home/laeb/.cache/Homebrew/Logs/perl/post_install.01.cpan:
chmod 644 "Expat.bs"
"/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Expat.bs ../blib/arch/auto/XML/Parser/Expat/Expat.bs 644
"/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/bin/perl" "/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1/ExtUtils/xsubpp" -noprototypes -typemap '/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1/ExtUtils/typemap' -typemap '/home/laeb/.cpan/build/XML-Parser-2.44-0/Expat/typemap'  Expat.xs > Expat.xsc
mv Expat.xsc Expat.c
cc -c   -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/linuxbrew/.linuxbrew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"2.44\" -DXS_VERSION=\"2.44\" -fPIC "-I/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1/x86_64-linux-thread-multi/CORE"   Expat.c
In file included from Expat.xs:15:0:
/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1/x86_64-linux-thread-multi/CORE/perl.h:738:24: fatal error: xlocale.h: No such file or directory
compilation terminated.
Makefile:319: recipe for target 'Expat.o' failed
make[1]: *** [Expat.o] Error 1
make[1]: Leaving directory '/home/laeb/.cpan/build/XML-Parser-2.44-0/Expat'
Makefile:536: recipe for target 'subdirs' failed
make: *** [subdirs] Error 2
  TODDR/XML-Parser-2.44.tar.gz
  /usr/bin/make -- NOT OK
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bash_profile
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1: 2,402 files, 65.4MB

- What you expected to happen
Not give an error
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install perl

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by iMichka** [comment]
Hi. The actual error seems to be:

```
In file included from Expat.xs:15:0:
/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1/x86_64-linux-thread-multi/CORE/perl.h:738:24: fatal error: xlocale.h: No such file or directory
```

See https://bugzilla.redhat.com/show_bug.cgi?id=1464244
The file was renamed in glibc: https://sourceware.org/git/?p=glibc.git;a=commit;h=f0be25b6336db7492e47d2e8e72eb8af53b5506d

It seems from the discussion that a perl rebuild would fix this:
`brew uninstall perl && brew install perl -s`

Could you try that? If it works, I'll rebuilt the bottle for Linux.

**Comment by cfblaeb** [comment]
I tried it, and it seems to work. No errors at least. Thanks.

**Comment by Tuxie** [comment]
This is still a problem with Perl 5.28 on Ubuntu 18.04. Rebuilding it with -s works.

```
Pouring perl-5.28.0.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/cpan -i XML::Parser
Last 15 lines from /home/tuxie/.cache/Homebrew/Logs/perl/post_install.01.cpan:
"/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/perl" "/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/ExtUtils/xsubpp" -noprototypes -typemap '/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/ExtUtils/typemap' -typemap '/home/tuxie/.cpan/build/XML-Parser-2.44-0/Expat/typemap'  Expat.xs > Expat.xsc
mv Expat.xsc Expat.c
cc -c   -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/linuxbrew/.linuxbrew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"2.44\" -DXS_VERSION=\"2.44\" -fPIC "-I/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi/CORE"   Expat.c
In file included from Expat.xs:15:0:
/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi/CORE/perl.h:719:13: fatal error: xlocale.h: No such file or directory
 #   include <xlocale.h>
             ^~~~~~~~~~~
compilation terminated.
Makefile:319: recipe for target 'Expat.o' failed
make[1]: *** [Expat.o] Error 1
make[1]: Leaving directory '/home/tuxie/.cpan/build/XML-Parser-2.44-0/Expat'
Makefile:537: recipe for target 'subdirs' failed
make: *** [subdirs] Error 2
  TODDR/XML-Parser-2.44.tar.gz
  /usr/bin/make -- NOT OK
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.zshrc
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0: 2,652 files, 72.7MB
```

**Comment by tammersaleh** [comment]
I just hit this as well.

**Comment by thoughton** [comment]
I also just hit this, for me when upgrading an already-installed `perl`.
```
$ brew --version
Homebrew 1.8.5-46-gaed4548
```
```
OS: Ubuntu 18.04.1 LTS x86_64 
Kernel: 4.15.0-43-generic
```
A `brew reinstall -s perl` re-install fixed it for me.
