### ISSUE TITLE
Systemd reverts to local bins?

### ISSUE THREAD

**Issue by Clor** [Linuxbrew/homebrew-core#4810]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install `systemd`, for GTK3+

- What happened (include command output)
First of all, I had to install linux-pam to overcome a build error (not given as pre-req ; which required libprelude to be build with `--without-ruby` as it failed otherwise). Then, the build fails still when checking for `gpg-error`. Now if I type `which gpg-error` in bash, I find the linuxbrew version (version 1.27). But the build finds an outdated version at `/usr/bin/gpg-error-config` (version 1.7). See the log here:
https://gist.github.com/e0898e061befcbd4b3e488dfc1eb8d8e

I am not sure how to fix. `autogen.sh` probably just finds the wrong file on the path... I am fine with an easy fix, like, creating a symbolic link towards the right version for this build..?

- What you expected to happen
I expect the installation to default to the linuxbrew bins instead.

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install systemd`

**Comment by Clor** [comment]
When disabling everything, https://lists.freedesktop.org/archives/systemd-devel/2015-March/029595.html , I overcome these issues, but then still run into the `plugin needed to handle lto object` errors... not resolved when following the instructions at https://github.com/Linuxbrew/homebrew-core/issues/4765 . I suppose the problem may be outside of the scope of Linuxbrew here...if you have any thoughts I'd be happy to hear about them, otherwise feel free to close it, I'll try to install GTK+3 from source rather than linuxbrew, or something...

**Comment by iMichka** [comment]
`systemd` is always tricky to build. It would be great if we could stabilise the building for non-root users on different platforms.

I had also the feeling when playing around with it lately that it picked up the wrong dependencies/binaries when building. I'll have to double-check that.
The `plugin needed to handle lto object` problems is also an unsolved problem.

I will not have much time to dig into that so I hope some linuxbrew users could continue to investigate these problems.
