### ISSUE TITLE
Linux 8.9 (jessie) Error: No such file or directory

### ISSUE THREAD

**Issue by Anthonykung** [Linuxbrew/homebrew-core#4831]
I am trying to install Certbot to get a Let's Encrypt SSL certificate.

An error occurs here is where you can see it https://gist.github.com/Anthonykung/248dd4c4a0646141cecff5011616e093

I expected to have Cerbot installed and start to run it. The sudo command does not work then after some time an error occurs every time when using brew doctor or brew install

I ran sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" to install Linuxbrew then brew install gcc to install whatever that is. After that I ran brew install certbot then sudo certbot --apache that is when it says -bash: sudo: command not found

I tried brew update twice then the brew doctor a few times and the brew doctor starts to show errors.

**Comment by iMichka** [comment]
Hi. Sorry we couldn't help you earlier. There seem to be something wrong with your setup. No clue what is going on. Could you try try to brew update again; to get the latest version of brew?

**Comment by Anthonykung** [comment]
Well, I have tried to update it but it doesn't seem to be working. I have also tried deleting it and install again, nothing happened too.

**Comment by iMichka** [comment]
Does the folder exist? /kunden/homepages/37/d699854806/htdocs/tmp/homebrew_check_tmpdir_executable20171029-1511-1khjace

It would be great if you could have a look at what place this folder is created/checked by brew.
