### ISSUE TITLE
Golang fails to install on ARM.

### ISSUE THREAD

**Issue by threkk** [Linuxbrew/homebrew-core#4855]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Installing go fails on ARM platforms (concretely a Raspberry Pi). The issues seem to be:
- It doesn't use the bottle (or it is not available).
- It pull the wrong binary to install from the source (it seems to pull `amd64` instead of `arm`).

```
brew install --force-bottle go                                                                                              1 ↵
Updating Homebrew...
==> Downloading https://storage.googleapis.com/golang/go1.9.2.src.tar.gz
Already downloaded: /home/threkk/.cache/Homebrew/go-1.9.2.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz
Already downloaded: /home/threkk/.cache/Homebrew/go--gobootstrap-1.7.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /home/threkk/.cache/Homebrew/Logs/go/01.make.bash:
2017-11-01 17:18:30 +0100

./make.bash
--no-clean

##### Building Go bootstrap tool.
cmd/dist
./make.bash: line 134: /tmp/go-20171101-2754-1nwzvxo/go/gobootstrap/bin/go: cannot execute binary file: Exec format error
```

My `brew config`:
```
brew config                                                                                                               130 ↵
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: b39b60a4bfd51e5f2e83f5dc927cdb1f67310686
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 30e84511083d311d7c451fe459fef2882b52e2e3
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 32-bit arm
Homebrew Ruby: 2.3.3 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.11.0 => /usr/bin/git
Perl: /usr/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: N/A
Kernel: Linux 4.9.59-v7+ armv7l GNU/Linux
OS: Raspbian GNU/Linux 9.1 (stretch) (stretch)
Host glibc: 2.24
/usr/bin/gcc: 6.3.0
glibc: N/A
gcc: N/A
xorg: N/A
```

**Comment by iMichka** [comment]
Hi. Sorry that I didn't answer earlier.

We do not create bottles for ARM. This is due to a lack of resources (mostly human). So ARM stuff is completely untested. We are willing to merge pull requests if you find a way to fix this, but we are not planning to work actively on this. I'll close this issue. It is up to you or somebody from the community to work on this if you want to get this fixed.
