### ISSUE TITLE
brew install ffmpeg --with-sdl2 results in malfunctioning ffplay

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#4857]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
use the installed ffplay to replay a mp4 movie encoded by ffmpeg from the same installation
- What happened (include command output)
ffplay issued error:

Could not initialize SDL - No available video device
(Did you set the DISPLAY variable?) 

even though DISPLAY variable is set to :0

I confirmed this is not due to corrupted mp4 file because it plays fine with vlc on the same machine

- What you expected to happen
playable mp4
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install ffmpeg --with-sdl2

This issue was found before by someone else (see http://www.ffmpeg-archive.org/Ubuntu-16-04-ffplay-display-variable-not-set-td4680602.html). I think I pinned the issue down to the linuxbrew-installed sdl2 library not being compiled to have X support. I made the following changes to sdl2.rb
```
diff --git a/Formula/sdl2.rb b/Formula/sdl2.rb
index dfde7da662..f93a583b7f 100644
--- a/Formula/sdl2.rb
+++ b/Formula/sdl2.rb
@@ -44,7 +44,7 @@ class Sdl2 < Formula
     if ENV.compiler == :clang && DevelopmentTools.clang_build_version < 421
       args << "--disable-assembly"
     end
-    args << "--without-x"
+    #args << "--without-x"
     args << "--disable-haptic" << "--disable-joystick" if MacOS.version <= :snow_leopard
 
     system "./configure", *args
@@ -62,7 +62,7 @@ class Sdl2 < Formula
                      testoverlay2.c testsprite2.c],
                   /"(\w+\.(?:bmp|dat|wav))"/,
                   "\"#{pkgshare}/test_extras/\\1\""
-        system "./configure", "--without-x"
+        system "./configure"#, "--without-x"
         system "make"
         # Tests don't have a "make install" target
         (pkgshare/"tests").install %w[checkkeys controllermap loopwave loopwavequeue testaudioinf
```
 and recompiled sdl2 by brew reinstall sdl2 --build-from-source and now ffplay works fine. Can someone fix this?

**Comment by iMichka** [comment]
Hi. Sorry I didn’t answer before. @sjackman I think this will fix the sdl error we are seeing in many tests.

Maybe this happens because the bottle is being build inside a socket container, which has no X.

@Char-Aznable were you installing from bottles? Could you remove your patch from your local installation, uninstall sdl2, and install it again from source. I want to check if the fix is really needed, or if the bottle would just need to be built outside of docker.

**Comment by sjackman** [comment]
`--with-x` should probably be the default behaviour on Linuxbrew.

**Comment by Char-Aznable** [comment]
When I had this issue the first time, I tried both bottled version of sdl2 and building it from source (with the original sdl2 formula) and both gave me the same error.

**Comment by iMichka** [comment]
@Char-Aznable I updated the formula to build with-x, see #5063.

Could you brew upgrade, uninstall `sdl2`, and install it again, to test the bottle? Thanks.

**Comment by Char-Aznable** [comment]
I can't afford running brew upgrade now but the same error persists if I do
```
brew uninstall sdl2 
brew install sdl2 --force-bottle
``
However, I can get a working ffplay by 
```
brew uninstall sdl2
brew install sdl2 --build-from-source
```

**Comment by iMichka** [comment]
DId you run brew update before?

**Comment by Char-Aznable** [comment]
Yes, I did and I saw changes in the formula.

**Comment by sjackman** [comment]
We close issues that we're not actively working on. We'd appreciate a PR if you have a suggested fix for the issue.

**Comment by iMichka** [comment]
I made the suggested changes. Building works, and bottles were updated.

If it still not works, then you need to ask the `sdl` developers or the `ffmpeg` developers to help you. I do not have time to do this myself, sorry. There are hundred of other build issues for other formulae that need to be addressed on my side. This is why this is was closed.

**Comment by Char-Aznable** [comment]
Doesn't this suggest there is an issue with the bottle rather than sdl2 itself? I would first look into the bottle building log to see if anything went wrong. As mentioned before, no X support on the bottle bot would be a reasonable hypothesis but I don't have access to those info.

**Comment by iMichka** [comment]
There is no X on the build bot because we build stuff in docker. I can provide the full log when I am back from work if needed.

But I think having no X at build time should not impact running sdl2 with X on another machine. I may be wrong though, I do not know how sdl2 works.

**Comment by iMichka** [comment]
I will have a look.

By the way, if building without x is not good, we may remove the bottles and add a « bottle :unneeded », forcing users to recompile this from source each time.

**Comment by sjackman** [comment]
If we go that route `bottle :disabled unless OS.mac?`

**Comment by iMichka** [comment]
I opened a PR here: reviews are welcome, because I have no clue what I am doing, there are way too many X options for sld2: #7188 :)
