### ISSUE TITLE
Neko depends on GTK+2???

### ISSUE THREAD

**Issue by TiZ-EX1** [Linuxbrew/homebrew-core#4914]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/b14b84a8d092a1ae7f3afe6ef322d8eb
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): Trying to install Haxe, which depends on Neko.
- What happened (include command output): Neko's install failed due to the Linux version requiring GTK+2 for some reason. Why is this? Is it optional? If I try to install GTK+2 manually, I'll pull a huge amount of dependencies. This is silly, why does Neko need GTK+2?
- What you expected to happen: Haxe installed with Neko as a dependency.
- Step-by-step reproduction instructions (by running `brew install` commands): `brew install haxe`

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by iMichka** [comment]
Hi. We never ran a build on `neko` as there seem to be no bottles for it.
I opened a pull request to build bottles here: #4919
This will run the build in a clean environment, so we can see if the same error happens in that build.

If gtk2 is needed I will add it as a dependency, that's all. Of course it would be better to check with the `neko` devs why that is different. Probably there is on explanation somewhere in the documentation or in their source code.

**Comment by iMichka** [comment]
By this I mean that this not directly Linuxbrew`s fault, but a choice made by the `neko` dev. But we would be pleased to have a working installation and sort this out.

**Comment by TiZ-EX1** [comment]
The problem with adding GTK2 as a dependency is that it pulls so much of Xorg to build it, all just to be able to use Haxe. I'm going to investigate to see if this is optional. Would it also be possible to just build against system GTK2 libs?

**Comment by TiZ-EX1** [comment]
I think it will be preferable to set the cmake option `WITH_UI` to `OFF` by default, and then set it to on if the user doesn't mind pulling so many Xorg deps to get a half-baked UI API that is barely bound in Haxe anyways.

**Comment by iMichka** [comment]
Fixed by #4919. Apache and Mysql will stay ON, because this is the default. If you want to have this  put on OFF, you need to lobby upstream (the neko devs) to put this to OFF by default. On the other side, all the dependencies and neko has bottles; so this should really fast to install.

**Comment by iMichka** [comment]
Closing as this is fixed.
