### ISSUE TITLE
install zeromq

### ISSUE THREAD

**Issue by MikeSoft** [Linuxbrew/homebrew-core#4949]
**Ubuntu 16.04 x64**

mikesoft@mikesoft:~$ brew install zeromq
Error: undefined method `rebuild' for #<BottleSpecification:0x000000017c56b8>
Please report this bug:
    **https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting**
/home/mikesoft/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:10:in `block in <class:Autoconf>'
/home/mikesoft/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/home/mikesoft/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/home/mikesoft/.linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'
/home/mikesoft/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:8:in `<class:Autoconf>'
/home/mikesoft/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:1:in `load_formula'
/home/mikesoft/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/mikesoft/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/mikesoft/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/mikesoft/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/mikesoft/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/mikesoft/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/mikesoft/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/mikesoft/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/mikesoft/.linuxbrew/Library/Homebrew/dependency.rb:93:in `block in expand'
/home/mikesoft/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/mikesoft/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/mikesoft/.linuxbrew/Library/Homebrew/dependency.rb:80:in `expand'
/home/mikesoft/.linuxbrew/Library/Homebrew/dependency.rb:93:in `block in expand'
/home/mikesoft/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/mikesoft/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/mikesoft/.linuxbrew/Library/Homebrew/dependency.rb:80:in `expand'
/home/mikesoft/.linuxbrew/Library/Homebrew/formula.rb:1223:in `recursive_dependencies'
/home/mikesoft/.linuxbrew/Library/Homebrew/requirement.rb:196:in `expand'
/home/mikesoft/.linuxbrew/Library/Homebrew/formula.rb:1229:in `recursive_requirements'
/home/mikesoft/.linuxbrew/Library/Homebrew/formula_installer.rb:313:in `expand_requirements'
/home/mikesoft/.linuxbrew/Library/Homebrew/formula_installer.rb:263:in `compute_dependencies'
/home/mikesoft/.linuxbrew/Library/Homebrew/formula_installer.rb:130:in `verify_deps_exist'
/home/mikesoft/.linuxbrew/Library/Homebrew/formula_installer.rb:123:in `prelude'
/home/mikesoft/.linuxbrew/Library/Homebrew/cmd/install.rb:231:in `install_formula'
/home/mikesoft/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/home/mikesoft/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/home/mikesoft/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/home/mikesoft/.linuxbrew/Library/brew.rb:84:in `<main>'

**Comment by iMichka** [comment]
Hi. Please fill out the issue template. I have not enough information to help you. Thanks.

**Comment by iMichka** [comment]
Closing here for the time being. I’ll reopen this if the needed information is added.
