### ISSUE TITLE
mkvtoolnix doesn't compile

### ISSUE THREAD

**Issue by JMoVS** [Linuxbrew/homebrew-core#4959]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I tried installing mkvtoolnix
- What happened (include command output)
failed at rake stage due to `/home/mc_server/.linuxbrew/bin/ld: cannot find -lpugixml`

[gist-logs](https://gist.github.com/5a9018ac32d293386abb478adfa6ce7f)
- What you expected to happen
installing mkvtoolnix
- Step-by-step reproduction instructions (by running `brew install` commands)
install mkvtoolnix

I'm running a CentOS 7 system here

**Comment by iMichka** [comment]
Hi. Thanks for reporting this.
Let's try to reproduce this on our CI: #4963

Interestingly the `pugixml` is in the formula, so it is weird that rake can't find it.

**Comment by JMoVS** [comment]
I just had a look, seems like the fix is on the way? ;-)

**Comment by JMoVS** [comment]
Any news on this one?

**Comment by iMichka** [comment]
Sorry hadn't much time to work on this. I'm stuck because the rake process does not output anything for more than 10 minutes and circle ci does not like that.

**Comment by JMoVS** [comment]
I've tried compiling with --verbose and put the resulting output here:

https://gist.github.com/358991daad50045faf7622de2840436e

**Comment by retokromer** [comment]
Hi bot, I guess this issue is still one.

**Comment by iMichka** [comment]
It is, but I do not have much time to work on this. The `stale` status is sort of correct :)

**Comment by retokromer** [comment]
Hey bot, don't hurry!
