### ISSUE TITLE
netcdf: bottle not found

### ISSUE THREAD

**Issue by sbfnk** [Linuxbrew/homebrew-core#4982]
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?

`brew install netcdf` yields the following error (on multiple machines and Travis CI). It is related to https://github.com/Linuxbrew/homebrew-core/pull/4958. Is there a delay between transferring the bottle to Bintray and availability for download?

```
Downloading https://linuxbrew.bintray.com/bottles/netcdf-4.5.0_1.x86_64_linux.bottle.tar.gz

/home/linuxbrew/.linuxbrew/opt/curl/bin/curl --show-error --user-agent Linuxbrew/1.X.Y (Linux; x86_64 Ubuntu 14.04.5 LTS) curl/7.56.1 --fail --silent --location --remote-time --continue-at - --output /home/linuxbrew/.cache/Homebrew/netcdf-4.5.0_1.x86_64_linux.bottle.tar.gz.incomplete https://linuxbrew.bintray.com/bottles/netcdf-4.5.0_1.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized

Error: Failed to download resource "netcdf"
```

**Comment by iMichka** [comment]
Hi. Sorry, my fault. I forgot to publish the bottle. It happens in rare cases where I pull stuff on my mac and there is a linux specific revision bump.

Please try again, I fixed it.
