### ISSUE TITLE
Brew python3 module zmq cannot find libstdc++.so.6

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/homebrew-core#4983]
- [ ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I've installed linuxbrew to /home/linuxbrew/.linuxbrew hoping that it would solve some issues that I've been having. It seems to have solved some issues that I was having while attempting to upgrade systemd, but I'm now experiencing a host of other problems... one being that when I attempt to import zmq using brewed python3, I get ```ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory```. I'm not sure why it can't find the one in the linuxbrew lib...
```
$ ls /home/linuxbrew/.linuxbrew/lib/libstdc++*
/home/linuxbrew/.linuxbrew/lib/libstdc++.a    /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6
/home/linuxbrew/.linuxbrew/lib/libstdc++fs.a  /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6.0.21
/home/linuxbrew/.linuxbrew/lib/libstdc++.so   /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6.0.21-gdb.py
```

Any suggestions? Thanks.

```
$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: b39b60a4bfd51e5f2e83f5dc927cdb1f67310686
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 096ecab4ca74bbeea5a29b81dba743a7bff92efd
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit merom
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 5.0 build
Git: 2.15.0 => /home/linuxbrew/.linuxbrew/bin/git
Perl: /home/linuxbrew/.linuxbrew/bin/perl => /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /home/linuxbrew/.linuxbrew/bin/ruby => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/bin/ruby
Java: 1.7.0_65
Kernel: Linux 2.6.32-504.el6.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 6.6 (Santiago) (Santiago)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.4.0
xorg: 20170115
```
```
$ brew dr
Your system is ready to brew.
```

**Comment by jwhite007** [comment]
I'm not sure what fixed it, but this no longer seems to be an issue.

**Comment by iMichka** [comment]
We pushed brew 1.3.7 and 1.3.8. This may have fixed it but not sure. Thanks for closing the issue.
