### ISSUE TITLE
Hangs: brew install python3 --with-tcl-tk --with-sphinx-doc

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/homebrew-core#4986]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I've recently installed linuxbrew to /home/linuxbrew/.linuxbrew hoping that it would solve several problems; however, there seem to be a host of new problems related to this installation. FYI, /home is an NFS share.
The following hangs:
```
$ brew install tcl-tk --without-tk
$ brew install sphinx-doc
$ brew install python3 --with-tcl-tk --with-sphinx-doc
```
The following does not hang:
```
$ brew install python3
```
```
$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: b39b60a4bfd51e5f2e83f5dc927cdb1f67310686
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: b5c316d5e1a0025f3c9c1d2b99caadc68e19d061
Core tap last commit: 21 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit merom
Homebrew Ruby: 2.4.2 => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/bin/ruby
Clang: N/A
Git: 2.15.0 => /home/linuxbrew/.linuxbrew/bin/git
Perl: /usr/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /home/linuxbrew/.linuxbrew/bin/ruby => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/bin/ruby
Java: 1.7.0_65
Kernel: Linux 2.6.32-504.el6.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 6.6 (Santiago) (Santiago)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.4.0
xorg: 20170115
```
```
$ brew dr
Your system is ready to brew.
```

**Comment by iMichka** [comment]
Hi. You did not post the gist-log; so we can not debug this. I see no error message here.

**Comment by jwhite007** [comment]
@iMichka 

There are no gist-logs as the install hangs.

Cheers,
James

**Comment by iMichka** [comment]
Could you add the `-v` flag to the install command to see if there is a least a little bit of debug output?

**Comment by jwhite007** [comment]
@iMichka 

Ok. I'll do that. Thanks.

**Comment by jwhite007** [comment]
```brew -v install python3 --with-tcl-tk --with-sphinx-doc``` just hangs with no output.

**Comment by jwhite007** [comment]
```$ brew install python --with-tcl-tk --with-sphinx-doc``` does not hang.

**Comment by jwhite007** [comment]
I'm not sure if something else fixed it and the following just being a coincidence, but it works...
```
$ brew install tcl-tk --build-from-source
$ brew install python3 --with-tcl-tk --with-sphinx-doc
```

**Comment by iMichka** [comment]
We pushed brew 1.3.7. Maybe there was a change in there that fixed it. Not sure. If it works for you now we can just close this. Not sure I have time to investigate this more.

**Comment by jwhite007** [comment]
@iMichka 
Thanks for the input.
