### ISSUE TITLE
Mysql install fails with Error 2 on RHEL

### ISSUE THREAD

**Issue by jonaszierer** [Linuxbrew/homebrew-core#4995]
I tried to install mysql (brew install mysql) on RHEL 6.3 after updating/cleaning brew (brew update/brew upgrade/brew cleanup --force) several times. 

It fails with "make: *** [all] Error 2" and no further explanations. 
log files are here: https://gist.github.com/anonymous/15a534fa004d0b11500a057f459420f6

I tried the same on a mac, where the installation works without any problem.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

**Comment by iMichka** [comment]
Looks similar to #3708.

No clue what is going on. Maybe you are hitting the memory limit. How much RAM does your computer have?

**Comment by jonaszierer** [comment]
Yes it does, but it doesn't offer a solution either. 

I tried to install it on different nodes of our grid with >128GB memory, so that shouldn't be the problem....

**Comment by iMichka** [comment]
Yes, 128 Gb is plenty of RAM. I would need to test this inside a RHEL 6.3 docker container to see if it can be reproduced, but I do not have much time.

It would be also interesting to see if this also happens outside of Linuxbrew's context, by compiling mysql manually (download the sources and run the compilation): if that does not work you may need to contact the mysql developers.

**Comment by jonaszierer** [comment]
I tried building it from source and get the error:

**Comment by iMichka** [comment]
Maybe try adding:
`depends_on "gsasl"`
to the formula

**Comment by jonaszierer** [comment]
doesn't solve the problem, unfortunately.

**Comment by fennerm** [comment]
Symlinking libsasl2 also fixed this for me. This issue also seems to be present in mariadb install.

**Comment by iMichka** [comment]
I do not have much time. Could somebody research what is the difference between gsasl and libsasl2? Ideally we should not need to make that symlink.

**Comment by lukauskas** [comment]
This issue is still active as of today.

The workaround suggested by @jonaszierer worked for me too

```
ln -s $HOME/.linuxbrew/lib/libgsasl2.so $HOME/.linuxbrew/lib/libsasl.so 
```
