### ISSUE TITLE
What to do with Homebrew formulae moved to casks

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#501]
This is a meta ticket to decide what to do with formulae that get moved to Casks as part of https://github.com/caskroom/homebrew-cask/issues/15603 . Nothing is concrete yet; just making suggestions. 

This list will need to be kept up to date with https://github.com/caskroom/homebrew-cask/issues/15603#issuecomment-223120969

We should probably also consider the popularity (wrt to Google Analytics) when making these decisions. We don't need to do all of these at once; we can copy them over as users request them, for example. For now, I've just said "keep", "wait", "let go", and "?" - meaning, "let's restore this if it is removed and put it somewhere (perhaps a custom tap)", "restore this later, once it's worthwhile to do so", "ignore that the formula was removed", and "I don't know". Other Linuxbrew devs, feel free to make suggestions and/or edit outright.

Also, this obviously depends on maintainer time, which we are a little short of to say the least :stuck_out_tongue: 

| name | what to do with it | reason | Installs in 90 days |
| --- | --- | --- | --- |
| avidemux | keep | Video editor; has some installs | 2 |
| gedit | wait | Does not build (blocked by GTK+3) | 0 |
| gimp | wait | can use system-provided version for now | ? |
| graphviz | keep | 10 core formulae use it | 63 |
| horndis | let go | Mac-only | 0 |
| kdiff3 | wait | can use system-provided version for now | 0 |
| macvim | let go | Mac-only, other vi-like formulae available (pyvim, nvi, vim, etc.) | 48 all BuildError? |
| ngrok | ? | Don't know what this is | 0 |
| tuntap | let go | Mac-only | 20 all BuildError? |
| quassel | wait | can use system-provided version for now | 0 |
| sqlitebrowser | ? | Never used it, is it popular? | 0 |
| wireshark | wait | can use system-provided version for now | 13 |

**Comment by sjackman** [comment]
Some of these formula could move to `Homebrew/homebrew-x11` or `Homebrew/homebrew-gui` or `Linuxbrew/homebrew-xorg` or some new Linuxbrew tap for Linux GUI apps.

**Comment by sjackman** [comment]
The only used formula are `avidemux`, `graphviz` and `wireshark`. I'd like to keep these three formula in Linuxbrew.

**Comment by sjackman** [comment]
Both `graphviz` and `wireshark` remained in `core`. `avidemux` has gone.
