### ISSUE TITLE
Installing brew fails with 403 error on openSuse 11.2

### ISSUE THREAD

**Issue by bitmask** [Linuxbrew/homebrew-core#502]
Installing linuxbrew fails on openSUSE 11.2, x86_64.

Dependencies are met:
- gcc (SUSE Linux) 4.4.1 [gcc-4_4-branch revision 150839]
- ruby 1.8.7 (2011-12-28 patchlevel 357) [x86_64-linux]
- Kernel version is 2.6.31.14-0.8-desktop

```
% ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
==> This script will install:
/home/green1/helen/.linuxbrew/bin/brew
/home/green1/helen/.linuxbrew/Library/...
/home/green1/helen/.linuxbrew/share/doc/homebrew
/home/green1/helen/.linuxbrew/share/man/man1/brew.1
/home/green1/helen/.linuxbrew/share/zsh/site-functions/_brew
/home/green1/helen/.linuxbrew/etc/bash_completion.d/brew
/home/green1/helen/.cache/Homebrew/

Press RETURN to continue or any other key to abort
==> Downloading and installing Linuxbrew...
==> Tapping homebrew/core
Initialized empty Git repository in /home/green1/helen/.linuxbrew/Library/Taps/homebrew/homebrew-core/.git/
error: The requested URL returned error: 403 while accessing https://github.com/Linuxbrew/homebrew-core/info/refs

fatal: HTTP request failed
Error: Failure while executing: git clone https://github.com/Linuxbrew/homebrew-core /home/green1/helen/.linuxbrew/Library/Taps/homebrew/homebrew-core --depth=1
Failed during: /home/green1/helen/.linuxbrew/bin/brew tap homebrew/core
```

Works perfectly fine from newer machines.  Please ask if you need more information.

**Comment by sjackman** [comment]
Hi. I believe your version of `git` is too old. See https://help.github.com/articles/https-cloning-errors/
We'd like to support your use case, but some troubleshooting will be required.
Report the output of `git --version`
If you have root access, try removing your host's version of `git`: `sudo zypper remove git`
and try reinstalling Linuxbrew. It should fall back to using `curl`, after which you can `brew install git`. Alternatively, try:
```
brew install https://raw.githubusercontent.com/Linuxbrew/homebrew-core/master/Formula/git.rb
```
You may have to manually repeat that command for each dependency of `git`:
`zlib openssl curl expat git`

**Comment by bitmask** [comment]
I have git version 1.6.4.2, no root access.  The command you suggested to install git via brew fails with the same error as I was getting before.

However, I built a more recent git from source, then I can install brew and brew install with no problem.  Thanks!

**Comment by sjackman** [comment]
Glad to hear it! Thanks for the feedback.
