### ISSUE TITLE
terraform: executable installed is the Mach-O executable

### ISSUE THREAD

**Issue by poblahblahblah** [Linuxbrew/homebrew-core#5032]
Installing terraform from the terraform formula drops a Mach-O executable on the filesystem since the formula is designed for OSX and is using gox to build the binary.

# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [X] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install terraform on my linux laptop

- What happened (include command output)
Terraform installed properly

- What you expected to happen
`terraform` binary would execute properly

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install terraform`
```
pobrien@pob:KITCHEN:~$ terraform -v
-bash: /home/pobrien/.linuxbrew/bin/terraform: cannot execute binary file: Exec format error
pobrien@pob:KITCHEN:~$ file /home/pobrien/.linuxbrew/Cellar/terraform/0.10.8/bin/terraform
/home/pobrien/.linuxbrew/Cellar/terraform/0.10.8/bin/terraform: Mach-O 64-bit x86_64 executable
```

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by poblahblahblah** [comment]
Now that I think about it, this can be closed - ya'll add the bottles to the formulas to account for this issue.

**Comment by iMichka** [comment]
Hi. I did not really understand what you you plan to do/we should do? Anyway, a pull request would be welcome if anything needs to be fixed.
