### ISSUE TITLE
Crystal-lang doesn't build against Linuxbrew's LLVM

### ISSUE THREAD

**Issue by TiZ-EX1** [Linuxbrew/homebrew-core#5090]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/anonymous/e2f00c6d88a210c7f8f881c8a8ff762a
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) I was actually trying to install Crystal 0.24.0 with a custom formula so I could get rid of llvm@4 and get some disk space back, but when I checked to make sure it worked, it said it used LLVM 3.8, which is what Ubuntu 16.04 uses. That's not quite right, so I decided to install stable, and it says the same thing.
- What happened (include command output) `crystal --version` indicates LLVM 3.8.
- What you expected to happen `crystal --version` on 0.23.1 indicates LLVM 4.0.1.
- Step-by-step reproduction instructions (by running `brew install` commands) `brew install crystal-lang`

**Comment by iMichka** [comment]
I think brew will pick up the first compiler found in your path. The idea is that you can the. Work with your system’s compiler.
I think you can force the usage of another compiler by using this:
‘HOMEBREW_CC=gcc-4.5 HOMEBREW_CXX=g++-4.5 brew install xxx’

**Comment by iMichka** [comment]
I'm working on a PR here: #5311
`crystal-clang` uses `llvm` now instead of `llvm@4`

**Comment by TiZ-EX1** [comment]
I guess changing it to use regular llvm was what allowed this to work right? I wonder why that is. In any case, `crystal --version` now indicates that llvm 5.0.1 is used.

**Comment by iMichka** [comment]
I still need to be able to build a bottle though :)

**Comment by TiZ-EX1** [comment]
Wait, the bottle's not working for you? That's weird, because I was able to build a bottle in my alternative cellar.
