### ISSUE TITLE
'brew install kubernetes-cli' error

### ISSUE THREAD

**Issue by lucasyvas** [Linuxbrew/homebrew-core#5091]
[✔] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
[N/A] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
[✔] Ran `brew update` and retried your prior step?
[✔] Ran `brew doctor`, fixed all issues and retried your prior step?
[✔] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
[✔] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I was just trying to install kubernetes-cli and bumped into this error without many details to help. I tried this earlier on another system and it was fine, so it might not be a formula error.

It's easy to reproduce on this machine by just trying to install it again in the same way. Here's the gist:

https://gist.github.com/anonymous/4c93e4179e0811263fc2964d0fee8450

Command Output:

```
==> Cloning https://github.com/kubernetes/kubernetes.git
Updating /home/lucas/.cache/Homebrew/kubernetes-cli--git
==> Checking out tag v1.8.4
==> make generated_files
Last 15 lines from /home/lucas/.cache/Homebrew/Logs/kubernetes-cli/01.make:
2017-12-06 08:44:15 -0800

make
generated_files


READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
```

I already tried deleting the cache folder of everything, but it didn't help.

**Comment by lucasyvas** [comment]
After looking at the formula, for a bit I considered that due to the need to have ENV.deparallelize there may have been a race condition somewhere.

I tried a tip from Homebrew to pass the environment variable:

HOMEBREW_MAKE_JOBS=1 on the execution line, but it made no difference.

**Comment by iMichka** [comment]
One solution would be to try to compile this “outside” of homebrew. This means following the same steps as the formula but in a local folder. If it fails there is is an upstream problem an need to be reported there

**Comment by lucasyvas** [comment]
I will see what I can figure out. I was mainly looking for validation that there was nothing odd looking in the gist output. The two machines are close, but there are some differences. This is the gist for the working machine:

https://gist.github.com/anonymous/765e1e8dc57ba831dc0c581b57e6048f

Maybe it is Clang/GCC related. I'll see if I can close the gap a bit between the machines when I have time

**Comment by iMichka** [comment]
I do not see anything special in the gist log.

I started working on fixing the build back then, in #4676, and gave up due to weird errors.

**Comment by lucasyvas** [comment]
I appreciate you taking time to look and bringing the existing issue to light. I got my machines in line as far as brew config goes, but no luck on the easy approach. They're beefy enough it shouldn't be a resource related problem. If need be I will just not use Linuxbrew for this one, so no biggie.

If I find anything I will post it here, but it seems like it could be an upstream issue that's tricky to nail down, so I will close this!

**Comment by iMichka** [comment]
Yes. I am personally not using that tool; so it is on my low priority list. If somebody wants to get this fixed he will need to have a closer look at the build process. I am willing to provide a little bit of support if there are any questions, but that's all I can do for the moment.

**Comment by lucasyvas** [comment]
Speak of the devil... I'm not sure what happened, but after getting them in line, all of a sudden "boom." I won't claim this helps you solve your original issue in any way, but there's something about this config that's not well liked. So the second gist is OK, and the first is not
