### ISSUE TITLE
pulseaudio failed to build on ArchLinux

### ISSUE THREAD

**Issue by AndLen** [Linuxbrew/homebrew-core#5126]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [ x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ N/A] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ N/A] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

gist-log: https://gist.github.com/anonymous/21207bc79efe0fdb1a5c9267a7c79ba0 

Installing qt5. Console output as below:

==> Installing qt dependency: pulseaudio
==> Downloading https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-11.1.tar.xz
Already downloaded: /home/lensenandr/.cache/Homebrew/pulseaudio-11.1.tar.xz
==> Downloading https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz
Already downloaded: /home/lensenandr/.cache/Homebrew/pulseaudio--XML::Parser-2.44.tar.gz
==> perl Makefile.PL INSTALL_BASE=/local/scratch/lensenandr/linuxbrew/Cellar/pulseaudio/11.1/libexec
==> make PERL5LIB=/local/scratch/lensenandr/linuxbrew/Cellar/pulseaudio/11.1/libexec/lib/perl5 CC=gcc-7
==> make install
==> ./configure --disable-silent-rules --prefix=/local/scratch/lensenandr/linuxbrew/Cellar/pulseaudio/11.1 --disable-neon-opt --with-mac-sy
==> make install
Last 15 lines from /home/lensenandr/.cache/Homebrew/Logs/pulseaudio/05.make:
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[4]: Leaving directory '/tmp/pulseaudio-20171211-19862-7i36lc/pulseaudio-11.1/src'
make[3]: *** [Makefile:11107: install-am] Error 2
make[3]: Leaving directory '/tmp/pulseaudio-20171211-19862-7i36lc/pulseaudio-11.1/src'
make[2]: *** [Makefile:11101: install] Error 2
make[2]: Leaving directory '/tmp/pulseaudio-20171211-19862-7i36lc/pulseaudio-11.1/src'
make[1]: *** [Makefile:808: install-recursive] Error 1
make[1]: Leaving directory '/tmp/pulseaudio-20171211-19862-7i36lc/pulseaudio-11.1'
make: *** [Makefile:1107: install] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

**Comment by iMichka** [comment]
Hi. I think the actual error is:
```
'/local/scratch/lensenandr/linuxbrew/Cellar/pulseaudio/11.1/share/pulseaudio/alsa-mixer/paths'
 /usr/bin/install -c -m 644 daemon/pulseaudio-system.conf '/local/scratch/lensenandr/linuxbrew/Cellar/pulseaudio/11.1/etc/dbus-1/system.d'
 /usr/bin/install -c -m 644 default.pa system.pa daemon.conf client.conf '/local/scratch/lensenandr/linuxbrew/Cellar/pulseaudio/11.1/etc/pulse'
 /usr/bin/install -c -m 644 modules/alsa/mixer/profile-sets/90-pulseaudio.rules '/lib/udev/rules.d'
/usr/bin/install: cannot create regular file '/lib/udev/rules.d/90-pulseaudio.rules': Permission denied
```

I do not have much time to look after this, but I guess the best bet would be to find a way to disable the writing of the `.rules` file. Of course this means that you will not be able to use features related to the usage of this `.rules` file (I guess some communication with external  hardware).

**Comment by AndLen** [comment]
Is there a way to use the system provided pulseaudio for dependencies as an interim solution?
