### ISSUE TITLE
gawk is required but no root privilege available

### ISSUE THREAD

**Issue by MrWanter** [Linuxbrew/homebrew-core#5127]
Hi! I came across a problem, not very involved, I also want to use `Linuxbrew` for setting up some pkg on a remote server which I have no root privilege on, after install `Linuxbrew` follow the direction on official `linuxbrew` site, then near eveything I want to install with brew install came with:
```
glibc: gawk is required to build glibc.
Install gawk with your host package manager if you have sudo access.
  sudo apt-get install gawk
  sudo yum install gawk
Error: An unsatisfied requirement failed this build.
```
I'm considering download source of `gawk` and build it manually in `HOME` directory, but don't know how to let `brew` recognize it, can anyone help?

**Comment by iMichka** [comment]
Hi. Why don't you `brew install gawk`?

I think that if you install it from source, it just needs to be first in your PATH to be picked up.

**Comment by MrWanter** [comment]
with `brew install gawk` prompts:
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
gtk-doc                    gtksourceview3             shellcheck

==> Installing dependencies for gawk: glibc, xz, m4, gmp, mpfr, libmpc, isl, gcc, pkg-config, gpatch, ncurses, readline
glibc: gawk is required to build glibc.
Install gawk with your host package manager if you have sudo access.
  sudo apt-get install gawk
  sudo yum install gawk
Error: An unsatisfied requirement failed this build.
```

**Comment by MrWanter** [comment]
Is there other ways for me to setup pkgs on a server without root privilege?

**Comment by iMichka** [comment]
I guess you can manually download the source code and compile by hand.
You can look at the command line used for that in the formula: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/gawk.rb

**Comment by JuPlutonic** [comment]
How I understand you want to try linuxbrew and don't have gawk's binaries
I use gawk from GNU Gawk site. I unpacked it to my home directory and run in console inside this directory. When I used `/.configure`command and `make` command afterwards.
Before trying LinuxBrew add ~/gawk-2.4.0 to PATH before all other paths.
And how at **current** moment the couple of lines in ~/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb blocks work with external gawk: replace lines 19-20 with this code: https://github.com/Linuxbrew/homebrew-core/blob/59b343a86689531bc59702e376654821f766b1c8/Formula/glibc.rb

**Comment by sjackman** [comment]
The easiest solution is to install GNU Gawk using the host's package manager. If you have a systems support group, I'd suggest asking them to install GNU Gawk.

To install GNU Gawk before `glibc`, try…
```sh
brew install patchelf
brew deps --include-build gawk
brew install --ignore-dependencies $(brew deps --include-build gawk)
brew install -s gawk
brew install glibc
```
The above is not tested. Please report back whether it works for you, or the error message if it does not.

**Comment by JuPlutonic** [comment]
@sjackman I will see it by reinstalling linuxbrew on clear profile

**Comment by iMichka** [comment]
Please tell us if this worked. I yes, I think it would be good to document this way of installing gawk in our wiki.

**Comment by sjackman** [comment]
`mawk` has fewer dependencies than `gawk` and is the default AWK implementation on Debian systems. I wonder whether it could be used instead of `gawk`.

@JuPlutonic Does your system have any `awk` installed? `which -a awk`

**Comment by JuPlutonic** [comment]
after:
```
brew deps --include-build gawk
brew install --ignore-dependencies $(brew deps --include-build gawk)
```
Got `Error: No such file or directory @ realpath_rec - /home/zhevlakov/.linuxbrew/bin/gcc-4.9`
_//////////////_
@sjackman
This is the output of `which -a awk`:
```
 /home/NNN/gawk-4.2.0/awk
/home/NNN/gawk-4.2.0/awk
/usr/bin/awk
```
`ls -l $(which awk)`:
```
bash: /home/NNN/.linuxbrew/bin/ls: No such file or directory
```

**Comment by JuPlutonic** [comment]
`brew install -s --ignore-dependencies gawk`
[gist](https://gist.github.com/bb66b4a76f14f385e793b8645e807a6f)
```
Last 15 lines from /home/NNN/.cache/Homebrew/Logs/gawk/03.make:
--- _mbstr2     Tue Dec 26 12:02:54 2017
***************
*** 1,5 ****
  2007
- gawk: mbstr2.awk:1: (FILENAME=- FNR=2) warning: Invalid multibyte data detected. There may be a mismatch between your data and your locale.
  2007
  2007
  2007
--- 1,4 ----
make[2]: Leaving directory '/tmp/gawk-20171226-34310-1sg8n39/gawk-4.2.0/test'
Makefile:1796: recipe for target 'check' failed
make[1]: *** [check] Error 1
make[1]: Leaving directory '/tmp/gawk-20171226-34310-1sg8n39/gawk-4.2.0/test'
Makefile:725: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
Error: Not a directory @ dir_s_rmdir - /home/NNN/.linuxbrew/Cellar/gawk
```

**Comment by JuPlutonic** [comment]
with editing /home/zhevlakov/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
changed 19 line to ` which "gawk"` I again can overcome gawk problem (because I have compiled /home/NNN/gawk-4.2.0/awk) on my clean linuxbrew installation.

**Comment by sjackman** [comment]
Thanks for the troubleshooting, @JuPlutonic, and for the workaround that worked for you: changing `!which("gawk").nil?` to `which "gawk"`. The following workaround may work as well:
```
HOMEBREW_NO_ENV_FILTERING=1 brew install glibc
```
I'm glad that we have workarounds. I don't have a perfect fix for this issue yet.

**Comment by iMichka** [comment]
@sjackman Do you remember why gawk was depending on glibc?

```
$ brew deps --include-build --include-requirements gawk
gettext
gmp
gpatch
m4
mpfr
ncurses
pkg-config
readline
xz
zlib
```

Maybe that dependency cycle got fixed by one of the commits I made to fix some a few months ago, for example 15b63a8db117cee3fde185d86b587fe1977dd6a5 for gettext.

I think we could directly depend on gawk and remove the gawk requirement from glibc now.

**Comment by sjackman** [comment]
We need to limit as much as possible the dependencies of `glibc`, because the bottles of the dependencies of `glibc` must be built to be portable. I'd like to know whether `mawk`, which has no dependencies, can be used to build `glibc`.

**Comment by sjackman** [comment]
`gawk` depends on `glibc` because it's linked against `libc.so.6`.
