### ISSUE TITLE
systemd failed on ArchLinux

### ISSUE THREAD

**Issue by AndLen** [Linuxbrew/homebrew-core#5132]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [n/a ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [n/a ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

gist-log: https://gist.github.com/anonymous/f3f20050ec5e89c4fb6cdb76776088e8

Installing systemd. Console output as below:

==> ./autogen.sh
==> ./configure --disable-acl --disable-silent-rules --prefix=/local/scratch/lensenandr/linuxbrew/Cellar/systemd/234_1 --localstatedir=/loc
==> make install
Last 15 lines from /home/lensenandr/.cache/Homebrew/Logs/systemd/03.make:
#12
replacement 
target 
string 
#13
target 
string 
#14
string 
error: file man/systemd.index.xml
xsltRunStylesheet : run failed
make[2]: *** [Makefile:27485: man/systemd.index.7] Error 11
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:23278: install-recursive] Error 1
make: *** [Makefile:24855: install] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

**Comment by TiZ-EX1** [comment]
I have a similar error, but I'm failing at a different step; it thinks that openssl is not available. Like you, I'm installing in a non-standard location. It seems like alternative installs are a great way to expose problems with formulae!

https://gist.github.com/417ec06cda2550051f0dc3200175f3a2

**Comment by iMichka** [comment]
The actual error is:
```
runtime error: file file:///local/scratch/lensenandr/linuxbrew/Cellar/docbook-xsl/1.79.1/docbook-xsl/lib/lib.xsl line 60 element variable
xsltApplySequenceConstructor: A potential infinite template recursion was detected.
You can adjust xsltMaxDepth (--maxdepth) in order to raise the maximum number of nested template calls and variables/params (currently set to 3000).
Templates:
```

>  installing in a non-standard location. It seems like alternative installs are a great way to expose problems with formulae!

Yes. Even on the mac version these are sometimes broken. We do not support these installations as much as standard ones. Basically, if you do exotic things, we can not provide much support because we do not have time to fix everything. So you are a little left alone for that kind of problems. @TiZ-EX1 as you encounter a different problem at a different step, you should open a separate issue. But as said, not sure we can help you much due to limited time to work on this.

**Comment by paulprovost** [comment]
I have the same error on Ubuntu 16.04.3 LTS. My install is at `~/.linuxbrew`.

Did you guys solve it?

Now, why `systemd` gets pulled in when I'm installing `notmuch` is another question, but well...

**Comment by iMichka** [comment]
Hi. No, nobody fixed this and nobody is working on this.

Do you install in /home/linuxbrew/.linuxbrew? Or is `~/.linuxbrew`  somewhere else for you (I guess yes, as `systemd` is probably being recompiled for you.

As why the dependency gets pulled may depend if you compiled some packages manually with some options. I also know that sometimes a dependency or another gets pulled even if not needed: this is a bug which will be fixed soon (as soon as we merge brew 1.4.0).

**Comment by paulprovost** [comment]
`~/.linuxbrew` is just that, not `/home/linuxbrew/.linuxbrew`. I guess I could add a `linuxbrew` user and group and add my user to the group.

**Comment by iMichka** [comment]
I think there is a patch for this bug: https://bugs.archlinux.org/task/54694

This is fixed in docbook-xsl 1.79.2-2. The sourceforge page shows that 1.79.1 was the last release, but there seem to be a GitHub repo with a newer version: https://github.com/docbook/xslt10-stylesheets/releases. 

Arch linux is at 1.79.2 (https://www.archlinux.org/packages/extra/any/docbook-xsl/), and debian/ubuntu is stuck at 1.79.1 ...

We could try to backport the patch to the `docbook-xsl` formula and see if it helps. Would you like to try?

**Comment by monofy** [comment]
I am having exactly the same issue...I downloaded docbook-xsl 1.79.2...how can i force brew to install it over 1.79.1 on ubuntu?

**Comment by iMichka** [comment]
After some digging I found the official statment here: https://lists.oasis-open.org/archives/docbook-apps/201612/msg00011.html

There are links to the new download location for the new version.

To update it, we need to update the formula in https://github.com/Homebrew/homebrew-core. It will then be merged here later on. Would you like to submit a PR for this?

**Comment by monofy** [comment]
Yes please. I would really appreciate it.
Thanks in Advance.

**Comment by iMichka** [comment]
I opened a pull request upstream: https://github.com/Homebrew/homebrew-core/pull/23916

**Comment by TiZ-EX1** [comment]
No good for me:

```
==> make install
Last 15 lines from /xusr/linuxbrew/.cache/Homebrew/Logs/systemd/03.make:
string 
#13
target 
string 
#14
string 
error: file man/systemd.index.xml
xsltRunStylesheet : run failed
Makefile:27485: recipe for target 'man/systemd.index.7' failed
make[2]: *** [man/systemd.index.7] Error 11
make[2]: *** Waiting for unfinished jobs....
Makefile:23278: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
Makefile:24855: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by TiZ-EX1** [comment]
Okay sorry to double-post, but scratch that; it worked after I did `brew cleanup` to get rid of old versions.

**Comment by iMichka** [comment]
Patch merged, please update, this should be OK now.

**Comment by TiZ-EX1** [comment]
How do I revert the pull? Homebrew tried to update after I had the pull and tripped all over itself, leaving `dockbook-xls` in a state where it consists of diffs.
