### ISSUE TITLE
RHEL6: gcc bootstrap with --without-glibc falls over with unrecognized ld option -B

### ISSUE THREAD

**Issue by draeath** [Linuxbrew/homebrew-core#5137]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? [link here](https://gist.github.com/76b2d05e96e341c2386cd40b3ae11828)

- What you were trying to do (and why)
  Stand up linuxbrew in a docker container, to evaluate the suitability of the approach. **This same build worked last week.**
- What happened (include command output)
  initial gcc install failed. attempting to follow [these instructions.](https://github.com/Linuxbrew/brew/wiki/CentOS6#install-linuxbrew-on-centos-6-without-sudo)
- What you expected to happen
  A working linuxbrew deployment
- Step-by-step reproduction instructions (by running `brew install` commands)

Dockerfile. It's pretty self-explanatory if you're not familiar.
```
# https://hub.docker.com/_/centos/
FROM centos:centos6

# oracle jre and epel
ADD RPMs/*.rpm /tmp/RPMs/
RUN yum localinstall -y /tmp/RPMs/*.rpm &&\
    rm -vf /tmp/RPMs/*.rpm &&\
    rmdir -v /tmp/RPMs
RUN yum makecache fast &&\
    yum -y upgrade &&\
    yum -y install coreutils curl file git python-setuptools '@Development Tools' blas-devel freetype-devel &&\
    yum clean all
RUN localedef -v -c -i en_US -f UTF-8 en_US.UTF-8 || true
ENV LC_ALL='en_US.UTF-8'

RUN useradd -m -U testuser
USER testuser
WORKDIR /home/testuser

RUN git clone https://github.com/Linuxbrew/brew.git .linuxbrew
RUN echo 'export PATH="${HOME}/.linuxbrew/bin:${HOME}/.linuxbrew/sbin:$PATH"' >> .bashrc &&\
    echo 'export MANPATH="$(brew --prefix)/share/man:${MANPATH}"' >> .bashrc &&\
    echo 'export INFOPATH="$(brew --prefix)/share/info:${INFOPATH}"' >> .bashrc &&\
    echo 'export HOMEBREW_MAKE_JOBS="$(/usr/bin/nproc)"' >> .bashrc

# using this dumb formatting to ensure the above environment vars are in effect, without resorting to ENV
RUN ["/bin/bash", "-l", "-c", "HOMEBREW_NO_AUTO_UPDATE=1 brew config"]
RUN ["/bin/bash", "-l", "-c", "HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc --without-glibc"]
# RUN ["/bin/bash", "-l", "-c", "HOMEBREW_NO_AUTO_UPDATE=1 brew install glibc"]
# RUN ["/bin/bash", "-l", "-c", "HOMEBREW_NO_AUTO_UPDATE=1 brew remove gcc"]
# RUN ["/bin/bash", "-l", "-c", "HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc"]
# RUN ["/bin/bash", "-l", "-c", "localedef -v -c -i en_US -f UTF-8 en_US.UTF-8 || true"]
# RUN ["/bin/bash", "-l", "-c", "HOMEBREW_NO_AUTO_UPDATE=1 brew install git"]

CMD ["/bin/bash", "-i"]
```

Eventually, the final uncommented brew install fails with: `ld: unrecognized option '-B/home/testuser/.linuxbrew/opt/glibc/lib'`

I suspect a syntax change in the gcc recipe that isn't supported on RHEL6/CentOS6, as this process did work last week.

**Comment by iMichka** [comment]
Hi. Got this also today with this pull request: #5143

I have the feeling this with brew 1.3.9. @sjackman may know more. I will have time to look at this but probably only tomorrow.

**Comment by sjackman** [comment]
Thanks for the bug report, Paul. I likely introduced this bug with PR https://github.com/Linuxbrew/brew/pull/531. I'll look into it.

**Comment by sjackman** [comment]
This PR should hopefully fix this issue: https://github.com/Linuxbrew/brew/pull/535

**Comment by sjackman** [comment]
I've merged PR https://github.com/Linuxbrew/brew/pull/535.

**Comment by draeath** [comment]
Thanks, confirming you fixed it!

**Comment by iMichka** [comment]
Cool. That worked! Thanks.

**Comment by sjackman** [comment]
Great!
