### ISSUE TITLE
How can I install vim with python && python3?

### ISSUE THREAD

**Issue by fcying** [Linuxbrew/homebrew-core#5149]
I try use this, All failed
```
brew reinstall vim --with-python3 --with-luajit
brew reinstall vim --enable-pythoninterp=dynamic --enable-python3interp=dynamic --with-luajit
```

**Comment by iMichka** [comment]
Hi. Please fill out the full issue template. I do not have enough information to help you.

**Comment by fcying** [comment]
I modify vim.ra's build script, it can build vim with python && python3 now.

**Comment by iMichka** [comment]
Is that a change that can be shared, so that other  people can use it? Pull requests are welcome!

**Comment by fcying** [comment]
just add two option to build vim8
```
"--enable-pythoninterp=dynamic",
"--enable-python3interp=dynamic",
```
It make vim  `+python3/dyn` && `+python/dyn`

In vim.rb, there is a comment
```
      # only compile with either python or python3 support, but not both
      # (if vim74 is compiled with +python3/dyn, the Python[3] library lookup segfaults
      # in other words, a command like ":py3 import sys" leads to a SEGV)
```
but I test ":py3 import sys" work fine.

[vim.zip](https://github.com/Linuxbrew/homebrew-core/files/1559231/vim.zip)
