### ISSUE TITLE
python3 with tcl tk not installing

### ISSUE THREAD

**Issue by eleonore88** [Linuxbrew/homebrew-core#5218]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
HOMEBREW_VERSION: 1.3.8
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: fbc16c2b5b62baea3e63bac5bf2e82f1e75126df
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 0b2641e3769c4d26155dc66f7e0838607641b274
Core tap last commit: 11 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/roussel/.cache/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_GIT_CONFIG_FILE: /home/linuxbrew/.linuxbrew/Homebrew/.git/config
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
CPU: octa-core 64-bit nehalem
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 5.0 build
Git: 2.15.1 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.57.0 => /home/linuxbrew/.linuxbrew/opt/curl/bin/curl
Perl: /home/linuxbrew/.linuxbrew/bin/perl => /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: N/A
Kernel: Linux 4.10.0-28-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.3 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: 5.4.0
xorg: 20170115
```
```
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install python3 works. However, when running python3 with pyplot from matplotlib, tkinder was missing. When installing brew install --with-tcl-tk python3, nothing happens. (command line stuck for at least 40 min)

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by iMichka** [comment]
Hi. Thanks for reporting this issue.

First investigations show that this while loop is running forever: https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L443-L465

**Comment by iMichka** [comment]
@sjackman Same problem with `brew install python --with-tcl-tk`.
`formulae.unshift(req_dependency.to_formula)`  is called repeatedly and there is an endless loop due to the `xorg` formula.

I could fix this by moving these lines:
```
elsif req.satisfied?
          Requirement.prune
```
before the `elsif install_requirement_formula?(req_dependency, req, install_bottle_for_dependent` line.
Not sure if this is the right fix. Any opinion on this? I will need to submit this upstream.

I'll run the test suite on my mac with that change before submitting it.

**Comment by sjackman** [comment]
This issue should hopefully be resolved by PR https://github.com/Linuxbrew/brew/pull/542
I cherry-picked 804393efc466e72ea07b3e38b09d39a5a64d1b78 from 1.4.0.

**Comment by sjackman** [comment]
I've merged PR https://github.com/Linuxbrew/brew/pull/542.
Try
```sh
brew update
brew --version
```
and see whether that fixes this issue.

**Comment by iMichka** [comment]
I wanted to wait that brew 1.4.2 has been merged, as there were some changes to the dependency tree setup. I'll give it a second try soon.

I already found out that removing the `:x11` requirement from the `tcl-tk` formula fixes it.

**Comment by iMichka** [comment]
This is fixed since the x11 requirement fix I made in #5820. Both python and python3 now build with tcl-tk by default, similarly to the Mac version.

Closing here.

**Comment by sjackman** [comment]
Thanks, Michka!

**Comment by diamondman** [comment]
This issue appears to be happening again with 'brew install python --with-tcl-tk'. Running brew 1.8.2, debian 9.6. Hanging with one core pegged at 100%. Without tcl-tk, python installs perfectly.
