### ISSUE TITLE
Brew:CommandNotFound

### ISSUE THREAD

**Issue by Juniorn1003** [Linuxbrew/homebrew-core#5253]
I installed brew by : sudo apt-get install build-essential curl file git
in Debian, but it does says no command found when I try to use the brew command.
Feel free to help me out.

**Comment by iMichka** [comment]
Hi. This issue should have been filled here: https://github.com/Linuxbrew/brew

On that page there is also a wiki with install instructions. 

A log file of the installation process would be great. Also, always fill out the issue template. I don’t have enough information to help you.

**Comment by iMichka** [comment]
Closing this issue as the issue template was not filled out and we got no answer in 5 days. Please open your issue on the right issue tracker: https://github.com/Linuxbrew/brew
