### ISSUE TITLE
ld error when try to install krb5

### ISSUE THREAD

**Issue by enzochiau** [Linuxbrew/homebrew-core#5306]
Try to install krb5 with `brew install krb5`.

I got error message as below:

    ==> Downloading https://kerberos.org/dist/krb5/1.16/krb5-1.16.tar.gz
    ######################################################################## 100.0%
    ==> ./configure --disable-silent-rules --prefix=/home/trading/echi/.linuxbrew/Cellar/krb5/1.16
    ==> make
    Last 15 lines from /export/home/echi/.cache/Homebrew/Logs/krb5/02.make:
    : updated OBJS.SH
    rm -f libkrad.so.0.0
    building shared krad library (0.0)
    set -x; objlist=`set -x && perl -p -e 'BEGIN { $SIG{__WARN__} = sub {die @_} }; $e=$ARGV; $e =~ s/OBJS\...$//; s/^/ /; s/ $//; s/ / $e/g;' OBJS.SH` && gcc-5 -shared -fPIC -Wl,-h,libkrad.so.0 -Wl,--no-undefined -o libkrad.so.0.0 $objlist -Wl,--enable-new-dtags -Wl,-rpath -Wl,/home/trading/echi/.linuxbrew/Cellar/krb5/1.16/lib -L../../lib -lkrb5 -lk5crypto -lcom_err -lkrb5support  -lresolv  -ldl -lverto    -Wl,--version-script binutils.versions 
    ++ set -x
    ++ perl -p -e 'BEGIN { $SIG{__WARN__} = sub {die @_} }; $e=$ARGV; $e =~ s/OBJS\...$//; s/^/ /; s/ $//; s/ / $e/g;' OBJS.SH
    + objlist=' attr.so attrset.so client.so code.so packet.so remote.so'
    + gcc-5 -shared -fPIC -Wl,-h,libkrad.so.0 -Wl,--no-undefined -o libkrad.so.0.0 attr.so attrset.so client.so code.so packet.so remote.so -Wl,--enable-new-dtags -Wl,-rpath -Wl,/home/trading/echi/.linuxbrew/Cellar/krb5/1.16/lib -L../../lib -lkrb5 -lk5crypto -lcom_err -lkrb5support -lresolv -ldl -lverto -Wl,--version-script binutils.versions
    /home/trading/echi/.linuxbrew/bin/ld: cannot find -lverto
    collect2: error: ld returned 1 exit status
    make[2]: *** [libkrad.so.0.0] Error 1
    make[2]: Leaving directory `/tmp/krb5-20171227-22796-1gghsrp/krb5-1.16/src/lib/krad'
    make[1]: *** [all-recurse] Error 1
    make[1]: Leaving directory `/tmp/krb5-20171227-22796-1gghsrp/krb5-1.16/src/lib'
    make: *** [all-recurse] Error 1

`brew gist-logs krb5` return result:

    https://gist.github.com/2962ba22dc658fde135a8f54836f7c85

**Comment by iMichka** [comment]
Hi. Thanks for reporting. I see that there is a flag for `verto` here: https://web.mit.edu/kerberos/krb5-1.13/doc/build/options2configure.html

But we do not have a `libverto` formula, so I am unsure how they were able to build this on mac.

**Comment by ezchi** [comment]
Installed libverto with YUM:

    libverto.x86_64                       0.2.5-4.el7                @pub-base
    libverto-devel.x86_64                 0.2.5-4.el7                @pub-base
    libverto-tevent.x86_64                0.2.5-4.el7                @anaconda/7

run `confiure` command with `--with-system-verto`, still can't detect libverto.
with `--without-system-verto`, it doesn't complain anything and compiles. But I have no idea about how to verify the compiled version works or not.

**Comment by iMichka** [comment]
We do not support linking against that system library, because when we build bottles, we can only link against our own libraries.

I do not think adding a verto formula is needed for the moment. I opened a patch upstream to add the flag: https://github.com/Homebrew/homebrew-core/pull/22328

Once this is merged, it will take 1 day or 2 to get this merged to linuxbrew. As you said, it fixes the build for you.

I am not sure about what you mean by:
> how to verify the compiled version works or not.

I guess that you should try to use krb5, and if it works everything should be fine.

**Comment by iMichka** [comment]
Should be fixed with d2842337ee72ba82e018537f2a44bf499b915947.
