### ISSUE TITLE
Reccurence Of Problem With nload

### ISSUE THREAD

**Issue by tundratim** [Linuxbrew/homebrew-core#5373]
I continue to work on a linuxbrew install to an arbitrary filesystem location.  I though I had this handled, but nload is giving me fits.  Gist here:

https://gist.github.com/anonymous/f767d1138c68f80ff81b5b484bb58102

System perl, autoconf, automake, installed.  Also there is a perl instance within the brew tree

**Comment by iMichka** [comment]
Hi. Thanks for reporting this.

The error is:

```
./run_autotools

Running aclocal...
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
Can't locate Autom4te/C4che.pm in @INC (@INC contains: @@HOMEBREW_CELLAR@@/autoconf/2.69/share/autoconf /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /opt/TundraWare/tools/opt/autoconf/bin/autom4te line 37.
BEGIN failed--compilation aborted at /opt/TundraWare/tools/opt/autoconf/bin/autom4te line 37.
aclocal: error: echo failed with exit status: 2
```

We never tried to build `nload`. Let's see if I can reproduce this here: #5387

**Comment by iMichka** [comment]
I did not stumble on that error but a different one. I added a patch and built a bottle: #5387

Can you please try again?
