### ISSUE TITLE
Cannot compile harfbuzz due to seg fault

### ISSUE THREAD

**Issue by andrewyatz** [Linuxbrew/homebrew-core#5396]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
Whilst updating some libraries I encounted an upgrade required to pango and subsequently harfbuzz. Harfbuzz no longer compiles on my machine. The last time I tried it was version 1.5.1 but that was built from source and with no problems. Any help here would be appreciated.

You can see more information from this Gist https://gist.github.com/eb459e3e5d3c31379eb686cc6bf8ef21

**Comment by andrewyatz** [comment]
Hi. it seems that whatever was wrong with `harfbuzz` is no longer wrong. No idea what's changed but happy to close the issue.

**Comment by iMichka** [comment]
Hi. Sorry I could not help you earlier. There is a constant stream of updates to brew and to the formulae, so maybe it got fixed along the way. As this is fixed I won’t be investigation further. Thanks!
