### ISSUE TITLE
Follow-up: GHC `make install` still fails on RHEL HPC, but with new Array to String typing error

### ISSUE THREAD

**Issue by ebzheng** [Linuxbrew/homebrew-core#5397]
# Summary
This is a follow-on to #5170 - I think the original issue was resolved by #5260, but something else seems to have been uncovered.

The error (encountered in trying to install GHC as a dependency of git-annex) on a RHEL HPC resource (hence, no sudo availability) now yields the following new error: 

`Error: no implicit conversion of Array into String`

I'm honestly baffled by why this didn't show up for me previously in #5170, as the new error-causing line (152) is before the old one (153), and I don't believe the line numbers have changed. Admittedly I have no experience with Ruby, so this may be a red herring.

## Full console output
```
==> Installing ghc
==> Downloading https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-src.tar.xz
Already downloaded: /ru-auth/local/home/ezheng/.cache/Homebrew/ghc-8.2.2.tar.xz
==> Downloading https://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz
Already downloaded: /ru-auth/local/home/ezheng/.cache/Homebrew/ghc--gmp-6.1.2.tar.xz
==> ./configure --prefix=/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Cellar/ghc/8.2.2/libexec/integer-gmp --with-pic --==> make
==> make check
==> make install
==> Downloading https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-deb8-linux.tar.xz
Already downloaded: /ru-auth/local/home/ezheng/.cache/Homebrew/ghc--binary-8.2.2.tar.xz
Error: no implicit conversion of Array into String
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:152:in `initialize'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:152:in `new'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:152:in `block (2 levels) in install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:151:in `each'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:151:in `block in install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:146:in `install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/build.rb:156:in `block (2 levels) in install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1094:in `block in brew'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1900:in `block (2 levels) in stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1899:in `block in stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1877:in `stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1089:in `brew'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/build.rb:127:in `block in install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/build.rb:124:in `install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/build.rb:205:in `<main>'
```
## Brew doctor output
As before, I don't believe there's anything relevant here, but I've attached it [here](https://gist.github.com/ebzheng/10557d994ae6723a6475c53af5a03f55) for completeness.
The detected items generally relate to config scripts from a conda install for python 3.

## Brew gist-logs ghc output
Gist logs are available [here](https://gist.github.com/anonymous/1cea766d21db9df56c468e160e5e0b8b).

Thanks all for your help.

**Comment by kaboroevich** [comment]
I also have no experience with ruby, but I believe the issue may be that in the array construction:

`["ghc/stage2/build/tmp/ghc-stage2", Dir["libraries/*/dist-install/build/*.so", "rts/dist/build/*.so*", "utils/*/dist*/build/tmp/*"]]`

Dir creates an array inside an array, and calling |s| on the second element causes the error. You can replace the above section with something like:

`["ghc/stage2/build/tmp/ghc-stage2"].concat(Dir["libraries/*/dist-install/build/*.so", "rts/dist/build/*.so*", "utils/*/dist*/build/tmp/*"])`

as a workaround. Unfortunately for me, I still run into the "Not enough room for program headers" ([#4413](https://github.com/Linuxbrew/homebrew-core/issues/4413)) issue.

**Comment by ebzheng** [comment]
@kaboroevich - thanks, your suggestion appears to work, and it's concordant with what I suspected. I also run into the #4413 problem, but I suspect that may be a makefile/upstream issue. I will try to do a bit of poking to see if I can replicate it in a cleaner install.

**Comment by iMichka** [comment]
Hi. Would you like to submit your fix for the array problem? Pull requests are welcome.

For the other issue, I never could fix it, but it would be great if somebody can contact upstream and ask for help. Thanks!

**Comment by ebzheng** [comment]
@kaboroevich - I'll defer to you for a week on the pull request (it was yours, after all).

I'm planning to try and contact GHC upstream once some other fires are put out on my end (still haven't had a chance to actually replicate it in a clean environment).

**Comment by ebzheng** [comment]
Closing this, as the titled issue has been fixed.

**Comment by iMichka** [comment]
Yes, right, I forgot to close this one. Thanks for all again!
