### ISSUE TITLE
openssl@1.1 will not build

### ISSUE THREAD

**Issue by tundratim** [Linuxbrew/homebrew-core#5407]
Gists here:

https://gist.github.com/anonymous/94427978e6f078bdcc2ea3d6b0209dd8

**Comment by tundratim** [comment]
Of interest:  It is possible to get it installed with:

brew install openssl@1.1 --without-test

This suggests that the tests need to be rethought ...

**Comment by iMichka** [comment]
Hi. Thanks for reporting this.

The error is:
```
make depend && make _tests
make[1]: Entering directory '/tmp/openssl@1.1-20180106-25486-1ifavv9/openssl-1.1.0g'
make[1]: Leaving directory '/tmp/openssl@1.1-20180106-25486-1ifavv9/openssl-1.1.0g'
make[1]: Entering directory '/tmp/openssl@1.1-20180106-25486-1ifavv9/openssl-1.1.0g'
( cd test; \
  mkdir -p test-runs; \
  SRCTOP=../. \
  BLDTOP=../. \
  RESULT_D=test-runs \
  PERL="/usr/bin/perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=`cd .././engines; pwd` \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl .././test/run_tests.pl  )
Can't locate Module/Load/Conditional.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at .././test/run_tests.pl line 20.
BEGIN failed--compilation aborted at .././test/run_tests.pl line 20.
make[1]: *** [Makefile:155: _tests] Error 2
make[1]: Leaving directory '/tmp/openssl@1.1-20180106-25486-1ifavv9/openssl-1.1.0g'
make: *** [Makefile:152: tests] Error 2
```

We could vendor the perl module (Conditional.pm), like in the `vit` formula for example, and see if it helps. Could you give this a try?

If not we could disable the `make test` call on Linux.

**Comment by tundratim** [comment]
@iMichka Sorry, I am pretty new to linuxbrew.  Not sure what this means: "vendor the perl module"

Happy to help otherwise.

**Comment by iMichka** [comment]
Look at the `vit.rb` formula for an example:

Vendoring means adding a resource block to download the missing perl package:
https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/vit.rb#L20-L23

And then in the install block we install it to the `libexec` subdirectory:
https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/vit.rb#L20-L23

Exactly the same can be done for `openssl@1.1`. Would you like to try to submit a pull request for this?
