### ISSUE TITLE
systemd failed to compile because configure is picking up old version of libgpg-error

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#5408]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
My linuxbrew is installed in a non-standard location and I have to build systemd from source. I was doing
```
brew upgrade systemd --keep-tmp
```
The building process halt at the configure stage when checking for the library GPG-ERROR. Digging into the config.log I found: 
```
configure:19286: result: no
configure:19521: checking for libgcrypt-config
configure:19539: found /usr/bin/libgcrypt-config
configure:19552: result: /usr/bin/libgcrypt-config
configure:19569: checking for LIBGCRYPT - version >= 1.4.5
configure:19603: result: yes (1.4.5)
configure:19704: checking for gpg-error-config
configure:19722: found /usr/bin/gpg-error-config
configure:19735: result: /usr/bin/gpg-error-config
configure:19744: checking for GPG Error - version >= 1.12
configure:19803: result: no
configure:19805: error: *** GCRYPT/GPG-ERROR headers not found.
```
The following patch can fix this issue:

```
diff --git a/Formula/systemd.rb b/Formula/systemd.rb
index 2e56064970..368db4d330 100644
--- a/Formula/systemd.rb
+++ b/Formula/systemd.rb
@@ -25,6 +25,7 @@ class Systemd < Formula
   depends_on "expat"
   depends_on "libcap"
   depends_on "util-linux" # for libmount
+  depends_on "libgpg-error"
 
   # src/core/dbus.c:1022:5: internal compiler error: Segmentation fault
   fails_with :gcc => "4.8"
@@ -52,7 +53,8 @@ class Systemd < Formula
       "--sysconfdir=#{prefix}/etc",
       "--with-rootprefix=#{prefix}",
       "--with-sysvinit-path=#{prefix}/etc/init.d",
-      "--with-sysvrcnd-path=#{prefix}/etc/rc.d"
+      "--with-sysvrcnd-path=#{prefix}/etc/rc.d",
+      "--with-libgpg-error-prefix=#{Formula["libgpg-error"].opt_prefix}"  
     system "make", "install"
   end
```
Also, it looks like the configure is picking up perl, gawk and libgcrypt in /usr/bin rather than those from linuxbrew, which might potentially break other things?

**Comment by iMichka** [comment]
Hi. Cool that you found that out. Would you like to submit a pull request to fix this? You will also need to bump the revision of systemd so that a new bottle is built.

For the other dependencies, it would be also great to find a way to tell systemd to use the right ones, and not the ones from `/usr/bin`. But I guess that configure is just looking at what is in the path?

**Comment by Char-Aznable** [comment]
I created PR #5446 for this. For other dependencies, there doesn't seem to be easy way to specify their paths in configure. It would perhaps involve tweaking some environment variables in brew.

**Comment by iMichka** [comment]
#5446 has been merged. Would you like to work on looking at the other dependencies?
