### ISSUE TITLE
wget: Error: wget contains conflicting version recursive dependencies:   openssl, openssl@1.1

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#5431]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
I'm trying to install wget by
```
brew install wget
```
and I get error:
```
Error: wget contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree wget`.
```
Running 
```
brew deps --tree wget
```
shows:
```
wget
├── libidn2
│   ├── gettext
│   │   ├── libxml2
│   │   │   ├── python
│   │   │   │   ├── readline
│   │   │   │   │   └── ncurses
│   │   │   │   ├── sqlite
│   │   │   │   │   └── readline
│   │   │   │   │       └── ncurses
│   │   │   │   ├── gdbm
│   │   │   │   ├── openssl
│   │   │   │   │   └── zlib
│   │   │   │   ├── bzip2
│   │   │   │   ├── ncurses
│   │   │   │   └── zlib
│   │   │   └── zlib
│   │   └── ncurses
│   └── libunistring
├── openssl@1.1
│   └── perl
│       ├── gdbm
│       ├── berkeley-db
│       └── expat
│           └── libbsd
└── util-linux
    └── ncurses
```
Can anyone look into this?

**Comment by sjackman** [comment]
Thanks for the bug report, @Char-Aznable. I'm looking into it.
These two PRs together should hopefully resolve the issue:
https://github.com/Linuxbrew/brew/pull/561
https://github.com/Linuxbrew/homebrew-core/pull/5448

**Comment by sjackman** [comment]
PR to Homebrew/brew: https://github.com/Homebrew/brew/pull/3654

**Comment by sjackman** [comment]
I've merge the above two PRs. This issue should be resolved.
