### ISSUE TITLE
protobuf cannot compile due to system python being too old

### ISSUE THREAD

**Issue by euclio** [Linuxbrew/homebrew-core#5436]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/b495c5968fb0bb95b4f6a8a5c2cb8460
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  I was trying to install the protobuf package as a dependency of mosh.
- What happened (include command output)
  Installation failed, because the system python does not support `option --no-user-cfg`.
- What you expected to happen
   I have a brewed Python, I would expect the installation to use that python to install the package.
- Step-by-step reproduction instructions (by running `brew install` commands)
  `brew install protobuf`

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. We will tag brew 1.4.2 in a few hours with a potential fix for this. I'll let you know when it is ready.

**Comment by iMichka** [comment]
We merged 1.4.2 and a fix for this. Please update and tell us if it works for you now.

**Comment by euclio** [comment]
Looks like it worked! Thanks.
