### ISSUE TITLE
brew install qmmp - musepack Error: No such file or directory - libmpcdec/libmpcdec.dylib

### ISSUE THREAD

**Issue by nick-dimitrov** [Linuxbrew/homebrew-core#5609]
==> Downloading https://files.musepack.net/source/musepack_src_r475.tar.gz
Already downloaded: /home/nick/.cache/Homebrew/musepack-r475.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
==> make install
Error: No such file or directory - libmpcdec/libmpcdec.dylib

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. I opened a pull request to try to fix this: #5612
