### ISSUE TITLE
brew install mpv error -python3 waf install  /home/linuxbrew/.linuxbrew/bin/ld: cannot find -llua.5.1

### ISSUE THREAD

**Issue by nick-dimitrov** [Linuxbrew/homebrew-core#5614]
I also hook up a log file:
[mpv_log_install.txt](https://github.com/Linuxbrew/homebrew-core/files/1629869/mpv_log_install.txt)
Is it possible to have something in common with the manually installed version of libass?
https://github.com/Linuxbrew/homebrew-core/pull/4873

==> python3 waf install
Last 15 lines from /home/nick/.cache/Homebrew/Logs/mpv/04.python3:
[425/439] Compiling video/out/vo_xv.c
[426/439] Compiling video/out/x11_common.c
[427/439] Compiling osdep/terminal-unix.c
[428/439] Compiling osdep/io.c
[429/439] Compiling ta/ta_talloc.c
+ install /home/linuxbrew/.linuxbrew/Cellar/mpv/0.27.0_5/lib/pkgconfig/mpv.pc (from build/libmpv/mpv.pc)
+ install /home/linuxbrew/.linuxbrew/Cellar/mpv/0.27.0_5/share/doc/mpv/mpv.html (from build/DOCS/man/mpv.html)
+ install /home/linuxbrew/.linuxbrew/Cellar/mpv/0.27.0_5/share/man/man1/mpv.1 (from build/DOCS/man/mpv.1)
[433/439] Linking build/mpv
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -llua.5.1
collect2: error: ld returned 1 exit status

**Comment by Verifirs** [comment]
I also have this problem.

**Comment by iMichka** [comment]
Hi. I do not have much time at the moment so somebody will have to troubleshoot this if you want to get this fixed. I have no clue what is going on, but I saw this lua error before in other formulae. Maybe the lua 5.1 is broken?

**Comment by iMichka** [comment]
Working on a solution here: https://github.com/Linuxbrew/homebrew-core/pull/7152
