### ISSUE TITLE
Both imagemagick and graphicsmagick: Wrong version of JPEG: library is 80, caller expects 90.

### ISSUE THREAD

**Issue by TiZ-EX1** [Linuxbrew/homebrew-core#5646]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): Use the convert utility in both graphicsmagick and imagemagick.
- What happened (include command output): The command immediately fails with: `convert: Wrong JPEG library version: library is 80, caller expects 90 '/home/tiz/Pictures/Wallpaper/Nature/bo0xvn/VII.098.jpg' @ error/jpeg.c/JPEGErrorHandler/332.`
- What you expected to happen: My image gets converted.
- Step-by-step reproduction instructions (by running `brew install` commands): I installed jpeg as a bottle initially, and graphicsmagick and imagemagick both compile from source against this. I compiled jpeg from source, and recompiled the two packages. They both failed in this circumstance as well.

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by iMichka** [comment]
Some other people have been struggling with this on mac:
https://groups.google.com/forum/#!topic/torch7/u3C7UdiMMyk
https://github.com/torch/image/issues/137

I will need to read this (or you can have a look).

**Comment by TiZ-EX1** [comment]
The top link fixes it by removing GTK+ which I don't think is gonna help us. The bottom link suggests conflicts between system libraries and homebrew libraries. I can't just get rid of libjpeg8 in my Ubuntu 16.04 system. It built against libjpeg9 that we bundle; I just don't know why it won't load it.

**Comment by iMichka** [comment]
Could you try to go to the `Cellar` folder and run:
`find -name "*.so" -print | xargs ldd | grep jpeg`

For me it gives:
```
linuxbrew@a40a32b4acd5:~/.linuxbrew/Cellar$ find -name "*.so" -print | xargs ldd | grep jpeg
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007f9545076000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007f1623c67000)
./imagemagick/7.0.7-22_1/lib/ImageMagick/modules-Q16HDRI/coders/jpeg.so:
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007f1b5fd23000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007efe5de84000)
./jpeg/9b/lib/libjpeg.so:
```

Just to be sure there is no dependency with an older libjpeg version in your dependency tree.
A `brew cleanup` is also recommended.

**Comment by TiZ-EX1** [comment]
For me, I get this:

```
WC130-TiZ:Cellar$ find -name "*.so" -print | xargs ldd | grep jpeg
./jpeg/9b/lib/libjpeg.so:
./gdk-pixbuf/2.36.11/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so:
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007fb30acff000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007fccc12a5000)
./graphicsmagick/1.3.28_2/lib/GraphicsMagick/modules-Q16/coders/jpeg.so:
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fe195031000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f4960da3000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f521d6fd000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f521c9a7000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fbfef21f000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007fbfee4c9000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f55eca41000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f55ebceb000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f825cb5a000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fc33b81b000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f334f732000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f378a2bc000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f3c2d3d4000)
./imlib2/1.4.10_2/lib/imlib2/loaders/jpeg.so:
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f231e49f000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f8bdde7c000)
```

I don't know why it got the libjpeg.so.8 from outside.

**Comment by TiZ-EX1** [comment]
I just tried it on my server since httpd works on it and not on my main boxes and got this:

```
Maxwell:Cellar$ find -name "*.so" -print | xargs ldd | grep jpeg
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007fd89f149000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f91b9f38000)
./graphicsmagick/1.3.28_2/lib/GraphicsMagick/modules-Q16/coders/jpeg.so:
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007fd65c9da000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f5031b8e000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f2948e85000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007fb7e26a6000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f2d45367000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f5d1fb14000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007f7ba1a16000)
	libjpeg.so.9 => /xusr/linuxbrew/lib/libjpeg.so.9 (0x00007ffa63e3a000)
./jpeg/9b/lib/libjpeg.so:
```

That server actually has libjpeg.so.8 installed too, though...

**Comment by iMichka** [comment]
I tried to install `graphicsmagick`, which got poured from our precompiled bottle:
```
linuxbrew@a40a32b4acd5:~/.linuxbrew/Cellar$ find -name "*.so" -print | xargs ldd | grep jpeg
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007fc2c97fe000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007f7060705000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007f5fb52c7000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007f67f70ba000)
./graphicsmagick/1.3.28_2/lib/GraphicsMagick/modules-Q16/coders/jpeg.so:
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007fca44483000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007f4f090c9000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007fac17141000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007fc0e9270000)
./imagemagick/7.0.7-22_1/lib/ImageMagick/modules-Q16HDRI/coders/jpeg.so:
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007f8da9651000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007f1d78c9e000)
./jpeg/9b/lib/libjpeg.so:
```

It may be that you installed it some time ago and there was some env filtering bug. Or some linkage bug. We have stricter checks for that now.

You can try uninstalling it and installing it again.

**Comment by TiZ-EX1** [comment]
I actually tried uninstalling and reinstalling it just now. Still no good. I even removed the development libraries for libjpeg8 from my Ubuntu installation, and it still finds it somehow.
