### ISSUE TITLE
problems: could not install swagger

### ISSUE THREAD

**Issue by ralfhauser** [Linuxbrew/homebrew-core#5705]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [ X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [X ] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/ac5e549cb4580f707079e8d96f11fe85 
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  /home/linuxbrew/.linuxbrew/bin/brew install swagger-codegen
- What happened (include command output)

...
==> Downloading https://github.com/swagger-api/swagger-codegen/archive/v2.3.1.ta
Already downloaded: /home/hauser/.cache/Homebrew/swagger-codegen-2.3.1.tar.gz
sh: 0: getcwd() failed: No such file or directory
==> mvn clean package
Last 15 lines from /home/hauser/.cache/Homebrew/Logs/swagger-codegen/01.mvn:

mvn
clean
package

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sh: 0: getcwd() failed: No such file or directory
/home/linuxbrew/.linuxbrew/Cellar/maven/3.5.2/libexec/bin/mvn: 71: cd: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
Picked up _JAVA_OPTIONS:  -Duser.home=/home/hauser/.cache/Homebrew/java_cache
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
	at java.lang.System.initProperties(Native Method)
	at java.lang.System.initializeSystemClass(System.java:1166)

Error: no implicit conversion of nil into String
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:18:in `exec'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:18:in `block in popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:11:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:11:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:3:in `popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/swagger-codegen.rb:21:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:156:in `block (2 levels) in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1094:in `block in brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1900:in `block (2 levels) in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1899:in `block in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1877:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1089:in `brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:127:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:124:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:205:in `<main>'
hauser@armin2:~$ /home/linuxbrew/.linuxbrew/bin/brew doctor
Your system is ready to brew.

- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by tutnes** [comment]
I am getting the same issue. Have tried to install on ubuntu, and on ubuntu in windows

**Comment by rubens21** [comment]
Same here... I guess you guys have found the solution, didn't you, @tutnes or @ralfhauser?

**Comment by lucyjosef** [comment]
Hi ! Exact same issue here too, I've tried to remove and reinstall java (as I thought java was responsible of my trouble... But still have this pb)
Did someone find a fix for this ?
