### ISSUE TITLE
Cannot build vimpc on LinuxMint 18.2

### ISSUE THREAD

**Issue by CaptainQuirk** [Linuxbrew/homebrew-core#5706]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? [GIST](https://gist.github.com/6f4b36e9b9d0d5099a33d4a3799a9090)
- **What you were trying to do (and why)**
I'm trying to install `vimpc` on a Linux Mint 18.2 Cinammon 64bit

- **What happened**

I get the following configure error on build : 

```
==> Downloading https://downloads.sourceforge.net/project/vimpc/Release%200.09.1/vimpc-0.09.1.tar.gz
Already downloaded: /home/leonard/.cache/Homebrew/vimpc-0.09.1.tar.gz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/vimpc/0.09.1_1
Last 15 lines from /home/leonard/.cache/Homebrew/Logs/vimpc/01.configure:
checking for taglib/taglib.h... yes
checking mpd/client.h usability... yes
checking mpd/client.h presence... yes
checking for mpd/client.h... yes
checking for mpdclient... no
configure: error: Package requirements (libmpdclient) were not met:

No package 'libmpdclient' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables mpdclient_CFLAGS
and mpdclient_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
```

- **What you expected to happen**

A working install !

- **What I tried**

- setting the `PKG_CONFIG_PATH` env variable : 

```
export PKG_CONFIG_PATH=/home/linuxbrew/.linuxbrew/Cellar/libmpdclient/2.13/lib/x86_64-linux-gnu/pkgconfig && brew install vimpc
```
> :-1: same result

- setting the `pdpclient_LIBS` env variable : 

```
export mpdclient_LIBS=/home/linuxbrew/.linuxbrew/Cellar/libmpdclient/2.13/lib/x86_64-linux-gnu/pkgconfig/libmpdclient.pc && brew install vimpc
```

> :-1: same result

- Step-by-step reproduction instructions (by running `brew install` commands)

* run `brew install vimpc`

**Comment by CaptainQuirk** [comment]
Someone maybe ?

**Comment by maxim-belkin** [comment]
could you please try the following one-liner :trollface::
```
brew cleanup --prune=0 && brew update && brew update && brew upgrade && brew cleanup --prune=0 && brew install --only-dependencies vimpc && brew install vimcp
```

**Comment by CaptainQuirk** [comment]
Seems to have done the trick ! What could have been the problem ?

**Comment by maxim-belkin** [comment]
Apparently, there was a transient bug with your local installation or in Linuxbrew's logic that handles dependencies:

```
configure: error: Package requirements (libmpdclient) were not met:

No package 'libmpdclient' found
```

You submitted your report on 01/24 and your Linuxbrew was 1.4.3, which was at least one version behind the current one at that moment (https://github.com/Linuxbrew/brew/releases) Basically, that "one-liner" did the `brew update` step (the second checkbox that you have, actually, checked). It cleaned up your cache and upgraded Linuxbrew/brew to the latest version. The rest is not so important (updating formulas and splitting `brew install` into two steps: dependencies and then the actual package).
