### ISSUE TITLE
How to install on ZSH?

### ISSUE THREAD

**Issue by ShalokShalom** [Linuxbrew/homebrew-core#5803]
The homepage shows no way currently how to install on zsh. Thanks

**Comment by iMichka** [comment]
Hi. This should be as simple as: `brew install zsh`. I am not sure I understand the question.

Also, please always fill out the issue template, with a more detailed description of the problem you are seeing. Thanks. Because now I will need to ask you your `brew doctor`, `brew config` and so on ..

**Comment by ShalokShalom** [comment]
On ZSH

How to install linuxbrew, when I use zsh?

The tutorial on the homepage shows only the commands for bash.

**Comment by iMichka** [comment]
OK I misread your sentence. You have zsh installed, and want to install brew. The instructions are similar, as bash and zsh are quite similar for basic commands.

The only difference is that you will need to edit your .zshrc to put brew in your path (if you wish to do that).

Without more details about what exactly is the problem or what error message you get I will not be able to help you further.

Also, I do not think we will add specific instructions for zsh (or maybe if it gains enough users to replace bash as a default on most distros).

**Comment by ShalokShalom** [comment]
Can you put this on the homepage?
