### ISSUE TITLE
Override bottle (provide linux bottle in hosted environment)

### ISSUE THREAD

**Issue by tivvit** [Linuxbrew/homebrew-core#5823]
This is not an issue. It is a question but I did not find a better place to ask.

I want to provide hosted bottle with fallback to original formula outside of bintray.com.
Is that possible?

Example:
https://github.com/Homebrew/homebrew-core/blob/1d6446a1db65f375e5ed0e12539b825708ee1d84/Formula/kubernetes-cli.rb is bottled for mac but not for linux. I see that some versions are bottled (https://bintray.com/linuxbrew/bottles/kubernetes-cli#) but not all of them. I want to build a bottle and upload it to internal company repository without having to create duplicate formula.

**Comment by iMichka** [comment]
`kubernetes-cli` was building fine until now, and then at one point it failed to build and I did not update the bottle. I gave up on fixing this here: #4676.

I just rebased that PR, to see if it builds again. Maybe you could have a look at the error message.

For the fallback, you could setup you own bintray org, fork Linuxbrew, and manage your own bottles. Or have your own tap with a `kubernetes-cli-private` formula. Modifications to Linuxbrew may be needed to do so.

**Comment by tivvit** [comment]
Thanks for quick answer. 

I will take a look at the error. 

I will think about both options and I will let you know.

**Comment by iMichka** [comment]
I am closing this issue. If you want, you can open a separate issue for `kubernetes-cli`, but I do not guarantee that I will have time to look at it in a near future.
