### ISSUE TITLE
libstfl: build failure [Linux]

### ISSUE THREAD

**Issue by xsteadfastx** [Linuxbrew/homebrew-core#5826]
# Please fill out the issue checklist below, and provide all of the requested information.

i try to install newsboat and run into an error with libstftl. i ran `brew install newsboat`. I get this error:

```gcc -pthread -shared -Wl -o libstfl.0.24.dylib -liconv -lncurses public.o base.o parser.o dump.o style.o binding.o iconv.o widgets/wt_label.o widgets/wt_textview.o widgets/wt_box.o widgets/wt_list.o widgets/wt_table.o widgets/wt_textedit.o widgets/wt_checkbox.o widgets/wt_input.o
gcc-7: error: unrecognized command line option ‘-Wl’; did you mean ‘-W’?
Makefile:42: recipe for target 'libstfl.0.24.dylib' failed
```

here is the gist: https://gist.github.com/anonymous/cb33f49f57b0308e2a9b0e0a9d1754c1

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by maxim-belkin** [comment]
Just by quickly looking at the formula, I believe it has yet to be updated to work on Linux...

**Comment by maxim-belkin** [comment]
@iMichka 
Here is what I had to change in the formula to make it compile on Linux:
```
$ git --no-pager diff
diff --git a/Formula/libstfl.rb b/Formula/libstfl.rb
index 1d6bc1b..e838b3c 100644
--- a/Formula/libstfl.rb
+++ b/Formula/libstfl.rb
@@ -12,10 +12,17 @@ class Libstfl < Formula
     sha256 "88971ef99df357abe7189391d3c6fe559dcd24c3faaf0e0b22d91a94ccbbeefb" => :el_capitan
   end
 
-  option "without-perl", "Build without Perl support"
+  if OS.mac?
+    option "without-perl", "Build without Perl support"
+  else
+    option "with-perl", "Build with Perl support"
+  end
+ 
   option "without-python", "Build without Python 2 support"
   option "without-ruby", "Build without Ruby support"
 
+  depends_on "python" unless OS.mac?
+  depends_on "perl" if build.with?("perl") && OS.linux?
   depends_on "ruby" => :recommended if MacOS.version <= :mountain_lion
   depends_on "swig" => :build if build.with?("python") || build.with?("ruby") || build.with?("perl")
 
@@ -35,10 +42,6 @@ class Libstfl < Formula
     inreplace "stfl_internals.h", "ncursesw/ncurses.h", "ncurses.h"
 
     inreplace "Makefile" do |s|
-      s.gsub! "ncursesw", "ncurses"
-      s.gsub! "-Wl,-soname,$(SONAME)", "-Wl"
-      s.gsub! "libstfl.so.$(VERSION)", "libstfl.$(VERSION).dylib"
-      s.gsub! "libstfl.so", "libstfl.dylib"
       s.gsub! "include perl5/Makefile.snippet", "" if build.without? "perl"
       s.gsub! "include python/Makefile.snippet", "" if build.without? "python"
       s.gsub! "include ruby/Makefile.snippet", "" if build.without? "ruby"
@@ -48,10 +51,7 @@ class Libstfl < Formula
       inreplace "python/Makefile.snippet" do |s|
         # Install into the site-packages in the Cellar (so uninstall works)
         s.change_make_var! "PYTHON_SITEARCH", lib/"python2.7/site-packages"
-        s.gsub! "lib-dynload/", ""
-        s.gsub! "ncursesw", "ncurses"
-        s.gsub! "gcc", "gcc -undefined dynamic_lookup #{`python-config --cflags`.chomp}"
-        s.gsub! "-lncurses", "-lncurses -liconv"
+        s.gsub! "/usr/include/python", "#{Formula["python"].opt_include}/python"
       end
 
       # Fails race condition of test:
@@ -62,7 +62,7 @@ class Libstfl < Formula
 
     system "make"
 
-    inreplace "perl5/Makefile", "Network/Library", libexec/"lib/perl5" if build.with? "perl"
+    inreplace "perl5/Makefile", "Network/Library", libexec/"lib/perl5" if OS.mac? && build.with?("perl")
 
     system "make", "install", "prefix=#{prefix}"
   end
```

The test fails but this diff can be used at least as a starting point.
Perl, as always,... gives some troubles so I disabled it. If you can adopt these changes to make formula work on Linux - that would be awesome!

**Comment by xsteadfastx** [comment]
hey thanks for working on it. i never worked on a recipe and i never thought this is so much work to get it working :)

**Comment by iMichka** [comment]
No, I had not time to look at this. A pull request would be welcome :)

**Comment by anishmittal2020** [comment]
Please fix this issue.

**Comment by sjackman** [comment]
This formula needs `depends_on :macos => :help_wanted` from PR https://github.com/Linuxbrew/brew/pull/831.

**Comment by iMichka** [comment]
I would be willing to review a pull request for this, but have no time to work on this myself.

**Comment by sjackman** [comment]
@jonchang is working on `depends_on :macos => :help_wanted`.
