### ISSUE TITLE
Error installing systemd on CentOS 6

### ISSUE THREAD

**Issue by willsALMANJ** [Linuxbrew/homebrew-core#5882]
When I tried to build systemd on a CentOS 6 system, I initially get an error about `audit_open` not being defined in `/usr/lib64/libaudit.so`. I assume that the system version of `libaudit` is probably just too old for systemd (should `libaudit` be packaged in brew?). I tried `brew edit systemd` and added `--disable-audit` to the configure step. The result is [this gist](https://gist.github.com/willsALMANJ/35e3403a65005b9a76fd2d45b8592e6a) (I hope the format is okay -- this is on a system without a network connection so I copied the files over by hand -- in hindsight, maybe I could have copied `~/.cache/Homebrew/Logs` to a machine with network access and run `brew gist-logs` there?).

It seems like the main error now is

```
/tmp/systemd-20180131-22271-1yfooia/systemd-234/src/test/test-ns.c:79: undefined reference to `setup_namespace'
```

and from my research this should come from PAM. I did install `util-linux --with-linux-pam` before trying to install systemd.

Also, I'd appreciate any feedback on what I am trying to do which is install `gtk+3` and use it to run GUI applications like Firefox on CentOS 6. The chain of dependencies I am on now with systemd is `systemd > linuxbrew/xorg/mesa > libepoxy > gtk+3`. Even if I get past the current problem, will I be able to get gtk+3 built on CentOS 6? And if I do, will I be able to use it to run something like Firefox 58?

**Comment by iMichka** [comment]
Hi. Thanks for reporting this.

For the first issue, we have 2 solutions:
- create a `libaudit` formula and use it as a dependency
- use the `--disable-audit` flag

Would you like to submit a PR for this? I can guide you through the process.

For the second issue, did you try compiling `util-linux` without the `pam` option?

**Comment by willsALMANJ** [comment]
I can try packaging `libaudit`. It looks like the place to look for it is https://github.com/linux-audit/audit-userspace

Regarding `util-linux` and `pam`, I can try building without `pam`, but I remember there being a reason I wanted the `pam` option. I might need to rebuild things without `pam` to figure out what that was again.

**Comment by iMichka** [comment]
There is another place where we would need pam, see #6132

@sjackman should we move pam to core?

**Comment by sjackman** [comment]
I'm happy with moving `linux-pam` to core.
