### ISSUE TITLE
Error with the installation of Mariadb

### ISSUE THREAD

**Issue by unixfox** [Linuxbrew/homebrew-core#5962]
I tried to install mariadb but it failed at:
```
-- Looking for include file numa.h - found
-- Looking for include file numaif.h
-- Looking for include file numaif.h - found
-- Performing Test HAVE_LIBNUMA
-- Performing Test HAVE_LIBNUMA - Failed
CMake Error at cmake/numa.cmake:38 (MESSAGE):
  Could not find numa headers/libraries
Call Stack (most recent call first):
  storage/innobase/innodb.cmake:34 (MYSQL_CHECK_NUMA)
  storage/innobase/CMakeLists.txt:21 (INCLUDE)
```

Note: I don't have any issue to install mysql on Linuxbrew.

Here is the gist logs: https://gist.github.com/unixfox/c3c5716675e4424f31b23b0decc7c95d
Brew is up-to-date and I ran `brew doctor`.
The package `libnuma-dev` is installed:
```
[vps ~] apt-cache policy libnuma-dev
libnuma-dev:
  Installed: 2.0.10-1
  Candidate: 2.0.10-1
  Version table:
 *** 2.0.10-1 0
        500 http://deb.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
```

Technical informations about my dedicated server:
- OS: `Debian 8.10`
- brew version:
```
[vps ~] brew --version
Homebrew 1.5.1
Homebrew/homebrew-core (git revision e37ec1; last commit 2018-02-05)
```

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. Here is what is happening.

You have libnuma installed. `cmake` finds that out, and wants to set that option to `ON`. But homebrew does not allow to include the library as it is not defined in it's dependency list.

Could you try to add `-DWITH_NUMA=OFF` to the formula and see if it helps? Of course this disables numa support. If numa support needs to be added, one would need to create a `libnuma` formula first.

If it works for you, we can submit a patch to https://github.com/Homebrew/homebrew-core to fix this (and it will be merged back here a few hours/days later).

**Comment by unixfox** [comment]
Thank you @iMichka, I got a successful build by adding `-DWITH_NUMA=OFF` to the formula.

**Comment by iMichka** [comment]
Would you like to submit a patch to https://github.com/Homebrew/homebrew-core ? Please fill out the issue template on their page. You can ping me there so I can help if there are any questions.

**Comment by unixfox** [comment]
@iMichka The developers of homebrew closed my pull request: https://github.com/Homebrew/homebrew-core/pull/23710#issuecomment-363364781

**Comment by iMichka** [comment]
Err sorry my bad, I didn't know this was a linux only library. If I had known that, I would have told you to submit the patch here. Do not worry :)

You can submit your patch here and I will merge it. Just change it to:
`args << -DWITH_NUMA=OFF unless OS.mac?`, so that we keep track of what is linux only. Thanks!

**Comment by iMichka** [comment]
I'm closing this issue, we have a pull request open with a fix for this.
