### ISSUE TITLE
Cannot find a vendored version of ruby for your i686 processor on Linuxbrew!

### ISSUE THREAD

**Issue by programizer** [Linuxbrew/homebrew-core#5995]
First I tried to `brew install rbenv` got error which told me to create an issue. Successfully ran `brew update` once. But the second time I got the pretty much self-explaining error in the title. Is there any hope of a x86 version of ruby being added to linuxbrew? Or would I have to self-compile and add to a certain repo where linuxbrew is looking?

**Comment by iMichka** [comment]
Hi. Same answer as here https://github.com/Linuxbrew/brew/issues/575#issuecomment-359698796

i686 is 32 bit. We could create a portable ruby bottle for this, but we do not have much time and no support, so this is not something we plan to do on short term. Also, most processors are going away from 32 bit, so it is a lot of work to support these old unsupported processors ...
