### ISSUE TITLE
path lost with sudo

### ISSUE THREAD

**Issue by jney** [Linuxbrew/homebrew-core#6085]
Hello, i installed neovim, but trying to use it using `sudo` failed because linux brew install path `/home/linuxbrew/.linuxbrew/bin/` is not available, even commenting `Defaults env_reset` in `sudoers` file.
 i know that mac brew install binaries in more common path `/usr/local/bin` so sudo work just fine.
how do you guys, deal with that issue?

**Comment by iMichka** [comment]
What is the error message you are getting?

Also, please fill out the issue template, because I will ask you your `brew doctor` and `brew config` ...

**Comment by maxim-belkin** [comment]
@jney have you tried `sudo PATH="$PATH" neovim`?
