### ISSUE TITLE
xz Not Building On ARM7 (Raspberry Pi)

### ISSUE THREAD

**Issue by tundratim** [Linuxbrew/homebrew-core#6190]
See: 

https://gist.github.com/83db50569b40b87b82d94c3fdda49dbf

It appears to be failing on of the post build tests, but not quite sure why.

**Comment by iMichka** [comment]
Hi. Thanks for reporting.

The error is:
```
unexpected output from xzgrep
FAIL: test_scripts.sh
=========================================
1 of 9 tests failed
Please report to lasse.collin@tukaani.org
```

Could you run:
`brew edit xz`, and comment out the `system "make", "check"` line?
Then run:
`export HOMEBREW_NO_AUTO_UPDATE=1 && brew install xz`

Once this is done, you should have a working `xz` installation.

I think the failing test is this one:
https://github.com/cameron/xz/blob/master/tests/test_scripts.sh#L55-L73

Would you mind to try to debug the failing test?

**Comment by tundratim** [comment]
Yes, removing the check allows xz to build completely

**Comment by iMichka** [comment]
A  pull request to disable the check is fine for me, but I would prefer that this is properly debugged and reported upstream. Your `xz` installation may be broken in some obscure way.

Anyway, there is a workaround now, so I'll close this issue. Pull requests with a patch are welcome.
