### ISSUE TITLE
Building ruby under ubuntu 17.10 fails

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/homebrew-core#6210]
Here is the content of the config.log content:

```
configure:3908: $? = 0
configure:3897: gcc-5 -v >&5
Reading specs from /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_1/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/specs
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_1/libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_1  --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/home/linuxbrew/.linuxbrew/opt/gmp --with-mpfr=/home/linuxbrew/.linuxbrew/opt/mpfr --with-mpc=/home/linuxbrew/.linuxbrew/opt/libmpc --with-isl=/home/linuxbrew/.linuxbrew/opt/isl  --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.5.0_1' --with-bugurl=https://github.com/Homebrew/homebrew/issues --with-boot-ldflags='-static-libstdc++ -static-libgcc ' --disable-nls --disable-multilib
Thread model: posix
gcc version 5.5.0 (Homebrew gcc 5.5.0_1) 
configure:3908: $? = 0
configure:3897: gcc-5 -V >&5
gcc-5: error: unrecognized command line option '-V'
configure:3908: $? = 1
configure:3897: gcc-5 -qversion >&5
gcc-5: error: unrecognized command line option '-qversion'
configure:3908: $? = 1
configure:3928: checking whether the C compiler works
configure:3950: gcc-5    conftest.c  >&5
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
configure:3954: $? = 1
configure:3992: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define CANONICALIZATION_FOR_MATHN 1
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3997: error: in `/tmp/ruby-20180221-16356-hwa41a/ruby-2.5.0':
configure:3999: error: C compiler cannot create executables
See `config.log' for more details
```

I guess these lines fix it in the case where `glibc` is installed from brew, when `glibc` is too old:
https://github.com/Linuxbrew/homebrew-core/blob/5505cd51594f9880c3c71784c58863d9a46a0494/Formula/gcc.rb#L273-L276

In my case the host `glibc` is version 2.26

@sjackman should we symlink the crt?.o files from the host's glibc in that case?

**Comment by sjackman** [comment]
This line of superenv is meant to specify the path to the `crt*.o` files so that GCC can find them. You can also specify the path to these files with the `LIBRARY_PATH` environment variable.
```ruby
args << "-B#{@opt}/glibc/lib" unless mode == :ld
```
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/shims/linux/super/cc#L256
Can you report `brew gist-logs ruby` using `/usr/bin/gcc-5` and the brewed `gcc-5`?

**Comment by iMichka** [comment]
https://gist.github.com/anonymous/e65718d5d731d9f288cbd93a5419b08d

Actually this is a plain new installation; stock ubuntu. There is no gcc installed (just the gcc-7-base package). So I can just use brewed gcc. I can install gcc7 though to see what happens.

**Comment by iMichka** [comment]
Installed `gcc` and it worked. Actually my fault ... it is part of the pre-requisites of brew. If you don't have gcc on the system, you can't install anything.

Though brewed gcc alone should be working too, no? Especially if you have no root?

**Comment by sjackman** [comment]
Yes, brewed GCC should work. First priority though is building a bottle on CircleCI on Ubuntu 16.04 (Xenial) with gcc-5, `docker pull linuxbrew/linuxbrew`.

**Comment by maxim-belkin** [comment]
We should switch to `ubuntu:bionic`, I think.

**Comment by iMichka** [comment]
We should, but some testing should be done before. I am on 17.10 and a lot of stuff is broken. I had no time to work on it lately though.

**Comment by maxim-belkin** [comment]
`bionic` has no known vulnerabilities: https://hub.docker.com/r/library/ubuntu/tags/

**Comment by iMichka** [comment]
I mean: a lot of Linuxbrew stuff is broken.

**Comment by sjackman** [comment]
Ubuntu 18.04 LTS (Bionic Beaver) will be released 2018-04-26. https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule
