### ISSUE TITLE
systemd does not find perl from path

### ISSUE THREAD

**Issue by denis-sumin** [Linuxbrew/homebrew-core#6234]
Similarly to #3471, brew doesn't see the brewed perl and gives the error when trying to install systemd:
```
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.20.2
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool
```

The workarounds in #3471 didn't help.

**Comment by sjackman** [comment]
See also https://github.com/Linuxbrew/brew/issues/623

**Comment by fusion809** [comment]
I'm getting this issue too. Trying to install GNU Octave and this issue occurs.

**Comment by sjackman** [comment]
Try adding…
```ruby
depends_on "perl" unless OS.mac?
```
or if it's a build-time-only dependency then
```ruby
depends_on "perl" => :build unless OS.mac?
```

**Comment by fusion809** [comment]
Delightful, now systemd is failing to configure due to:

```bash
checking for intltool >= 0.40.0...  found
configure: error: Your intltool is too old.  You need intltool 0.40.0 or later.
```

**Comment by sjackman** [comment]
Please report…
```
which -a intltoolize
brew gist-logs systemd
```

**Comment by fusion809** [comment]
Returns:

```bash
/home/fusion809/.linuxbrew/bin/intltoolize
https://gist.github.com/885aa2e955ce396d68849586e93f95e9
```

**Comment by sjackman** [comment]
```
checking for intltool-merge... yes
checking whether NLS is requested... yes
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^(.*)\${ <-- HERE ?([A-Z_]+)}?(.*)$/ at /home/fusion809/.linuxbrew/opt/intltool/bin/intltool-update line 1066.
checking for intltool >= 0.40.0...  found
configure: error: Your intltool is too old.  You need intltool 0.40.0 or later.
```
https://gist.github.com/anonymous/885aa2e955ce396d68849586e93f95e9#file-02-configure-L106

**Comment by sjackman** [comment]
This appears to be a known bug in `intltool` with Perl 5.26. Here's the Debian bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826471
Here's a patch from Arch Linux
https://git.archlinux.org/svntogit/packages.git/tree/trunk/intltool-0.51.0-perl-5.26.patch?h=packages/intltool
A PR to fix this issue would be welcome.

**Comment by fusion809** [comment]
I don't understand ruby, or the formulae so I'm not even sure how I would make the PR.

**Comment by sjackman** [comment]
Is your host's version of Perl older? Please report `/usr/bin/perl --version`
If so, a workaround would be to use that version of Perl instead.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle systemd`, but no promises.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by fusion809** [comment]
Perl 5.26.0, so no not that old. https://gist.github.com/100de1a1639f31ab09c816d4bad7895f

**Comment by sjackman** [comment]
I'd suggest either install Linuxbrew in `/home/linuxbrew/.linuxbrew`, which will make your life much easier, or use `/usr/bin/perl` instead of brewed Perl.

**Comment by fusion809** [comment]
So I have to create a new user called linuxbrew?

**Comment by sjackman** [comment]
The Linuxbrew installation handles that for you.
See http://linuxbrew.sh/#install-linuxbrew
and run
```sh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

**Comment by fusion809** [comment]
That's bizarre because that's how I installed Linux brew in the first place. Oh /home/linuxbrew/.linuxbrew does already exist.

**Comment by sjackman** [comment]
You're using `/home/fusion809/.linuxbrew/bin/brew`
and you want to be using `/home/linuxbrew/.linuxbrew/bin/brew`
If you're okay uninstall the installation in your home directory, I'd suggest running…
```sh
rm -r /home/fusion809/.linuxbrew
```
and then
```sh
PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
hash -r
which -a brew
brew install systemd
```
