### ISSUE TITLE
"help2man: can't get `--help' info from automake-1.16"

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/homebrew-core#6275]
Builds on macosx high sierra fine, but not  #linuxbrew:
```
==> Downloading https://ftp.gnu.org/gnu/automake/automake-1.16.tar.xz
################################################################################################### 100.0%
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/automake/1.16
==> make install
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/automake/02.make:
  GEN      t/ax/shell-no-trail-bslash
  GEN      t/ax/cc-no-c-o
  GEN      doc/aclocal.1
  GEN      runtest
  GEN      doc/automake.1
  GEN      lib/Automake/Config.pm
  GEN      t/ax/test-defs.sh
  GEN      bin/aclocal-1.16
  GEN      doc/aclocal-1.16.1
  GEN      bin/automake-1.16
  GEN      doc/automake-1.16.1
help2man: can't get `--help' info from automake-1.16
Try `--no-discard-stderr' if option outputs to stderr
make: *** [doc/automake-1.16.1] Error 255
make: *** Waiting for unfinished jobs....
```

On macosx the lines after this are:
```
 lib/install-sh -c -d '/usr/local/Cellar/automake/1.16/bin'
 lib/install-sh -c -d '/usr/local/Cellar/automake/1.16/share/automake-1.16/am'
 lib/install-sh -c -d '/usr/local/Cellar/automake/1.16/share/aclocal-1.16'
 lib/install-sh -c -d '/usr/local/Cellar/automake/1.16/share/aclocal-1.16/internal'
mkdir: /usr/local/Cellar/automake/1.16/share: File exists
 /usr/bin/install -c bin/automake bin/aclocal '/usr/local/Cellar/automake/1.16/bin'
```

**Comment by tseemann** [comment]
Hmm, when i run gist-logs:
```
brew gist-logs automake
Error: source sequence is illegal/malformed utf-8
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/home/linuxbrew/.linuxbrew/Library/Homebrew/utils/github.rb:146:in `open'
/home/linuxbrew/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:116:in `create_gist'
/home/linuxbrew/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:48:in `gistify_logs'
/home/linuxbrew/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:129:in `gist_logs'
/home/linuxbrew/.linuxbrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by dsarov** [comment]
https://gist.github.com/fe821ff8b78d782a5bc364fe2533dfd2

My gist-log ran fine though.

**Comment by iMichka** [comment]
I just pushed the bottle: #6270
Build works on ubuntu 16.04.

Maybe you could dig a little bit further to try to debug this?

**Comment by tseemann** [comment]
(Hello there @dsarov!)

Ok, so `help2man` accepts a GNU-style binary, and runs it with `--help` and outputs a man page for the tool. Very slick.


```
% help2man automake

.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.5.
.TH AUTOMAKE "1" "February 2018" "automake 1.15.1" "User Commands"
.SH NAME
automake \- manual page for automake 1.15.1
.SH SYNOPSIS
```

**Comment by okhowang** [comment]
i add --env=std and build successfully
who can explain about env args

**Comment by tseemann** [comment]
@okhowang mac or linux?  if linux, which dist?

**Comment by okhowang** [comment]
linux centos6
my system has no help2man
but i installed a brewed help2man in my PATH
but it seems not recognized when brew upgrade automake without `--env=std`

**Comment by sjackman** [comment]
Changing `#!/usr/bin/perl -w` to the brewed Perl worked around the issue for me.

**Comment by sjackman** [comment]
@iMichka How should we resolve this? I'm afraid that if we make `automake` depend on brewed `perl` it will cause cyclic dependencies. Change the interpreter to `#!/usr/bin/env perl`?

**Comment by sjackman** [comment]
```
❯❯❯ /usr/bin/perl -e 'use List::Util qw(none)'
"none" is not exported by the List::Util module
Can't continue after import errors at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```
Is `List::Util qw(none)` a new dependency of Automake? Why hasn't this issue come up before?

**Comment by tseemann** [comment]
List::Util has been around in *perl core* for a long time, and the `none()` function has too I believe. So this is weird.

**Comment by sjackman** [comment]
> Since version 1.33.

https://perldoc.perl.org/List/Util.html#any

```
/usr/bin/perl -MList::Util -e 'print $List::Util::VERSION';
1.27
```
😭

**Comment by sjackman** [comment]
```
❯❯❯ docker run -it --rm ubuntu:14.04 /usr/bin/perl -MList::Util -e 'print $List::Util::VERSION'
1.27
❯❯❯ docker run -it --rm ubuntu:16.04 /usr/bin/perl -MList::Util -e 'print $List::Util::VERSION'
1.41
```

**Comment by tseemann** [comment]
Ubuntu 14.04 was `17 April 2014` ... 4 years ago.

**Comment by tseemann** [comment]
So it seems `none` came in at `List::Util` 1.33  @sjackman 
It is just `! any` ...


```
none
notall
    my $bool = none { BLOCK } @list;

    my $bool = notall { BLOCK } @list;
Since version 1.33.

Similar to "any" and "all", but with the return sense inverted. none returns true only if no value in the @list causes the BLOCK to return true, and notall returns true only if not all of the values do.
```

**Comment by tseemann** [comment]
WE ARE NOT ALONE!

http://lists.gnu.org/archive/html/bug-automake/2018-02/msg00018.html

"I get this build failure when building automake 1.6 with perl 5.18.2"

**Comment by sjackman** [comment]
> Best solution would be for automake to use ! any instead.

Can we simply…
```ruby
inreplace "automake", "none", "!any"
```
?

**Comment by tseemann** [comment]
WHOOPS.

**Comment by tseemann** [comment]
@sjackman I have patched `automake` for linuxbrew https://github.com/Linuxbrew/homebrew-core/pull/6352/files

It should work with older versions of Perl List::Util.  It makes it's own `none` function using `reduce` instead.

THis is a blocker because I can't build any `autogen.sh` packages on `bio`.

**Comment by sjackman** [comment]
CircleCI is running on Ubuntu 16.04, which should be fine. Once the formulae are bottled, you can use those bottles on your machine, since automake is a build dependency. I agree it's an important issue to fix, but it shouldn't hold back your Brewsci/bio development.

**Comment by sjackman** [comment]
This issue will hopefully be resolved by PR https://github.com/Linuxbrew/homebrew-core/pull/6352
