### ISSUE TITLE
glib: "none" is not exported by the List::Util module

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/homebrew-core#6347]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
@sjackman Alright, here I am. I tried a fresh checkout of brew and installing using bottles (instead of purely from source).
- What happened (include command output)
"none" is not exported by the List::Util module
This probably happened due to only having perl 5.10 installed. brew installing perl does not have an affect since recent brew versions prefer system binaries over brew installed software :/

- What you expected to happen
glib to install
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install glib

https://gist.github.com/anonymous/c79af65ec59af2251323a4ffcdb6f9ee

**Comment by sjackman** [comment]
```
OS: Red Hat Enterprise Linux Workstation release 6.9 (Santiago) (Santiago)
```
https://gist.github.com/anonymous/c79af65ec59af2251323a4ffcdb6f9ee#file-00-config-out-L30

I recently ran into this problem myself, not with `glib`, but a different formula. The proper solution I think is to modify the `glib` formula to install its own copy of `List::Util`, something like this:
https://github.com/brewsci/homebrew-bio/blob/b9768b1a81e511689ee0113ae8d1b69cc20ef59e/Formula/repeatmasker.rb#L31-L34
@iMichka Your thoughts?

**Comment by tseemann** [comment]
Same bug as https://github.com/Linuxbrew/homebrew-core/issues/6275

I think patching `automake` to use `/usr/bin/env perl` instead of hard-coded `/usr/bin/perl` would help?

**Comment by maxim-belkin** [comment]
I don't think using `/usr/bin/env perl` is an option because some scripts pass `-w` flag to perl and ... https://stackoverflow.com/a/4304187

**Comment by tundratim** [comment]
Seeing this exact problem when trying to build nload

**Comment by sjackman** [comment]
This issue will hopefully be resolved by PR https://github.com/Linuxbrew/homebrew-core/pull/6352
