### ISSUE TITLE
Bottles that need to be rebuilt after the python migration

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/homebrew-core#6380]
- [ ] asciinema
- [ ] azure-cli
- [ ] biogeme
- [ ] certbot
- [ ] ddgr
- [ ] googler
- [ ] graphene
- [ ] jupyter
- [ ] magic-wormhole
- [x] numpy #6374
- [ ] pybind11
- [ ] pyqt
- [ ] todoman
- [ ] twtxt
- [ ] vdirsyncer
- [ ] vim
- [ ] xdot
- [ ] ansible
- [ ] csvtomd
- [ ] diffoscope
- [ ] fades
- [ ] gst-python
- [ ] ipython
- [ ] mypy
- [ ] pipenv
- [ ] py3cairo
- [ ] pygobject3
- [x] pygobject #6373
- [ ] scipy
- [ ] simgrid
- [ ] sip
- [ ] snakemake
- [ ] thefuck
- [ ] vim@7.4
- [ ] xonsh
- [ ] you-get
- [ ] corebird
- [ ] dateutils
- [ ] nmap
 - [ ] dnscrypt-proxy
- [ ]  fish
- [ ]  libpq
- [ ]  libpqxx
 - [ ] magic-wormhole
 - [ ] node
 - [ ] postgresql
 - [ ] postgresql@9.5

@sjackman @maxim-belkin

**Comment by JuPlutonic** [comment]
Is it right link created by migration?
[Cellar (imgur)](http://i.imgur.com/iWXgLqg.png).
Also the misspell corrector "thefuck" need to be rebuilt.

**Comment by sjackman** [comment]
Yes, `python3` should be a symlink to `python`.

**Comment by randy3k** [comment]
Not sure if it is related. I noted that python3 cannot be installed completely as the `postinstall` fails.

```
linuxbrew@05a601509b6e:~/project$ brew postinstall python3
==> Postinstalling python
==> /home/linuxbrew/.linuxbrew/Cellar/python/3.6.4/bin/python3 -s setup.py --no-
==> /home/linuxbrew/.linuxbrew/Cellar/python/3.6.4/bin/python3 -s setup.py --no-
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/python/post_install.02.python3:
-s
setup.py
--no-user-cfg
install
--force
--verbose
--install-scripts=/home/linuxbrew/.linuxbrew/Cellar/python/3.6.4/bin
--install-lib=/home/linuxbrew/.linuxbrew/lib/python3.6/site-packages
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

These open issues may also help:
gdb: fix building due to python 2 https://github.com/Linuxbrew/homebrew-core/pull/6404
python: Build a bottle for Linuxbrew https://github.com/Linuxbrew/homebrew-core/pull/6363
Bottles that need to be rebuilt after the python migration https://github.com/Linuxbrew/homebrew-core/issues/6380
```

**Comment by iMichka** [comment]
Closing here, the `python` change has been reverted, some bottles have been rebuilt. We will fix broken this on a case by case basis.

**Comment by JuPlutonic** [comment]
I will see asciinema thefuck postgresql @9.5 node libpq libpqxx this weekend.
They are successfully built by circleci?

**Comment by iMichka** [comment]
Yes, at one point these formulae got a bottle.
The idea is probably to:
- brew install formula (with bottle)
- brew linkage --test formula
- brew test formula
And then maybe:
- brew uninstall formula
- brew install formula -s
- brew linkage --test formula
- brew test formula

If you have docker installed it is probably even better to test this in our build docker:
- docker pull linuxbrew/linuxbrew
- docker run -it linuxbrew/linuxbrew /bin/bash

and start hacking around from there.
