### ISSUE TITLE
Formulae that may need a revision bump

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/homebrew-core#6384]
All these pythons were optional on mac, not sure if we need to revision bump anything here.

Probably only the ones which had a conflict:

#6381
#6382
#6383
#6385

@sjackman @maxim-belkin

**Comment by sjackman** [comment]
The shebang line of this Python script included with BLAST needs to be changed. The fix probably needs more than just a rebuild though. This is not high priority though.
```
❯❯❯ head -n1 ~/.linuxbrew/Cellar/blast/2.7.1/bin/windowmasker_2.2.22_adapter.py
#!/usr/bin/python
```
