### ISSUE TITLE
installed softwares does not work with the same error

### ISSUE THREAD

**Issue by YantingHuang** [Linuxbrew/homebrew-core#6618]
[yhua295@nebula ~]$ tabix
tabix: relocation error: /usr/lib64/libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

Could you please give me some suggestions on how to solve this problem.

**Comment by tseemann** [comment]
@YantingHuang  `tabix` is no longer a separate formula.  It is part of `htslib` now. 
```
brew uninstall --force tabix
brew install htslib
```
