### ISSUE TITLE
opencv formula has git merge conflict symbols in it

### ISSUE THREAD

**Issue by russkel** [Linuxbrew/homebrew-core#6621]
Can be seen here:
https://github.com/Linuxbrew/homebrew-core/blob/5821b97b00a4962c04c0f1703bfb7f55d16a80f5/Formula/opencv.rb#L84

**Comment by iMichka** [comment]
Hi. Thanks for reporting. This should not have happened, don’t know why I didn’t see it when doing the merge.

Would you like to open a pull request to fix this? The lower version is the right one, but the #dylib change needs to be kept.

**Comment by russkel** [comment]
Hi iMichka,
I tried to submit a PR using the web editor but the submit button seems to be grayed out. I don't use linuxbrew at this point and stumbled across this by chance. I don't have the repo cloned on my machine.

Russ

**Comment by russkel** [comment]
Hi @iMichka, done!

**Comment by sjackman** [comment]
Fixed by https://github.com/Linuxbrew/homebrew-core/pull/6631
