### ISSUE TITLE
Installing all applications that require build ```configure: error: C compiler cannot create executables```

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/homebrew-core#6647]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

To help us debug your issue please explain:
- What you were trying to do (and why)
```brew upgrade```
- What happened (include command output)
All applications which require compiling... configure error
- What you expected to happen
A proper build
- Step-by-step reproduction instructions (by running `brew install` commands)
e.g. ```brew upgrade gcc```

```brew gist-logs gcc```: https://gist.github.com/jwhite007/315f2de012c81a85cd937393634d17e5

**Comment by jwhite007** [comment]
Does this have something to do with the change-ups you guys are making to how Linuxbrew functions, similar to what you're doing with curl? Are you guys now pointing to the system gcc instead of the brewed gcc?

**Comment by horta** [comment]
Same problem here when I try `brew upgrade gcc`: https://gist.github.com/6741d4d58855139e62603b8389f385d2

**Comment by sbfnk** [comment]
Should be fixed by https://github.com/Linuxbrew/homebrew-core/pull/6637, see https://github.com/Linuxbrew/homebrew-core/issues/6628.

**Comment by iMichka** [comment]
Yes, should be fixed. Closing here.

**Comment by jwhite007** [comment]
I can confirm the fix. Thanks, guys!!
