### ISSUE TITLE
Problems with bottles

### ISSUE THREAD

**Issue by maxim-belkin** [Linuxbrew/homebrew-core#6648]
I tested all bottled formulae in https://github.com/Linuxbrew/homebrew-core and found that some of them either fail to install (because of dependencies) or have dependencies with no linkage.
I suggest going through these lists as time permits and fixing the problems.

(<a href="#nolinkage">go to formulae that have deps with no linkage</a>)
### Problems with dependencies<a name="with-errors"></a>
 - [x] abyss
 - [x] afuse #7606
 - [x] apng2gif #7607
 - [x] archivemount
 - [x] armadillo
 - [x] arpack
 - [ ] asciinema2gif (needs #7646)
 - [x] avfs #7655
 - [x] bindfs #7656
 - [x] blastem
 - [x] boost-mpi
 - [x] bsponmpi
 - [x] datetime-fortran
 - [x] diff-pdf #7732
 - [x] djview4
 - [x] erlang@18
 - [x] erlang@19
 - [x] fftw
 - [ ] flann #7275
 - [x] fltk
 - [x] fobis
 - [x] fontforge
 - [x] freeglut
 - [x] ftgl
 - [x] ftjam
 - [x] fuzzy-find
 - [ ] fwup
 - [ ] fzf
 - [ ] game-music-emu
 - [ ] gcsfuse
 - [ ] gdk-pixbuf
 - [ ] genometools
 - [ ] geocode-glib
 - [ ] get_iplayer
 - [ ] gl2ps
 - [ ] glew
 - [ ] gmsh
 - [ ] gmt
 - [ ] gmt@4
 - [ ] goocanvas
 - [ ] goofys
 - [ ] gpsbabel
 - [ ] grib-api
 - [ ] gromacs
 - [ ] gst-editing-services
 - [ ] gst-libav
 - [ ] gst-plugins-bad
 - [ ] gst-plugins-base
 - [ ] gst-plugins-good
 - [ ] gst-plugins-ugly
 - [ ] gst-rtsp-server
 - [ ] gst-validate
 - [ ] gtk-gnutella
 - [ ] gtkdatabox
 - [ ] gtkextra
 - [ ] gtkmm
 - [ ] gtkmm3
 - [ ] gv
 - [ ] hdf5
 - [ ] hdf5@1.8
 - [ ] hypre
 - [ ] igraph
 - [ ] inspectrum
 - [ ] kallisto
 - [ ] konoha
 - [ ] lapack
 - [ ] latex2html
 - [ ] libcds
 - [ ] libepoxy
 - [ ] libglade
 - [ ] libgnomecanvas
 - [ ] libgweather
 - [ ] libical-glib
 - [ ] libinfinity
 - [ ] libmatio
 - [ ] libxc
 - [ ] liquid-dsp
 - [ ] llvm
 - [ ] llvm@4
 - [ ] logstalgia
 - [ ] mat
 - [ ] mednafen
 - [ ] mpich
 - [ ] mupdf
 - [ ] ncview
 - [ ] netcdf
 - [ ] nlopt
 - [ ] nspr
 - [ ] nsq
 - [ ] nss
 - [ ] ntl
 - [ ] numpy
 - [ ] open-mpi
 - [ ] openblas
 - [ ] opencoarrays
 - [ ] opencv@2
 - [ ] packmol
 - [ ] pangomm
 - [ ] pdf2htmlex
 - [ ] pdfpc
 - [ ] plplot
 - [ ] pqiv
 - [ ] profanity
 - [ ] pushpin
 - [ ] pygtk
 - [ ] qca
 - [ ] qd
 - [ ] qrupdate
 - [ ] qt
 - [ ] quvi
 - [ ] ratfor
 - [ ] rust
 - [ ] scalapack
 - [ ] scriptcs
 - [ ] securefs
 - [ ] shared-mime-info
 - [ ] spades
 - [ ] sratoolkit
 - [ ] sshfs
 - [ ] suil
 - [ ] suite-sparse
 - [ ] sundials
 - [ ] superlu
 - [ ] sylpheed
 - [ ] treefrog
 - [ ] vte
 - [x] vtk #7685
 - [ ] w3m
 - [ ] wpscan
 - [x] wxmac #7657
 - [ ] wxpython
 - [ ] xmount
 - [ ] zurl

(<a href="#with-errors">go back up</a>)
### Problems with linkage<a name="nolinkage"></a>
 - [ ] alot
 - [ ] arabica
 - [ ] asciidoc
 - [ ] awslogs
 - [ ] bash
 - [ ] bastet
 - [ ] boost-python
 - [ ] cairo
 - [ ] cgal
 - [ ] dlib
 - [ ] docbook-xsl
 - [ ] docbook2x
 - [ ] ecl
 - [ ] exempi
 - [ ] eye-d3
 - [ ] fcl
 - [ ] ffmpeg
 - [ ] gdcm
 - [ ] gdnsd
 - [ ] ghostscript
 - [ ] gifsicle
 - [ ] glib-networking
 - [ ] gnome-doc-utils
 - [ ] gnu-apl
 - [ ] gnupg
 - [ ] grafana
 - [ ] graphicsmagick
 - [ ] groonga
 - [ ] gtk-doc
 - [ ] imagemagick
 - [ ] imlib2
 - [ ] jed
 - [ ] kitchen-sync
 - [ ] libcdr
 - [ ] libebur128
 - [ ] librdkafka
 - [ ] librevenge
 - [ ] libtcod
 - [ ] libxkbcommon
 - [ ] links
 - [ ] mdds
 - [ ] megatools
 - [ ] minimal-racket
 - [ ] mono-libgdiplus
 - [ ] mrboom
 - [ ] mutt
 - [ ] ncp
 - [ ] notmuch
 - [ ] open-babel
 - [ ] orocos-kdl
 - [ ] osmium-tool
 - [x] pari
 - [ ] percona-server
 - [ ] pianobar
 - [ ] pike
 - [ ] plotutils
 - [ ] plzip
 - [ ] points2grid
 - [ ] pulseaudio
 - [ ] pyenv
 - [ ] rakudo-star
 - [ ] sagittarius-scheme
 - [ ] scrollkeeper
 - [ ] sdl_mixer
 - [ ] singular
 - [ ] snappystream
 - [ ] speex
 - [ ] tcl-tk
 - [ ] termius
 - [ ] theora
 - [ ] thrift
 - [ ] thrift@0.9
 - [ ] ttyd
 - [ ] uhd
 - [ ] urdfdom
 - [ ] xclip
 - [ ] xdotool
 - [ ] xml-tooling-c
 - [ ] xmlto
 - [ ] xmrig
 - [ ] z3

**Comment by iMichka** [comment]
Hey, cool. This list may overlap with #6380 and #6384, but totally worth going through it and fix everything.

Would that check be something we could automatise on a build bot and test once a week or so?

**Comment by maxim-belkin** [comment]
> Would that check be something we could automatise on a build bot and test once a week or so?

It is doable but it took me more than a day to go through all of the bottled formulae.

"Problems with linkage" might be upstream problems.
"Problems with dependencies" are specific to Linuxbrew for sure.

**Comment by sjackman** [comment]
Deps with no linkage is not necessarily an issue. It may use an executable of that package rather than a library.

**Comment by iMichka** [comment]
@maxim-belkin what exact test did you run for this?

I guess that you ran `brew install foo`, and then `brew linkage --test foo`, and that's all?

**Comment by maxim-belkin** [comment]
1. This was done in a clean Linuxbrew docker container
2. grep for all formulas that have a bottle for Linux (grep -l)

for every such formula:  
- build all prerequisites.
        * failure? -> save to  "Problems with dependencies", then `brew remove --force $(brew list)`
        * success? -> proceed. 
- build formula (should be poured from the bottle)
        - failure? -> save to "Problem with bottle" (did not happen, I believe)
        - success? -> proceed
- run `brew linkage` ( I didn't use  --test)
 sed output with:
```
sed -ne "/^Broken/,/^[^ ]/p; /^Missing/,/^[^ ]/p; /^Undeclared/,/^[^ ]/p;"
```
Have some output? -> save to "Problem with linkage". You can remove the "Undeclared" part.

**Comment by iMichka** [comment]
Right, but in practice, "Indirect dependencies with linkage" are not a bad thing?
I mean, for armadillo, I can add a `depends_on "zlib"`, which moves it to the `Homebrew libraries` part. But even without doing that the linkage was fine I guess.

**Comment by sjackman** [comment]
`Dependencies with no linkage` is purely informational for developers when creating a new formula. It's a hint that this dependency *may* be a build-time only dep.  For example, a formula that has no linkage to `boost` almost certainly doesn't need it at run time.

**Comment by maxim-belkin** [comment]
> `Dependencies with no linkage` is purely informational for developers when creating a new formula

Anything that `brew linkage` reports is "informational" because it has no effect on anything.
`brew linkage --test` is not only informational because it is used in CI.
As you know, I'm arguing that `no linkage` part should be moved to the actionable category, but that will require an ability to say that no-linkage is the expected state.

**Comment by iMichka** [comment]
I am not sure what error you saw for `fuzzy-find` (and some others too). The formula has bot been touched for ages. Not sure all entries in the list were broken.

**Comment by sjackman** [comment]
`Problems with dependencies` means that one of the dependencies of `fuzzy-find` had trouble installing (I believe). `fuzzy-find` doesn't have any dependencies though.

**Comment by maxim-belkin** [comment]
Um... I did not record the reason for that failure... but I agree that this one is weird and casts a shadow on the list in general. Let's close this one then :)

**Comment by iMichka** [comment]
Some other bottles were fine. Something went wrong with your list.
Though some were really broken in the top of the list, and I already fixed them.

**Comment by maxim-belkin** [comment]
I'll look into this when I have a bit more time... in the meantime: `w3m` and `wpscan` have problems with bottles:
```
==> Downloading https://linuxbrew.bintray.com/bottles/w3m-0.5.3_5.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "w3m"
```

```
==> Downloading https://linuxbrew.bintray.com/bottles/wpscan-2.9.3_6.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "wpscan"
```
