### ISSUE TITLE
glibc: Segfaults on Ubuntu 16 with glibc 2.23

### ISSUE THREAD

**Issue by iggyvolz** [Linuxbrew/homebrew-core#670]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

tl;dr
```bash
$ brew install bzip2
*everything is fine*
$ bzip2
Segmentation fault (core dumped)
```

The system is a near-fresh install, just got it yesterday.  I'm fairly certain I've followed all the instructions for install properly. 

Running a gdb backtrace gives https://gist.github.com/8b31536416d2a3d9f53a9038f7b74947 (not sure if that helps whatsoever).

Brew gist-log: https://gist.github.com/anonymous/5a2dea6fe0a1df7824e5effea1291e57

**Comment by sjackman** [comment]
I see that you have the brewed `glibc` 2.19 installed, though your host OS Ubuntu 16 has a newer `glibc` 2.23. In that situation, I don't recommend installing Linuxbrew `glibc` but instead use your host's `glibc`. I would like to support installing brewed `glibc` on Ubuntu 16, but we haven't got there yet.

**Comment by iggyvolz** [comment]
That did the trick, thanks Sean!

I also had to remove coreutils, because I was running into funky errors with it installed (like .linuxbrew/bin/ls, file not found)

**Comment by sjackman** [comment]
Glad to hear it!
