### ISSUE TITLE
thefuck can't import setuptools

### ISSUE THREAD

**Issue by TiZ-EX1** [Linuxbrew/homebrew-core#6703]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

This issue occurs on every computer I have running linuxbrew, including my server which tends to magically succeed in building things where my laptop and work box fail.

```
WC130-TiZ:~$ brew upgrade thefuck
==> Upgrading 1 outdated package, with result:
thefuck 3.25_3
==> Upgrading thefuck 
==> Downloading https://files.pythonhosted.org/packages/ec/20/3f136313c27ea36ba3
Already downloaded: /xusr/linuxbrew/.cache/Homebrew/thefuck-3.25.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e0308733
Already downloaded: /xusr/linuxbrew/.cache/Homebrew/thefuck--homebrew-virtualenv-15.1.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/thefuck--
Last 15 lines from /xusr/linuxbrew/.cache/Homebrew/Logs/thefuck/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/thefuck--homebrew-virtualenv-20180319-22794-1txk1nf/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
```

Things in linuxbrew have been kind of a mess lately... I remember one time I tried to upgrade after the python migration and most of my packages failed to upgrade in some way or another, so I just kind of left everything alone. It seems things are calming down and stabilizing a little bit, but this is one issue that still remains.

**Comment by TiZ-EX1** [comment]
This issue seems to have solved itself with a recent build of brew. Not sure how or why.

**Comment by iMichka** [comment]
Cool. Not sure what happened, but we had some back and forth with python stuff lately. Glad it is sorted out.
