### ISSUE TITLE
can not install httpd on ubuntu 16.04 `libaprutil-1.so: undefined reference to `apr_allocator_align'`

### ISSUE THREAD

**Issue by vertexvaar** [Linuxbrew/homebrew-core#6711]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/a432d871e6e29574fbefd7727a7b33d0

To help us debug your issue please explain:
- What you were trying to do (and why)
I tried to install php72 with `brew install php72` for local PHP development
- What happened (include command output)
```$ brew install php72
==> Installing dependencies for php: httpd, argon2, aspell, freetds, libffi, glib, imap-uw, libpq, libsodium, libzip, libtiff, webp
==> Installing php dependency: httpd
==> Downloading https://www.apache.org/dyn/closer.cgi?path=httpd/httpd-2.4.29.tar.bz2
Already downloaded: /home/oeglseder/.cache/Homebrew/httpd-2.4.29.tar.bz2
==> ./configure --enable-layout=Slackware-FHS --prefix=/home/linuxbrew/.linuxbrew/Cellar/httpd/2.4.29
==> make install
Last 15 lines from /home/oeglseder/.cache/Homebrew/Logs/httpd/02.make:
make[2]: *** [logresolve] Error 1
/home/linuxbrew/.linuxbrew/opt/apr-util/libexec/lib/libaprutil-1.so: undefined reference to `apr_allocator_align'
collect2: error: ld returned 1 exit status
Makefile:90: recipe for target 'httxt2dbm' failed
make[2]: *** [httxt2dbm] Error 1
/home/linuxbrew/.linuxbrew/opt/apr-util/libexec/lib/libaprutil-1.so: undefined reference to `apr_allocator_align'
collect2: error: ld returned 1 exit status
Makefile:48: recipe for target 'htpasswd' failed
make[2]: *** [htpasswd] Error 1
make[2]: Leaving directory '/tmp/httpd-20180319-5832-11fn8s0/httpd-2.4.29/support'
/tmp/httpd-20180319-5832-11fn8s0/httpd-2.4.29/build/rules.mk:75: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/tmp/httpd-20180319-5832-11fn8s0/httpd-2.4.29/support'
/tmp/httpd-20180319-5832-11fn8s0/httpd-2.4.29/build/rules.mk:75: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

These open issues may also help:
httpd: Build a bottle for Linuxbrew https://github.com/Linuxbrew/homebrew-core/pull/6475
```
- Step-by-step reproduction instructions (by running `brew install` commands)
Run `brew install php72` or `brew install httpd`

I tried this on two different machines, one which was freshly set up with Ubuntu 16.04 including all updates. Also on a virtualized Ubuntu 16.04. The error is always reproducible.

**Comment by iMichka** [comment]
Hi. We had a similar bug report here but gave up on fixing this: #5074

It may be that you have `apr-util` installed locally and `httpd` tries to use it, but brew will prevent that through the env filtering mechanism. Or there is different problem.

**Comment by vertexvaar** [comment]
Hi. Thanks for your fast response. A pity you were not able to solve the issue. I will read into the other issue and report back here if i was able to get beyond.

**Comment by vertexvaar** [comment]
Well, this one was easy, at least for me, thanks to
> It may be that you have apr-util installed locally
As a matter of fact i have apache2-dev installed via apt-get, which depends on a lot of apr* libs.
`sudo apt-get remove apache2-dev` and `sudo apt-get autoremove` did the trick.

I'm now stuck at
```==> Installing php dependency: imap-uw
==> Downloading https://mirrorservice.org/sites/ftp.cac.washington.edu/imap/imap-2007f.tar.gz
######################################################################## 100.0%
==> make oxp
Last 15 lines from /home/oeglseder/.cache/Homebrew/Logs/imap-uw/01.make:
In file included from osdep.c:49:0:
env_unix.c:504:7: note: previous implicit declaration of 'localtime' was here
   t = localtime (&tn);  /* get local time now */
       ^
Makefile:921: recipe for target 'osdep.o' failed
make[3]: *** [osdep.o] Error 1
make[3]: Leaving directory '/tmp/imap-uw-20180320-7275-k9cklf/imap-2007f/c-client'
Makefile:591: recipe for target 'osx' failed
make[2]: *** [osx] Error 2
make[2]: Leaving directory '/tmp/imap-uw-20180320-7275-k9cklf/imap-2007f/c-client'
Makefile:684: recipe for target 'OSTYPE' failed
make[1]: *** [OSTYPE] Error 2
make[1]: Leaving directory '/tmp/imap-uw-20180320-7275-k9cklf/imap-2007f'
Makefile:419: recipe for target 'oxp' failed
make: *** [oxp] Error 2
```
I will also dig into that one and reply again

**Comment by unixfox** [comment]
Sorry for bumping this issue, I wasn't able to install `httpd` because of this similar issue: `undefined reference to `apr_os_uuid_get'`.

To fix the issue I did a reinstall of the package `apr-util` using `brew reinstall -s apr-util`!

**Comment by iMichka** [comment]
How old was your previous installation? There you had a previous broken `apr-util` installation. It would have been good to look at `brew doctor` before to see if anything was broken or unlinked.

**Comment by unixfox** [comment]
My previous installation of `apr-util` was on March 2018 and I didn't know that `brew doctor` would indicate me if something is wrong with a package, thank you for the tip.

**Comment by iMichka** [comment]
It may tell you some stuff, and is sometimes helpful. A full `brew gist-logs` reports after a build failure is also really helpful, and contains the `brew doctor` output.

At least you got it sorted out so I guess we can stop investigating here for the moment.
