### ISSUE TITLE
Linuxbrew builds only work on the same arch

### ISSUE THREAD

**Issue by albertz** [Linuxbrew/homebrew-core#677]
Earlier, my Linuxbrew builds worked across different systems (I build them on some Intel platform and later used them on some AMD platform).

Now, this is not the case anymore. Most Linuxbrew builds fail with `illegal hardware instruction (core dumped)` when I run them on another platform / architecture.

I want the old behavior back. How?

**Comment by sjackman** [comment]
```sh
export HOMEBREW_ARCH=core2
```

**Comment by albertz** [comment]
Thanks a lot. I was searching in the code and found such things but I didn't realized that `core2` was the previous default. Was that really the case? The CPU where my binaries fail now but have worked previously is an AMD (Dual-Core AMD Opteron(tm) Processor 2220). I thought that `core2` is the name for the [Intel Core 2](https://en.wikipedia.org/wiki/Intel_Core_2). Or is AMD always compatible with that? (Or maybe at least newer AMDs?)

Regarding documentation, or maybe `brew doctor`, I was thinking, is there a way to tell for a binary with what `HOMEBREW_ARCH` it was compiled, or maybe with what `-march` compiler flag (or other compiler flags) it was compiled? If so, `brew doctor`, or maybe some other tool (maybe some new clever tool invoked like `brew fixmyproblem python3 illegal hardware instruction`) could check if there is some inconsistency, maybe between different packages, or maybe between the host architecture and the architecture of the packages, so when I run it on the platform where I get this crash, it will tell me "We found that the binaries were compiled for a different architecture. Please do <this>..." or so.

**Comment by sjackman** [comment]
Intel Core 2 is the very first Intel x86-64 processor, and yes, as far as I know, all 64-bit CPU both Intel and AMD are compatible with `core2`.

> Regarding documentation, or maybe brew doctor, I was thinking, is there a way to tell for a binary with what HOMEBREW_ARCH it was compiled, or maybe with what -march compiler flag (or other compiler flags) it was compiled?

That's a great feature suggestion. I'd like to store the architecture that the keg/bottle was compiled for in `INSTALL_RECEIPT.json`. A pull request is welcome if you'd like to take a go at it.

cc @rwhogg

**Comment by rwhogg** [comment]
> That's a great feature suggestion. I'd like to store the architecture that the keg/bottle was compiled for in INSTALL_RECEIPT.json. A pull request is welcome if you'd like to take a go at it.

I like that idea too. I'm also curious if Tigerbrew does something similar or would benefit from something like that too.

**Comment by sjackman** [comment]
Tigerbrew use case is a bit different. I think it simply targets the oldest CPU that can run Tiger.
