### ISSUE TITLE
open-babel: error: ‘std::tr1’ has not been declared

### ISSUE THREAD

**Issue by UnixJunkie** [Linuxbrew/homebrew-core#678]
brew gist-logs open-babel
    https://gist.github.com/anonymous/7eace90d13508946aaa988428b729b5f

**Comment by UnixJunkie** [comment]
at least 'brew install --HEAD open-babel' works

**Comment by sjackman** [comment]
```
/tmp/open-babel-20160727-18042-17a76xp/openbabel-2.3.2/include/openbabel/shared_ptr.h:34:16: error: ‘std::tr1’ has not been declared
     using std::tr1::shared_ptr;
```
https://gist.github.com/anonymous/7eace90d13508946aaa988428b729b5f#file-02-make-L35

**Comment by sjackman** [comment]
Seems like an upstream bug that's been fixed. I would suggest waiting for the next upstream release, or contact the upstream developers for a fix.

**Comment by sjackman** [comment]
@Homebrew/core @Homebrew/science Should this formula be moved to Homebrew-Science?
```
❯❯❯ brew desc open-babel
open-babel: Chemical toolbox
```

**Comment by UnixJunkie** [comment]
It's related to chemistry, so for sure it's science.
Since --HEAD is working, I am OK if this issue is closed (babel is most useful when installed from sources to get the latest features).

**Comment by sjackman** [comment]
Okay. Closing. Thanks for the feedback.
