### ISSUE TITLE
pyqt5 failed to build on fedora rhe 6.6

### ISSUE THREAD

**Issue by ljschumacher** [Linuxbrew/homebrew-core#679]
Tried to install pyqt5 but ran into issues with shared libraries, see gist below.

https://gist.github.com/anonymous/1bb326a9a6a70d0bfba1bd0d8c9c9aa7

```
Error: ./qtdetail failed to create qtdetail.out. Make sure your Qt installation
is correct.
Querying qmake about your Qt installation...
Determining the details of your Qt installation...
/end/home/lschumac/.linuxbrew/Cellar/qt5/5.6.1-1/bin/qmake -o qtdetail.mk qtdetail.pro
make -f qtdetail.mk
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I/end/home/lschumac/.linuxbrew/Cellar/qt5/5.6.1-1/include -I/end/home/lschumac/.linuxbrew/Cellar/qt5/5.6.1-1/include/QtCore -I. -I/end/home/lschumac/.linuxbrew/Cellar/qt5/5.6.1-1/mkspecs/linux-g++ -o qtdetail.o qtdetail.cpp
g++ -Wl,-O1 -o qtdetail qtdetail.o   -L/end/home/lschumac/.linuxbrew/Cellar/qt5/5.6.1-1/lib -lQt5Core -lpthread 
./qtdetail
./qtdetail: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

**Comment by sjackman** [comment]
As a workaround, there's a non-relocatble precompiled binary bottle of `qt` available. If you install Linuxbrew in `/home/linuxbrew/.linuxbrew`, you can use this binary bottle. If you're feeling adventurous, you can try in your current installation `brew install --force-bottle qt`. It may or may not work. I'd be interested to hear your experience if you try this approach.

**Comment by sjackman** [comment]
Sorry, I misread the subject. I'm attempting to build bottles for `qt5` and `pyqt5` now at #681 and #683 respectively.

**Comment by sjackman** [comment]
Does `brew test qt5` succeed?

**Comment by ljschumacher** [comment]
Testing qt5
==> /end/home/lschumac/.linuxbrew/Cellar/qt5/5.6.1-1/bin/qmake /tmp/qt5-test-20160728-30061-bawhb0/hello.p
==> make
==> ./hello

**Comment by sjackman** [comment]
Glad to see that the test succeeds. Bob @rwhogg is working on bottling `qt5` after which we can work on troubleshooting `pyqt5`.
