### ISSUE TITLE
gdal install fails on cpp preprocessor

### ISSUE THREAD

**Issue by sandeep-gh** [Linuxbrew/homebrew-core#6889]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.
```
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /bin/python3.6-config
  /bin/firewall-config
  /bin/brltty-config
  /bin/ncursesw6-config
  /bin/pkg-config
  /bin/krb5-config
  /bin/ncurses6-config
  /bin/python3.6m-config
  /bin/x86_64-redhat-linux-gnu-pkg-config
  /bin/python3-config
  /bin/xfce4-notifyd-config
  /bin/pcre2-config
  /bin/python3.6m-x86_64-config
```

- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/f632a972878496b2580415e1f35c0da1     

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
installing gdal  to install postgis

- What happened (include command output)
it failed on preprocessor check. 
```
checking if gcc-7 static flag -static works... no
checking if gcc-7 supports -c -o file.o... yes
checking if gcc-7 supports -c -o file.o... (cached) yes
checking whether the gcc-7 linker (/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/ld -m el
f_x86_64) supports shared libraries... yes                                                                       
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/tmp/gdal-20180325-31231-1bardb2/gdal-2.2.4':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
```

- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install gcc
brew install gdal 
```
# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by iMichka** [comment]
Hi. The build error is actually for `harfbuzz`. I can confirm this when using my system's gcc7 to build it. I built the bottle for `harfbuzz`, which was missing: #6507

Are you using bottles? In that case this should be fixed.

Else, you may try:
`HOMEBREW_CC=gcc-5 HOMEBREW_CXX=g++5 brew install harfbuzz`

**Comment by sandeep-gh** [comment]
Thank you. The "HOMEBREW_CC=gcc-5 HOMEBREW_CXX=g++5 brew install harfbuzz" worked and I am past that error.

**Comment by iMichka** [comment]
Cool. I do not know why it doesn’t work with gcc7 but at least we have a workaround. Somebody can work on this later if needed.
