### ISSUE TITLE
neomutt fails to install with sasl

### ISSUE THREAD

**Issue by xsteadfastx** [Linuxbrew/homebrew-core#7107]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Here is the [gist](https://gist.github.com/xsteadfastx/1dc336b788f6cc2c1f4fdfc2b4fae129)!

It looks like neomutt cant find sasl. 

```==> ./configure --prefix=/home/preuss/.linuxbrew/Cellar/neomutt/20180323 --enable-gpgme --gss --lmdb --notmuch --sasl -
Last 15 lines from /home/preuss/.cache/Homebrew/Logs/neomutt/01.configure:
Checking for strsep...ok
Checking for vasprintf...ok
Checking for wcscasecmp...ok
Checking libs for gethostent...none needed
Checking libs for setsockopt...none needed
Checking libs for getaddrinfo_a...-lanl
Checking for xsltproc...ok
Checking for DocBook DTDs...yes
Checking for gpgme.h...ok
Checking libs for gpgme_new...-lgpgme
Checking for gpgme_op_export_keys...ok
Checking for sasl/sasl.h...not found
Checking for sasl/sasl.h...(cached) not found
Error: Unable to find SASL
Try: 'configure --help' for options
```

I looked into the recipe for mutt and found the line `#{OS.mac? ? "--with-sasl" : "--with-sasl2"}`. so i think there is a problem with sasl in the configure script. trying to replace `--sasl` with `--sasl2` didnt worked.

**Comment by iMichka** [comment]
Trying to fix this here: #7441
