### ISSUE TITLE
crystal-lang: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by fibric** [Linuxbrew/homebrew-core#716]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

It looks like `crystal-lang.rb` downloads the OSX binaries and tries to execute them for the build/compile phase. Maybe nobody has ever tried installing `crystal-lang` via linux brew.

`brew gist-logs crystal-lang`
https://gist.github.com/anonymous/5c9ca976eada52d5a067ffe3047f15da

**Comment by rwhogg** [comment]
Reproduced. Thanks a bunch for the bug report @fibric!

I've fixed the formula to download the correct bootstrap binaries and am currently attempting to build this locally.

**Comment by rwhogg** [comment]
I've submitted PR #718 to fix this issue. Hopefully we should have a precompiled binary bottle available for this formula soon.

**Comment by fibric** [comment]
Sounds great to me man! Can't wait, obviously ;-)

**Comment by rwhogg** [comment]
The bottle has been built, but `crystal` doesn't compile code correctly unfortunately. It fails saying it cannot find "-lgc" and "-lpcre".

This appears to be a problem with Crystal being installed anywhere except the default paths, which happens on Homebrew too. You may want to take a look at https://github.com/crystal-lang/crystal/issues/3067 if this happens to you.

**Comment by fibric** [comment]
Thanks, man. It Builds and runs as I would expect.

```bash
$ crystal -v
Crystal 0.18.7 (2016-08-01)
```
```bashls/ us
$ crystal env
CRYSTAL_CACHE_DIR="/home/fibric/.cache/crystal"
CRYSTAL_PATH="/home/fibric/.linuxbrew/Cellar/crystal-lang/0.18.7/src:libs"
CRYSTAL_VERSION="0.18.7"
```

As you mentioned it, it fails to execute / to build code.
```bash
$ crystal eval puts 1
/usr/bin/ld: cannot find -lpcre
/usr/bin/ld: cannot find -lgc
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/fibric/.cache/crystal/crystal-run-eval.tmp" "${@}"  -rdynamic  -lpcre -lgc -lpthread /home/fibric/.linuxbrew/Cellar/crystal-lang/0.18.7/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

Something has changed while and after building `crystal`. Because in the `crystal-lang.rb`[file](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/crystal-lang.rb#L98), we see a super short test, the same I just did now too. I assumed the test either didn't run or passed. If it passed then, something is going on here.
