### ISSUE TITLE
Linuxbrew's sdl2 bottle doesn't have X support

### ISSUE THREAD

**Issue by TiZ-EX1** [Linuxbrew/homebrew-core#7187]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): Build GZDoom using Linuxbrew's SDL2.
- What happened (include command output): Build succeeded, but GZDoom doesn't start. "No available video device."
- What you expected to happen: GZDoom opens and I play the game.
- Step-by-step reproduction instructions (by running `brew install` commands): Just install sdl2, you'll get the bottle that doesn't have X. Then build something that uses SDL2 and try to run it, it'll fail. When you have xorg installed, build SDL2 from source and you'll get X and then applications built against it might work.

In actuality, GZDoom built against this SDL2 crashes immediately. But let's start with a bottle that *has* X and go from there.

**Comment by iMichka** [comment]
Hi. We had a discussion about this lately here: #4857

I will make an attempt to fix this here: #7188

Reviews and help to get this sorted out are welcome.

**Comment by iMichka** [comment]
Bottles have now X support (with #7188)
