### ISSUE TITLE
Upgrade to R 3.4.4 from 3.4.3_2 on Ubuntu 14.04 fails 

### ISSUE THREAD

**Issue by nickjhathaway** [Linuxbrew/homebrew-core#7189]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

----

Hi, 
brew fails to install R 3.4.4 on Ubuntu 14.04 when running `brew upgrade r` but does work on Ubuntu 16.04. I am upgrading from R 3.4.3_2 so the brew install R has worked before. I have links to two different gist logs from two different machines running 14.04 and they both fail in the same way. 

https://gist.github.com/721b9a5c7a9a400d05cde3dd109148e7
https://gist.github.com/3917fdcbe951a84f8377c4ba399c39ac

Looking at the make command output file it looks the error comes from installing the additional packages to R and fails when creating the shared library files which the commands to do so begin with "-shared" rather than "[COMPILER] -shared" and errors out with ```/bin/bash: line 2: -shared: command not found```. This error appears several times and since it looks like compiler is being omitted, it might an environmental variable problem or something.  

The first line this error appears on for https://gist.github.com/nickjhathaway/721b9a5c7a9a400d05cde3dd109148e7 is 1207. 

Any help is appreciated. 

Thanks!

**Comment by iMichka** [comment]
Hi. Thank you for reporting this.
I rebuilt the `r` bottles; so if you have linuxbrew installed in `/home/linuxbrew/.linuxbrew you can install using the bottles.

I am not exactly sure what the problem is, so we may need some time until we find a solution.

**Comment by iMichka** [comment]
I just tested in a Trusty docker container and it worked without problem. So I can not reproduce this.

What is this gcc? : `/usr/bin/gcc: 6.3.0`
Under Trusty, gcc should be 4.8.4, so I am wondering why you have another version as main gcc in bin?

**Comment by iMichka** [comment]
And I also see that the `r` script catches a gcc-7, and I do not know where that one is coming from?
