### ISSUE TITLE
No package 'cairo-xlib' found in compiling gtk+(yocto)

### ISSUE THREAD

**Issue by ganesh-keasyarmcom** [Linuxbrew/homebrew-core#7199]
checking whether to enable maintainer-specific portions of Makefiles... yes
| checking for some Win32 platform... no
| checking whether build environment is sane... yes
| checking for library containing strerror... none required
| checking whether make sets $(MAKE)... (cached) yes
| checking for arm-phytec-linux-gnueabi-pkg-config... no
| checking for pkg-config... /home/ganesh/work/am335x/yocto/build/tmp-glibc/sysroots/i686-linux/usr/bin/pkg-config
| checking pkg-config is at least version 0.9.0... yes
| checking for BASE_DEPENDENCIES... yes
| checking for CAIRO_BACKEND... no
| configure: error: Package requirements (cairo-xlib >= 1.6) were not met:
| 
| No package 'cairo-xlib' found
| 
| Consider adjusting the PKG_CONFIG_PATH environment variable if you
| installed software in a non-standard prefix.
| 
| Alternatively, you may set the environment variables CAIRO_BACKEND_CFLAGS
| and CAIRO_BACKEND_LIBS to avoid the need to call pkg-config.
| See the pkg-config man page for more details.
| Configure failed. The contents of all config.log files follows to aid debugging
| ERROR: oe_runconf failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/ganesh/work/am335x/yocto/build/tmp-glibc/work/cortexa8hf-vfp-neon-phytec-linux-gnueabi/gtk+/2.24.25-r0/temp/log.do_configure.3196)
ERROR: Task 5 (/home/ganesh/work/am335x/yocto/sources/poky/meta/recipes-gnome/gtk+/gtk+_2.24.25.bb, do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 922 tasks of which 921 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory
No currently running tasks (799 of 930)

please help me out from this issue...
compiling yocto in ubuntu 14.04 32-bit....

**Comment by iMichka** [comment]
Can you update and try again?

**Comment by JuPlutonic** [comment]
This is mb convenient _brew install gtk+ --ignore-dependencies --env=std_ 
https://gist.github.com/7c5fcaa0d932b9474e5b16f254127538
Also :100: % installed tested and linkage--tested: gdk-pixbuf cairo pango atk
& glib

**Comment by iMichka** [comment]
Should be fixed. The cair-xlib thing is fixed, and the atk problem from #7175 is fixed too.

Closing here. If you still have trouble with you build please open a new issue, and fill out the issue template.
