### ISSUE TITLE
GCC specs reference /nonexistent directory, breaks GCC when it exists

### ISSUE THREAD

**Issue by sambrightman** [Linuxbrew/homebrew-core#7461]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.

Once the broken GCC is installed, it affects all other packages built from source.

- [X] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.

The changes were supposedly Linux-specific. I don't have a macOS system handy right now to double-check.

- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?

No, but the issue seems pretty clear.

- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

The formula installs correctly but the resulting compiler is broken on my system. Example log below.

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

As above.

- What you were trying to do (and why)

`brew upgrade` my system (which included a `gcc` upgrade).

- What happened (include command output)

GCC got upgraded early on and successfully, all other from-source packages fail with broken compiler. Compiler is indeed broken:

```
$ gcc-5 -o test code/test.c
cc1: error: /nonexistent/usr/local/include/x86_64-linux-gnu: Permission denied
cc1: error: /nonexistent/usr/local/include: Permission denied
cc1: error: /nonexistent/usr/include/x86_64-linux-gnu: Permission denied
cc1: error: /nonexistent/usr/include: Permission denied
```

Changes from #6649 have been backported to this version, and modify the specs file to point to this directory. For whatever reason I actually have this directory on my machine (outside of my control) but no permission to access it. This is Ubuntu 16.04. Workaround is to modify `Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/specs` to point `/nonexistent` at `/reallynonexistent`.

- What you expected to happen

Compiler works, upgrade of other compile-from-source packages works.

- Step-by-step reproduction instructions (by running `brew install` commands)

  - Create the directory `/nonexistent` and ensure you do not have permission to access it.
  - Install or upgrade GCC to a version including #6649 changes
  - Compile a test program or `brew install` a package from source

**Comment by iMichka** [comment]
Weird. You have no clue where this folder is coming from?
We could change the path to `reallynonexistent`, but what happens when that folder exists without the right permissions too?

@sjackman Any opinion on this?

**Comment by sjackman** [comment]
Wow. I would have bet money that this issue would not have arisen. 💸

For this issue to occur, the directory `/nonexistent` exists (despite the clear existential crisis), and the user does not have access to read it. I suggest changing `/nonexistent` to `#{HOMEBREW_PREFIX}/sysroot`.
@sambrightman If you agree, please submit a PR.

When making this change, I nearly misspelt `nonexistent` as `nonexistant`, which also would have prevented this issue. Let's blame my spell checker then.

**Comment by xu-cheng** [comment]
HOMEBREW_PREFIX/nonexistent may be a better path.

**Comment by sjackman** [comment]
I'm fine with either.
