### ISSUE TITLE
What is the best practice for porting software that requires distribution specific libs?

### ISSUE THREAD

**Issue by IVXCVI** [Linuxbrew/homebrew-core#750]
I am trying to port Easystroke to Linuxbrew, but the libraries vary quite a bit depending on distribution.

https://github.com/thjaeger/easystroke/wiki/BuildInstructions

Some of the dependencies are satisfied with Linuxbrew, and some are not. This will be my first formula.

Thanks for any direction you may have.

**Comment by sjackman** [comment]
Try the following:
```ruby
depends_on :x11
depends_on "boost"
depends_on "dbus"
depends_on "gtkmm3"
depends_on "intltool"
```

Thanks for your interest in Linuxbrew! We're not accepting GUI formula into Linuxbrew that are not present in Homebrew. If you have access to a Mac, and if the formula builds on a Mac, you could submit it to https://github.com/Homebrew/homebrew-gui. If it does not build on a Mac, we've discussed setting up a Linuxbrew GUI tap, but no one has yet to take on that project.
@maxim-belkin @rwhogg

**Comment by maxim-belkin** [comment]
@sjackman do you mean porting homebrew/homebrew-gui to Linux?

**Comment by sjackman** [comment]
Assuming it's portable to Mac, I mean adding the `Easystroke` to https://github.com/Homebrew/homebrew-gui
