### ISSUE TITLE
Forking homebrew/homebrew-core when I have a fork of linuxbrew/homebrew-core

### ISSUE THREAD

**Issue by hartzell** [Linuxbrew/homebrew-core#754]
I'd like to update the *mkdocs* formula.  My normal MO would be to fork the homebrew-core repository, make a branch, push to my fork, and make a pull request.

But, I already have a fork of the LInuxbrew/homebrew-core repository.  Even if I rename it (e.g. linuxbrew-homebrew-core), when I try to fork Homebrew/homebrew-core GitHub warns me that I already have a fork.

If my goal is to push a fix upstream, are {Homebrew,Linuxbrew}/homebrew-core effectively interchangeable?

What's the Right Way(tm) to deal with this?

Thanks!

**Comment by sjackman** [comment]
I'm in the airport so only have time for a quick response. Feel free to ask more questions if it's not clear. Forking `linuxbrew` is correct, and you can still push to either Homebrew or Linuxbrew. Use one local repo with multiple remotes.
```sh
brew install hub
cd ~/.linuxbrew
hub remote add homebrew
hub remote add linuxbrew
hub remote add hartzell
git fetch homebrew
git checkout -b mkdocs homebrew/master
vi mkdocs.rb
git commit mkdocs.rb
git push hartzell mkdocs
hub browse
# open a pull request
```

**Comment by hartzell** [comment]
That's all I need to hear.  Hope you're not flying Delta!
