### ISSUE TITLE
segmentation fault (core dumped) occurred when installing python@2 in CentOS6

### ISSUE THREAD

**Issue by Gwang-Jin** [Linuxbrew/homebrew-core#7574]
Hello. After succeeding on installing brewed gcc and glibc in CentOS 6.3,  I'm trying to install python@2. But an error message occurred in make step of compiling `_bsddb.c:`
````
building '_bsddb' extension
gcc-5 -pthread -fPIC -fno-strict-aliasing -Wall -DNDEBUG -g -O3 -Wall -Wstrict-prototypes \\
-I/usr/include \\ 
-I. -IInclude \\
-I./Include \\
-I/home/skpark/.linuxbrew/include \\
-I/usr/local/include \\
-I/home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Include \\
-I/home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15 \\
-c /home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Modules/_bsddb.c \\
-o build/temp.linux-x86_64-2.7/home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Modules/_bsddb.o
In file included from /usr/include/limits.h:27:0,
                 from /usr/include/Python.h:19,
                 from /home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Modules/_bsddb.c:97:
/usr/include/features.h:327:0: warning: "__STDC_IEC_559__" redefined
 #define __STDC_IEC_559__  1
 ^
In file included from <command-line>:0:0:
/home/skpark/.linuxbrew/include/stdc-predef.h:38:0: note: this is the location of the previous definition
 #  define __STDC_IEC_559__  1
 ^
In file included from /usr/include/limits.h:27:0,
                 from /usr/include/Python.h:19,
                 from /home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Modules/_bsddb.c:97:
/usr/include/features.h:328:0: warning: "__STDC_IEC_559_COMPLEX__" redefined
 #define __STDC_IEC_559_COMPLEX__ 1
 ^
In file included from <command-line>:0:0:
/home/skpark/.linuxbrew/include/stdc-predef.h:46:0: note: this is the location of the previous definition
 #  define __STDC_IEC_559_COMPLEX__ 1
 ^
In file included from /usr/include/limits.h:27:0,
                 from /usr/include/Python.h:19,
                 from /home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Modules/_bsddb.c:97:
/usr/include/features.h:331:0: warning: "__STDC_ISO_10646__" redefined
 #define __STDC_ISO_10646__  200009L
^
In file included from <command-line>:0:0:
/home/skpark/.linuxbrew/include/stdc-predef.h:55:0: note: this is the location of the previous definition
 #define __STDC_ISO_10646__  201505L
 ^
/home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Modules/_bsddb.c: In function 'init_bsddb':
/home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Modules/_bsddb.c:10303:18: warning: implicit declaration of function 'PyCapsule_New' [-Wimplicit-function-declaration]
         py_api = PyCapsule_New((void*)&bsddb_api, py_api_name, NULL);
                  ^
/home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Modules/_bsddb.c:10303:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         py_api = PyCapsule_New((void*)&bsddb_api, py_api_name, NULL);
                ^
gcc-5 -pthread -shared -L/home/skpark/.linuxbrew/lib -fno-strict-aliasing -Wall -DNDEBUG -g -O3 -Wall -Wstrict-prototypes build/temp.linux-x86_64-2.7/home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15/Modules/_bsddb.o -L/usr/lib64 -L/home/skpark/.linuxbrew/lib -L/usr/local/lib -L. -Wl,-R/usr/lib64 -ldb-4.7 -lpython2.7 -o build/lib.linux-x86_64-2.7/_bsddb.so
/bin/sh: line 6: 10186 Segmentation fault      (core dumped) LD_LIBRARY_PATH=/home/skpark/tmp/python@2-20180521-1986-1trgzmb/Python-2.7.15 CC='gcc-5 -pthread' LDSHARED='gcc-5 -pthread -shared -L/home/skpark/.linuxbrew/lib' OPT='-DNDEBUG -g  -O3 -Wall -Wstrict-prototypes' _TCLTK_INCLUDES='' _TCLTK_LIBS='' ./python -E ./setup.py $quiet build
make: *** [sharedmods] Error 139
````

I wrote configure command used in linuxbrew.
````
./configure --prefix=/home/skpark/.linuxbrew/Cellar/python@2/2.7.15 --enable-ipv6 \\
--datarootdir=/home/skpark/.linuxbrew/Cellar/python@2/2.7.15/share \\
--datadir=/home/skpark/.linuxbrew/Cellar/python@2/2.7.15/share \\
--enable-shared \\
--without-ensurepip \\
MACOSX_DEPLOYMENT_TARGET= \\
LDFLAGS=  -L/home/skpark/.linuxbrew/lib \\
CPPFLAGS=  -I/home/skpark/.linuxbrew/include
````

Using unbrew gcc-4.9.7 with system glibc 2.12, I succeeded in compile Python-2.7.15 in my system, and no warning there was in compiling `_bsddb.c.` 
````
building '_bsddb' extension
gcc -pthread -fPIC -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes \\
-I/usr/include \\
-I. -IInclude \\
-I./Include \\
-I/usr/local/include \\
-I/home/kwangjin/Downloads/Python-2.7.15/Include \\
-I/home/kwangjin/Downloads/Python-2.7.15 \\
-c /home/kwangjin/Downloads/Python-2.7.15/Modules/_bsddb.c \\
-o build/temp.linux-x86_64-2.7/home/kwangjin/Downloads/Python-2.7.15/Modules/_bsddb.o

gcc -pthread -shared build/temp.linux-x86_64-2.7/home/kwangjin/Downloads/Python-2.7.15/Modules/_bsddb.o -L/usr/lib64 -L/usr/local/lib -Wl,-R/usr/lib64 -ldb-4.7 -o build/lib.linux-x86_64-2.7/_bsddb.so
````
I think that there seems to be some path or linking bug in brew gcc or brew glibc.

My `brew config` is

HOMEBREW_VERSION: 1.6.3
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: b67917c837f1fb9c5bf2494cfd89b4eee6802802
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 669038e1dea01dfa66258aa8d410a5174b44820b
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /home/skpark/.linuxbrew
HOMEBREW_REPOSITORY: /home/skpark/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/skpark/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/skpark/.cache/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_FORCE_BREWED_CURL: 1
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_TEMP: /home/skpark/tmp
CPU: octa-core 64-bit penryn
Homebrew Ruby: 2.3.3 => /home/skpark/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: N/A
Git: 2.17.0 => /home/skpark/.linuxbrew/bin/git
Curl: 7.59.0 => /home/skpark/.linuxbrew/opt/curl/bin/curl
Java: N/A
Kernel: Linux 2.6.32-220.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.3 (Final) (Final)
Host glibc: 2.12
/usr/bin/gcc: 4.4.6
glibc: 2.23
gcc: 5.5.0_4
xorg: N/A

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
[https://gist.github.com/6f6d44930450e9d1b3a256a3a6a64269](https://gist.github.com/6f6d44930450e9d1b3a256a3a6a64269)
- [] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew install python@2`

- What happened (include command output)
````
/bin/sh: line 6: 22757 Segmentation fault      (core dumped) LD_LIBRARY_PATH=/home/skpark/tmp/python@2-20180508-14934-pqfh03/Python-2.7.15 CC='gcc-5 -pthread' LDSHARED='gcc-5 -pthread -shared -L/home/skpark/.linuxbrew/lib' OPT='-DNDEBUG -g  -O3 -Wall -Wstrict-prototypes' _TCLTK_INCLUDES='' _TCLTK_LIBS='' ./python -E ./setup.py $quiet build
make: *** [sharedmods] Error 139
````

- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install python@2`

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by gipert** [comment]
I can confirm a similar behaviour when trying to compile Python 3.6.5 on Scientific Linux 'Nitrogen' 7.3:
```
gcc-4.8 -pthread -shared -L/lfs/l2/gerda/pertoldi/.linuxbrew/lib build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/_decimal.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/basearith.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/constants.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/context.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/convolute.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/crt.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/difradix2.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/fnt.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/fourstep.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/io.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/memory.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/mpdecimal.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/numbertheory.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/sixstep.o build/temp.linux-x86_64-3.6/tmp/python-20180509-109746-1btqc31/Python-3.6.5/Modules/_decimal/libmpdec/transpose.o -L. -L/lfs/l2/gerda/pertoldi/.linuxbrew/lib -L/usr/local/lib -lm -lpython3.6m -o build/lib.linux-x86_64-3.6/_decimal.cpython-36m-x86_64-linux-gnu.so
/bin/sh: line 6: 134688 Aborted                 (core dumped) LD_LIBRARY_PATH=/tmp/python-20180509-109746-1btqc31/Python-3.6.5 CC='gcc-4.8 -pthread' LDSHARED='gcc-4.8 -pthread -shared -L/lfs/l2/gerda/pertoldi/.linuxbrew/lib ' OPT='-DNDEBUG -g  -O3 -Wall -Wstrict-prototypes' _TCLTK_INCLUDES='' _TCLTK_LIBS='' ./python -E ./setup.py $quiet build
make: *** [sharedmods] Error 134
```

**Comment by iMichka** [comment]
Hi. Thanks for reporting this.
My first impression is that this is a Python bug.

Does one of you use docker? It would be great if we could reproduce the error in a clean docker container, to rule out anything from your setup interfering with the build.

Another solution is to try to build this from source outside of Linuxbrew, and to remove the `$quiet` from the `setup.py` file to have a look at the log.

**Comment by gipert** [comment]
Python compiles fine for me after solving #7597

**Comment by iMichka** [comment]
@Gwang-Jin I believe this is fixed now; please update and try again.

**Comment by Gwang-Jin** [comment]
Now I tried

`brew update`
`brew reinstall gcc`
`brew install python@2`

But I met the same error message. In my system environment, maybe 'Development Tools' seems not to be installed perfectly.

**Comment by Gwang-Jin** [comment]
> gcc-5 -pthread -fPIC -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/include -I. -IInclude -I./Include -I/ho    me/skpark/.linuxbrew/include -I/usr/local/include -I/home/skpark/tmp/python@2-20180516-2007-inh0xe/Python-2.7.15/Include -I/home/skpark/t    mp/python@2-20180516-2007-inh0xe/Python-2.7.15 -c /home/skpark/tmp/python@2-20180516-2007-inh0xe/Python-2.7.15/Modules/_bsddb.c -o build/    temp.linux-x86_64-2.7/home/skpark/tmp/python@2-20180516-2007-inh0xe/Python-2.7.15/Modules/_bsddb.o
310 In file included from /usr/include/limits.h:27:0,
311                  from /usr/include/Python.h:19,
312                  from /home/skpark/tmp/python@2-20180516-2007-inh0xe/Python-2.7.15/Modules/_bsddb.c:97:
313 /usr/include/features.h:327:0: warning: "__STDC_IEC_559__" redefine

How can I remove `-I/usr/include` from `CFLAGS`?

System python header caused redefine `/usr/include/Python.h:19`.

**Comment by Gwang-Jin** [comment]
I cannot find why the warning of "implicit declaration" when calling `PyCapsule_New` function:
````
warning: implicit declaration of function 'PyCapsul
e_New' [-Wimplicit-function-declaration]
         py_api = PyCapsule_New((void*)&bsddb_api, py_api_name, NULL);
````

**Comment by Gwang-Jin** [comment]
Is anyone who have the same problem with CentOS 6?

**Comment by iMichka** [comment]
It seems that it is using gcc 4 to build Python.

You could try to set this in the formula:
`fails_with :gcc => "4"`

This will force the usage of `gcc5` from homebrew.

**Comment by Gwang-Jin** [comment]
I found a solution. I modified python source adding `#include "pycapsule.h"` to `Include/pycapsule.h`.

**Comment by iMichka** [comment]
It tried to use gcc 4.9. Maybe that one is too old too.

You can try to add:
```
fails_with :gcc => "4"
fails_with :gcc => "4.9"
```

**Comment by Gwang-Jin** [comment]
@iMichka Should I install gcc@4.9 before trying your recommendation? But I failed to install gcc@4.9.

**Comment by iMichka** [comment]
No, don't. gcc 4.9 is the only gcc formula from all where we did not put any effort to make it work, so it does not compile correctly at all.

**Comment by Gwang-Jin** [comment]
@iMichka I tried to add 
````
fails_with :gcc => "4"
fails_with :gcc => "4.9"
```` to `python@2.rb`. But I met the same problem.

**Comment by iMichka** [comment]
Actually I do not think it is a good idea to add `fails_with :gcc => "4"`, because we may end up adding it to a lot of formulae. The thing is that your system gcc is probably too old.

What I do in that case is to use:
`HOMEBREW_CC=gcc-5 HOMEBREW_CXX=g++-5 brew install python@2`

This will force the usage of brewed gcc 5. You can also set this as exports in your .bash_profile if you want.

Could you try this solution?

**Comment by Gwang-Jin** [comment]
I failed to install with your recommendation.

**Comment by iMichka** [comment]
Regarding the gcc@4.9 formula, it should build fine now.

For python, I am running out of ideas for the moment. The warnings are just warnings and have probably nothing to do with our problem here. Maybe I can try to reproduce this in a docker container.
