### ISSUE TITLE
python3: error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.5/_ctypes.cpython-35m-x86_64-linux-gnu.so' -

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#759]
brew install python works but:
brew install python3 fails:

**\* WARNING: renaming "_ctypes" since importing it failed: build/lib.linux-x86_64-3.5/_ctypes.cpython-35m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.5/_ctypes.cpython-35m-x86_64-linux-gnu.so' -> 'build/lib.linux-x86_64-3.5/_ctypes.cpython-35m-x86_64-linux-gnu_failed.so'
make: **\* [sharedmods] Error 1
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

https://gist.github.com/anonymous/09c3eae00b60c10d98f5db080f22403a

**Comment by timotheecour** [comment]
after running this:
sudo apt-get install g++
it fixed the issue

would be nice if this were automatic

**Comment by rwhogg** [comment]
From https://gist.github.com/anonymous/09c3eae00b60c10d98f5db080f22403a#file-config-log-L21052
> CXX='/usr/bin/g++-4.8'

This gist was made from before you installed `g++`, right?

`g++` is an implicit dependency on Ubuntu. It's pulled in by `build-essential`, which we recommend installing on Debian-derived systems. [Here's the complete list](http://linuxbrew.sh/#debian-or-ubuntu).

**Comment by sjackman** [comment]
We could add a `brew doctor` check that both the selected gcc compiler and g++ compiler are present.
