### ISSUE TITLE
freetype 2.9.1 cannot be installed with recent binutils

### ISSUE THREAD

**Issue by sambrightman** [Linuxbrew/homebrew-core#7625]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

For me this hassle is a really big disincentive to help out on the project, or even bother reporting issues.

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

All answers are the same as #7624, gist URL is: 

https://gist.github.com/86128189e1989a8e32e9c862df5d6fe6

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I was trying to upgrade `freetype`, having previously upgraded `binutils` at some point.

It seems that `binutils` was changed to include all targets, which includes `windres` for MinGW etc. After upgrading to a `binutils` including this, I think the `freetype` build will find it and assume they need to compile the resource file `ftver.rc` which `#include`s `windows.h` and fails.

Possibly this issue should be upstreamed (`freetype` should be more explicit about being on Windows), but perhaps windres (or the Windows target) should be excluded from `binutils`? It seems unlikely that `windres` would work ever properly without `windows.h`.

**Comment by iMichka** [comment]
Hi. Not sure what changes you mean in `binutils`? I do not see any big changes, just some version updates.

`freetype` was successfully rebuilt on the 10th of April, so I can not reproduce your error.

We may need to call some `freetype` devs to help. You could maybe open an issue on their issue tracker?

**Comment by sambrightman** [comment]
It does look like the `binutils` all-targets change was much longer ago, I must have mis-read the blame output. I assume frreetype is being built in isolation though, so would never encounter the presece of `windres`?

**Comment by jrood-nrel** [comment]
I'm seeing this behavior as well, but in a different project (https://github.com/spack/spack). I just reported this bug to Freetype here https://savannah.nongnu.org/bugs/index.php?54967

**Comment by apodtele** [comment]
I agree with the original analysis, windres is only useful in Windows environment with windows.h, emulated or not.

Workaround for FreeType: make RC=""
