### ISSUE TITLE
ruby: doesn't build the formula as is [windows]

### ISSUE THREAD

**Issue by JMoVS** [Linuxbrew/homebrew-core#765]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

I am trying to get something to run on windows subsystem for linux, and so far have fallen over
- https://github.com/Linuxbrew/homebrew-core/issues/761
- https://github.com/Linuxbrew/brew/issues/95

now that openssl built, I tried to build ruby but fell onto this:

https://gist.github.com/096099bb2039c62fc9c2250f4e548f83

**Comment by sjackman** [comment]
```
/tmp/ruby-20160815-29085-1igkd0n/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require': libcrypto.so.1.0.0: cannot enable executable stack as shared object requires: Invalid argument - /tmp/ruby-20160815-29085-1igkd0n/ruby-2.3.1/.ext/x86_64-linux/openssl.so (LoadError)
```
https://gist.github.com/anonymous/096099bb2039c62fc9c2250f4e548f83

I'm afraid that I don't have a solution for this issue. You can try Googling `cannot enable executable stack as shared object requires`. Good luck!

**Comment by yorickdowne** [comment]
For any shared library, but for a crypto library doubly so, requiring an executable stack is a Bad Idea.

With any luck, it's just a side effect of GNU as, and can be solved by adding code to the end of .S files, see https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart

If libcrypto actually does require an executable stack, the fix will be a bit more complicated.

This is also likely to trip up SELinux / Exec Shield, not just WSL.

**Comment by sjackman** [comment]
Please comment at this related PR
https://github.com/Linuxbrew/homebrew-core/pull/1510
