### ISSUE TITLE
systemd: build error

### ISSUE THREAD

**Issue by nir-krakauer** [Linuxbrew/homebrew-core#7658]
- [ x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I need `systemd` as a dependency for upgrading `octave`.

`brew install -v systemd 2>&1`

failed with the message

```
In file included from ./src/basic/util.h:46:0,
                 from ./src/basic/hashmap.h:29,
                 from ./src/shared/bus-util.h:30,
                 from src/core/socket.c:33:
./src/basic/missing.h:494:17: error: expected identifier before numeric constant
 #define MS_MOVE 8192
                 ^
Makefile:18031: recipe for target 'src/core/libcore_la-socket.lo' failed
make[2]: *** [src/core/libcore_la-socket.lo] Error 1
Makefile:24263: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
Makefile:25843: recipe for target 'install' failed
make: *** [install] Error 2
```

Full logs are [here](https://gist.github.com/0d57d92cb038416e2da0e5beb83ec171)

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. This is not a Linuxbrew bug, but a bug in systemd, see https://github.com/systemd/systemd/issues/8507

We will accept a pull request which adds a patch to fix this in Linuxbrew, based on the work done by upstream. I have not much time to work on this myself, but can review that pull request.

**Comment by dpo** [comment]
@nir-krakauer #7936 fixes it for me on CentOS. It would be great if you could check that it also works for you.

**Comment by nir-krakauer** [comment]
The revised `systemd.rb` works for me, thanks.
