### ISSUE TITLE
Should curl be used from $PATH when installing linuxbrew?

### ISSUE THREAD

**Issue by Gwang-Jin** [Linuxbrew/homebrew-core#7694]
Hello. When I started linuxbrew with non-root user, I met a problem with curl path.
In my system,
`/usr/bin/curl --version `

`curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.12.9.0 zlib/1.2.3 libidn/1.18 libssh2/1.2.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz`

, and the version of curl is too old to install linuxbrew.

So I compiled curl source in my /home/my/local. But when installing linuxbrew, the script of
`https://raw.githubusercontent.com/Linuxbrew/install/master/install`
always use `/usr/bin/curl` although there is another curl in $PATH `/home/my/local/bin/curl`

Could you change `install`  into
`386     system "/bin/bash -o pipefail -c 'curl -#{curl_flags} #{BREW_REPO}/tarball/master | /bin/tar xz -m --strip 1'"`

`392       system "/bin/bash -o pipefail -c 'curl -#{curl_flags} #{CORE_TAP_REPO}/tarball/master | /bin/tar xz -m --strip 1'"`
?

Then we can use curl from $PATH.

**Comment by iMichka** [comment]
Hi. I think it would be fine to make that change (replacing `/usr/bin/curl` with `curl`). I think this comes from the mac logic where they may want to force you to use the system's curl. On Linux it is probably fine to use whatever curl is in the path (but maybe upstream would be interested to make that change too).

@sjackman Any opinion on this. I bet it has already been discussed :)

By the way, this issue should have been raison on a different issue tracker:
https://github.com/Linuxbrew/install

We can continue the discussion here for the moment though.

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/install#27
