### ISSUE TITLE
CentOS6 install of glibc fails with crti.o not found

### ISSUE THREAD

**Issue by Gwang-Jin** [Linuxbrew/homebrew-core#7695]
Thank you for fixing [#7172](https://github.com/Linuxbrew/homebrew-core/issues/7172#issuecomment-388984850). But when installing
`HOMEBREW_NO_AUTO_UPDATE=1 brew install glibc`
the same error massage with `crti.o not found` occrred after succeeding `gcc --without-glibc`
So should it be also added in `glibc.rb` ?

> ENV.prepend_path "LIBRARY_PATH", "/usr/lib"
        if Hardware::CPU.is_32_bit?
          ENV.prepend_path "LIBRARY_PATH", "/usr/lib32"
        else
          ENV.prepend_path "LIBRARY_PATH", "/usr/lib64"
        end

Thank you.

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by hqax** [comment]
I have the same issue building glibc after successfully installing gcc --without-glibc on RHEL server 6.9 on a 64-bit machine. The installer attempts to read libraries from /lib rather than /lib64.

**Comment by Gwang-Jin** [comment]
I attached glib.rb.
[glibc.rb.txt](https://github.com/Linuxbrew/homebrew-core/files/2015247/glibc.rb.txt)

**Comment by iMichka** [comment]
Hi. Right, I can reproduce this. I will work on a patch that adds the lib folders to the formula during this weekend.

**Comment by iMichka** [comment]
I opened a patch for this: #7736

**Comment by iMichka** [comment]
Fixed by #7736

You will need to update, and run `brew posinstall gcc`.
