### ISSUE TITLE
Building p11-kit

### ISSUE THREAD

**Issue by ipatch** [Linuxbrew/homebrew-core#7866]
I was unable to install `p11-kit` with `brew install p11-kit` on Debian 9.4 this morning, so I created a [branch](https://github.com/ipatch/homebrew-core/blob/exp-p11-kit/Formula/p11-kit.rb) where `p11-kit` can build on Debian, I hope this helps for those who need to build `p11-kit`

cheers
Chris

**Comment by iMichka** [comment]
Fixed by #7849. Thanks for reporting though :)
