### ISSUE TITLE
Fail to build opencv in CenOS6

### ISSUE THREAD

**Issue by Gwang-Jin** [Linuxbrew/homebrew-core#7869]
Hello.

When `brew install opencv` in CentOS 6, I met an error at `modules/core/src/hal_internal.cpp`

````
[ 40%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/kmeans.cpp.o
cd /home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/build/modules/core && /home/skpark/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5  -DCVAPI_EXPORTS -DOPENCV_WITH_ITT=1 -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/build/3rdparty/ippicv/ippicv_lnx/include -I/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/build/3rdparty/ippicv/ippiw_lnx/include -I/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/build -isystem /home/skpark/.linuxbrew/include/eigen3 -isystem /home/skpark/.linuxbrew/include -I/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/modules/core/include -I/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/modules/core/src -I/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/build/modules/core -I/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/3rdparty/include/opencl/1.2 -I/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/3rdparty/ittnotify/include  -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG  -DNDEBUG -fPIC    -Winvalid-pch  -include "/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/build/modules/core/precomp.hpp" -o CMakeFiles/opencv_core.dir/src/kmeans.cpp.o -c /home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/modules/core/src/kmeans.cpp
In file included from /home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/modules/core/src/hal_internal.cpp:49:0:
/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/modules/core/src/hal_internal.cpp: In function 'int lapack_gemm_c(const fptype*, size_t, const fptype*, size_t, fptype, const fptype*, size_t, fptype, fptype*, size_t, int, int, int, int)':
/home/skpark/tmp/opencv-20180528-4964-6c0blx/opencv-3.4.1/modules/core/src/hal_internal.cpp:438:48: error: expected unqualified-id before '_Complex'
     int ldsrc1 = (int)(src1_step / sizeof(std::complex<fptype>));
                                                ^
````

Thank you.

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
[https://gist.github.com/ecacf538b20b3540fdf8d604e5f79d4a](https://gist.github.com/ecacf538b20b3540fdf8d604e5f79d4a)

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by Gwang-Jin** [comment]
I found a solution: adding `#undef complex` to `modules/core/src/hal_internal.cpp` like:

````
 49 #include <complex.h>
 50 #undef complex     // adding !!
 51 #include "opencv_lapack.h"
 52 
 53 #include <cmath>
 54 #include <algorithm>
 55 #include <typeinfo>
 56 #include <limits>
 57 #include <complex>
 58 #include <vector>
````

[C++ <complex> and <complex.h> in the same file](https://stackoverflow.com/questions/23414270/c-complex-and-complex-h-in-the-same-file)

**Comment by iMichka** [comment]
Weird, because brewed gcc5 is used on our build bot and it worked ...

Not sure if this is an opencv bug or not. You may want to try to build opencv in a separate folder, manually, and see if it still happens. If yes, the bug needs to be reported upstream.
