### ISSUE TITLE
RHEL 6 - cannot find crti.o: No such file or directory

### ISSUE THREAD

**Issue by glmanhtu** [Linuxbrew/homebrew-core#7881]
Hello,

I have got an exception during install glibc on my RHEL6. The problem's about the system couldn't found the crt1.o, crti.o
``cannot find crti.o: No such file or directory``
Although, I found those libraries placed in /usr/lib64. But I don't understand why it not worked. Howerver, I managed to make it worked by add the following line into glibc formula

``ENV["LIBRARY_PATH"] = "/usr/lib64"``

Hope this help other people who have got this problem

**Comment by iMichka** [comment]
Hi. Thanks for reporting. This is the right fix. We are trying to find a more general solution here: #7736

Closing as this is fixed for you.
