### ISSUE TITLE
mesa build error in CentOS6: No package 'glproto' found

### ISSUE THREAD

**Issue by Gwang-Jin** [Linuxbrew/homebrew-core#7913]
Hello.

Although `glproto` is installed in my system, when building `mesa`, I met the error messages
````
configure: error: Package requirements (glproto >= 1.4.14) were not met:

No package 'glproto' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLPROTO_CFLAGS
and GLPROTO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
````

Thank you.

[https://gist.github.com/091234dc707b47899d6fda3f19b8f2bf](https://gist.github.com/091234dc707b47899d6fda3f19b8f2bf)
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by iMichka** [comment]
Hi. Can you open this issue in the xorg repository where the formula is hosted? Thanks
https://github.com/Linuxbrew/homebrew-xorg
