### ISSUE TITLE
installing pulseaudio in CentOS6: ./pacat.1': No such file or directory

### ISSUE THREAD

**Issue by Gwang-Jin** [Linuxbrew/homebrew-core#7914]
Hello. When I tried to install `pulseaudio` in CentOS6, I met an error message:

````
/usr/bin/install: cannot stat `./pacat.1': No such file or directory
/usr/bin/install: cannot stat `./pacmd.1': No such file or directory
/usr/bin/install: cannot stat `./pactl.1': No such file or directory
/usr/bin/install: cannot stat `./pasuspender.1': No such file or directory
/usr/bin/install: cannot stat `./padsp.1': No such file or directory
/usr/bin/install: cannot stat `./start-pulseaudio-x11.1': No such file or directory
make[3]: *** [install-man5] Error 1
````
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

[https://gist.github.com/cc1e0ec1427d7c634571a5f8b71fd363](https://gist.github.com/cc1e0ec1427d7c634571a5f8b71fd363)

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by iMichka** [comment]
> https://patchwork.openembedded.org/patch/13321/
```
Building man pages is using host perl and fails if there isn't
XML/Parser.pm on host:
```

This means that we need to install xml parser for you.
Would you willing to test this and open a pull request. You can grep for `resource "XML::Parser" do` in homebrew-core to see how this is done.

**Comment by hisakatha** [comment]
I had the same problem on CentOS6 with brewed perl.
As I noted in #8148, it seems that, for any reason, perl in libexec cannot find brewed libc and uses the system (OS) libc. It causes GLIBC version mismatch in an old environment such as CentOS6.
The related output can be found in https://gist.github.com/Gwang-Jin/cc1e0ec1427d7c634571a5f8b71fd363#file-05-make

> Can't load '/home/skpark/.linuxbrew/Cellar/pulseaudio/11.1_1/libexec/lib/perl5/x86_64-linux-thread-multi/auto/XML/Parser/Expat/Expat.so' for module XML::Parser::Expat: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/skpark/.linuxbrew/Cellar/pulseaudio/11.1_1/libexec/lib/perl5/x86_64-linux-thread-multi/auto/XML/Parser/Expat/Expat.so) at /usr/lib64/perl5/DynaLoader.pm line 200.

I've found a workaround (#8148), which removes perl in libexec.
However, it cancels #4499, so I think more suitable solution is needed.
