### ISSUE TITLE
protobuf: error: Python.h: No such file or directory 

### ISSUE THREAD

**Issue by zhuangsirui** [Linuxbrew/homebrew-core#794]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

Install `protobuf` failed.

https://gist.github.com/anonymous/54883662e4f6a288cb360d952f4d82b6

**Comment by zhuangsirui** [comment]
I think it's depend on python-dev but I don't have it. Problem resolved.

**Comment by zhuangsirui** [comment]
Still should add python-dev in this formula.

**Comment by rwhogg** [comment]
@zhuangsirui, `python-setuptools` is a dependency of Linuxbrew, but `python-dev` is not.

Does building `protobuf` work if you uninstall `python-dev` but install `python-setuptools`?

If not, then IMO we need to add a `brew doctor` check for when the first Python found in the path is the system Python but you don't have `python-dev` installed. We can't make system packages dependencies of individual formulae, unfortunately, and I'd be very hesitant to make `python-dev` a global dependency of Linuxbrew. Thoughts @DoomHammer, @sjackman?

**Comment by zhuangsirui** [comment]
@rwhogg No, cannot build `protobuf` without `python-dev`.

**Comment by sjackman** [comment]
`protobuf` does required `libpython2.7.so` provided `python-dev`. Adding a `brew doctor` check would make sense I think. Would it be too noisy for `brew doctor` to complain that you don't `python-dev` installed when the user has no intention of ever using Python?

**Comment by vasanthv** [comment]
Any update on this? I am getting the following error is this related to this thread?

`Last 15 lines from /home/quixey/.cache/Homebrew/Logs/protobuf/11.python:
creating build/lib.linux-x86_64-2.7/google/protobuf/internal/import_test_package
copying google/protobuf/internal/import_test_package/__init__.py -> build/lib.linux-x86_64-2.7/google/protobuf/internal/import_test_package
copying google/protobuf/internal/import_test_package/inner_pb2.py -> build/lib.linux-x86_64-2.7/google/protobuf/internal/import_test_package
copying google/protobuf/internal/import_test_package/outer_pb2.py -> build/lib.linux-x86_64-2.7/google/protobuf/internal/import_test_package
running build_ext
building 'google.protobuf.pyext._message' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/google
creating build/temp.linux-x86_64-2.7/google/protobuf
creating build/temp.linux-x86_64-2.7/google/protobuf/pyext
gcc-5 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -I/home/quixey/.linuxbrew/Cellar/protobuf/3.3.0/include -L/home/quixey/.linuxbrew/Cellar/protobuf/3.3.0/lib -fPIC -I. -I../src -I/usr/include/python2.7 -c google/protobuf/pyext/message.cc -o build/temp.linux-x86_64-2.7/google/protobuf/pyext/message.o -Wno-write-strings -Wno-invalid-offsetof -Wno-sign-compare
In file included from google/protobuf/pyext/message.cc:34:0:
./google/protobuf/pyext/message.h:37:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'gcc-5' failed with exit status 1
`

**Comment by sjackman** [comment]
Does installing `python` resolve your issue?
```sh
brew install python protobuf
```
If not, please report…
```sh
brew gist-logs protobuf
```

**Comment by vasanthv** [comment]
@sjackman being a Ubuntu machine it had python by default but even then 
`brew install python protobuf` 
fixed the problem now.

Thank you for your help but a small explanation would be enlightening.

**Comment by sjackman** [comment]
Either `sudo apt-get install python-dev` or `brew install python` should resolve your issue. The current check for `python` only checks that the `python` executable is installed. It doesn't check that `Python.h` is installed, which is a bug.
The relevant code is here: https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/requirements/python_requirement.rb#L7
