### ISSUE TITLE
Failed to install crystal-lang on fedora 28

### ISSUE THREAD

**Issue by MadBomber** [Linuxbrew/homebrew-core#8093]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

The "frank" host is Fedora v28

ruby-2.5.1  frank:~ $ brew --version
Homebrew 1.6.8
Homebrew/homebrew-core (git revision d241; last commit 2018-06-18)

ruby-2.5.1  frank:~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /bin/pkg-config
  /bin/pcre2-config
  /bin/jemalloc-config
  /bin/xml2-config
  /bin/x86_64-redhat-linux-gnu-pkg-config
  /bin/ncursesw6-config
  /bin/ncurses6-config
  /bin/krb5-config
  /bin/brltty-config

ruby-2.5.1  frank:~ $ which crystal
/usr/bin/which: no crystal in (/home/linuxbrew/.linuxbrew/bin:/home/dewayne/.rvm/gems/ruby-2.5.1/bin:/home/dewayne/.rvm/gems/ruby-2.5.1@global/bin:/home/dewayne/.rvm/rubies/ruby-2.5.1/bin:/home/dewayne/.rvm/bin:/home/dewayne/scripts:/home/dewayne/bin:/usr/local/sbin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/opt/go/libexec/bin:/home/dewayne/.rvm/bin:/home/dewayne/.local/bin:/home/dewayne/bin)

ruby-2.5.1  frank:~ $ brew install crystal-lang
==> Downloading https://github.com/crystal-lang/crystal/archive/0.25.0.tar.gz
Already downloaded: /home/dewayne/.cache/Homebrew/crystal-lang-0.25.0.tar.gz
==> Downloading https://github.com/crystal-lang/crystal/releases/download/v0.24.1/crystal-0.24.1-2-darwin-x86_
Already downloaded: /home/dewayne/.cache/Homebrew/crystal-lang--boot-0.24.1.tar.gz
==> make deps
==> bin/crystal build -D without_openssl -D without_zlib -o .build/crystal src/compiler/crystal.cr --release -
Last 15 lines from /home/dewayne/.cache/Homebrew/Logs/crystal-lang/02.crystal:
2018-06-18 16:32:06 -0500

bin/crystal
build
-D
without_openssl
-D
without_zlib
-o
.build/crystal
src/compiler/crystal.cr
--release
--no-debug

/tmp/crystal-lang-20180618-878-1s9tusq/crystal-0.25.0/boot/bin/crystal: line 102: /tmp/crystal-lang-20180618-878-1s9tusq/crystal-0.25.0/boot/embedded/bin/crystal: cannot execute binary file: Exec format error   <<<<<========= Here is the ERROR

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

ruby-2.5.1  frank:~ $ brew gist-logs crystal-lang
https://gist.github.com/a6e6e90a266c29ecf31ff3d967be949c

**Comment by MadBomber** [comment]
I just circled back around to this and found it to be a non-problem.  I was able to successfully install crystal on my fedora 28 box using 'brew install crystal'  Whatever that problem was back in June has obviously been resolved.

**Comment by iMichka** [comment]
There have been multiple updates to that formula since then, so one of these probably fixed it. Glad you got it working.
