### ISSUE TITLE
brew install ripgrep => cargo syntax error

### ISSUE THREAD

**Issue by black-snow** [Linuxbrew/homebrew-core#8144]
- [X] are reporting a bug others will be able to reproduce and not asking a question.
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)?
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? => https://gist.github.com/black-snow/bf46e8b013e03863334eec23b0786cc4

To help us debug your issue please explain:
- What you were trying to do: `brew install ripgrep`
- What happened: *can be seen in the gist - install failed*
- What you expected to happen: *succeeding install*
- Step-by-step reproduction instructions: *s.a.*

**Comment by iMichka** [comment]
Hi. I built a bottle without problem here: #8146
If you use precompiled bottle, you should be good to go after an update.

If not we will need to investigate more.

**Comment by black-snow** [comment]
Will try again on Monday

**Comment by black-snow** [comment]
> ==> Downloading https://linuxbrew.bintray.com/bottles/ripgrep-0.8.1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/fc/fcb18ab822dcd2d5f40697f50467999692434e98b40e860c8b3534d1852a0502?__gda__=exp=1530260998~hmac=ce8f6a08cbb3f6f25bfc7a7e89867f55d9ece17504baaa58c8f0d
######################################################################## 100.0%
==> Pouring ripgrep-0.8.1.x86_64_linux.bottle.tar.gz
nice: cannot set niceness: Permission denied
==> Caveats
Bash completion has been installed to:
  /home/linuxbrew/.linuxbrew/etc/bash_completion.d
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/ripgrep/0.8.1: 10 files, 37MB

**Comment by iMichka** [comment]
Glad it worked for you.
