### ISSUE TITLE
fail to install gnutls-3.5.18 on CentOS 6 due to old kernel?

### ISSUE THREAD

**Issue by azrdev** [Linuxbrew/homebrew-core#8238]
#7886

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask).
- [x] ran `brew update` and can still reproduce the problem?
- [/] ran `brew doctor`, fixed all issues and can still reproduce the problem?
  - the warnings about `"config" scripts` are usual on uberspace hosting & were present before this bug
  - perl is not installed, but would only be needed because of weechat
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link: <https://gist.github.com/azrdev/cb21add0a9ab1804043a3738966906ff>

To help us debug your issue please explain:
- What you were trying to do (and why)
  - `brew upgrade  weechat --with-python --with-perl  --without-tcl` 2.0 -> 2.1
- What happened (include command output)
  - got an error about `__NR_getrandom`:
~~~sh
==> Upgrading 1 outdated package, with result:
weechat 2.0 -> 2.1
==> Upgrading weechat --with-perl --without-tcl --with-python@2
==> Installing dependencies for weechat: gnutls, libgpg-error, gdbm, sqlite, python@2, libxml2, libgcrypt, gettext, berkeley-db, libbsd, expat, perl
==> Installing weechat dependency: gnutls
==> Downloading https://gnupg.org/ftp/gcrypt/gnutls/v3.5/gnutls-3.5.18.tar.xz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --disable-static --prefix=/home/qrdn/.linuxbrew/Cellar/gnutls/3.5.18 --sysconfdir=/home/qrdn/.linuxbrew/etc --with-default-trust-store-file=/h
==> make install

Last 15 lines from /home/qrdn/.cache/Homebrew/Logs/gnutls/02.make:
sysrng-linux.c: In function 'force_getrandom':
sysrng-linux.c:60:43: error: '__NR_getrandom' undeclared (first use in this function)
 #   define getrandom(dst,s,flags) syscall(SYS_getrandom, (void*)dst, (size_t)s, (unsigned int)flags)
                                           ^
sysrng-linux.c:84:9: note: in expansion of macro 'getrandom'
   ret = getrandom(p, left, flags);
         ^
make[3]: *** [sysrng-linux.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/tmp/gnutls-20180629-14627-dhj708/gnutls-3.5.18/lib/nettle'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/tmp/gnutls-20180629-14627-dhj708/gnutls-3.5.18/lib'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/tmp/gnutls-20180629-14627-dhj708/gnutls-3.5.18/lib'
make: *** [install-recursive] Error 1
~~~

Googling finds https://github.com/rbenv/ruby-build/issues/914#issuecomment-225272855 which suggests the CentOS kernel (Linux 2.6.32-696.18.7.el6.x86_64) is too old.
This contrasts with https://github.com/Linuxbrew/brew#dependencies stating a requirement of "Linux 2.6.16 or newer".

**Comment by iMichka** [comment]
The 2.6.16 dependency is a sort of a general dependency, which makes sure you can install brew and some basic formulae. Some specific formulae may need a newer kernel, but we have no way to make sure this is consistent for the 4000 formulae in homebrew-core. So it may be that you will not be able to install everything.

We would maybe be willing to provide a versioned version of an older gnutls. Though as this is a library used for secure networking, I am a little bit worried to provide an older version of it ...

**Comment by azrdev** [comment]
@iMichka maybe one of the distros providing older versions with backported security patches do have an appropriate source code which could be used?

**Comment by iMichka** [comment]
I would accept a pull request for that. Of course I do not want to personally take care of such a formula, but would review it and merge it.

**Comment by iMichka** [comment]
Closing here. If you need an older gnutls version, you need to provide your own versioned formula for that. I would accept and review a pull request for that.
