### ISSUE TITLE
An error occurred when installing Linuxbrew on AWS 

### ISSUE THREAD

**Issue by Rybots** [Linuxbrew/homebrew-core#8375]
$sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/****/.cache/Homebrew/
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Linuxbrew...
HEAD is now at e78a9dae2 keg_relocate: deal with 'no string table' (#740)
==> Tapping homebrew/core
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4835, done.
remote: Compressing objects: 100% (4633/4633), done.
remote: Total 4835 (delta 53), reused 384 (delta 10), pack-reused 0
Receiving objects: 100% (4835/4835), 4.07 MiB | 7.51 MiB/s, done.
Resolving deltas: 100% (53/53), done.
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/shogun.rb
no implicit conversion of false into String
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ice.rb
no implicit conversion of false into String
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/linuxbrew/.linuxbrew/bin/brew tap homebrew/core
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force

An error occurred on AWS. How can I fix it?
Thanks!

**Comment by iMichka** [comment]
Hi. Can you try again. There were multiple updates to linuxbrew since then. Thanks.

**Comment by iMichka** [comment]
Closing here. Feel free to ping us if there are still problems with this. Thanks.
