### ISSUE TITLE
gettext compile fails because it cannot find zlib.h

### ISSUE THREAD

**Issue by ssjhv** [Linuxbrew/homebrew-core#8431]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [Y] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [Y] ran `brew update` and can still reproduce the problem?
- [Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [NA] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [NA] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install gettext (Actually was installing neovim and gettext was being installed as a dependency)

- What happened (include command output)
Compile failed because it could not find zlib.h. See logs below.

The problem went away when I installed zlib1g-dev by apt (Debian). Even though zlib is a brew-dependency for gettext, it looks like gettext compile setup is trying to use system zlib rather than brew version of zlib.

Last 15 lines from .../.cache/Homebrew/Logs/gettext/02.make:
compilation terminated.
Makefile:1253: recipe for target 'parser.lo' failed
make[2]: *** [parser.lo] Error 1
parserInternals.c:36:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
Makefile:1253: recipe for target 'parserInternals.lo' failed
make[2]: *** [parserInternals.lo] Error 1
make[2]: Leaving directory '/tmp/gettext--libxml2-20180720-254237-1skbca4/libxml2-2.9.7'
Makefile:1441: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/tmp/gettext--libxml2-20180720-254237-1skbca4/libxml2-2.9.7'
Makefile:1745: recipe for target 'install' failed
make: *** [install] Error 2

- What you expected to happen
Succeed compiling and installing gettext

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install gettext

**Comment by MightyChaos** [comment]
I encounter this issues today as well.
I was trying to install ffmpeg via ``brew install ffmpeg'' and meet this 'zlib.h' not found error.
Latter, I tried ``brew update'' and also ``brew doctor'', then run ``brew install gettext'', the error is still there.

**Comment by timotheecour** [comment]
@maxim-belkin originally reported here: https://github.com/Linuxbrew/homebrew-core/issues/8440#issuecomment-408303610
seeing a different error (no mention of zlib.h)

brew gist-logs gettext
https://gist.github.com/71285e3e73bc38e5f7b33ac8a0edcb66

```
brew install gettext
==> Downloading https://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz
Already downloaded: /home/ubuntu/.cache/Homebrew/gettext-0.19.8.1.tar.xz
==> Downloading http://xmlsoft.org/sources/libxml2-2.9.7.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/gettext--libxml2-2.9.7.tar.gz
==> ./configure --prefix=/home/ubuntu/.linuxbrew/Cellar/gettext/0.19.8.1_1/libexec --without-python --without-lzma
==> make install
==> ./configure --disable-silent-rules --prefix=/home/ubuntu/.linuxbrew/Cellar/gettext/0.19.8.1_1  --with-included-glib --with-included-libcroco --with-included-libunistring --with-emacs --with-lispdir=/home/ubuntu/.linuxbrew/Cellar/gettext/0.19.8.1_1/share/emacs/site-lisp
==> make
Last 15 lines from /home/ubuntu/.cache/Homebrew/Logs/gettext/04.make:
make[5]: Leaving directory '/tmp/gettext-20180727-21088-v4yszw/gettext-0.19.8.1/gettext-tools/gnulib-lib'
Makefile:2618: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/tmp/gettext-20180727-21088-v4yszw/gettext-0.19.8.1/gettext-tools/gnulib-lib'
Makefile:2026: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/tmp/gettext-20180727-21088-v4yszw/gettext-0.19.8.1/gettext-tools'
Makefile:1892: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/gettext-20180727-21088-v4yszw/gettext-0.19.8.1/gettext-tools'
Makefile:414: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/gettext-20180727-21088-v4yszw/gettext-0.19.8.1'
Makefile:370: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

These open issues may also help:
gettext compile fails because it cannot find zlib.h https://github.com/Linuxbrew/homebrew-core/issues/8431
```

**Comment by iMichka** [comment]
Can you try to run `export HOMEBREW_DEVELOPER=1` and `brew update`, to get the latest brew version? We still did not tag 1.7.2 but the latest changes should fix this.
