### ISSUE TITLE
C compiler problem while executing "brew install funannotate"

### ISSUE THREAD

**Issue by soumyarao86** [Linuxbrew/homebrew-core#846]
Hi
I tried to install funannotate on centos 6 by following the instructions on https://github.com/nextgenusfs/funannotate/blob/master/docs/ubuntu_install.md
It introduced me to linuxbrew that installs many tools automatically.
I followed every step till I got stuck while running the command
```
brew install funannotate
```
There seems to be no config.log file created. I tried ```brew gist-logs funannotate``` which didn't work.
I could only make out the problem with c compiler from .linuxbrew/bin.
```
Last 15 lines from /home/lgpa/.cache/Homebrew/Logs/pkg-config/01.configure:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... /home/lgpa/.linuxbrew/bin/gcc-5
checking whether the C compiler works... no
configure: error: in `/tmp/pkg-config-20160830-28790-ykpq9q/pkg-config-0.29.1':
configure: error: C compiler cannot create executables
```
Please help me fix it.

**Comment by nextgenusfs** [comment]
Cross-posted here: https://github.com/nextgenusfs/funannotate/issues/24

**Comment by rwhogg** [comment]
Closing since the majority of the discussion has happened on the cross-posted issue, but feel free to comment here if there is something needed on our end to help resolve this.
