### ISSUE TITLE
brew install cmake fails

### ISSUE THREAD

**Issue by mswyers** [Linuxbrew/homebrew-core#8546]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
 Token: 8923152199c6919cab7408fa604c7a9e05c58cbc

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
outputs:
```
HOMEBREW_VERSION: 1.7.0
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 400af242fd7252edc461dba473961097507eed48
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: ec2a690c0895e6e2d67264a72fa7b28ea81f1871
Core tap last commit: 57 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/seq/.cache/Homebrew
HOMEBREW_BOTTLE_DEFAULT_DOMAIN_LINUX: https://linuxbrew.bintray.com
HOMEBREW_BOTTLE_DEFAULT_DOMAIN_MACOS: https://homebrew.bintray.com
CPU: octa-core 64-bit dunno
Homebrew Ruby: 2.5.1 => /usr/bin/ruby2.5
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.15.0-29-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.1 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.3.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A

seq@igseq-Dell:~$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Attempting to install funannotate via brew install funannotate. I've managed to get all dependencies except for those relying on cmake to install. I would post the problem there but I figured a cmake error is something more general.

- What happened (include command output)
```
seq@igseq-Dell:~$ brew install cmake
==> Downloading https://cmake.org/files/v3.12/cmake-3.12.0.tar.gz
Already downloaded: /home/seq/.cache/Homebrew/cmake-3.12.0.tar.gz
==> ./bootstrap --prefix=/home/linuxbrew/.linuxbrew/Cellar/cmake/3.12.0 --no-sys
Last 15 lines from /home/seq/.cache/Homebrew/Logs/cmake/01.bootstrap:
                               ^
Makefile:12: recipe for target 'cmAddExecutableCommand.o' failed
make: *** [cmAddExecutableCommand.o] Error 1
Makefile:6: recipe for target 'cmAddCustomTargetCommand.o' failed
make: *** [cmAddCustomTargetCommand.o] Error 1
Makefile:4: recipe for target 'cmAddCustomCommandCommand.o' failed
make: *** [cmAddCustomCommandCommand.o] Error 1
Makefile:14: recipe for target 'cmAddLibraryCommand.o' failed
make: *** [cmAddLibraryCommand.o] Error 1
---------------------------------------------
Error when bootstrapping CMake:
Problem while running make
---------------------------------------------
Log of errors: /tmp/cmake-20180727-22104-eqqzmx/cmake-3.12.0/Bootstrap.cmk/cmake_bootstrap.log
---------------------------------------------

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.


```

- What you expected to happen

I expected cmake to install normally and sunshine and rainbows to pop out of my workstation.
- Step-by-step reproduction instructions (by running `brew install` commands)

I've followed these instructions up until this point:
http://funannotate.readthedocs.io/en/latest/homebrew.html#homebrew

except this package has some recursive dependencies due to kent-tools and blat, so I run the package install like:
brew install --without-kent-tools --without-blat funannotate
in order to avoid the mysql, mysql@5.7 recursion.

In addition, I had to install some not-listed dependencies since this is a fresh Ubuntu install. (autoheader, autoconf, autotools) to get some of the other dependencies to work (htslib i think).

**Comment by iMichka** [comment]
I think there was a bug in brew, and I made a workaround for it. I rebuilt the cmake bottle here and it worked: #8488

Can you update and try again?
