### ISSUE TITLE
Make bottle for node?

### ISSUE THREAD

**Issue by cmdcolin** [Linuxbrew/homebrew-core#8574]
I am just wondering if it would be possible to make a precompiled bottle for node.js on linuxbrew?

Or is there something maybe that makes compiling from source better or necessary?

**Comment by iMichka** [comment]
Hi. The bottle was just gone for a few hours. I added it right now (#8558). You may have moments without bottle during the day, when there is a version update. Or when I am in holidays like right now and I get stuck at the beach :D
