### ISSUE TITLE
pulseaudio: libltdl.so No such file or directory

### ISSUE THREAD

**Issue by Gwang-Jin** [Linuxbrew/homebrew-core#8596]
Hello, when I tried to install `pulseaudio` in openSUSE, I met
```
gcc-5: error: /usr/lib/libltdl.so: No such file or directory
```

[https://gist.github.com/fd555a0e70df5dc89fcd11163098d044](https://gist.github.com/fd555a0e70df5dc89fcd11163098d044)

Thank you.

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by iMichka** [comment]
Hi. This was an equivalent problem to the perl problem. This has been fixed and you can test this again with `export HOMEBREW_DEVELOPER=1` and `brew update`.
