### ISSUE TITLE
icu4c test fails on Circle CI

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/homebrew-core#860]
It needs the package `wamerican` installed.

Perhaps there's some alternate dictionary that we could use that is installable through Linuxbrew so we could fix the test, but I'm not aware of any.

See #859

**Comment by DoomHammer** [comment]
Maybe we should skip tests when dict is not available and issue a warning? I made something similar for a formula whose tests depended on `cmp`. Can't recall the name, though :/

**Comment by rwhogg** [comment]
@sjackman has opened PRs (#1324 and #1323) that will install `wbritish` instead.

Those should resolve this issue.

**Comment by sjackman** [comment]
I closed #1323 for Travis because I think it's already installed by default.
I merged #1324.

**Comment by sjackman** [comment]
Fixed by PR #1324.
