### ISSUE TITLE
gtk+ failed to build on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by LichFaker** [Linuxbrew/homebrew-core#873]
[https://gist.github.com/b85e0b209dcfcc6627d3193eafd80827
](url)

**Comment by rwhogg** [comment]
From https://gist.github.com/anonymous/b85e0b209dcfcc6627d3193eafd80827#file-02-make-L582-L583

```
Could not find GIR file 'GdkPixbuf-2.0.gir'; check XDG_DATA_DIRS or use --includedir
error parsing file Gdk-2.0.gir: Failed to parse included gir GdkPixbuf-2.0
```

@LichFaker, I think this is a problem with XDG_DATA_DIRS. Can you try doing the following change (or something similar) and then retrying the build?

```
Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
echo 'export XDG_DATA_DIRS="/home/dqc/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile
```

Thanks a bunch for the bug report!

**Comment by LichFaker** [comment]
sorry for late reply, it was worked, thanks!

**Comment by rwhogg** [comment]
np, happy to help
