### ISSUE TITLE
brew install vorbis-tools fails: undefined reference to symbol 'tanh@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by jamescostian** [Linuxbrew/homebrew-core#8888]
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Install all the programs I installed via macOS Homebrew to help test if Linuxbrew is ready for the merger - see [this comment](https://github.com/Linuxbrew/brew/issues/612#issuecomment-411257424).

This issue is specifically about vorbis-tools not installing

# What happened (include command output)

The build failed [here](https://gist.github.com/jamescostian/db4bb41a43c0b5008f3253c73875fca5#file-02-make-L233).

Check out [the full  gist](https://gist.github.com/jamescostian/db4bb41a43c0b5008f3253c73875fca5)

# What you expected to happen

`brew install vorbis-tools` should work

# Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install vorbis-tools || echo "It didn't work"
```

**Comment by iMichka** [comment]
Hi. Thanks for reporting. Will try to build it here: #8948

**Comment by iMichka** [comment]
Fixed by #8948
