### ISSUE TITLE
brew install rust fails on CentOS7

### ISSUE THREAD

**Issue by shivakumargn** [Linuxbrew/homebrew-core#9012]
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)
Tried "brew install ripgrep" which in turn triggered "...install rust"

- What happened (include command output)
Failure when it tries to install rust as part of d

- What you expected to happen
Successful installation

- Step-by-step reproduction instructions (by running `brew install` commands)
Try "brew install rust" on CentOS7.

**Comment by iMichka** [comment]
You need to provide us the information asked by the issue template to be able to help you. I will close this issue for the time being and will reopen it if you provide what was asked. Thanks.
