### ISSUE TITLE
Kyoto Cabinet Fails to Configure

### ISSUE THREAD

**Issue by andrewyatz** [Linuxbrew/homebrew-core#915]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

https://gist.github.com/6737239a3e65d1f3a571e76649000599.

When trying to compile Kyoto Cabinet I get the following error

```
configure:2637: checking whether the C compiler works
configure:2659: /nfs/gns/homes/ayates/linuxbrew/linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -isystem/nfs/gns/homes/ayates/linuxbrew/linuxbrew/include -L/nfs/gns/homes/ayates/linuxbrew/linuxbrew/lib -Wl,--dynamic-linker=/nfs/gns/homes/ayates/linuxbrew/linuxbrew/lib/ld.so -Wl,-rpath,/nfs/gns/homes/ayates/linuxbrew/linuxbrew/lib conftest.c  >&5
/usr/bin/ld: unrecognized option '-plugin'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
```

GCC is 5.3. The error is replicable if I download and attempt to configure Kyoto without going through brew.

**Comment by rwhogg** [comment]
> The error is replicable if I download and attempt to configure Kyoto without going through brew.

Sounds like an upstream issue to me. Can you send a bug report to the upstream developers?

**Comment by andrewyatz** [comment]
I can do though I'm surprised that no one else with linuxbrew and
attempting to install this isn't see the same issue. As an FYI the code can
compile if I pass it another version of GCC. Also Tokyo Cabinet (by the
same people) compiles fine. Go figure ...

**Comment by rwhogg** [comment]
I just built a precompiled bottle for this on #918. Can you do a `brew update` and then retry the installation from the bottle?

Since this is an upstream issue, feel free to close this thread if the bottle works for you.

Thanks a bunch for the bug report!

**Comment by andrewyatz** [comment]
So I've got the update and it mentions the bottle but for some reason `brew
install kyoto-cabinet` does not trigger the bottle process. I'm not
compiling to a standard location so that might cause it some issues. Okay
I'll raise the issue upstream as well and will report back.

**Comment by rwhogg** [comment]
> I'm not compiling to a standard location so that might cause it some issues.

Oops, you're right. The bottle has to be installed to /home/linuxbrew/.linuxbrew.

**Comment by sjackman** [comment]
You can try `brew install --force-bottle kyoto-cabinet`. It may or may not work.
