### ISSUE TITLE
xz: brew install node blowing up with GCC issues (`/usr/bin/gcc-4.9': double free or corruption (top): 0x0035e718) --- Raspbian

### ISSUE THREAD

**Issue by wkruddy** [Linuxbrew/homebrew-core#923]
- [X] Ran `brew update` and retried your prior step? Yes, twice.
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step? Yes, twice.
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Hi there, apologies if I'm not entering the correct information, but following the steps to submit didn't deliver me anything in the gist-logs.  I attempted to do `brew install node`, and seem to be seeing issues with GCC? Not sure if this is due to the fact that I'm on my RaspberryPi, but everything else has seemed to go smoothly so far, so I didn't think there were any issues.

Ran `brew gist-logs node` and got "Error: No logs."

This is what I'm seeing though:

```
pi@raspberrypi:~ $ brew install node
==> Installing dependencies for node: xz, pkg-config
==> Installing node dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.2.tar.gz
Already downloaded: /home/pi/.cache/Homebrew/xz-5.2.2.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/pi/.linuxbrew/Cellar/xz/5.2.2
*** Error in `/usr/bin/gcc-4.9': double free or corruption (top): 0x00ebc718 ***
Last 15 lines from /home/pi/.cache/Homebrew/Logs/xz/01.configure:
Initializing Automake:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for style of include used by make... GNU
checking for gcc... /usr/bin/gcc-4.9
checking whether the C compiler works... no
configure: error: in `/tmp/xz-20160915-23720-pru9sv/xz-5.2.2':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues
```

Here's my `brew doctor` info:

```
Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
    echo 'export XDG_DATA_DIRS="/home/pi/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile
```

and finally, here's my `brew config`:

```
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 92d76c2daa3816456adbacfd224dea65141774d4
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: cc7fe023b92983db3a0b1abb3277409298e27745
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /home/pi/.linuxbrew
HOMEBREW_REPOSITORY: /home/pi/.linuxbrew
HOMEBREW_CELLAR: /home/pi/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 32-bit arm
Homebrew Ruby: 2.1.5 => /usr/bin/ruby2.1
Clang: N/A
Git: 2.1.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.1
Java: 1.8.0_65
Kernel: Linux 4.4.11-v7+ armv7l GNU/Linux
OS: Raspbian GNU/Linux 8.0 (jessie)
Codename: jessie
OS glibc: 2.19
OS gcc: 4.9.2
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A
```

I love using Homebrew on my Mac, and when I found out I could possibly use it on my RPi, I was stoked.  

Any advice would be helpful. Thanks!

**Comment by sjackman** [comment]
Unfortunately it seems like a bug in GCC 4.9. My best suggestion would be to try `brew install gcc`.
`brew gist-logs node` didn't work because `xz` failed, so you'd have to instead run `brew gist-logs xz`

**Comment by krlight** [comment]
If you are using Raspberry PI 3 then adding `export HOMEBREW_ARCH=armv8-a+crc` to your `.bashrc` will solve this problem. Tested on Raspbian GNU/Linux 8.0 (jessie) with Raspberry PI 3B.

ref: https://github.com/Linuxbrew/brew/issues/42

**Comment by sjackman** [comment]
Thanks, KR!

**Comment by wkruddy** [comment]
Can confirm, this definitely works. Node installed like a champ. Thanks a ton!.

**Comment by sjackman** [comment]
The default is `HOMEBREW_ARCH=native` that is `-march=native`. Is it GCC `-march=native` buggy on Raspberry Pi 3?

**Comment by krlight** [comment]
@sjackman Yes, due to [this bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132).

**Comment by sjackman** [comment]
Would you like to submit a PR to work around this issue?
See https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/os/linux/hardware/cpu.rb#L23
and https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/hardware.rb#L15

**Comment by krlight** [comment]
Sure, will do.
