### ISSUE TITLE
Installing rabbitmq fails on Ubuntu server 18.04

### ISSUE THREAD

**Issue by madis** [Linuxbrew/homebrew-core#9263]
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  > Was trying to install RabbitMQ server on ubuntu 18.04 server
- What happened (include command output)
  > install failed (command output in gist  https://gist.github.com/madis/de7fd448fbd15ab3f0469ca41ee1f52a
- What you expected to happen
  > Expected rabbitmq server to get installed and to be able to run `rabbitmq-server` 
- Step-by-step reproduction instructions (by running `brew install` commands)
  > `brew install rabbitmq`

Link to gist with outputs from `brew config` and `brew doctor` and `brew install`: https://gist.github.com/madis/de7fd448fbd15ab3f0469ca41ee1f52a

**Comment by iMichka** [comment]
>  Failed to execute: /usr/bin/unzip

Hi. Would you like to open a pull request for this? The formula probably just needs a `depends_on "unzip"  unless OS.mac?" statement.

**Comment by iMichka** [comment]
Fixed by #10380
