### ISSUE TITLE
fontconfig: needs an additional dependency

### ISSUE THREAD

**Issue by hisakatha** [Linuxbrew/homebrew-core#9270]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew upgrade fontconfig`

- What happened (include command output)
Upgrading failed with the following error including:
```
test-conf.c:28:18: fatal error: json.h: No such file or directory
```

Full gist-logs: https://gist.github.com/hisakatha/d6fb63c7c2ab0feb5025fbe85a10fcfd

- What you expected to happen
Successful upgrade

- Step-by-step reproduction instructions (by running `brew install` commands)
After `brew uninstall --ignore-dependencies fontconfig`, `brew install fontconfig --without-docs`.
Because my environment is CentOS6, I have to use the `--without-docs` option as noted in #4950. I was able to install the previous version (2.13.0) of `fontconfig` with `--without-docs`.

- Workaround
From the error message, I guessed that `fontconfig` needs a dependency on a json-related library. I happened to have `json-c` installed, and `json-c` has `json.h`. Therefore, I added a (full) dependency on `json-c`, that is, `depends_on "json-c"`, and then, `fontconfig` was successfully installed.
However, there are other formulae related to json (according to `brew search json`), so I don't know which formula is appropriate. In addition, I don't know this phenomenon is specific to CentOS6.

**Comment by iMichka** [comment]
I would be OK to add `depends_on "json-c"` to the formula. Probably as build time dependency only. Would you like to open a pull request for that?

**Comment by hisakatha** [comment]
OK. I'll open a pull request soon.

As @iMichka suggested, a build-time dependency on "json-c" was enough according to `brew test` and `brew audit --strict`.
