### ISSUE TITLE
gettext build from source finds wrong libxml2 if later already installed

### ISSUE THREAD

**Issue by drbenmorgan** [Linuxbrew/homebrew-core#9272]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  - Install `gettext` from source (not able to have `/home/linuxbrew/.linuxbrew` on all systems I'm supporting, though issue is reproducible in that environment)
- What happened (include command output)
  - Installation of `gettext` formula fails with output:

  ```console
  $ brew install gettext --build-from-source
  ==> Downloading https://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz
  ######################################################################## 100.0%
  ==> Downloading http://xmlsoft.org/sources/libxml2-2.9.7.tar.gz
  ######################################################################## 100.0%
  ==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/gettext/0.19.8.1_1/libexec --without-python --without-lzma
  ==> make install
  ==> ./configure --disable-silent-rules --prefix=/home/linuxbrew/.linuxbrew/Cellar/gettext/0.19.8.1_1  --with-included-glib --with-included-libcroco --with-included-libunistring --
  ==> make
  Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/gettext/04.make:
  make[5]: Leaving directory '/tmp/gettext-20180906-6144-ddcqnr/gettext-0.19.8.1/gettext-tools/gnulib-lib'
  Makefile:2618: recipe for target 'all' failed
  make[4]: *** [all] Error 2
  make[4]: Leaving directory '/tmp/gettext-20180906-6144-ddcqnr/gettext-0.19.8.1/gettext-tools/gnulib-lib'
  Makefile:2026: recipe for target 'all-recursive' failed
  make[3]: *** [all-recursive] Error 1
  make[3]: Leaving directory '/tmp/gettext-20180906-6144-ddcqnr/gettext-0.19.8.1/gettext-tools'
  Makefile:1892: recipe for target 'all' failed
  make[2]: *** [all] Error 2
  make[2]: Leaving directory '/tmp/gettext-20180906-6144-ddcqnr/gettext-0.19.8.1/gettext-tools'
  Makefile:414: recipe for target 'all-recursive' failed
  make[1]: *** [all-recursive] Error 1
  make[1]: Leaving directory '/tmp/gettext-20180906-6144-ddcqnr/gettext-0.19.8.1'
  Makefile:370: recipe for target 'all' failed
  make: *** [all] Error 2

  READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
  Please do not report this issue to Homebrew/brew or Homebrew/core,
  which support macOS only."

  These open issues may also help:
  midnight-commander gettext failed compile https://github.com/Linuxbrew/homebrew-core/issues/9183
  ```

  I believe it's the same issue as #9183 and down to the way libxml2 is being vendored/located.

  The gist is here: https://gist.github.com/drbenmorgan/01baa12d439ebd13e3e7f00025783da1

- What you expected to happen
  - `gettext` to have been installed without error

- Step-by-step reproduction instructions (by running `brew install` commands)

The problem was originally identified on a CentOS7 box, but can be reproduced in the linuxbrew Docker image:

1. This works:
  ``` console
  $ docker run --rm -it linuxbrew/linuxbrew
  linuxbrew@SOMEHASH:~$ brew install gcc
  linuxbrew@SOMEHASH:~$ brew install gettext --build-from-source
 ```
2. This reproduces the failure:
  ``` console
  $ docker run --rm -it linuxbrew/linuxbrew
  linuxbrew@SOMEHASH:~$ brew install gcc libxml2
  linuxbrew@SOMEHASH:~$ brew install gettext --build-from-source
  ```

Checking through the gists, https://gist.github.com/drbenmorgan/01baa12d439ebd13e3e7f00025783da1#file-04-make has the error:

```console
libtool: compile:  gcc-5 -DHAVE_CONFIG_H -DEXEEXT=\"\" -DEXEEXT=\"\" -DEXEEXT=\"\" -I. -I.. -I../intl -I../intl -I.. -I.. -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1 -I///home/linuxbrew/.linuxbrew/include/libxml2 -I./libcroco -g -O2 -c tempname.c -o tempname.o >/dev/null 2>&1
In file included from term-styled-ostream.oo.c:26:0:
./libcroco/cr-sel-eng.h:34:26: fatal error: libxml/tree.h: No such file or directory
compilation terminated.
```

What I _think_ is happening is that the libxml2 `resource` in the gettext formula isn't getting picked up by gettext's configure/build. It picks up any linuxbrew/system install instead, and then fails I guess because superenv/gcc spec file is stripping the include path.

I was able to resolve the problem in the gettext formula by either:

1. Adding `("--with-libxml2-prefix=#{libexec}" unless OS.mac?)` to gettext's configure args.
2. Removing the libxml2 resource entirely from gettext and adding `("--with-included-libxml" unless OS.mac?)` to gettext's `configure` args.

My feeling is the latter is neater as it removes the additional resource, but I'm not sure of preferences for resources vs using a package's own vendored version.

If I've identified things correctly, and one of the above fixes would be suitable, let me know which one and I can submit a PR.

**Comment by iMichka** [comment]
Fixed by #9299
