### ISSUE TITLE
TexLive install fails

### ISSUE THREAD

**Issue by akastrin** [Linuxbrew/homebrew-core#9442]
* [x]  have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
* [x]  ran `brew update` and can still reproduce the problem? 
* [x]  ran `brew doctor`, fixed all issues and can still reproduce the problem?
* [ ]  ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
* [ ]  if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I try to install TexLive using the command `brew install texlive`. However, it seem that this command installs the LaTeX with minimal capabilities. Unfortuantely, I can not find symlinks to `tlmgr` tool (and other tools from the `texmf-dist/scripts` directory) in the installation directory (`/home/linuxbrew/.linuxbrew/Cellar/texlive/20180617/bin`).

Next, I try with the command `brew install --with-full texlive`. TeX and friends (`latex`, `pdflatex`, `bibtex`) install successfully, but again, there are no symlinks to script tools located in `texmf-dist/scripts`.

I kindly ask for help and/or advise how to modify the `texlive.rb` script.

**Comment by iMichka** [comment]
Some symlinks were fixed with #10046, can you try again?

**Comment by akastrin** [comment]
Works perfectly now. But I have no idea why the files in `/bin` are symlinked two times, i.e., in `/home/linuxbrew/.linuxbrew/Cellar/texlive/20181030/bin` and again in `/home/linuxbrew/.linuxbrew/Cellar/texlive/20181030/bin/x86_64-linux$`?

**Comment by iMichka** [comment]
Can you update again. I see that @sjackman made another round of changes in #10089.

**Comment by sjackman** [comment]
I believe that I've fixed this issue. Please do let me know how it works out for you.

**Comment by akastrin** [comment]
Works like a charm! Thanks!

**Comment by sjackman** [comment]
Great! Thanks for following up.
