### ISSUE TITLE
openssl failed to build on Fedora18

### ISSUE THREAD

**Issue by jhornsberger** [Linuxbrew/homebrew-core#949]
This was my first attempt at using brew (brew install tmux). Kind of blew up at openssl for some reason. Please let me know what other information I can provide.

I keep seeing `error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`. Sorry, I'm not very familiar with linuxbrew at this point.

https://gist.github.com/6f08f091aa7885859939eee5852f2317

**Comment by rwhogg** [comment]
Maybe try installing `libstdc++` via `yum`? I'd be surprised if that's not installed by default, but it might not be.

**Comment by sjackman** [comment]
`brew` is preferring `/usr/bin/clang` over the brew installed `gcc-5`. We need to fix that.
The workaround is
```sh
export HOMEBREW_CC=gcc-5
brew install openssl
```
