### ISSUE TITLE
autoconf cannot find Perl modules due to mounted location difference

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#950]
```
brew install protobuf
==> Downloading https://github.com/google/protobuf/archive/v3.0.2.tar.gz
Already downloaded: /home/timothee/.cache/Homebrew/protobuf-3.0.2.tar.gz
==> Downloading https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/googlemock/gmock-1.7.0.zip
Already downloaded: /home/timothee/.cache/Homebrew/protobuf--gmock-1.7.0.zip
==> ./autogen.sh
Last 15 lines from /home/timothee/.cache/Homebrew/Logs/protobuf/01.autogen.sh:
2016-09-23 14:19:40 -0700

./autogen.sh

+ autoreconf -f -i -Wall,no-obsolete
Can't locate Autom4te/ChannelDefs.pm in @INC (you may need to install the Autom4te::ChannelDefs module) (@INC contains: /katrina/home/timothee/.linuxbrew/Cellar/autoconf/2.69/share/autoconf /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/timothee/.linuxbrew/bin/autoreconf line 39.
BEGIN failed--compilation aborted at /home/timothee/.linuxbrew/bin/autoreconf line 39.

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues

These open issues may also help:
error during protobuf 3.0.2 install https://github.com/Homebrew/homebrew-core/issues/4688
```

https://gist.github.com/0f5b66729f5e6b67ad5b8c820de27b47

**Comment by rwhogg** [comment]
From https://gist.github.com/anonymous/0f5b66729f5e6b67ad5b8c820de27b47#file-01-autogen-sh-L6

`/katrina/home/timothee/.linuxbrew/Cellar/autoconf/2.69/share/autoconf`

Any idea where `/katrina/` is coming from? That might explain not just this issue, but a lot of them.

**Comment by timotheecour** [comment]
yes, that was the cause; this worked:
```
brew uninstall autoconf automake make m4 makedepend
brew install autoconf automake make m4 makedepend
brew install protobuf
```

however the real reason was that:
```
machine 1: $HOME=/home/timothee
machine 2: $HOME=/katrina/home/timothee (pointing to same mounted location)
```
what probably happened is I've installed some packages on both, and then it messed things up

not sure if there's a way brew doctor would find this issue and offer a fix?

**Comment by rwhogg** [comment]
Just to clarify: this build was being done from machine 1, on which `/katrina` does not exist, right?

In that case, you might be in a spot of trouble, since several formulae have a history of hardcoding absolute paths into themselves.

If it's possible, you might want to try creating a folder `/katrina/` on machine 1 and symlinking `/home` into `/katrina/home`, so paths like that will always be available.

I'm not sure off the top of my head how we could write a reliable `brew doctor` check for cases like this, but I wouldn't be surprised if issues like this are fairly common in institutional setups. @sjackman, any insights here?

**Comment by sjackman** [comment]
My best suggestion would be to store the values of `HOMEBREW_PREFIX` and `HOMEBREW_CELLAR` the first time the `brew install` is run, and check that they're the same from then on for every other call to `brew install`.
