### ISSUE TITLE
vtk: No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'lib/libvtkglew-7.1.so.1'

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#954]
brew gist-logs vtk
https://gist.github.com/abc37baaa6b2d78e5751a83c84570dc9

```
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/timothee/.linuxbrew/Cellar/vtk/7.0.0_4 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAS
==> make
Last 15 lines from /home/timothee/.cache/Homebrew/Logs/vtk/02.make:
/home/timothee/.linuxbrew/bin/g++-5  -fPIC -Os -w -pipe -march=native   -DNDEBUG  -Wl,--no-undefined -lc  -L/home/timothee/.linuxbrew/lib -Wl,--dynamic-linker=/home/timothee/.linuxbrew/lib/ld.so -Wl,-rpath,/home/timothee/.linuxbrew/lib  -shared -Wl,-soname,libvtkCommonTransforms-7.0.so.1 -o ../../lib/libvtkCommonTransforms-7.0.so.1 CMakeFiles/vtkCommonTransforms.dir/vtkAbstractTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkCylindricalTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkGeneralTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkHomogeneousTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkIdentityTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkLinearTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkMatrixToHomogeneousTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkMatrixToLinearTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkPerspectiveTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkSphericalTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkThinPlateSplineTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkTransform2D.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkTransformCollection.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkWarpTransform.cxx.o CMakeFiles/vtkCommonTransforms.dir/vtkLandmarkTransform.cxx.o ../../lib/libvtkCommonMath-7.0.so.1 ../../lib/libvtkCommonCore-7.0.so.1 -Wl,-rpath,/home/timothee/.linuxbrew/Cellar/vtk/7.0.0_4/lib
cd /tmp/vtk-20160927-30670-yetu4/VTK-7.0.0/build/Common/Transforms && /home/timothee/.linuxbrew/Cellar/cmake/3.6.2/bin/cmake -E cmake_symlink_library ../../lib/libvtkCommonTransforms-7.0.so.1 ../../lib/libvtkCommonTransforms-7.0.so.1 ../../lib/libvtkCommonTransforms-7.0.so
make[2]: Leaving directory '/tmp/vtk-20160927-30670-yetu4/VTK-7.0.0/build'
[ 12%] Built target vtkCommonTransforms
[ 12%] Linking CXX shared library ../../lib/libvtkCommonMisc-7.0.so
cd /tmp/vtk-20160927-30670-yetu4/VTK-7.0.0/build/Common/Misc && /home/timothee/.linuxbrew/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/vtkCommonMisc.dir/link.txt --verbose=1
make[2]: Leaving directory '/tmp/vtk-20160927-30670-yetu4/VTK-7.0.0/build'
make[1]: *** [CMakeFiles/Makefile2:4070: Wrapping/PythonCore/CMakeFiles/vtkWrappingPythonCore.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/timothee/.linuxbrew/bin/g++-5  -fPIC -Os -w -pipe -march=native   -DNDEBUG  -Wl,--no-undefined -lc  -L/home/timothee/.linuxbrew/lib -Wl,--dynamic-linker=/home/timothee/.linuxbrew/lib/ld.so -Wl,-rpath,/home/timothee/.linuxbrew/lib  -shared -Wl,-soname,libvtkCommonMisc-7.0.so.1 -o ../../lib/libvtkCommonMisc-7.0.so.1 CMakeFiles/vtkCommonMisc.dir/vtkContourValues.cxx.o CMakeFiles/vtkCommonMisc.dir/vtkErrorCode.cxx.o CMakeFiles/vtkCommonMisc.dir/vtkFunctionParser.cxx.o CMakeFiles/vtkCommonMisc.dir/vtkHeap.cxx.o CMakeFiles/vtkCommonMisc.dir/vtkPolygonBuilder.cxx.o ../../lib/libvtkCommonMath-7.0.so.1 ../../lib/libvtkCommonCore-7.0.so.1 -Wl,-rpath,/home/timothee/.linuxbrew/Cellar/vtk/7.0.0_4/lib
cd /tmp/vtk-20160927-30670-yetu4/VTK-7.0.0/build/Common/Misc && /home/timothee/.linuxbrew/Cellar/cmake/3.6.2/bin/cmake -E cmake_symlink_library ../../lib/libvtkCommonMisc-7.0.so.1 ../../lib/libvtkCommonMisc-7.0.so.1 ../../lib/libvtkCommonMisc-7.0.so
make[2]: Leaving directory '/tmp/vtk-20160927-30670-yetu4/VTK-7.0.0/build'
[ 12%] Built target vtkCommonMisc
make[1]: Leaving directory '/tmp/vtk-20160927-30670-yetu4/VTK-7.0.0/build'
make: *** [Makefile:131: all] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

These open issues may also help:
vtk: fix linking to python https://github.com/Homebrew/homebrew-science/pull/3811
opencv: fix build with vtk https://github.com/Homebrew/homebrew-science/pull/3750
opencv3: fix build with vtk https://github.com/Homebrew/homebrew-science/pull/3749
vtk crashes when brewed python is installed https://github.com/Homebrew/homebrew-science/issues/3401
vtk: Depends on libxml2 for Linuxbrew https://github.com/Homebrew/homebrew-science/pull/3754
Problem installing vtk https://github.com/Homebrew/homebrew-science/issues/2442
Possible fix for reported issues with VTK linking to wrong Python https://github.com/Homebrew/homebrew-science/issues/4334
vtk: Build with options fails linking due to missing OpenGL symbols https://github.com/Homebrew/homebrew-science/issues/4322
VTK forces the directory `.../include/python3.5m` https://github.com/Homebrew/homebrew-science/issues/3577
PCL 1.7.2 with VTK 7 https://github.com/Homebrew/homebrew-science/issues/3370
opencv fail to build with ffmpeg or vtk https://github.com/Homebrew/homebrew-science/issues/3371
brew install gdcm --with-python3 --with-vtk failed https://github.com/Homebrew/homebrew-science/issues/2257
```

**Comment by sjackman** [comment]
It's a bit of a shot in the dark, but try
```
HOMEBREW_MAKE_JOBS=1 brew install vtk -v
```

**Comment by timotheecour** [comment]
tried it and got:
```
[ 19%] Building C object ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/src/glew.c.o
cd /tmp/vtk-20161218-7452-10te09d/VTK-7.1.0/build/ThirdParty/glew/vtkglew && /usr/bin/gcc-4.8 -DVTK_IN_VTK -Dvtkglew_EXPORTS -DGLEW_NO_GLU -I/tmp/vtk-20161218-7452-10te09d/VTK-7.1.0/build/ThirdParty/glew -I/tmp/vtk-20161218-7452-10te09d/VTK-7.1.0/ThirdParty/glew -I/tmp/vtk-20161218-7452-10te09d/VTK-7.1.0/ThirdParty/glew/vtkglew -I/tmp/vtk-20161218-7452-10te09d/VTK-7.1.0/ThirdParty/glew/vtkglew/include  -Os -w -pipe -march=native  -w -w -DNDEBUG -fPIC   -o CMakeFiles/vtkglew.dir/src/glew.c.o   -c /tmp/vtk-20161218-7452-10te09d/VTK-7.1.0/ThirdParty/glew/vtkglew/src/glew.c
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'lib/libvtkglew-7.1.so.1'.  Stop.
make[2]: Leaving directory '/tmp/vtk-20161218-7452-10te09d/VTK-7.1.0/build'
make[1]: *** [CMakeFiles/Makefile2:2390: ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/all] Error 2
make[1]: Leaving directory '/tmp/vtk-20161218-7452-10te09d/VTK-7.1.0/build'
make: *** [Makefile:131: all] Error 2
```

I believe the error is : 
No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so which was already visible in the original gist log i posted above

**Comment by sjackman** [comment]
Try
```
brew install linuxbrew/xorg/mesa vtk
```

**Comment by timotheecour** [comment]
update:
just reran`brew install homebrew/science/vtk` and looking again at logs I am getting:

make[2]: *** No rule to make target '/home/timothee/.linuxbrew/Cellar/python/2.7.12_3/lib/libpython2.7.dylib', needed by 'lib/libvtkWrappingPython27Core-7.1.so.1'.  Stop.

which is a bug: should be s/libpython2.7.dylib/libpython2.7.so

(haven't tried adding `brew install linuxbrew/xorg/xorg linuxbrew/xorg/mesa` yet)

**Comment by timotheecour** [comment]
fix: https://github.com/Homebrew/homebrew-science/pull/4834

**Comment by sjackman** [comment]
Resolved by #4834

**Comment by sjackman** [comment]
Thanks for the fix, Timothee!

**Comment by timotheecour** [comment]
@sjackman  how is #4834 related to this PR?

**Comment by sjackman** [comment]
I meant Homebrew/homebrew-science#4834. Does it not resolve this issue?

**Comment by timotheecour** [comment]
Yes (you previous message had the wrong link). But please reopen this issue until that PR is submitted

**Comment by danielaDESM** [comment]
Hi! I am quiet new using PCL v 1.8 and I have problems installing VTK-7.1.0. I am following the instructions of this post:
https://askubuntu.com/questions/916260/how-to-install-point-cloud-library-v1-8-pcl-1-8-0-on-ubuntu-16-04-2-lts-for
but there is a problem shown after I ran the command make: 

make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'lib/libvtkglew-7.1.so.1'.  Stop.
CMakeFiles/Makefile2:2675: recipe for target 'ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/all' failed
make[1]: *** [ThirdParty/glew/vtkglew/CMakeFiles/vtkglew.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I tried the following versions: VTK-7.1.0, VTK-7.1.1, VTK-8.1.2 and in all of them I have the same error.
I also tried the installation through brew install vtk, and the following error is shown:

make[1]: Leaving directory '/tmp/llvm@4-20181116-7687-1a4yg63/llvm-4.0.1.src/build'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

It appears to me that there is a linking issue (but I am really not an expert), i tried to run the following command to see if with it the problem would be solved, but it did not work:
ln -s /usr/lib/x86_64-linux-gnu/libGL.so /home/daniela/Downloads/vtkpython-7.1.1-Linux-64bit/lib/libvtkglew-7.1.so.1
ln: failed to create symbolic link '/home/daniela/Downloads/vtkpython-7.1.1-Linux-64bit/lib/libvtkglew-7.1.so.1': File exists

I have Ubuntu 16.04 LTS, Installed on a PC in double booting with Windows (if that helps at all)

**Comment by danielaDESM** [comment]
Update:

I ran : brew audit --strict --online vtk
and know I only have the following mistake after brew install vtk
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2
Could you help me solving this last one?

**Comment by maxim-belkin** [comment]
Daniela, welcome to Linuxbrew!
The package you're trying to install (`pcl`) has a formula in Linuxbrew. Therefore, I suggest you try running the following sequence of commands:
```
brew prune
brew update
brew update
brew upgrade
brew cleanup --prune=0
brew install pcl
```

If you see an error message at this point, execute:
```
brew gist-logs pcl
```
and report the URL that you receive in a [new issue](https://github.com/Linuxbrew/homebrew-core/issues/new/) in this repository.

**Comment by danielaDESM** [comment]
Hi! Thanks a lot for the help!
The installation stopped when installing the dependency llvm@4. I executed **brew gist-logs pcl** and the following appears:
Error: No logs.
The last lines of the information shown in terminal are:

[ 20%] Linking CXX static library ../../../../../lib/liblldMachO.a
cd /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO && /home/daniela/.linuxbrew/Cellar/cmake/3.12.4/bin/cmake -P CMakeFiles/lldMachO.dir/cmake_clean_target.cmake
cd /tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build/tools/lld/lib/ReaderWriter/MachO && /home/daniela/.linuxbrew/Cellar/cmake/3.12.4/bin/cmake -E cmake_link_script CMakeFiles/lldMachO.dir/link.txt --verbose=1
/home/daniela/.linuxbrew/bin/ar qc ../../../../../lib/liblldMachO.a  CMakeFiles/lldMachO.dir/ArchHandler.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_arm.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_arm64.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_x86.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_x86_64.cpp.o CMakeFiles/lldMachO.dir/CompactUnwindPass.cpp.o CMakeFiles/lldMachO.dir/GOTPass.cpp.o CMakeFiles/lldMachO.dir/LayoutPass.cpp.o CMakeFiles/lldMachO.dir/MachOLinkingContext.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileBinaryReader.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileBinaryWriter.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileFromAtoms.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileToAtoms.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileYAML.cpp.o CMakeFiles/lldMachO.dir/ObjCPass.cpp.o CMakeFiles/lldMachO.dir/ShimPass.cpp.o CMakeFiles/lldMachO.dir/StubsPass.cpp.o CMakeFiles/lldMachO.dir/TLVPass.cpp.o CMakeFiles/lldMachO.dir/WriterMachO.cpp.o
/home/daniela/.linuxbrew/bin/ranlib ../../../../../lib/liblldMachO.a
make[2]: Leaving directory '/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build'
[ 20%] Built target lldMachO
make[1]: Leaving directory '/tmp/llvm@4-20181119-13858-oz1nqq/llvm-4.0.1.src/build'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

Should I, in any case, create a new issue for my error?

**Comment by maxim-belkin** [comment]
`gist-logs` command has to be issued for the formula that Linuxbrew fails to install. This time, in your case it is `llvm@4`. Please run `brew gist-logs llvm@4`, record the URL, and create a new issue.
