### ISSUE TITLE
ncurses failed to build on  Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by lbesnard** [Linuxbrew/homebrew-core#955]
https://gist.github.com/anonymous/3dd44ca71371a9b8a5bd02de0f85cb71

After a fresh installation of linuxbrew, and normal setup of path, this package
`brew install zsh` fails on ncurses, as well as glibc with weird Assembler messages

cheers

**Comment by rwhogg** [comment]
From https://gist.github.com/anonymous/3dd44ca71371a9b8a5bd02de0f85cb71#file-02-make-L1437-L1439

```
{standard input}: Assembler messages:
{standard input}:46: Error: no such instruction: `vfmadd312sd .LC1(%rip),%xmm1,%xmm0'
{standard input}:67: Error: no such instruction: `vfmadd312sd .LC1(%rip),%xmm1,%xmm0'
```

Those are x86 vector extensions, so I suspect that Linuxbrew isn't determining your CPU's architecture correctly.

You could try doing the following:

```bash
$ export HOMEBREW_ARCH=core2
$ brew install gcc --with-glibc
```

Thanks a bunch for the bug report :smile:

**Comment by lbesnard** [comment]
awesome ! it works well ! 
cheers

**Comment by rwhogg** [comment]
Happy to help!

If you don't mind, can you tell me what your actual processor model is? We might have to make an adjustment to Linuxbrew's hardware detection so that this issue doesn't happen again.

**Comment by lbesnard** [comment]
done it ! just sent you an email

**Comment by sjackman** [comment]
```
Linuxbrew gcc: N/A
```
I suspect `brew install gcc` would resolve this issue.

```
CPU: octa-core 64-bit haswell
```
https://gist.github.com/anonymous/3dd44ca71371a9b8a5bd02de0f85cb71#file-00-config-out-L12

Try also
```
export HOMEBREW_ARCH=haswell
```
