### ISSUE TITLE
Trouble installing Node on Windows

### ISSUE THREAD

**Issue by eliw00d** [Linuxbrew/homebrew-core#958]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

I am trying to install node using `brew install node`. My environment is Bash on Ubuntu on Windows, with Ubuntu 16.04.1 installed. I followed all the installation steps for Linuxbrew and its dependencies. Here is what it looks like:

```
eliw0@eliw00d-PC:~/.linuxbrew$ brew install node
==> Downloading https://nodejs.org/dist/v6.5.0/node-v6.5.0.tar.xz
Already downloaded: /home/eliw0/.cache/Homebrew/node-6.5.0.tar.xz
==> ./configure --prefix=/home/eliw0/.linuxbrew/Cellar/node/6.5.0 --without-npm --without-snapshot
Last 15 lines from /home/eliw0/.cache/Homebrew/Logs/node/01.configure:
2016-09-29 16:36:14 -0500

./configure
--prefix=/home/eliw0/.linuxbrew/Cellar/node/6.5.0
--without-npm
--without-snapshot


READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues
```

And here are my gist-logs for node:

https://gist.github.com/a54d69b3b1d5e7ba44988276174b9b5d

Any thoughts?

**Comment by sjackman** [comment]
No, but I'll be building a precompiled binary bottle for node at PR #978. If you install Linuxbrew in `/home/linuxbrew/.linuxbrew` you'll be able to use that bottle without having to compiled node yourself.
