### ISSUE TITLE
Error installing open-mpi

### ISSUE THREAD

**Issue by abelsiqueira** [Linuxbrew/homebrew-core#9672]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install `open-mpi`, which is a dependency to `mumps`;

- What happened (include command output)
```
$ brew install open-mpi
==> Downloading https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.2.tar.bz2
Already downloaded: /home/abel/.cache/Homebrew/downloads/5d3e0f92a1a4d438b52b4417025fffb60fa343c42d331aa167271b6f098d898b--openmpi-3.1.2.tar.bz2
==> ./configure --prefix=/home/abel/.linuxbrew/Cellar/open-mpi/3.1.2 --disable-silent-rules --enable-ipv6 --with
==> make all
Last 15 lines from /home/abel/.cache/Homebrew/Logs/open-mpi/02.make:
               ^
In file included from libnl_utils.h:49:0,
                 from reachable_netlink_utils_common.c:52:
libnl3_utils.h:68:16: error: 'NLE_AGAIN' undeclared (first use in this function)
    if (err == -NLE_AGAIN) \
                ^
reachable_netlink_utils_common.c:410:5: note: in expansion of macro 'NL_RECVMSGS'
     NL_RECVMSGS(unlsk->nlh, arg, EHOSTUNREACH, err, out);
     ^
make[2]: *** [Makefile:1888: reachable_netlink_utils_common.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/open-mpi-20181004-22639-6yvt0s/openmpi-3.1.2/opal/mca/reachable/netlink'
make[1]: *** [Makefile:2375: all-recursive] Error 1
make[1]: Leaving directory '/tmp/open-mpi-20181004-22639-6yvt0s/openmpi-3.1.2/opal'
make: *** [Makefile:1897: all-recursive] Error 1

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."
```

- What you expected to happen
The installation to succeed.

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install open-mpi`.

gist: https://gist.github.com/abelsiqueira/31f65b428c071c31df24b374a32d4c75

**Comment by dpo** [comment]
Seems like the first error is
```
In file included from libnl_utils.h:49:0,
                 from reachable_netlink_utils_common.c:52:
reachable_netlink_utils_common.c: In function 'opal_reachable_netlink_sk_alloc':
libnl3_utils.h:54:26: error: too many arguments to function 'nl_geterror'
 #define NL_GETERROR(err) nl_geterror(err)
                          ^
reachable_netlink_utils_common.c:158:21: note: in expansion of macro 'NL_GETERROR'
                     NL_GETERROR(err));
                     ^
In file included from /usr/include/netlink/object.h:16:0,
                 from /usr/include/netlink/msg.h:16,
                 from /usr/include/netlink/cache.h:16,
                 from /usr/include/netlink/route/route.h:16,
                 from libnl3_utils.h:49,
                 from libnl_utils.h:49,
                 from reachable_netlink_utils_common.c:52:
/usr/include/netlink/utils.h:41:15: note: declared here
 extern char * nl_geterror(void);
               ^
```

**Comment by dpo** [comment]
All I find is https://www.mail-archive.com/users@lists.open-mpi.org/msg31567.html, but the discussion suggests that the issue is fixed in OpenMPI 3.1.x.

**Comment by dpo** [comment]
I notice that `configure` says:
```
configure: checking for libnl v3
checking for /usr/include/libnl3... found
```
I wonder if OpenMPI somehow picks up the wrong `libnl`. @abelsiqueira Would you mind uninstalling any other `open-mpi` you might have (e.g., installed with `apt-get`), and `libnl` if it's part of a different package, and try `brew install open-mpi` again?

**Comment by dpo** [comment]
Seems like you might need `libnfnetlink-dev` and `libnl-route-3-dev`.

**Comment by abelsiqueira** [comment]
Those are for Debian systems, Arch Linux ships libraries and headers along with the usual package.
- [Debian `libnl-route-3-dev`](https://packages.debian.org/sid/amd64/libnl-route-3-dev/filelist)
- [Arch Linux `libnl`](https://www.archlinux.org/packages/core/x86_64/libnl/files/)

**Comment by dpo** [comment]
Would something like `CFLAGS="-I/usr/include/libnl3 brew install open-mpi` work?

**Comment by abelsiqueira** [comment]
Same error. Also tried adding the folder to `C_INCLUDE_PATH`, but also nothing.

**Comment by dpo** [comment]
I meant `HOMEBREW_CFLAGS` instead of `CFLAGS`. Does that make a difference?

**Comment by abelsiqueira** [comment]
No, same error.

**Comment by dpo** [comment]
Do you have `pkg-config` installed (`brew install pkg-config`)?

**Comment by abelsiqueira** [comment]
Yes:
```
$ brew list
archdefs  gcc  gmp  gpatch  gsl@1  hello  isl@0.18  libevent 
libmpc  libyaml  mpfr  ncurses  openssl  patchelf  pkg-config 
readline  zlib
```
I tried removing `gcc` and using the system, but it install gcc as dependency of `open-mpi`.

**Comment by dpo** [comment]
`brew install open-mpi --env=std` works for me on an ArchLinux VM.

**Comment by abelsiqueira** [comment]
This worked for me!

**Comment by sjackman** [comment]
My best guess is that OpenMPI was picking up libnfnetlink-dev and libnl-route-3-dev from the host system, when it shouldn't. It's hard to prevent though, since we don't have a sandbox preventing access to `/usr/include`. If you have sudo access, removing those two packages may help.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
Glad to hear that you got it working, Abel, even though it wasn't entirely smooth.

**Comment by abelsiqueira** [comment]
Thanks, closing this.
