### ISSUE TITLE
gtk-doc: Superenv remove necessary compiler flags during build

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#9685]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
brew install gtk-doc
- What happened (include command output)
build failed with error:
```
Last 15 lines from /scratch/.cache/gtk-doc/03.make:
make[3]: Entering directory '/scratch/tmp/gtk-doc-20181005-8780-1lb904p/gtk-doc-1.28/tests/annotations'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/scratch/tmp/gtk-doc-20181005-8780-1lb904p/gtk-doc-1.28/tests/annotations'
Making all in src
make[3]: Entering directory '/scratch/tmp/gtk-doc-20181005-8780-1lb904p/gtk-doc-1.28/tests/annotations/src'
  CC       tester.lo
tester.c:9:18: fatal error: glib.h: No such file or directory
compilation terminated.
```

03.make.cc shows:
```
gcc-5 called with: -DPACKAGE_NAME="gtk-doc" -DPACKAGE_TARNAME="gtk-doc" -DPACKAGE_VERSION="1.28" -DPACKAGE_STRING="gtk-doc 1.28" -DPACKAGE_BUGREPORT="http://bugzilla.gnome.org/enter_bug.cgi  ?product=gtk-doc" -DPACKAGE_URL="" -DPACKAGE="gtk-doc" -DVERSION="1.28" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAV  E_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -I. -I/scratch/.linuxbrew/Cellar/glib/2.56.1/include/glib-2.0 -I/scratch/.linuxbr  ew/Cellar/glib/2.56.1/lib/glib-2.0/include -I/scratch/.linuxbrew/Cellar/pcre/8.42/include -g -O2 -Wall -c tester.c -fPIC -DPIC -o .libs/tester.o
  superenv removed:  -I/scratch/.linuxbrew/Cellar/glib/2.56.1/include/glib-2.0 -I/scratch/.linuxbrew/Cellar/glib/2.56.1/lib/glib-2.0/include -I/scratch/.linuxbrew/Cellar/pcre/8.42/include -g   -Wall
  superenv added:    -pipe -w -isystem/scratch/.linuxbrew/include
  superenv executed: gcc-5 -pipe -w -O2 -DPACKAGE_NAME="gtk-doc" -DPACKAGE_TARNAME="gtk-doc" -DPACKAGE_VERSION="1.28" -DPACKAGE_STRING="gtk-doc 1.28" -DPACKAGE_BUGREPORT="http://bugzilla.gnom  e.org/enter_bug.cgi?product=gtk-doc" -DPACKAGE_URL="" -DPACKAGE="gtk-doc" -DVERSION="1.28" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHA  VE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -I. -c tester.c -fPIC -DPIC -o .libs/tester.o -isystem/scratch  /.linuxbrew/include
```
The error is caused by `superenv removed:  -I/scratch/.linuxbrew/Cellar/glib/2.56.1/include/glib-2.0` where `glib.h` resides.

**Comment by Char-Aznable** [comment]
Also, adding `env :std` to the formula works

**Comment by iMichka** [comment]
Adding `depends_on "glib"` to the formula should fix it. It will add glib to the dependency tree, and superenv will stop removing the flags. Can you test this, and if it works, open a pull request for that? It looks like we do not have a bottle for `gtk-doc`, so this is a good opportunity to build one.

**Comment by iMichka** [comment]
We may still have a problem though: `glib` also depends on `gtk-doc`. This means we have a circular dependency here ...

We need to find a way to disable the usage of `gtk-doc` in `glib`. I guess it is only there to build the documentation, which we do not want to do most of the time. So removing it is probably fine, but we need to disable the documentation building.
