### ISSUE TITLE
glib: Upgrade fails upon applying gnotification-mountain.patch

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/homebrew-core#987]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:
Is the gnotification-mountain.patch even necessary on Linux? From glib.rb:
```
if MacOS.version < :mavericks
    patch do
      url "https://raw.githubusercontent.com/Homebrew/formula-patches/59e4d32/glib/gnotification-mountain.patch"
```
`$ brew upgrade glib` results in https://gist.github.com/jwhite007/ac4feb3d3cbdf7724197555610872aec

`brew gist-logs <formula>`:
```
$ brew gist-logs glib
Error: No logs.
```
`brew config`: https://gist.github.com/jwhite007/4bdb9df5b061ecc14ef7bfe0a3c56bcc
```
$ brew dr
Your system is ready to brew.
```

**Comment by rwhogg** [comment]
This will probably be fixed by #966

**Comment by rwhogg** [comment]
#966 has been merged. Thanks a bunch @sjackman!

@jwhite007, please do a `brew update` and then retry the upgrade.

**Comment by jwhite007** [comment]
@rwhogg, after update glib built without any issues. Thanks for your help.
