### ISSUE TITLE
glib installation failing on SLES 12 SP1

### ISSUE THREAD

**Issue by bhaskarvaish** [Linuxbrew/homebrew-core#996]
I am having a hard time for installation of wxpython, currently the installation is failing for glib.
brew install glib is failing with "Error: Failure while executing: patch -g 0 -f -p1 -i /tmp/glib--patch-20161004-64937-vpq5bd/gnotification-mountain.patch
[issue.txt](https://github.com/Linuxbrew/homebrew-core/files/509522/issue.txt)
"

**Comment by rwhogg** [comment]
Thanks for the bug report!

@sjackman, want me to take over #966? I can fix it myself if you're pressed for time.

**Comment by sjackman** [comment]
I fixed two issues in `glib`. I'm hoping that'll fix it. Feel free to merge #966 if it does fix it.

**Comment by rwhogg** [comment]
I merged #966. Thanks a bunch Shaun!

@bhaskarvaish, please do a `brew update` and then retry the installation.

**Comment by bhaskarvaish** [comment]
Works now, thanks a lot:)
